# Generated by Django 4.1.5 on 2023-04-04 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Password_Saver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='us',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
