# Generated by Django 4.1.5 on 2023-04-05 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Password_Saver', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acc_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
