# Generated by Django 5.0.6 on 2024-08-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Password_Saver', '0006_alter_accountinfo_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountinfo',
            name='reminder_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
