Django Project: django.utils.jslex.JsLexer Class Reference
django.utils.jslex.JsLexer Class Reference
Public Member Functions
__init__ (self)
Public Member Functions inherited from django.utils.jslex.Lexer
lex (self, text)
Public Attributes
states
Public Attributes inherited from django.utils.jslex.Lexer
regexes
toks
state
Static Public Attributes
list both_before
list both_after
dict states
Detailed Description
A JavaScript lexer
>>> lexer = JsLexer()
>>> list(lexer.lex("a = 1"))
[('id', 'a'), ('ws', ' '), ('punct', '='), ('ws', ' '), ('dnum', '1')]
This doesn't properly handle non-ASCII characters in the JavaScript source.
Constructor & Destructor Documentation
__init__()
django.utils.jslex.JsLexer.__init__ (self)
Reimplemented from django.utils.jslex.Lexer.
Referenced by setuptools._vendor.typing_extensions._ProtocolMeta.__init__(), pip._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.ordered_set.OrderedSet.__setstate__(), and django.db.models.expressions.Expression.identity().
Member Data Documentation
both_after
list django.utils.jslex.JsLexer.both_after static
Initial value:
=  [
        Tok("other", r"."),
    ]
both_before
list django.utils.jslex.JsLexer.both_before static
states [1/2]
dict django.utils.jslex.JsLexer.states static
Initial value:
=  {
        # slash will mean division
        "div": both_before
        + [
            Tok("punct", literals("/= /"), next="reg"),
        ]
        + both_after,
        # slash will mean regex
        "reg": both_before
        + [
            Tok(
                "regex",
                ,
                next="div",
            ),
        ]
        + both_after,
    }
states [2/2]
django.utils.jslex.JsLexer.states
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/django/utils/jslex.py