Django Project: django.core.checks.messages.Debug Class Reference
django.core.checks.messages.Debug Class Reference
Public Member Functions
__init__ (self, *args, **kwargs)
Public Member Functions inherited from django.core.checks.messages.CheckMessage
__eq__ (self, other)
__str__ (self)
__repr__ (self)
is_serious (self, level=ERROR)
is_silenced (self)
Additional Inherited Members
Public Attributes inherited from django.core.checks.messages.CheckMessage
level
msg
hint
obj
id
Constructor & Destructor Documentation
__init__()
django.core.checks.messages.Debug.__init__ (self, * args, ** kwargs)
Reimplemented from django.core.checks.messages.CheckMessage.
References django.core.checks.messages.Debug.__init__().
Referenced by django.core.checks.messages.Debug.__init__(), setuptools._vendor.typing_extensions._ProtocolMeta.__init__(), pip._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.ordered_set.OrderedSet.__setstate__(), and django.db.models.expressions.Expression.identity().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/django/core/checks/messages.py