Django Project: pip._internal.index.sources.LinkSource Class Reference
pip._internal.index.sources.LinkSource Class Reference
Public Member Functions
Optional[Link] link (self)
FoundCandidates page_candidates (self)
FoundLinks file_links (self)
Member Function Documentation
file_links()
FoundLinks pip._internal.index.sources.LinkSource.file_links (self)
Links found by specifying archives directly.
Reimplemented in pip._internal.index.sources._FlatDirectorySource, pip._internal.index.sources._IndexDirectorySource, pip._internal.index.sources._LocalFileSource, and pip._internal.index.sources._RemoteFileSource.
link()
Optional[Link] pip._internal.index.sources.LinkSource.link (self)
Returns the underlying link, if there's one.
Reimplemented in pip._internal.index.sources._FlatDirectorySource, pip._internal.index.sources._IndexDirectorySource, pip._internal.index.sources._LocalFileSource, and pip._internal.index.sources._RemoteFileSource.
Referenced by pip._internal.models.candidate.InstallationCandidate.__repr__(), pip._internal.exceptions.DiagnosticPipError.__rich_console__(), pip._internal.req.req_install.InstallRequirement.__str__(), pip._internal.req.req_install.InstallRequirement.hashes(), pip._internal.req.req_install.InstallRequirement.is_wheel(), setuptools._distutils.ccompiler.CCompiler.link_executable(), setuptools._distutils.ccompiler.CCompiler.link_shared_lib(), setuptools._distutils.ccompiler.CCompiler.link_shared_object(), and pip._internal.req.req_install.InstallRequirement.update_editable().
page_candidates()
FoundCandidates pip._internal.index.sources.LinkSource.page_candidates (self)
Candidates found by parsing an archive listing HTML file.
Reimplemented in pip._internal.index.sources._FlatDirectorySource, pip._internal.index.sources._IndexDirectorySource, pip._internal.index.sources._LocalFileSource, and pip._internal.index.sources._RemoteFileSource.
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/pip/_internal/index/sources.py