Django Project: setuptools.command.easy_install.ScriptWriter Class Reference
setuptools.command.easy_install.ScriptWriter Class Reference
Public Member Functions
get_script_args (cls, dist, executable=None, wininst=False)
get_script_header (cls, script_text, executable=None, wininst=False)
get_args (cls, dist, header=None)
get_writer (cls, force_windows)
best (cls)
get_header (cls, script_text="", executable=None)
Static Public Attributes
template = textwrap.dedent().lstrip()
command_spec_class = CommandSpec
Protected Member Functions
_get_script_args (cls, type_, name, header, script_text)
Static Protected Member Functions
_ensure_safe_name (name)
Detailed Description
Encapsulates behavior around writing entry point scripts for console and
gui apps.
Member Function Documentation
_ensure_safe_name()
setuptools.command.easy_install.ScriptWriter._ensure_safe_name (name) static protected
Prevent paths in *_scripts entry point names.
_get_script_args()
setuptools.command.easy_install.ScriptWriter._get_script_args (cls, type_, name, header, script_text) protected
Reimplemented in setuptools.command.easy_install.WindowsExecutableLauncherWriter, and setuptools.command.easy_install.WindowsScriptWriter.
best()
setuptools.command.easy_install.ScriptWriter.best (cls)
Select the best ScriptWriter for this environment.
Reimplemented in setuptools.command.easy_install.WindowsScriptWriter.
get_args()
setuptools.command.easy_install.ScriptWriter.get_args (cls, dist, header = None)
Yield write_script() argument tuples for a distribution's
console_scripts and gui_scripts entry points.
get_header()
setuptools.command.easy_install.ScriptWriter.get_header (cls, script_text = "", executable = None)
Create a #! line, getting options (if any) from script_text
get_script_args()
setuptools.command.easy_install.ScriptWriter.get_script_args (cls, dist, executable = None, wininst = False)
get_script_header()
setuptools.command.easy_install.ScriptWriter.get_script_header (cls, script_text, executable = None, wininst = False)
get_writer()
setuptools.command.easy_install.ScriptWriter.get_writer (cls, force_windows)
Reimplemented in setuptools.command.easy_install.WindowsScriptWriter.
Member Data Documentation
command_spec_class
setuptools.command.easy_install.ScriptWriter.command_spec_class = CommandSpec static
template
setuptools.command.easy_install.ScriptWriter.template = textwrap.dedent().lstrip() static
Referenced by django.db.backends.ddl_references.Statement.__str__(), django.db.models.expressions.WindowFrame.__str__(), setuptools.command.egg_info.manifest_maker.add_defaults(), django.db.models.aggregates.Aggregate.as_sql(), django.db.models.expressions.Case.as_sql(), django.db.models.expressions.Func.as_sql(), django.db.models.expressions.OrderBy.as_sql(), django.db.models.expressions.Subquery.as_sql(), django.db.models.expressions.When.as_sql(), django.db.models.expressions.Window.as_sql(), django.db.models.expressions.WindowFrame.as_sql(), django.template.context.Context.bind_template(), django.template.context.RequestContext.bind_template(), setuptools._distutils.command.sdist.sdist.finalize_options(), _pytest.warning_types.UnformattedWarning.format(), setuptools._distutils.command.sdist.sdist.get_file_list(), django.template.backends.django.Template.origin(), django.template.context.RenderContext.push_state(), setuptools._distutils.command.sdist.sdist.read_template(), django.template.backends.django.Template.render(), django.template.backends.jinja2.Template.render(), and django.template.loader_tags.IncludeNode.render().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/setuptools/command/easy_install.py