Django Project: django.contrib.auth.views.PasswordChangeDoneView Class Reference
django.contrib.auth.views.PasswordChangeDoneView Class Reference
Public Member Functions
dispatch (self, *args, **kwargs)
Public Member Functions inherited from django.contrib.auth.views.PasswordContextMixin
get_context_data (self, **kwargs)
Public Member Functions inherited from django.views.generic.base.TemplateView
get (self, request, *args, **kwargs)
Public Member Functions inherited from django.views.generic.base.TemplateResponseMixin
render_to_response (self, context, **response_kwargs)
get_template_names (self)
Public Member Functions inherited from django.views.generic.base.ContextMixin
get_context_data (self, **kwargs)
Public Member Functions inherited from django.views.generic.base.View
__init__ (self, **kwargs)
view_is_async (cls)
as_view (cls, **initkwargs)
setup (self, request, *args, **kwargs)
http_method_not_allowed (self, request, *args, **kwargs)
options (self, request, *args, **kwargs)
Static Public Attributes
str template_name = "registration/password_change_done.html"
title = _("Password change successful")
Static Public Attributes inherited from django.contrib.auth.views.PasswordContextMixin
extra_context = None
Static Public Attributes inherited from django.views.generic.base.TemplateResponseMixin
template_name = None
template_engine = None
response_class = TemplateResponse
content_type = None
Static Public Attributes inherited from django.views.generic.base.ContextMixin
extra_context = None
Static Public Attributes inherited from django.views.generic.base.View
list http_method_names
Additional Inherited Members
Public Attributes inherited from django.contrib.auth.views.PasswordContextMixin
title
Public Attributes inherited from django.views.generic.base.View
view_is_async
head
request
args
kwargs
Protected Member Functions inherited from django.views.generic.base.View
_allowed_methods (self)
Member Function Documentation
dispatch()
django.contrib.auth.views.PasswordChangeDoneView.dispatch (self, * args, ** kwargs)
Reimplemented from django.views.generic.base.View.
Referenced by django.views.generic.base.View.as_view().
Member Data Documentation
template_name
str django.contrib.auth.views.PasswordChangeDoneView.template_name = "registration/password_change_done.html" static
Referenced by django.views.generic.base.TemplateResponseMixin.get_template_names(), django.contrib.admin.templatetags.base.InclusionAdminNode.render(), django.forms.utils.RenderableMixin.render(), django.forms.widgets.Widget.render(), django.template.response.SimpleTemplateResponse.rendered_content(), django.test.testcases._AssertTemplateNotUsedContext.test(), and django.test.testcases._AssertTemplateUsedContext.test().
title
django.contrib.auth.views.PasswordChangeDoneView.title = _("Password change successful") static
Referenced by pip._vendor.rich._inspect.Inspect.__rich__(), pip._vendor.rich.columns.Columns.__rich_console__(), pip._vendor.rich.rule.Rule.__rich_console__(), pip._vendor.rich.table.Table.__rich_console__(), django.contrib.flatpages.models.FlatPage.__str__(), pip._vendor.rich.panel.Panel._title(), and pip._vendor.pygments.formatters.html.HtmlFormatter._wrap_full().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/django/contrib/auth/views.py