Django Project: setuptools.command.build.SubCommand Class Reference
setuptools.command.build.SubCommand Class Reference
Public Member Functions
initialize_options (self)
finalize_options (self)
run (self)
List[str] get_source_files (self)
List[str] get_outputs (self)
Dict[str, str] get_output_mapping (self)
Static Public Attributes
bool editable_mode = False
Detailed Description
In order to support editable installations (see :pep:`660`) all
build subcommands **SHOULD** implement this protocol. They also **MUST** inherit
from ``setuptools.Command``.
When creating an :pep:`editable wheel <660>`, ``setuptools`` will try to evaluate
custom ``build`` subcommands using the following procedure:
1. ``setuptools`` will set the ``editable_mode`` attribute to ``True``
2. ``setuptools`` will execute the ``run()`` command.
   .. important::
      Subcommands **SHOULD** take advantage of ``editable_mode=True`` to adequate
      its behaviour or perform optimisations.
      For example, if a subcommand don't need to generate any extra file and
      everything it does is to copy a source file into the build directory,
      ``run()`` **SHOULD** simply "early return".
      Similarly, if the subcommand creates files that would be placed alongside
      Python files in the final distribution, during an editable install
      the command **SHOULD** generate these files "in place" (i.e. write them to
      the original source directory, instead of using the build directory).
      Note that ``get_output_mapping()`` should reflect that and include mappings
      for "in place" builds accordingly.
3. ``setuptools`` use any knowledge it can derive from the return values of
   ``get_outputs()`` and ``get_output_mapping()`` to create an editable wheel.
   When relevant ``setuptools`` **MAY** attempt to use file links based on the value
   of ``get_output_mapping()``. Alternatively, ``setuptools`` **MAY** attempt to use
   :doc:`import hooks <python:reference/import>` to redirect any attempt to import
   to the directory with the original source code and other files built in place.
Please note that custom sub-commands **SHOULD NOT** rely on ``run()`` being
executed (or not) to provide correct return values for ``get_outputs()``,
``get_output_mapping()`` or ``get_source_files()``. The ``get_*`` methods should
work independently of ``run()``.
Member Function Documentation
finalize_options()
setuptools.command.build.SubCommand.finalize_options (self)
(Required by the original :class:`setuptools.Command` interface)
Referenced by setuptools._distutils.cmd.Command.ensure_finalized(), and setuptools._distutils.command.register.register.run().
get_output_mapping()
Dict[str, str] setuptools.command.build.SubCommand.get_output_mapping (self)
Return a mapping between destination files as they would be produced by the
build (dict keys) into the respective existing (source) files (dict values).
Existing (source) files should be represented as strings relative to the project
root directory.
Destination files should be strings in the form of
``"{build_lib}/destination/file/path"``.
Referenced by setuptools.command.build_ext.build_ext.get_outputs(), and setuptools.command.build_py.build_py.get_outputs().
get_outputs()
List[str] setuptools.command.build.SubCommand.get_outputs (self)
Return a list of files intended for distribution as they would have been
produced by the build.
These files should be strings in the form of
``"{build_lib}/destination/file/path"``.
.. note::
   The return value of ``get_output()`` should include all files used as keys
   in ``get_output_mapping()`` plus files that are generated during the build
   and don't correspond to any source file already present in the project.
Referenced by setuptools._distutils.command.build_py.build_py.run(), and setuptools._distutils.command.install.install.run().
get_source_files()
List[str] setuptools.command.build.SubCommand.get_source_files (self)
Return a list of all files that are used by the command to create the expected
outputs.
For example, if your build command transpiles Java files into Python, you should
list here all the Java files.
The primary purpose of this function is to help populating the ``sdist``
with all the files necessary to build the distribution.
All files should be strings relative to the project root directory.
initialize_options()
setuptools.command.build.SubCommand.initialize_options (self)
(Required by the original :class:`setuptools.Command` interface)
run()
setuptools.command.build.SubCommand.run (self)
(Required by the original :class:`setuptools.Command` interface)
Referenced by _pytest.pytester.Pytester.runpytest_subprocess(), _pytest.pytester.Pytester.runpython(), and _pytest.pytester.Pytester.runpython_c().
Member Data Documentation
editable_mode
bool setuptools.command.build.SubCommand.editable_mode = False static
Referenced by setuptools.command.build_ext.build_ext.finalize_options(), and setuptools.command.build_py.build_py.get_outputs().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/setuptools/command/build.py