Django Project: cryptography.hazmat.primitives.asymmetric.ed448.Ed448PrivateKey Class Reference
cryptography.hazmat.primitives.asymmetric.ed448.Ed448PrivateKey Class Reference
Public Member Functions
Ed448PrivateKey generate (cls)
Ed448PrivateKey from_private_bytes (cls, bytes data)
Ed448PublicKey public_key (self)
bytes sign (self, bytes data)
bytes private_bytes (self, _serialization.Encoding encoding, _serialization.PrivateFormat format, _serialization.KeySerializationEncryption encryption_algorithm)
bytes private_bytes_raw (self)
Member Function Documentation
from_private_bytes()
Ed448PrivateKey cryptography.hazmat.primitives.asymmetric.ed448.Ed448PrivateKey.from_private_bytes (cls, bytes data)
generate()
Ed448PrivateKey cryptography.hazmat.primitives.asymmetric.ed448.Ed448PrivateKey.generate (cls)
Referenced by cryptography.hazmat.primitives.twofactor.hotp.HOTP.verify(), and cryptography.hazmat.primitives.twofactor.totp.TOTP.verify().
private_bytes()
bytes cryptography.hazmat.primitives.asymmetric.ed448.Ed448PrivateKey.private_bytes (self, _serialization.Encoding encoding, _serialization.PrivateFormat format, _serialization.KeySerializationEncryption encryption_algorithm)
The serialized bytes of the private key.
private_bytes_raw()
bytes cryptography.hazmat.primitives.asymmetric.ed448.Ed448PrivateKey.private_bytes_raw (self)
The raw bytes of the private key.
Equivalent to private_bytes(Raw, Raw, NoEncryption()).
public_key()
Ed448PublicKey cryptography.hazmat.primitives.asymmetric.ed448.Ed448PrivateKey.public_key (self)
The Ed448PublicKey derived from the private key.
sign()
bytes cryptography.hazmat.primitives.asymmetric.ed448.Ed448PrivateKey.sign (self, bytes data)
Signs the data.
Referenced by setuptools._distutils.command.upload.upload.finalize_options(), django.core.signing.Signer.sign_object(), and setuptools._distutils.command.upload.upload.upload_file().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/cryptography/hazmat/primitives/asymmetric/ed448.py