Django Project: django.contrib.admindocs.views.TemplateTagIndexView Class Reference
django.contrib.admindocs.views.TemplateTagIndexView Class Reference
Public Member Functions
get_context_data (self, **kwargs)
Public Member Functions inherited from django.contrib.admindocs.views.BaseAdminDocsView
dispatch (self, request, *args, **kwargs)
Public Member Functions inherited from django.views.generic.base.TemplateView
get (self, request, *args, **kwargs)
Public Member Functions inherited from django.views.generic.base.TemplateResponseMixin
render_to_response (self, context, **response_kwargs)
get_template_names (self)
Public Member Functions inherited from django.views.generic.base.View
__init__ (self, **kwargs)
view_is_async (cls)
as_view (cls, **initkwargs)
setup (self, request, *args, **kwargs)
http_method_not_allowed (self, request, *args, **kwargs)
options (self, request, *args, **kwargs)
Static Public Attributes
str template_name = "admin_doc/template_tag_index.html"
Static Public Attributes inherited from django.views.generic.base.TemplateResponseMixin
template_name = None
template_engine = None
response_class = TemplateResponse
content_type = None
Static Public Attributes inherited from django.views.generic.base.ContextMixin
extra_context = None
Static Public Attributes inherited from django.views.generic.base.View
list http_method_names
Additional Inherited Members
Public Attributes inherited from django.contrib.admindocs.views.BaseAdminDocsView
template_name
request
Public Attributes inherited from django.views.generic.base.View
view_is_async
head
request
args
kwargs
Protected Member Functions inherited from django.views.generic.base.View
_allowed_methods (self)
Member Function Documentation
get_context_data()
django.contrib.admindocs.views.TemplateTagIndexView.get_context_data (self, ** kwargs)
Reimplemented from django.contrib.admindocs.views.BaseAdminDocsView.
References django.contrib.admindocs.views.TemplateTagIndexView.get_context_data().
Referenced by django.views.generic.edit.FormMixin.form_invalid(), django.views.generic.base.TemplateView.get(), django.views.generic.edit.ProcessFormView.get(), django.contrib.admindocs.views.TemplateTagIndexView.get_context_data(), and django.contrib.syndication.views.Feed.get_feed().
Member Data Documentation
template_name
str django.contrib.admindocs.views.TemplateTagIndexView.template_name = "admin_doc/template_tag_index.html" static
Referenced by django.views.generic.base.TemplateResponseMixin.get_template_names(), django.contrib.admin.templatetags.base.InclusionAdminNode.render(), django.forms.utils.RenderableMixin.render(), django.forms.widgets.Widget.render(), django.template.response.SimpleTemplateResponse.rendered_content(), django.test.testcases._AssertTemplateNotUsedContext.test(), and django.test.testcases._AssertTemplateUsedContext.test().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/django/contrib/admindocs/views.py