Django Project: pip._internal.network.auth.MultiDomainBasicAuth Class Reference
pip._internal.network.auth.MultiDomainBasicAuth Class Reference
Public Member Functions
None __init__ (self, bool prompting=True, Optional[List[str]] index_urls=None, str keyring_provider="auto")
KeyRingBaseProvider keyring_provider (self)
None keyring_provider (self, str provider)
bool use_keyring (self)
Request __call__ (self, Request req)
Response handle_401 (self, Response resp, **Any kwargs)
None warn_on_401 (self, Response resp, **Any kwargs)
None save_credentials (self, Response resp, **Any kwargs)
Public Attributes
prompting
index_urls
keyring_provider
Dict[str, AuthInfo] passwords
handle_401
use_keyring
warn_on_401
save_credentials
Protected Member Functions
Optional[AuthInfo] _get_keyring_auth (self, Optional[str] url, Optional[str] username)
Optional[str] _get_index_url (self, str url)
AuthInfo _get_new_credentials (self, str original_url, *, bool allow_netrc=True, bool allow_keyring=False)
Tuple[str, Optional[str], Optional[str]] _get_url_and_credentials (self, str original_url)
Tuple[Optional[str], Optional[str], bool] _prompt_for_password (self, str netloc)
bool _should_save_password_to_keyring (self)
Protected Attributes
Optional[Credentials] _credentials_to_save
_keyring_provider
Constructor & Destructor Documentation
__init__()
None pip._internal.network.auth.MultiDomainBasicAuth.__init__ (self, bool prompting = True, Optional[List[str]] index_urls = None, str keyring_provider = "auto")
Referenced by setuptools._vendor.typing_extensions._ProtocolMeta.__init__(), pip._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.ordered_set.OrderedSet.__setstate__(), and django.db.models.expressions.Expression.identity().
Member Function Documentation
__call__()
Request pip._internal.network.auth.MultiDomainBasicAuth.__call__ (self, Request req)
Reimplemented from pip._vendor.requests.auth.AuthBase.
Referenced by asgiref.sync.AsyncToSync.__get__(), and asgiref.sync.SyncToAsync.__get__().
_get_index_url()
Optional[str] pip._internal.network.auth.MultiDomainBasicAuth._get_index_url (self, str url) protected
Return the original index URL matching the requested URL.
Cached or dynamically generated credentials may work against
the original index URL rather than just the netloc.
The provided url should have had its username and password
removed already. If the original index url had credentials then
they will be included in the return value.
Returns None if no matching index was found, or if --no-index
was specified by the user.
_get_keyring_auth()
Optional[AuthInfo] pip._internal.network.auth.MultiDomainBasicAuth._get_keyring_auth (self, Optional[str] url, Optional[str] username) protected
Return the tuple auth for a given url from keyring.
_get_new_credentials()
AuthInfo pip._internal.network.auth.MultiDomainBasicAuth._get_new_credentials (self, str original_url, * , bool allow_netrc = True, bool allow_keyring = False) protected
Find and return credentials for the specified URL.
_get_url_and_credentials()
Tuple[str, Optional[str], Optional[str]] pip._internal.network.auth.MultiDomainBasicAuth._get_url_and_credentials (self, str original_url) protected
Return the credentials to use for the provided URL.
If allowed, netrc and keyring may be used to obtain the
correct credentials.
Returns (url_without_credentials, username, password). Note
that even if the original URL contains credentials, this
function may return a different username and password.
_prompt_for_password()
Tuple[Optional[str], Optional[str], bool] pip._internal.network.auth.MultiDomainBasicAuth._prompt_for_password (self, str netloc) protected
_should_save_password_to_keyring()
bool pip._internal.network.auth.MultiDomainBasicAuth._should_save_password_to_keyring (self) protected
handle_401()
Response pip._internal.network.auth.MultiDomainBasicAuth.handle_401 (self, Response resp, **Any kwargs)
keyring_provider() [1/2]
KeyRingBaseProvider pip._internal.network.auth.MultiDomainBasicAuth.keyring_provider (self)
keyring_provider() [2/2]
None pip._internal.network.auth.MultiDomainBasicAuth.keyring_provider (self, str provider)
save_credentials()
None pip._internal.network.auth.MultiDomainBasicAuth.save_credentials (self, Response resp, **Any kwargs)
Response callback to save credentials on success.
use_keyring()
bool pip._internal.network.auth.MultiDomainBasicAuth.use_keyring (self)
warn_on_401()
None pip._internal.network.auth.MultiDomainBasicAuth.warn_on_401 (self, Response resp, **Any kwargs)
Response callback to warn about incorrect credentials.
Member Data Documentation
_credentials_to_save
Optional[Credentials] pip._internal.network.auth.MultiDomainBasicAuth._credentials_to_save protected
_keyring_provider
pip._internal.network.auth.MultiDomainBasicAuth._keyring_provider protected
handle_401
pip._internal.network.auth.MultiDomainBasicAuth.handle_401
index_urls
pip._internal.network.auth.MultiDomainBasicAuth.index_urls
Referenced by pip._internal.models.search_scope.SearchScope.get_formatted_locations(), and pip._internal.models.search_scope.SearchScope.get_index_urls_locations().
keyring_provider
pip._internal.network.auth.MultiDomainBasicAuth.keyring_provider
passwords
Dict[str, AuthInfo] pip._internal.network.auth.MultiDomainBasicAuth.passwords
Referenced by django.contrib.auth.password_validation.CommonPasswordValidator.validate().
prompting
pip._internal.network.auth.MultiDomainBasicAuth.prompting
save_credentials
pip._internal.network.auth.MultiDomainBasicAuth.save_credentials
use_keyring
pip._internal.network.auth.MultiDomainBasicAuth.use_keyring
warn_on_401
pip._internal.network.auth.MultiDomainBasicAuth.warn_on_401
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/pip/_internal/network/auth.py