Django Project: setuptools.dist.Distribution Class Reference
setuptools.dist.Distribution Class Reference
Public Member Functions
patch_missing_pkg_info (self, attrs)
__init__ (self, attrs=None)
warn_dash_deprecation (self, opt, section)
make_option_lowercase (self, opt, section)
parse_config_files (self, filenames=None, ignore_option_errors=False)
fetch_build_eggs (self, requires)
finalize_options (self)
get_egg_cache_dir (self)
fetch_build_egg (self, req)
get_command_class (self, command)
print_commands (self)
get_command_list (self)
include (self, **attrs)
exclude_package (self, package)
has_contents_for (self, package)
exclude (self, **attrs)
get_cmdline_options (self)
iter_distribution_names (self)
handle_display_options (self, option_order)
run_command (self, command)
Public Attributes
package_data
dist_files
src_root
dependency_links
setup_requires
set_defaults
metadata
install_requires
extras_require
command_options
cmdclass
packages
py_modules
ext_modules
exclude_package
global_options
negative_opt
help_commands
Protected Member Functions
_validate_metadata (self)
_set_metadata_defaults (self, attrs)
_finalize_requires (self)
_convert_extras_requirements (self)
_move_install_requirements_markers (self)
_clean_req (self, req)
_finalize_license_files (self)
_parse_config_files (self, filenames=None)
_setuptools_commands (self)
_set_command_options (self, command_obj, option_dict=None)
_get_project_config_files (self, filenames)
_finalize_setup_keywords (self)
_exclude_misc (self, name, value)
_include_misc (self, name, value)
_exclude_packages (self, packages)
_parse_command_opts (self, parser, args)
Static Protected Member Functions
_normalize_version (version)
_validate_version (version)
_suffix_for (req)
_expand_patterns (patterns)
_removed (ep)
Protected Attributes
_orig_extras_require
_orig_install_requires
_tmp_extras_require
_clean_req
Static Protected Attributes
dict _DISTUTILS_UNSUPPORTED_METADATA
_patched_dist = None
Detailed Description
Distribution with support for tests and package data
This is an enhanced version of 'distutils.dist.Distribution' that
effectively adds the following new optional keyword arguments to 'setup()':
 'install_requires' -- a string or sequence of strings specifying project
    versions that the distribution requires when installed, in the format
    used by 'pkg_resources.require()'.  They will be installed
    automatically when the package is installed.  If you wish to use
    packages that are not available in PyPI, or want to give your users an
    alternate download location, you can add a 'find_links' option to the
    '[easy_install]' section of your project's 'setup.cfg' file, and then
    setuptools will scan the listed web pages for links that satisfy the
    requirements.
 'extras_require' -- a dictionary mapping names of optional "extras" to the
    additional requirement(s) that using those extras incurs. For example,
    this::
        extras_require = dict(reST = ["docutils>=0.3", "reSTedit"])
    indicates that the distribution can optionally provide an extra
    capability called "reST", but it can only be used if docutils and
    reSTedit are installed.  If the user installs your package using
    EasyInstall and requests one of your extras, the corresponding
    additional requirements will be installed if needed.
 'test_suite' -- the name of a test suite to run for the 'test' command.
    If the user runs 'python setup.py test', the package will be installed,
    and the named test suite will be run.  The format is the same as
    would be used on a 'unittest.py' command line.  That is, it is the
    dotted name of an object to import and call to generate a test suite.
 'package_data' -- a dictionary mapping package names to lists of filenames
    or globs to use to find data files contained in the named packages.
    If the dictionary has filenames or globs listed under '""' (the empty
    string), those names will be searched for in every package, in addition
    to any names for the specific package.  Data files found using these
    names/globs will be installed along with the package, in the same
    location as the package.  Note that globs are allowed to reference
    the contents of non-package subdirectories, as long as you use '/' as
    a path separator.  (Globs are automatically converted to
    platform-specific paths at runtime.)
In addition to these new keywords, this class also has several new methods
for manipulating the distribution's contents.  For example, the 'include()'
and 'exclude()' methods can be thought of as in-place add and subtract
commands that add or remove packages, modules, extensions, and so on from
the distribution.
Constructor & Destructor Documentation
__init__()
setuptools.dist.Distribution.__init__ (self, attrs = None)
Referenced by setuptools._vendor.typing_extensions._ProtocolMeta.__init__(), pip._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.ordered_set.OrderedSet.__setstate__(), and django.db.models.expressions.Expression.identity().
Member Function Documentation
_clean_req()
setuptools.dist.Distribution._clean_req (self, req) protected
Given a Requirement, remove environment markers and return it.
_convert_extras_requirements()
setuptools.dist.Distribution._convert_extras_requirements (self) protected
Convert requirements in `extras_require` of the form
`"extra": ["barbazquux; {marker}"]` to
`"extra:{marker}": ["barbazquux"]`.
_exclude_misc()
setuptools.dist.Distribution._exclude_misc (self, name, value) protected
Handle 'exclude()' for list/tuple attrs without a special handler
_exclude_packages()
setuptools.dist.Distribution._exclude_packages (self, packages) protected
_expand_patterns()
setuptools.dist.Distribution._expand_patterns (patterns) static protected
>>> list(Distribution._expand_patterns(['LICENSE']))
['LICENSE']
>>> list(Distribution._expand_patterns(['setup.cfg', 'LIC*']))
['setup.cfg', 'LICENSE']
_finalize_license_files()
setuptools.dist.Distribution._finalize_license_files (self) protected
Compute names of all license files which should be included.
_finalize_requires()
setuptools.dist.Distribution._finalize_requires (self) protected
Set `metadata.python_requires` and fix environment markers
in `install_requires` and `extras_require`.
_finalize_setup_keywords()
setuptools.dist.Distribution._finalize_setup_keywords (self) protected
_get_project_config_files()
setuptools.dist.Distribution._get_project_config_files (self, filenames) protected
Add default file and split between INI and TOML
_include_misc()
setuptools.dist.Distribution._include_misc (self, name, value) protected
Handle 'include()' for list/tuple attrs without a special handler
_move_install_requirements_markers()
setuptools.dist.Distribution._move_install_requirements_markers (self) protected
Move requirements in `install_requires` that are using environment
markers `extras_require`.
_normalize_version()
setuptools.dist.Distribution._normalize_version (version) static protected
_parse_command_opts()
setuptools.dist.Distribution._parse_command_opts (self, parser, args) protected
_parse_config_files()
setuptools.dist.Distribution._parse_config_files (self, filenames = None) protected
Adapted from distutils.dist.Distribution.parse_config_files,
this method provides the same functionality in subtly-improved
ways.
_removed()
setuptools.dist.Distribution._removed (ep) static protected
When removing an entry point, if metadata is loaded
from an older version of Setuptools, that removed
entry point will attempt to be loaded and will fail.
See #2765 for more details.
_set_command_options()
setuptools.dist.Distribution._set_command_options (self, command_obj, option_dict = None) protected
Set the options for 'command_obj' from 'option_dict'.  Basically
this means copying elements of a dictionary ('option_dict') to
attributes of an instance ('command').
'command_obj' must be a Command instance.  If 'option_dict' is not
supplied, uses the standard option dictionary for this command
(from 'self.command_options').
(Adopted from distutils.dist.Distribution._set_command_options)
Referenced by setuptools._distutils.dist.Distribution.get_command_obj(), and setuptools._distutils.dist.Distribution.reinitialize_command().
_set_metadata_defaults()
setuptools.dist.Distribution._set_metadata_defaults (self, attrs) protected
Fill-in missing metadata fields not supported by distutils.
Some fields may have been set by other tools (e.g. pbr).
Those fields (vars(self.metadata)) take precedence to
supplied attrs.
_setuptools_commands()
setuptools.dist.Distribution._setuptools_commands (self) protected
_suffix_for()
setuptools.dist.Distribution._suffix_for (req) static protected
For a requirement, return the 'extras_require' suffix for
that requirement.
_validate_metadata()
setuptools.dist.Distribution._validate_metadata (self) protected
_validate_version()
setuptools.dist.Distribution._validate_version (version) static protected
exclude()
setuptools.dist.Distribution.exclude (self, ** attrs)
Remove items from distribution that are named in keyword arguments
For example, 'dist.exclude(py_modules=["x"])' would remove 'x' from
the distribution's 'py_modules' attribute.  Excluding packages uses
the 'exclude_package()' method, so all of the package's contained
packages, modules, and extensions are also excluded.
Currently, this method only supports exclusion from attributes that are
lists or tuples.  If you need to add support for excluding from other
attributes in this or a subclass, you can add an '_exclude_X' method,
where 'X' is the name of the attribute.  The method will be called with
the value passed to 'exclude()'.  So, 'dist.exclude(foo={"bar":"baz"})'
will try to call 'dist._exclude_foo({"bar":"baz"})', which can then
handle whatever special exclusion logic is needed.
Referenced by django.contrib.admin.options.BaseModelAdmin.get_exclude(), and django.contrib.contenttypes.admin.GenericInlineModelAdmin.get_formset().
exclude_package()
setuptools.dist.Distribution.exclude_package (self, package)
Remove packages, modules, and extensions in named package
fetch_build_egg()
setuptools.dist.Distribution.fetch_build_egg (self, req)
Fetch an egg needed for building
fetch_build_eggs()
setuptools.dist.Distribution.fetch_build_eggs (self, requires)
Resolve pre-setup requirements
Reimplemented in setuptools.build_meta.Distribution.
finalize_options()
setuptools.dist.Distribution.finalize_options (self)
Allow plugins to apply arbitrary operations to the
distribution. Each hook may optionally define a 'order'
to influence the order of execution. Smaller numbers
go first and the default is 0.
Referenced by setuptools._distutils.cmd.Command.ensure_finalized(), and setuptools._distutils.command.register.register.run().
get_cmdline_options()
setuptools.dist.Distribution.get_cmdline_options (self)
Return a '{cmd: {opt:val}}' map of all command-line options
Option names are all long, but do not include the leading '--', and
contain dashes rather than underscores.  If the option doesn't take
an argument (e.g. '--quiet'), the 'val' is 'None'.
Note that options provided by config files are intentionally excluded.
get_command_class()
setuptools.dist.Distribution.get_command_class (self, command)
Pluggable version of get_command_class()
Referenced by setuptools._distutils.dist.Distribution._parse_command_opts(), setuptools._distutils.dist.Distribution.get_command_list(), setuptools._distutils.dist.Distribution.get_command_obj(), and setuptools._distutils.dist.Distribution.print_command_list().
get_command_list()
setuptools.dist.Distribution.get_command_list (self)
get_egg_cache_dir()
setuptools.dist.Distribution.get_egg_cache_dir (self)
handle_display_options()
setuptools.dist.Distribution.handle_display_options (self, option_order)
If there were any non-global "display-only" options
(--help-commands or the metadata display options) on the command
line, display the requested info and return true; else return
false.
has_contents_for()
setuptools.dist.Distribution.has_contents_for (self, package)
Return true if 'exclude_package(package)' would do something
include()
setuptools.dist.Distribution.include (self, ** attrs)
Add items to distribution that are named in keyword arguments
For example, 'dist.include(py_modules=["x"])' would add 'x' to
the distribution's 'py_modules' attribute, if it was not already
there.
Currently, this method only supports inclusion for attributes that are
lists or tuples.  If you need to add support for adding to other
attributes in this or a subclass, you can add an '_include_X' method,
where 'X' is the name of the attribute.  The method will be called with
the value passed to 'include()'.  So, 'dist.include(foo={"bar":"baz"})'
will try to call 'dist._include_foo({"bar":"baz"})', which can then
handle whatever special inclusion logic is needed.
Referenced by django.contrib.postgres.constraints.ExclusionConstraint.__eq__(), django.db.models.constraints.UniqueConstraint.__eq__(), django.contrib.postgres.constraints.ExclusionConstraint.__repr__(), django.db.models.constraints.UniqueConstraint.__repr__(), django.db.models.indexes.Index.__repr__(), django.contrib.postgres.constraints.ExclusionConstraint.check_supported(), django.contrib.postgres.indexes.SpGistIndex.check_supported(), django.contrib.postgres.constraints.ExclusionConstraint.constraint_sql(), django.db.models.constraints.UniqueConstraint.constraint_sql(), django.db.models.constraints.UniqueConstraint.create_sql(), django.db.models.indexes.Index.create_sql(), django.contrib.postgres.constraints.ExclusionConstraint.deconstruct(), django.db.models.constraints.UniqueConstraint.deconstruct(), django.db.models.indexes.Index.deconstruct(), pycparser.ply.cpp.Preprocessor.parsegen(), and django.db.models.constraints.UniqueConstraint.remove_sql().
iter_distribution_names()
setuptools.dist.Distribution.iter_distribution_names (self)
Yield all packages, modules, and extension names in distribution
make_option_lowercase()
setuptools.dist.Distribution.make_option_lowercase (self, opt, section)
parse_config_files()
setuptools.dist.Distribution.parse_config_files (self, filenames = None, ignore_option_errors = False)
Parses configuration files from various levels
and loads configuration.
patch_missing_pkg_info()
setuptools.dist.Distribution.patch_missing_pkg_info (self, attrs)
print_commands()
setuptools.dist.Distribution.print_commands (self)
run_command()
setuptools.dist.Distribution.run_command (self, command)
Referenced by pip._internal.vcs.subversion.Subversion._get_svn_url_rev(), setuptools.command.editable_wheel.editable_wheel._run_build_subcommands(), setuptools.command.editable_wheel.editable_wheel._run_install(), setuptools.command.editable_wheel.editable_wheel._safely_run(), setuptools._distutils.command.install_lib.install_lib.build(), pip._internal.vcs.subversion.Subversion.call_vcs_version(), pip._internal.vcs.bazaar.Bazaar.fetch_new(), pip._internal.vcs.mercurial.Mercurial.fetch_new(), pip._internal.vcs.subversion.Subversion.fetch_new(), pip._internal.vcs.bazaar.Bazaar.get_remote_url(), pip._internal.vcs.mercurial.Mercurial.get_remote_url(), pip._internal.vcs.mercurial.Mercurial.get_repository_root(), pip._internal.vcs.mercurial.Mercurial.get_requirement_revision(), pip._internal.vcs.bazaar.Bazaar.get_revision(), pip._internal.vcs.mercurial.Mercurial.get_revision(), pip._internal.vcs.mercurial.Mercurial.get_subdirectory(), setuptools.command.develop.develop.install_for_development(), setuptools.command.test.test.project_on_sys_path(), setuptools._distutils.command.bdist.bdist.run(), setuptools._distutils.command.bdist_dumb.bdist_dumb.run(), setuptools._distutils.command.bdist_rpm.bdist_rpm.run(), setuptools._distutils.command.build.build.run(), setuptools._distutils.command.install.install.run(), setuptools._distutils.command.install_scripts.install_scripts.run(), setuptools._distutils.command.register.register.run(), setuptools.command.bdist_egg.bdist_egg.run(), setuptools.command.bdist_rpm.bdist_rpm.run(), setuptools.command.install_egg_info.install_egg_info.run(), setuptools.command.install_scripts.install_scripts.run(), setuptools.command.rotate.rotate.run(), setuptools.command.sdist.sdist.run(), setuptools.command.upload_docs.upload_docs.run(), setuptools._distutils.dist.Distribution.run_commands(), pip._vendor.distlib.index.PackageIndex.sign_file(), pip._internal.vcs.bazaar.Bazaar.switch(), pip._internal.vcs.mercurial.Mercurial.switch(), pip._internal.vcs.subversion.Subversion.switch(), pip._internal.vcs.bazaar.Bazaar.update(), pip._internal.vcs.mercurial.Mercurial.update(), pip._internal.vcs.subversion.Subversion.update(), and pip._vendor.distlib.index.PackageIndex.verify_signature().
warn_dash_deprecation()
setuptools.dist.Distribution.warn_dash_deprecation (self, opt, section)
Member Data Documentation
_clean_req
setuptools.dist.Distribution._clean_req protected
_DISTUTILS_UNSUPPORTED_METADATA
dict setuptools.dist.Distribution._DISTUTILS_UNSUPPORTED_METADATA static protected
Initial value:
=  {
        'long_description_content_type': lambda: None,
        'project_urls': dict,
        'provides_extras': ordered_set.OrderedSet,
        'license_file': lambda: None,
        'license_files': lambda: None,
    }
_orig_extras_require
setuptools.dist.Distribution._orig_extras_require protected
_orig_install_requires
setuptools.dist.Distribution._orig_install_requires protected
_patched_dist
setuptools.dist.Distribution._patched_dist = None static protected
_tmp_extras_require
setuptools.dist.Distribution._tmp_extras_require protected
cmdclass
setuptools.dist.Distribution.cmdclass
Referenced by setuptools._distutils.dist.Distribution.get_command_class(), setuptools._distutils.dist.Distribution.get_command_list(), setuptools._distutils.dist.Distribution.print_command_list(), and setuptools._distutils.dist.Distribution.print_commands().
command_options
setuptools.dist.Distribution.command_options
Referenced by setuptools._distutils.dist.Distribution.dump_option_dicts(), setuptools._distutils.dist.Distribution.get_command_obj(), setuptools._distutils.dist.Distribution.get_option_dict(), and setuptools._distutils.dist.Distribution.parse_config_files().
dependency_links
setuptools.dist.Distribution.dependency_links
dist_files
setuptools.dist.Distribution.dist_files
exclude_package
setuptools.dist.Distribution.exclude_package
ext_modules
setuptools.dist.Distribution.ext_modules
Referenced by setuptools._distutils.dist.Distribution.has_ext_modules().
extras_require
setuptools.dist.Distribution.extras_require
global_options
setuptools.dist.Distribution.global_options
Referenced by setuptools._distutils.dist.Distribution._get_toplevel_options(), setuptools._distutils.dist.Distribution._parse_command_opts(), and setuptools._distutils.dist.Distribution._show_help().
help_commands
setuptools.dist.Distribution.help_commands
install_requires
setuptools.dist.Distribution.install_requires
metadata
setuptools.dist.Distribution.metadata
Referenced by pip._vendor.distlib.database.Distribution._get_requirements(), setuptools._vendor.importlib_metadata.Distribution._read_dist_info_reqs(), pip._internal.req.req_install.InstallRequirement._set_requirement(), pip._internal.req.req_install.InstallRequirement.archive(), pip._internal.req.req_install.InstallRequirement.assert_source_matches_version(), setuptools._distutils.dist.Distribution.finalize_options(), pip._internal.metadata.importlib._dists.Distribution.is_extra_provided(), pip._internal.metadata.importlib._dists.Distribution.iter_dependencies(), pip._internal.metadata.importlib._dists.Distribution.iter_provided_extras(), pip._vendor.distlib.database.Distribution.matches_requirement(), pip._internal.metadata.base.BaseDistribution.metadata_version(), setuptools._vendor.importlib_metadata.Distribution.name(), pluggy._manager.DistFacade.project_name(), pip._vendor.distlib.database.Distribution.provides(), pip._internal.metadata.base.BaseDistribution.raw_name(), pip._internal.metadata.base.BaseDistribution.requires_python(), setuptools._distutils.command.check.check.run(), pip._vendor.distlib.database.Distribution.source_url(), setuptools._vendor.importlib_metadata.Distribution.version(), and pip._internal.req.req_install.InstallRequirement.warn_on_mismatching_name().
negative_opt
setuptools.dist.Distribution.negative_opt
Referenced by setuptools._distutils.dist.Distribution._parse_command_opts(), setuptools._distutils.command.install.install.dump_dirs(), and setuptools._distutils.dist.Distribution.parse_config_files().
package_data
setuptools.dist.Distribution.package_data
Referenced by setuptools._distutils.command.build_py.build_py.find_data_files(), and setuptools.command.build_py.build_py.find_data_files().
packages
setuptools.dist.Distribution.packages
Referenced by setuptools._distutils.command.build_py.build_py.build_packages(), setuptools._distutils.command.build_py.build_py.find_all_modules(), django.views.i18n.JavaScriptCatalog.get(), setuptools._distutils.command.build_py.build_py.get_data_files(), setuptools.command.build_py.build_py.get_data_files_without_manifest(), setuptools._distutils.dist.Distribution.has_pure_modules(), and setuptools._distutils.command.build_py.build_py.run().
py_modules
setuptools.dist.Distribution.py_modules
Referenced by setuptools._distutils.command.build_py.build_py.find_all_modules(), setuptools._distutils.command.build_py.build_py.find_modules(), setuptools._distutils.dist.Distribution.has_pure_modules(), and setuptools._distutils.command.build_py.build_py.run().
set_defaults
setuptools.dist.Distribution.set_defaults
setup_requires
setuptools.dist.Distribution.setup_requires
src_root
setuptools.dist.Distribution.src_root
Referenced by setuptools.command.editable_wheel._NamespaceInstaller._get_root().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/setuptools/dist.py