Django Project: cryptography.x509.ocsp.OCSPResponse Class Reference
cryptography.x509.ocsp.OCSPResponse Class Reference
Public Member Functions
typing.Iterator[OCSPSingleResponse] responses (self)
OCSPResponseStatus response_status (self)
x509.ObjectIdentifier signature_algorithm_oid (self)
hashes.HashAlgorithm|None signature_hash_algorithm (self)
bytes signature (self)
bytes tbs_response_bytes (self)
list[x509.Certificate] certificates (self)
bytes|None responder_key_hash (self)
x509.Name|None responder_name (self)
datetime.datetime produced_at (self)
OCSPCertStatus certificate_status (self)
datetime.datetime|None revocation_time (self)
x509.ReasonFlags|None revocation_reason (self)
datetime.datetime this_update (self)
datetime.datetime|None next_update (self)
bytes issuer_key_hash (self)
bytes issuer_name_hash (self)
hashes.HashAlgorithm hash_algorithm (self)
int serial_number (self)
x509.Extensions extensions (self)
x509.Extensions single_extensions (self)
bytes public_bytes (self, serialization.Encoding encoding)
Member Function Documentation
certificate_status()
OCSPCertStatus cryptography.x509.ocsp.OCSPResponse.certificate_status (self)
The status of the certificate (an element from the OCSPCertStatus enum)
certificates()
list[x509.Certificate] cryptography.x509.ocsp.OCSPResponse.certificates (self)
A list of certificates used to help build a chain to verify the OCSP
response. This situation occurs when the OCSP responder uses a delegate
certificate.
extensions()
x509.Extensions cryptography.x509.ocsp.OCSPResponse.extensions (self)
The list of response extensions. Not single response extensions.
Referenced by setuptools._distutils.command.build_ext.build_ext._build_extensions_serial(), setuptools.command.build_ext.build_ext._get_output_mapping(), setuptools._distutils.command.build_ext.build_ext.build_extensions(), setuptools._distutils.command.build_ext.build_ext.finalize_options(), setuptools.command.build_ext.build_ext.finalize_options(), django.core.management.commands.makemessages.Command.find_files(), setuptools._distutils.command.build_ext.build_ext.get_outputs(), setuptools._distutils.command.build_ext.build_ext.get_source_files(), and setuptools._distutils.command.build_ext.build_ext.run().
hash_algorithm()
hashes.HashAlgorithm cryptography.x509.ocsp.OCSPResponse.hash_algorithm (self)
The hash algorithm used in the issuer name and key hashes
Referenced by django.test.runner.Shuffler._hash_text().
issuer_key_hash()
bytes cryptography.x509.ocsp.OCSPResponse.issuer_key_hash (self)
The hash of the issuer public key
issuer_name_hash()
bytes cryptography.x509.ocsp.OCSPResponse.issuer_name_hash (self)
The hash of the issuer name
next_update()
datetime.datetime | None cryptography.x509.ocsp.OCSPResponse.next_update (self)
The time when newer information will be available
produced_at()
datetime.datetime cryptography.x509.ocsp.OCSPResponse.produced_at (self)
The time the response was produced
public_bytes()
bytes cryptography.x509.ocsp.OCSPResponse.public_bytes (self, serialization.Encoding encoding)
Serializes the response to DER
responder_key_hash()
bytes | None cryptography.x509.ocsp.OCSPResponse.responder_key_hash (self)
The responder's key hash or None
responder_name()
x509.Name | None cryptography.x509.ocsp.OCSPResponse.responder_name (self)
The responder's Name or None
response_status()
OCSPResponseStatus cryptography.x509.ocsp.OCSPResponse.response_status (self)
The status of the response. This is a value from the OCSPResponseStatus
enumeration
responses()
typing.Iterator[OCSPSingleResponse] cryptography.x509.ocsp.OCSPResponse.responses (self)
An iterator over the individual SINGLERESP structures in the
response
revocation_reason()
x509.ReasonFlags | None cryptography.x509.ocsp.OCSPResponse.revocation_reason (self)
The reason the certificate was revoked or None if not specified or
not revoked.
revocation_time()
datetime.datetime | None cryptography.x509.ocsp.OCSPResponse.revocation_time (self)
The date of when the certificate was revoked or None if not
revoked.
serial_number()
int cryptography.x509.ocsp.OCSPResponse.serial_number (self)
The serial number of the cert whose status is being checked
signature()
bytes cryptography.x509.ocsp.OCSPResponse.signature (self)
The signature bytes
Referenced by django.core.signing.Signer.sign(), django_cryptography.core.signing.BytesSigner.sign(), django_cryptography.core.signing.FernetSigner.sign(), django.core.signing.Signer.unsign(), django_cryptography.core.signing.BytesSigner.unsign(), django_cryptography.core.signing.FernetSigner.unsign(), and django_cryptography.core.signing.Signer.unsign().
signature_algorithm_oid()
x509.ObjectIdentifier cryptography.x509.ocsp.OCSPResponse.signature_algorithm_oid (self)
The ObjectIdentifier of the signature algorithm
signature_hash_algorithm()
hashes.HashAlgorithm | None cryptography.x509.ocsp.OCSPResponse.signature_hash_algorithm (self)
Returns a HashAlgorithm corresponding to the type of the digest signed
single_extensions()
x509.Extensions cryptography.x509.ocsp.OCSPResponse.single_extensions (self)
The list of single response extensions. Not response extensions.
tbs_response_bytes()
bytes cryptography.x509.ocsp.OCSPResponse.tbs_response_bytes (self)
The tbsResponseData bytes
this_update()
datetime.datetime cryptography.x509.ocsp.OCSPResponse.this_update (self)
The most recent time at which the status being indicated is known by
the responder to have been correct
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/cryptography/x509/ocsp.py