Django Project: graphviz.dot.GraphSyntax Class Reference
graphviz.dot.GraphSyntax Class Reference
Static Protected Attributes
_head = staticmethod(graph_head)
_edge = staticmethod(graph_edge)
Detailed Description
DOT graph head and edge syntax.
Member Data Documentation
_edge
graphviz.dot.GraphSyntax._edge = staticmethod(graph_edge) static protected
Referenced by graphviz.dot.Dot._edge_plain(), and graphviz.dot.Dot.edge().
_head
graphviz.dot.GraphSyntax._head = staticmethod(graph_head) static protected
Referenced by graphviz.dot.Dot.__iter__().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/graphviz/dot.py