Django Project: sqlparse.engine.filter_stack.FilterStack Class Reference
sqlparse.engine.filter_stack.FilterStack Class Reference
Public Member Functions
__init__ (self, strip_semicolon=False)
enable_grouping (self)
run (self, sql, encoding=None)
Public Attributes
preprocess
stmtprocess
postprocess
Protected Attributes
_grouping
Constructor & Destructor Documentation
__init__()
sqlparse.engine.filter_stack.FilterStack.__init__ (self, strip_semicolon = False)
Referenced by setuptools._vendor.typing_extensions._ProtocolMeta.__init__(), pip._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.ordered_set.OrderedSet.__setstate__(), and django.db.models.expressions.Expression.identity().
Member Function Documentation
enable_grouping()
sqlparse.engine.filter_stack.FilterStack.enable_grouping (self)
run()
sqlparse.engine.filter_stack.FilterStack.run (self, sql, encoding = None)
Referenced by _pytest.pytester.Pytester.runpytest_subprocess(), _pytest.pytester.Pytester.runpython(), and _pytest.pytester.Pytester.runpython_c().
Member Data Documentation
_grouping
sqlparse.engine.filter_stack.FilterStack._grouping protected
postprocess
sqlparse.engine.filter_stack.FilterStack.postprocess
preprocess
sqlparse.engine.filter_stack.FilterStack.preprocess
stmtprocess
sqlparse.engine.filter_stack.FilterStack.stmtprocess
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/sqlparse/engine/filter_stack.py