Django Project: django.db.backends.oracle.base.OracleParam Class Reference
django.db.backends.oracle.base.OracleParam Class Reference
Public Member Functions
__init__ (self, param, cursor, strings_only=False)
Public Attributes
force_bytes
input_size
Detailed Description
Wrapper object for formatting parameters for Oracle. If the string
representation of the value is large enough (greater than 4000 characters)
the input size needs to be set as CLOB. Alternatively, if the parameter
has an `input_size` attribute, then the value of the `input_size` attribute
will be used instead. Otherwise, no input size will be set for the
parameter when executing the query.
Constructor & Destructor Documentation
__init__()
django.db.backends.oracle.base.OracleParam.__init__ (self, param, cursor, strings_only = False)
Referenced by setuptools._vendor.typing_extensions._ProtocolMeta.__init__(), pip._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.ordered_set.OrderedSet.__setstate__(), and django.db.models.expressions.Expression.identity().
Member Data Documentation
force_bytes
django.db.backends.oracle.base.OracleParam.force_bytes
input_size
django.db.backends.oracle.base.OracleParam.input_size
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/django/db/backends/oracle/base.py