Django Project: pip._vendor.rich.highlighter.NullHighlighter Class Reference
pip._vendor.rich.highlighter.NullHighlighter Class Reference
Public Member Functions
None highlight (self, Text text)
Public Member Functions inherited from pip._vendor.rich.highlighter.Highlighter
Text __call__ (self, Union[str, Text] text)
Detailed Description
A highlighter object that doesn't highlight.
May be used to disable highlighting entirely.
Member Function Documentation
highlight()
None pip._vendor.rich.highlighter.NullHighlighter.highlight (self, Text text)
Nothing to do
Reimplemented from pip._vendor.rich.highlighter.Highlighter.
Referenced by pip._vendor.rich.highlighter.Highlighter.__call__(), pip._vendor.rich.panel.Panel.__rich_console__(), pip._vendor.rich.table.Table.__rich_console__(), pip._vendor.rich.tree.Tree.__rich_console__(), pip._vendor.rich.syntax.Syntax._get_syntax(), and pip._vendor.rich.tree.Tree.add().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/pip/_vendor/rich/highlighter.py