Django Project: pip._vendor.cachecontrol.heuristics.OneDayCache Class Reference
pip._vendor.cachecontrol.heuristics.OneDayCache Class Reference
Public Member Functions
dict[str, str] update_headers (self, HTTPResponse response)
Public Member Functions inherited from pip._vendor.cachecontrol.heuristics.BaseHeuristic
str|None warning (self, HTTPResponse response)
HTTPResponse apply (self, HTTPResponse response)
Detailed Description
Cache the response by providing an expires 1 day in the
future.
Member Function Documentation
update_headers()
dict[str, str] pip._vendor.cachecontrol.heuristics.OneDayCache.update_headers (self, HTTPResponse response)
Update the response headers with any new headers.
NOTE: This SHOULD always include some Warning header to
      signify that the response was cached by the client, not
      by way of the provided headers.
Reimplemented from pip._vendor.cachecontrol.heuristics.BaseHeuristic.
References pip._vendor.cachecontrol.heuristics.datetime_to_header(), and pip._vendor.cachecontrol.heuristics.expire_after().
Referenced by pip._vendor.cachecontrol.heuristics.BaseHeuristic.apply().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/pip/_vendor/cachecontrol/heuristics.py