Django Project: cryptography.x509.base.RevokedCertificate Class Reference
cryptography.x509.base.RevokedCertificate Class Reference
Public Member Functions
int serial_number (self)
datetime.datetime revocation_date (self)
datetime.datetime revocation_date_utc (self)
Extensions extensions (self)
Member Function Documentation
extensions()
Extensions cryptography.x509.base.RevokedCertificate.extensions (self)
Returns an Extensions object containing a list of Revoked extensions.
Reimplemented in cryptography.x509.base._RawRevokedCertificate.
Referenced by setuptools._distutils.command.build_ext.build_ext._build_extensions_serial(), setuptools.command.build_ext.build_ext._get_output_mapping(), setuptools._distutils.command.build_ext.build_ext.build_extensions(), setuptools._distutils.command.build_ext.build_ext.finalize_options(), setuptools.command.build_ext.build_ext.finalize_options(), django.core.management.commands.makemessages.Command.find_files(), setuptools._distutils.command.build_ext.build_ext.get_outputs(), setuptools._distutils.command.build_ext.build_ext.get_source_files(), and setuptools._distutils.command.build_ext.build_ext.run().
revocation_date()
datetime.datetime cryptography.x509.base.RevokedCertificate.revocation_date (self)
Returns the date of when this certificate was revoked.
Reimplemented in cryptography.x509.base._RawRevokedCertificate.
revocation_date_utc()
datetime.datetime cryptography.x509.base.RevokedCertificate.revocation_date_utc (self)
Returns the date of when this certificate was revoked as a non-naive
UTC datetime.
Reimplemented in cryptography.x509.base._RawRevokedCertificate.
serial_number()
int cryptography.x509.base.RevokedCertificate.serial_number (self)
Returns the serial number of the revoked certificate.
Reimplemented in cryptography.x509.base._RawRevokedCertificate.
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/cryptography/x509/base.py