Django Project: whitenoise.runserver_nostatic.management.commands.runserver.Command Class Reference
whitenoise.runserver_nostatic.management.commands.runserver.Command Class Reference
Public Member Functions
add_arguments (self, parser)
Member Function Documentation
add_arguments()
whitenoise.runserver_nostatic.management.commands.runserver.Command.add_arguments (self, parser)
References whitenoise.runserver_nostatic.management.commands.runserver.Command.add_arguments().
Referenced by whitenoise.runserver_nostatic.management.commands.runserver.Command.add_arguments(), and django.core.management.base.BaseCommand.create_parser().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/whitenoise/runserver_nostatic/management/commands/runserver.py