Django Project: pkg_resources.NullProvider Class Reference
pkg_resources.NullProvider Class Reference
Public Member Functions
__init__ (self, module)
get_resource_filename (self, manager, resource_name)
get_resource_stream (self, manager, resource_name)
get_resource_string (self, manager, resource_name)
has_resource (self, resource_name)
has_metadata (self, name)
get_metadata (self, name)
get_metadata_lines (self, name)
resource_isdir (self, resource_name)
metadata_isdir (self, name)
resource_listdir (self, resource_name)
metadata_listdir (self, name)
run_script (self, script_name, namespace)
Public Attributes
module_path
Static Public Attributes
egg_name = None
egg_info = None
loader = None
Protected Member Functions
_get_metadata_path (self, name)
_has (self, path)
_isdir (self, path)
_listdir (self, path)
_fn (self, base, resource_name)
_get (self, path)
Static Protected Member Functions
_validate_resource_path (path)
Detailed Description
Try to implement resources and metadata for arbitrary PEP 302 loaders
Constructor & Destructor Documentation
__init__()
pkg_resources.NullProvider.__init__ (self, module)
Reimplemented in pkg_resources.EggMetadata, pkg_resources.EggProvider, pkg_resources.EmptyProvider, pkg_resources.FileMetadata, pkg_resources.PathMetadata, and pkg_resources.ZipProvider.
Referenced by setuptools._vendor.typing_extensions._ProtocolMeta.__init__(), pip._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.ordered_set.OrderedSet.__setstate__(), and django.db.models.expressions.Expression.identity().
Member Function Documentation
_fn()
pkg_resources.NullProvider._fn (self, base, resource_name) protected
Referenced by pip._vendor.cachecontrol.caches.file_cache._FileCacheMixin._delete(), pip._vendor.cachecontrol.caches.file_cache._FileCacheMixin.get(), pip._vendor.cachecontrol.caches.file_cache.SeparateBodyFileCache.get_body(), pip._vendor.cachecontrol.caches.file_cache._FileCacheMixin.set(), and pip._vendor.cachecontrol.caches.file_cache.SeparateBodyFileCache.set_body().
_get()
pkg_resources.NullProvider._get (self, path) protected
Reimplemented in pkg_resources.DefaultProvider, and pkg_resources.EmptyProvider.
Referenced by django.contrib.messages.storage.base.BaseStorage._loaded_messages(), django.contrib.sitemaps.Sitemap._location(), and django.contrib.sitemaps.Sitemap._urls().
_get_metadata_path()
pkg_resources.NullProvider._get_metadata_path (self, name) protected
Reimplemented in pkg_resources.FileMetadata.
_has()
pkg_resources.NullProvider._has (self, path) protected
Reimplemented in pkg_resources.DefaultProvider, and pkg_resources.ZipProvider.
_isdir()
pkg_resources.NullProvider._isdir (self, path) protected
Reimplemented in pkg_resources.DefaultProvider, and pkg_resources.ZipProvider.
_listdir()
pkg_resources.NullProvider._listdir (self, path) protected
Reimplemented in pkg_resources.DefaultProvider, pkg_resources.EmptyProvider, and pkg_resources.ZipProvider.
_validate_resource_path()
pkg_resources.NullProvider._validate_resource_path (path) static protected
Validate the resource paths according to the docs.
https://setuptools.pypa.io/en/latest/pkg_resources.html#basic-resource-access
>>> warned = getfixture('recwarn')
>>> warnings.simplefilter('always')
>>> vrp = NullProvider._validate_resource_path
>>> vrp('foo/bar.txt')
>>> bool(warned)
False
>>> vrp('../foo/bar.txt')
>>> bool(warned)
True
>>> warned.clear()
>>> vrp('/foo/bar.txt')
>>> bool(warned)
True
>>> vrp('foo/../../bar.txt')
>>> bool(warned)
True
>>> warned.clear()
>>> vrp('foo/f../bar.txt')
>>> bool(warned)
False
Windows path separators are straight-up disallowed.
>>> vrp(r'\\foo/bar.txt')
Traceback (most recent call last):
...
ValueError: Use of .. or absolute path in a resource path \
is not allowed.
>>> vrp(r'C:\\foo/bar.txt')
Traceback (most recent call last):
...
ValueError: Use of .. or absolute path in a resource path \
is not allowed.
Blank values are allowed
>>> vrp('')
>>> bool(warned)
False
Non-string values are not.
>>> vrp(None)
Traceback (most recent call last):
...
AttributeError: ...
get_metadata()
pkg_resources.NullProvider.get_metadata (self, name)
Reimplemented in pkg_resources.FileMetadata.
Referenced by pip._internal.metadata.pkg_resources.InMemoryMetadata.get_metadata_lines().
get_metadata_lines()
pkg_resources.NullProvider.get_metadata_lines (self, name)
Reimplemented in pkg_resources.FileMetadata.
get_resource_filename()
pkg_resources.NullProvider.get_resource_filename (self, manager, resource_name)
Reimplemented in pkg_resources.ZipProvider.
get_resource_stream()
pkg_resources.NullProvider.get_resource_stream (self, manager, resource_name)
Reimplemented in pkg_resources.DefaultProvider.
get_resource_string()
pkg_resources.NullProvider.get_resource_string (self, manager, resource_name)
has_metadata()
pkg_resources.NullProvider.has_metadata (self, name)
Reimplemented in pkg_resources.FileMetadata.
has_resource()
pkg_resources.NullProvider.has_resource (self, resource_name)
metadata_isdir()
pkg_resources.NullProvider.metadata_isdir (self, name)
metadata_listdir()
pkg_resources.NullProvider.metadata_listdir (self, name)
resource_isdir()
pkg_resources.NullProvider.resource_isdir (self, resource_name)
resource_listdir()
pkg_resources.NullProvider.resource_listdir (self, resource_name)
run_script()
pkg_resources.NullProvider.run_script (self, script_name, namespace)
Member Data Documentation
egg_info
pkg_resources.NullProvider.egg_info = None static
Referenced by setuptools.command.egg_info.egg_info.check_broken_egg_info(), setuptools.command.bdist_egg.bdist_egg.copy_metadata_to(), setuptools.command.egg_info.egg_info.egg_info, setuptools.command.egg_info.egg_info.finalize_options(), setuptools.command.egg_info.egg_info.find_sources(), setuptools.command.dist_info.dist_info.run(), and setuptools.command.egg_info.egg_info.run().
egg_name
pkg_resources.NullProvider.egg_name = None static
Referenced by setuptools.command.egg_info.egg_info.check_broken_egg_info(), and setuptools.command.egg_info.egg_info.finalize_options().
loader
pkg_resources.NullProvider.loader = None static
Referenced by django.template.base.Origin.__eq__(), pip._vendor.distlib.resources.ZipResourceFinder.__init__(), django.db.migrations.executor.MigrationExecutor._create_project_state(), pip._vendor.distlib.resources.ZipResourceFinder._find(), django.db.migrations.executor.MigrationExecutor._migrate_all_backwards(), django.db.migrations.executor.MigrationExecutor.check_replacements(), django.db.migrations.executor.MigrationExecutor.detect_soft_applied(), pip._vendor.distlib.resources.ZipResourceFinder.get_bytes(), pip._vendor.distlib.resources.ZipResourceFinder.get_cache_info(), django.template.base.Origin.loader_name(), django.db.migrations.executor.MigrationExecutor.migrate(), and django.db.migrations.executor.MigrationExecutor.migration_plan().
module_path
pkg_resources.NullProvider.module_path
Referenced by _pytest.assertion.rewrite.AssertionRewriter.visit_Assert().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/pkg_resources/__init__.py