Django Project: pip._vendor.tenacity.wait.wait_fixed Class Reference
pip._vendor.tenacity.wait.wait_fixed Class Reference
Public Member Functions
None __init__ (self, _utils.time_unit_type wait)
float __call__ (self, "RetryCallState" retry_state)
Public Member Functions inherited from pip._vendor.tenacity.wait.wait_base
"wait_combine" __add__ (self, "wait_base" other)
typing.Union["wait_combine", "wait_base"] __radd__ (self, "wait_base" other)
Public Attributes
wait_fixed
Detailed Description
Wait strategy that waits a fixed amount of time between each retry.
Constructor & Destructor Documentation
__init__()
None pip._vendor.tenacity.wait.wait_fixed.__init__ (self, _utils.time_unit_type wait)
Reimplemented in pip._vendor.tenacity.wait.wait_none.
Referenced by setuptools._vendor.typing_extensions._ProtocolMeta.__init__(), pip._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.ordered_set.OrderedSet.__setstate__(), and django.db.models.expressions.Expression.identity().
Member Function Documentation
__call__()
float pip._vendor.tenacity.wait.wait_fixed.__call__ (self, "RetryCallState" retry_state)
Reimplemented from pip._vendor.tenacity.wait.wait_base.
References pip._vendor.tenacity.wait.wait_fixed.wait_fixed.
Referenced by asgiref.sync.AsyncToSync.__get__(), and asgiref.sync.SyncToAsync.__get__().
Member Data Documentation
wait_fixed
pip._vendor.tenacity.wait.wait_fixed.wait_fixed
References pip._vendor.tenacity.wait.wait_fixed.wait_fixed.
Referenced by pip._vendor.tenacity.wait.wait_fixed.__call__(), and pip._vendor.tenacity.wait.wait_fixed.wait_fixed.
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/pip/_vendor/tenacity/wait.py