Django Project: pip._vendor.chardet.jpcntx.SJISContextAnalysis Class Reference
pip._vendor.chardet.jpcntx.SJISContextAnalysis Class Reference
Public Member Functions
None __init__ (self)
str charset_name (self)
Tuple[int, int] get_order (self, Union[bytes, bytearray] byte_str)
Public Member Functions inherited from pip._vendor.chardet.jpcntx.JapaneseContextAnalysis
None reset (self)
None feed (self, Union[bytes, bytearray] byte_str, int num_bytes)
bool got_enough_data (self)
float get_confidence (self)
Protected Attributes
_charset_name
Protected Attributes inherited from pip._vendor.chardet.jpcntx.JapaneseContextAnalysis
_total_rel
List[int] _rel_sample
_need_to_skip_char_num
_last_char_order
_done
Additional Inherited Members
Static Public Attributes inherited from pip._vendor.chardet.jpcntx.JapaneseContextAnalysis
int NUM_OF_CATEGORY = 6
int DONT_KNOW = -1
int ENOUGH_REL_THRESHOLD = 100
int MAX_REL_THRESHOLD = 1000
int MINIMUM_DATA_THRESHOLD = 4
Constructor & Destructor Documentation
__init__()
None pip._vendor.chardet.jpcntx.SJISContextAnalysis.__init__ (self)
Reimplemented from pip._vendor.chardet.jpcntx.JapaneseContextAnalysis.
References pip._vendor.chardet.jpcntx.SJISContextAnalysis.__init__().
Referenced by pip._vendor.chardet.jpcntx.SJISContextAnalysis.__init__(), setuptools._vendor.typing_extensions._ProtocolMeta.__init__(), pip._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.ordered_set.OrderedSet.__setstate__(), and django.db.models.expressions.Expression.identity().
Member Function Documentation
charset_name()
str pip._vendor.chardet.jpcntx.SJISContextAnalysis.charset_name (self)
References pip._vendor.chardet.jpcntx.SJISContextAnalysis._charset_name.
get_order()
Tuple[int, int] pip._vendor.chardet.jpcntx.SJISContextAnalysis.get_order (self, Union[bytes, bytearray] byte_str)
Reimplemented from pip._vendor.chardet.jpcntx.JapaneseContextAnalysis.
References pip._vendor.chardet.jpcntx.SJISContextAnalysis._charset_name.
Referenced by pip._vendor.chardet.chardistribution.CharDistributionAnalysis.feed(), and pip._vendor.chardet.jpcntx.JapaneseContextAnalysis.feed().
Member Data Documentation
_charset_name
pip._vendor.chardet.jpcntx.SJISContextAnalysis._charset_name protected
Referenced by pip._vendor.chardet.jpcntx.SJISContextAnalysis.charset_name(), and pip._vendor.chardet.jpcntx.SJISContextAnalysis.get_order().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/pip/_vendor/chardet/jpcntx.py