Django Project: setuptools._vendor.importlib_metadata._meta.PackageMetadata Class Reference
setuptools._vendor.importlib_metadata._meta.PackageMetadata Class Reference
Public Member Functions
int __len__ (self)
bool __contains__ (self, str item)
str __getitem__ (self, str key)
Iterator[str] __iter__ (self)
Union[List[Any], _T] get_all (self, str name, _T failobj=...)
Dict[str, Union[str, List[str]]] json (self)
Public Member Functions inherited from setuptools._vendor.typing_extensions.Protocol
__new__ (cls, *args, **kwds)
__class_getitem__ (cls, params)
__init_subclass__ (cls, *args, **kwargs)
__new__ (cls, *args, **kwds)
Public Member Functions inherited from setuptools._vendor.typing_extensions._ProtocolMeta
__instancecheck__ (cls, instance)
__init__ (cls, *args, **kwargs)
__instancecheck__ (self, instance)
__subclasscheck__ (self, cls)
Additional Inherited Members
Protected Attributes inherited from setuptools._vendor.typing_extensions._ProtocolMeta
_is_protocol
_abc_registry
_abc_cache
Static Protected Attributes inherited from setuptools._vendor.typing_extensions.Protocol
bool _is_protocol = True
Member Function Documentation
__contains__()
bool setuptools._vendor.importlib_metadata._meta.PackageMetadata.__contains__ (self, str item)
__getitem__()
str setuptools._vendor.importlib_metadata._meta.PackageMetadata.__getitem__ (self, str key)
Reimplemented from setuptools._vendor.typing_extensions._ProtocolMeta.
Referenced by django.test.utils.ContextList.get().
__iter__()
Iterator[str] setuptools._vendor.importlib_metadata._meta.PackageMetadata.__iter__ (self)
Referenced by django.db.models.query.BaseIterable._async_generator().
__len__()
int setuptools._vendor.importlib_metadata._meta.PackageMetadata.__len__ (self)
Referenced by waitress.buffers.OverflowableBuffer.__bool__().
get_all()
Union[List[Any], _T] setuptools._vendor.importlib_metadata._meta.PackageMetadata.get_all (self, str name, _T failobj = ...)
Return all values associated with a possibly multi-valued key.
Referenced by setuptools._vendor.importlib_metadata._adapters.Message.json().
json()
Dict[str, Union[str, List[str]]] setuptools._vendor.importlib_metadata._meta.PackageMetadata.json (self)
A JSON-compatible form of the metadata.
Referenced by pip._vendor.requests.models.Request.prepare().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/setuptools/_vendor/importlib_metadata/_meta.py