Django Project: django.db.models.enums.Choices Class Reference
django.db.models.enums.Choices Class Reference
Public Member Functions
do_not_call_in_templates (self)
label (self)
__repr__ (self)
Public Member Functions inherited from django.db.models.enums.ChoicesType
__new__ (metacls, classname, bases, classdict, **kwds)
__contains__ (cls, member)
names (cls)
choices (cls)
labels (cls)
values (cls)
Static Public Attributes
do_not_call_in_templates = enum.nonmember(True)
Detailed Description
Class for creating enumerated choices.
Member Function Documentation
__repr__()
django.db.models.enums.Choices.__repr__ (self)
do_not_call_in_templates()
django.db.models.enums.Choices.do_not_call_in_templates (self)
label()
django.db.models.enums.Choices.label (self)
Referenced by django.apps.config.AppConfig.__repr__(), django.core.management.base.LabelCommand.add_arguments(), django.apps.config.AppConfig.get_model(), django.apps.config.AppConfig.import_models(), django.db.migrations.state.AppConfigStub.import_models(), and django.forms.boundfield.BoundField.label_tag().
Member Data Documentation
do_not_call_in_templates
django.db.models.enums.Choices.do_not_call_in_templates = enum.nonmember(True) static
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/django/db/models/enums.py