Django Project: cryptography.hazmat.primitives.padding.PaddingContext Class Reference
cryptography.hazmat.primitives.padding.PaddingContext Class Reference
Public Member Functions
bytes update (self, bytes data)
bytes finalize (self)
Member Function Documentation
finalize()
bytes cryptography.hazmat.primitives.padding.PaddingContext.finalize (self)
Finalize the padding, returns bytes.
Reimplemented in cryptography.hazmat.primitives.padding._ANSIX923PaddingContext, cryptography.hazmat.primitives.padding._ANSIX923UnpaddingContext, cryptography.hazmat.primitives.padding._PKCS7PaddingContext, and cryptography.hazmat.primitives.padding._PKCS7UnpaddingContext.
Referenced by cryptography.hazmat.backends.openssl.ciphers._CipherContext.finalize_with_tag(), and _pytest.junitxml.LogXML.pytest_runtest_logreport().
update()
bytes cryptography.hazmat.primitives.padding.PaddingContext.update (self, bytes data)
Pads the provided bytes and returns any available data as bytes.
Reimplemented in cryptography.hazmat.primitives.padding._ANSIX923PaddingContext, cryptography.hazmat.primitives.padding._ANSIX923UnpaddingContext, cryptography.hazmat.primitives.padding._PKCS7PaddingContext, and cryptography.hazmat.primitives.padding._PKCS7UnpaddingContext.
Referenced by pip._vendor.rich.progress.Progress.open(), pip._vendor.rich.progress.Progress.track(), and pip._vendor.rich.progress.Progress.wrap_file().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/cryptography/hazmat/primitives/padding.py