Django Project: cryptography.hazmat.primitives.ciphers.modes.ModeWithAuthenticationTag Class Reference
cryptography.hazmat.primitives.ciphers.modes.ModeWithAuthenticationTag Class Reference
Public Member Functions
bytes|None tag (self)
Public Member Functions inherited from cryptography.hazmat.primitives.ciphers.modes.Mode
str name (self)
None validate_for_algorithm (self, CipherAlgorithm algorithm)
Member Function Documentation
tag()
bytes | None cryptography.hazmat.primitives.ciphers.modes.ModeWithAuthenticationTag.tag (self)
The value of the tag supplied to the constructor of this mode.
Reimplemented in cryptography.hazmat.primitives.ciphers.modes.GCM.
Referenced by django.forms.boundfield.BoundWidget.__str__(), cryptography.hazmat.backends.openssl.ciphers._CipherContext.finalize(), django.template.library.Library.inclusion_tag(), django.template.library.Library.simple_tag(), and django.template.library.Library.tag().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/cryptography/hazmat/primitives/ciphers/modes.py