Django Project: cryptography.x509.base.CertificateRevocationList Class Reference
cryptography.x509.base.CertificateRevocationList Class Reference
Public Member Functions
bytes public_bytes (self, serialization.Encoding encoding)
bytes fingerprint (self, hashes.HashAlgorithm algorithm)
RevokedCertificate|None get_revoked_certificate_by_serial_number (self, int serial_number)
hashes.HashAlgorithm|None signature_hash_algorithm (self)
ObjectIdentifier signature_algorithm_oid (self)
None|padding.PSS|padding.PKCS1v15|ec.ECDSA signature_algorithm_parameters (self)
Name issuer (self)
datetime.datetime|None next_update (self)
datetime.datetime|None next_update_utc (self)
datetime.datetime last_update (self)
datetime.datetime last_update_utc (self)
Extensions extensions (self)
bytes signature (self)
bytes tbs_certlist_bytes (self)
bool __eq__ (self, object other)
int __len__ (self)
RevokedCertificate __getitem__ (self, int idx)
list[RevokedCertificate] __getitem__ (self, slice idx)
RevokedCertificate|list[RevokedCertificate] __getitem__ (self, int|slice idx)
typing.Iterator[RevokedCertificate] __iter__ (self)
bool is_signature_valid (self, CertificateIssuerPublicKeyTypes public_key)
Member Function Documentation
__eq__()
bool cryptography.x509.base.CertificateRevocationList.__eq__ (self, object other)
Checks equality.
Referenced by _pytest.python_api.ApproxScalar.__eq__(), pip._vendor.distlib.version.Version.__ge__(), pip._vendor.distlib.version.Version.__gt__(), pip._vendor.distlib.version.Version.__le__(), pip._vendor.distlib.version.Matcher.__ne__(), pip._vendor.distlib.version.Version.__ne__(), pip._vendor.msgpack.ext.Timestamp.__ne__(), and pip._vendor.urllib3._collections.HTTPHeaderDict.__ne__().
__getitem__() [1/3]
RevokedCertificate cryptography.x509.base.CertificateRevocationList.__getitem__ (self, int idx)
Referenced by django.test.utils.ContextList.get().
__getitem__() [2/3]
RevokedCertificate | list[RevokedCertificate] cryptography.x509.base.CertificateRevocationList.__getitem__ (self, int | slice idx)
Returns a revoked certificate (or slice of revoked certificates).
Referenced by django.test.utils.ContextList.get().
__getitem__() [3/3]
list[RevokedCertificate] cryptography.x509.base.CertificateRevocationList.__getitem__ (self, slice idx)
Referenced by django.test.utils.ContextList.get().
__iter__()
typing.Iterator[RevokedCertificate] cryptography.x509.base.CertificateRevocationList.__iter__ (self)
Iterator over the revoked certificates
Referenced by django.db.models.query.BaseIterable._async_generator().
__len__()
int cryptography.x509.base.CertificateRevocationList.__len__ (self)
Number of revoked certificates in the CRL.
Referenced by waitress.buffers.OverflowableBuffer.__bool__().
extensions()
Extensions cryptography.x509.base.CertificateRevocationList.extensions (self)
Returns an Extensions object containing a list of CRL extensions.
Referenced by setuptools._distutils.command.build_ext.build_ext._build_extensions_serial(), setuptools.command.build_ext.build_ext._get_output_mapping(), setuptools._distutils.command.build_ext.build_ext.build_extensions(), setuptools._distutils.command.build_ext.build_ext.finalize_options(), setuptools.command.build_ext.build_ext.finalize_options(), django.core.management.commands.makemessages.Command.find_files(), setuptools._distutils.command.build_ext.build_ext.get_outputs(), setuptools._distutils.command.build_ext.build_ext.get_source_files(), and setuptools._distutils.command.build_ext.build_ext.run().
fingerprint()
bytes cryptography.x509.base.CertificateRevocationList.fingerprint (self, hashes.HashAlgorithm algorithm)
Returns bytes using digest passed.
get_revoked_certificate_by_serial_number()
RevokedCertificate | None cryptography.x509.base.CertificateRevocationList.get_revoked_certificate_by_serial_number (self, int serial_number)
Returns an instance of RevokedCertificate or None if the serial_number
is not in the CRL.
is_signature_valid()
bool cryptography.x509.base.CertificateRevocationList.is_signature_valid (self, CertificateIssuerPublicKeyTypes public_key)
Verifies signature of revocation list against given public key.
issuer()
Name cryptography.x509.base.CertificateRevocationList.issuer (self)
Returns the X509Name with the issuer of this CRL.
last_update()
datetime.datetime cryptography.x509.base.CertificateRevocationList.last_update (self)
Returns the date of last update for this CRL.
last_update_utc()
datetime.datetime cryptography.x509.base.CertificateRevocationList.last_update_utc (self)
Returns the date of last update for this CRL as a non-naive UTC
datetime.
next_update()
datetime.datetime | None cryptography.x509.base.CertificateRevocationList.next_update (self)
Returns the date of next update for this CRL.
next_update_utc()
datetime.datetime | None cryptography.x509.base.CertificateRevocationList.next_update_utc (self)
Returns the date of next update for this CRL as a non-naive UTC
datetime.
public_bytes()
bytes cryptography.x509.base.CertificateRevocationList.public_bytes (self, serialization.Encoding encoding)
Serializes the CRL to PEM or DER format.
signature()
bytes cryptography.x509.base.CertificateRevocationList.signature (self)
Returns the signature bytes.
Referenced by django.core.signing.Signer.sign(), django_cryptography.core.signing.BytesSigner.sign(), django_cryptography.core.signing.FernetSigner.sign(), django.core.signing.Signer.unsign(), django_cryptography.core.signing.BytesSigner.unsign(), django_cryptography.core.signing.FernetSigner.unsign(), and django_cryptography.core.signing.Signer.unsign().
signature_algorithm_oid()
ObjectIdentifier cryptography.x509.base.CertificateRevocationList.signature_algorithm_oid (self)
Returns the ObjectIdentifier of the signature algorithm.
signature_algorithm_parameters()
None | padding.PSS | padding.PKCS1v15 | ec.ECDSA cryptography.x509.base.CertificateRevocationList.signature_algorithm_parameters (self)
Returns the signature algorithm parameters.
signature_hash_algorithm()
hashes.HashAlgorithm | None cryptography.x509.base.CertificateRevocationList.signature_hash_algorithm (self)
Returns a HashAlgorithm corresponding to the type of the digest signed
in the certificate.
tbs_certlist_bytes()
bytes cryptography.x509.base.CertificateRevocationList.tbs_certlist_bytes (self)
Returns the tbsCertList payload bytes as defined in RFC 5280.
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/cryptography/x509/base.py