Django Project: pip._vendor.pkg_resources.EmptyProvider Class Reference
pip._vendor.pkg_resources.EmptyProvider Class Reference
Public Member Functions
__init__ (self)
Public Member Functions inherited from pip._vendor.pkg_resources.NullProvider
get_resource_filename (self, manager, resource_name)
get_resource_stream (self, manager, resource_name)
get_resource_string (self, manager, resource_name)
has_resource (self, resource_name)
has_metadata (self, name)
get_metadata (self, name)
get_metadata_lines (self, name)
resource_isdir (self, resource_name)
metadata_isdir (self, name)
resource_listdir (self, resource_name)
metadata_listdir (self, name)
run_script (self, script_name, namespace)
Static Public Attributes
module_path = None
Static Public Attributes inherited from pip._vendor.pkg_resources.NullProvider
egg_name = None
egg_info = None
loader = None
Protected Member Functions
_get (self, path)
_listdir (self, path)
Protected Member Functions inherited from pip._vendor.pkg_resources.NullProvider
_get_metadata_path (self, name)
_has (self, path)
_isdir (self, path)
_fn (self, base, resource_name)
Static Protected Attributes
False _isdir = lambda self, path
Additional Inherited Members
Public Attributes inherited from pip._vendor.pkg_resources.NullProvider
module_path
Static Protected Member Functions inherited from pip._vendor.pkg_resources.NullProvider
_validate_resource_path (path)
Detailed Description
Provider that returns nothing for all requests
Constructor & Destructor Documentation
__init__()
pip._vendor.pkg_resources.EmptyProvider.__init__ (self)
Reimplemented from pip._vendor.pkg_resources.NullProvider.
Reimplemented in pip._vendor.pkg_resources.FileMetadata.
Referenced by setuptools._vendor.typing_extensions._ProtocolMeta.__init__(), pip._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.ordered_set.OrderedSet.__setstate__(), and django.db.models.expressions.Expression.identity().
Member Function Documentation
_get()
pip._vendor.pkg_resources.EmptyProvider._get (self, path) protected
Reimplemented from pip._vendor.pkg_resources.NullProvider.
Referenced by django.contrib.messages.storage.base.BaseStorage._loaded_messages(), django.contrib.sitemaps.Sitemap._location(), and django.contrib.sitemaps.Sitemap._urls().
_listdir()
pip._vendor.pkg_resources.EmptyProvider._listdir (self, path) protected
Reimplemented from pip._vendor.pkg_resources.NullProvider.
Member Data Documentation
_isdir
False pip._vendor.pkg_resources.EmptyProvider._isdir = lambda self, path static protected
module_path
pip._vendor.pkg_resources.EmptyProvider.module_path = None static
Referenced by _pytest.assertion.rewrite.AssertionRewriter.visit_Assert().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/pip/_vendor/pkg_resources/__init__.py