Django Project: graphviz.dot.DigraphSyntax Class Reference
graphviz.dot.DigraphSyntax Class Reference
Static Protected Attributes
_head = staticmethod(digraph_head)
_edge = staticmethod(digraph_edge)
Detailed Description
DOT digraph head and edge syntax.
Member Data Documentation
_edge
graphviz.dot.DigraphSyntax._edge = staticmethod(digraph_edge) static protected
Referenced by graphviz.dot.Dot._edge_plain(), and graphviz.dot.Dot.edge().
_head
graphviz.dot.DigraphSyntax._head = staticmethod(digraph_head) static protected
Referenced by graphviz.dot.Dot.__iter__().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/graphviz/dot.py