Django Project: django.utils.html.Urlizer Class Reference
django.utils.html.Urlizer Class Reference
Public Member Functions
__call__ (self, text, trim_url_limit=None, nofollow=False, autoescape=False)
handle_word (self, word, *, safe_input, trim_url_limit=None, nofollow=False, autoescape=False)
trim_url (self, x, *, limit)
trim_punctuation (self, word)
Static Public Member Functions
is_email_simple (value)
Static Public Attributes
str trailing_punctuation_chars = ".,:;!"
list wrapping_punctuation = [("(", ")"), ("[", "]")]
simple_url_re = _lazy_re_compile(r"^https?://\[?\w", re.IGNORECASE)
simple_url_2_re
word_split_re = _lazy_re_compile()
str mailto_template = "mailto:{local}@{domain}"
str url_template = '<a href="{href}"{attrs}>{url}</a>'
Detailed Description
Convert any URLs in text into clickable links.
Work on http://, https://, www. links, and also on links ending in one of
the original seven gTLDs (.com, .edu, .gov, .int, .mil, .net, and .org).
Links can have trailing punctuation (periods, commas, close-parens) and
leading punctuation (opening parens) and it'll still do the right thing.
Member Function Documentation
__call__()
django.utils.html.Urlizer.__call__ (self, text, trim_url_limit = None, nofollow = False, autoescape = False)
If trim_url_limit is not None, truncate the URLs in the link text
longer than this limit to trim_url_limit - 1 characters and append an
ellipsis.
If nofollow is True, give the links a rel="nofollow" attribute.
If autoescape is True, autoescape the link text and URLs.
References django.utils.html.Urlizer.handle_word(), and django.utils.html.Urlizer.word_split_re.
Referenced by asgiref.sync.AsyncToSync.__get__(), and asgiref.sync.SyncToAsync.__get__().
handle_word()
django.utils.html.Urlizer.handle_word (self, word, * , safe_input, trim_url_limit = None, nofollow = False, autoescape = False)
References django.utils.html.Urlizer.is_email_simple(), django.utils.html.Urlizer.mailto_template, django.utils.html.Urlizer.simple_url_2_re, django.utils.html.Urlizer.simple_url_re, django.utils.html.Urlizer.trim_punctuation(), django.utils.html.Urlizer.trim_url(), and django.utils.html.Urlizer.url_template.
Referenced by django.utils.html.Urlizer.__call__().
is_email_simple()
django.utils.html.Urlizer.is_email_simple (value) static
Return True if value looks like an email address.
Referenced by django.utils.html.Urlizer.handle_word().
trim_punctuation()
django.utils.html.Urlizer.trim_punctuation (self, word)
Trim trailing and wrapping punctuation from `word`. Return the items of
the new state.
References django.utils.html.Urlizer.trailing_punctuation_chars, and django.utils.html.Urlizer.wrapping_punctuation.
Referenced by django.utils.html.Urlizer.handle_word().
trim_url()
django.utils.html.Urlizer.trim_url (self, x, * , limit)
Referenced by django.utils.html.Urlizer.handle_word().
Member Data Documentation
mailto_template
str django.utils.html.Urlizer.mailto_template = "mailto:{local}@{domain}" static
Referenced by django.utils.html.Urlizer.handle_word().
simple_url_2_re
django.utils.html.Urlizer.simple_url_2_re static
Initial value:
=  _lazy_re_compile(
        r"^www\.|^(?!http)\w[^@]+\.(com|edu|gov|int|mil|net|org)($|/.*)$", re.IGNORECASE
    )
Referenced by django.utils.html.Urlizer.handle_word().
simple_url_re
django.utils.html.Urlizer.simple_url_re = _lazy_re_compile(r"^https?://\[?\w", re.IGNORECASE) static
Referenced by django.utils.html.Urlizer.handle_word().
trailing_punctuation_chars
str django.utils.html.Urlizer.trailing_punctuation_chars = ".,:;!" static
Referenced by django.utils.html.Urlizer.trim_punctuation().
url_template
str django.utils.html.Urlizer.url_template = '<a href="{href}"{attrs}>{url}</a>' static
Referenced by django.utils.html.Urlizer.handle_word().
word_split_re
django.utils.html.Urlizer.word_split_re = _lazy_re_compile() static
Referenced by django.utils.html.Urlizer.__call__().
wrapping_punctuation
list django.utils.html.Urlizer.wrapping_punctuation = [("(", ")"), ("[", "]")] static
Referenced by django.utils.html.Urlizer.trim_punctuation().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/django/utils/html.py