Django Project: _pytest.outcomes.Skipped Class Reference
_pytest.outcomes.Skipped Class Reference
Public Member Functions
None __init__ (self, str|None msg=None, bool pytrace=True, bool allow_module_level=False, *, bool _use_item_location=False)
Public Member Functions inherited from _pytest.outcomes.OutcomeException
str __repr__ (self)
Public Attributes
allow_module_level
Public Attributes inherited from _pytest.outcomes.OutcomeException
msg
pytrace
Protected Attributes
_use_item_location
Constructor & Destructor Documentation
__init__()
None _pytest.outcomes.Skipped.__init__ (self, str | None msg = None, bool pytrace = True, bool allow_module_level = False, * , bool _use_item_location = False)
Reimplemented from _pytest.outcomes.OutcomeException.
References _pytest.outcomes.Skipped.__init__().
Referenced by _pytest.outcomes.Skipped.__init__(), setuptools._vendor.typing_extensions._ProtocolMeta.__init__(), pip._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.ordered_set.OrderedSet.__setstate__(), and django.db.models.expressions.Expression.identity().
Member Data Documentation
_use_item_location
_pytest.outcomes.Skipped._use_item_location protected
allow_module_level
_pytest.outcomes.Skipped.allow_module_level
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/_pytest/outcomes.py