Django Project: django.template.exceptions.TemplateDoesNotExist Class Reference
django.template.exceptions.TemplateDoesNotExist Class Reference
Public Member Functions
__init__ (self, msg, tried=None, backend=None, chain=None)
Public Attributes
backend
tried
chain
Detailed Description
The exception used when a template does not exist. Optional arguments:
backend
    The template backend class used when raising this exception.
tried
    A list of sources that were tried when finding the template. This
    is formatted as a list of tuples containing (origin, status), where
    origin is an Origin object or duck type and status is a string with the
    reason the template wasn't found.
chain
    A list of intermediate TemplateDoesNotExist exceptions. This is used to
    encapsulate multiple exceptions when loading templates from multiple
    engines.
Constructor & Destructor Documentation
__init__()
django.template.exceptions.TemplateDoesNotExist.__init__ (self, msg, tried = None, backend = None, chain = None)
Referenced by setuptools._vendor.typing_extensions._ProtocolMeta.__init__(), pip._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.ordered_set.OrderedSet.__setstate__(), and django.db.models.expressions.Expression.identity().
Member Data Documentation
backend
django.template.exceptions.TemplateDoesNotExist.backend
Referenced by django.forms.renderers.EngineMixin.engine(), django.template.backends.django.Template.render(), and django.template.backends.jinja2.Template.render().
chain
django.template.exceptions.TemplateDoesNotExist.chain
Referenced by _pytest._code.code.ExceptionChainRepr.__init__(), _pytest._code.code.FormattedExcinfo.repr_excinfo(), and _pytest._code.code.ExceptionChainRepr.toterminal().
tried
django.template.exceptions.TemplateDoesNotExist.tried
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/django/template/exceptions.py