Django Project: pip._internal.build_env.NoOpBuildEnvironment Class Reference
pip._internal.build_env.NoOpBuildEnvironment Class Reference
Public Member Functions
None __init__ (self)
None __enter__ (self)
None __exit__ (self, Optional[Type[BaseException]] exc_type, Optional[BaseException] exc_val, Optional[TracebackType] exc_tb)
None cleanup (self)
None install_requirements (self, "PackageFinder" finder, Iterable[str] requirements, str prefix_as_string, *, str kind)
Public Member Functions inherited from pip._internal.build_env.BuildEnvironment
Tuple[Set[Tuple[str, str]], Set[str]] check_requirements (self, Iterable[str] reqs)
Additional Inherited Members
Static Protected Member Functions inherited from pip._internal.build_env.BuildEnvironment
None _install_requirements (str pip_runnable, "PackageFinder" finder, Iterable[str] requirements, _Prefix prefix, *, str kind)
Protected Attributes inherited from pip._internal.build_env.BuildEnvironment
_prefixes
List[str] _bin_dirs
List[str] _lib_dirs
_site_dir
_save_env
_lib_dirs
Detailed Description
A no-op drop-in replacement for BuildEnvironment
Constructor & Destructor Documentation
__init__()
None pip._internal.build_env.NoOpBuildEnvironment.__init__ (self)
Reimplemented from pip._internal.build_env.BuildEnvironment.
Referenced by setuptools._vendor.typing_extensions._ProtocolMeta.__init__(), pip._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.ordered_set.OrderedSet.__setstate__(), and django.db.models.expressions.Expression.identity().
Member Function Documentation
__enter__()
None pip._internal.build_env.NoOpBuildEnvironment.__enter__ (self)
Reimplemented from pip._internal.build_env.BuildEnvironment.
__exit__()
None pip._internal.build_env.NoOpBuildEnvironment.__exit__ (self, Optional[Type[BaseException]] exc_type, Optional[BaseException] exc_val, Optional[TracebackType] exc_tb)
Reimplemented from pip._internal.build_env.BuildEnvironment.
cleanup()
None pip._internal.build_env.NoOpBuildEnvironment.cleanup (self)
Referenced by pip._internal.operations.build.build_tracker.BuildTracker.__exit__().
install_requirements()
None pip._internal.build_env.NoOpBuildEnvironment.install_requirements (self, "PackageFinder" finder, Iterable[str] requirements, str prefix_as_string, * , str kind)
Reimplemented from pip._internal.build_env.BuildEnvironment.
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/pip/_internal/build_env.py