Django Project: cryptography.hazmat.primitives.ciphers.base.AEADEncryptionContext Class Reference
cryptography.hazmat.primitives.ciphers.base.AEADEncryptionContext Class Reference
Public Member Functions
bytes tag (self)
Public Member Functions inherited from cryptography.hazmat.primitives.ciphers.base.AEADCipherContext
None authenticate_additional_data (self, bytes data)
Public Member Functions inherited from cryptography.hazmat.primitives.ciphers.base.CipherContext
bytes update (self, bytes data)
int update_into (self, bytes data, bytes buf)
bytes finalize (self)
Member Function Documentation
tag()
bytes cryptography.hazmat.primitives.ciphers.base.AEADEncryptionContext.tag (self)
Returns tag bytes. This is only available after encryption is
finalized.
Reimplemented in cryptography.hazmat.primitives.ciphers.base._AEADEncryptionContext.
Referenced by django.forms.boundfield.BoundWidget.__str__(), cryptography.hazmat.backends.openssl.ciphers._CipherContext.finalize(), django.template.library.Library.inclusion_tag(), django.template.library.Library.simple_tag(), and django.template.library.Library.tag().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/cryptography/hazmat/primitives/ciphers/base.py