Django Project: pip._vendor.requests.sessions.SessionRedirectMixin Class Reference
pip._vendor.requests.sessions.SessionRedirectMixin Class Reference
Public Member Functions
get_redirect_target (self, resp)
should_strip_auth (self, old_url, new_url)
resolve_redirects (self, resp, req, stream=False, timeout=None, verify=True, cert=None, proxies=None, yield_requests=False, **adapter_kwargs)
rebuild_auth (self, prepared_request, response)
rebuild_proxies (self, prepared_request, proxies)
rebuild_method (self, prepared_request, response)
Public Attributes
cookies
Member Function Documentation
get_redirect_target()
pip._vendor.requests.sessions.SessionRedirectMixin.get_redirect_target (self, resp)
Receives a Response. Returns a redirect URI or ``None``
Referenced by pip._vendor.requests.sessions.SessionRedirectMixin.resolve_redirects().
rebuild_auth()
pip._vendor.requests.sessions.SessionRedirectMixin.rebuild_auth (self, prepared_request, response)
When being redirected we may want to strip authentication from the
request to avoid leaking credentials. This method intelligently removes
and reapplies authentication where possible to avoid credential loss.
References pip._vendor.requests.sessions.SessionRedirectMixin.should_strip_auth(), and pip._vendor.requests.sessions.Session.trust_env.
rebuild_method()
pip._vendor.requests.sessions.SessionRedirectMixin.rebuild_method (self, prepared_request, response)
When being redirected we may want to change the method of the request
based on certain specs or browser behavior.
Referenced by pip._vendor.requests.sessions.SessionRedirectMixin.resolve_redirects().
rebuild_proxies()
pip._vendor.requests.sessions.SessionRedirectMixin.rebuild_proxies (self, prepared_request, proxies)
This method re-evaluates the proxy configuration by considering the
environment variables. If we are redirected to a URL covered by
NO_PROXY, we strip the proxy configuration. Otherwise, we set missing
proxy keys for this URL (in case they were stripped by a previous
redirect).
This method also replaces the Proxy-Authorization header where
necessary.
:rtype: dict
References pip._vendor.requests.sessions.Session.trust_env.
resolve_redirects()
pip._vendor.requests.sessions.SessionRedirectMixin.resolve_redirects (self, resp, req, stream = False, timeout = None, verify = True, cert = None, proxies = None, yield_requests = False, ** adapter_kwargs)
Receives a Response. Returns a generator of Responses or Requests.
References pip._vendor.requests.sessions.SessionRedirectMixin.get_redirect_target(), pip._vendor.requests.sessions.Session.max_redirects, and pip._vendor.requests.sessions.SessionRedirectMixin.rebuild_method().
Referenced by pip._vendor.requests.sessions.Session.send().
should_strip_auth()
pip._vendor.requests.sessions.SessionRedirectMixin.should_strip_auth (self, old_url, new_url)
Decide whether Authorization header should be removed when redirecting
Referenced by pip._vendor.requests.sessions.SessionRedirectMixin.rebuild_auth().
Member Data Documentation
cookies
pip._vendor.requests.sessions.SessionRedirectMixin.cookies
Referenced by django.test.client.RequestFactory._base_environ(), django.test.client.ClientMixin._set_login_cookies(), django.test.client.ClientMixin.alogout(), pip._vendor.requests.models.Request.prepare(), pip._vendor.requests.sessions.Session.prepare_request(), pip._vendor.requests.sessions.Session.send(), django.test.client.ClientMixin.session(), and django.http.response.HttpResponseBase.set_cookie().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/pip/_vendor/requests/sessions.py