Django Project: django.db.migrations.serializer.BaseUnorderedSequenceSerializer Class Reference
django.db.migrations.serializer.BaseUnorderedSequenceSerializer Class Reference
Public Member Functions
__init__ (self, value)
Public Member Functions inherited from django.db.migrations.serializer.BaseSequenceSerializer
serialize (self)
Additional Inherited Members
Public Attributes inherited from django.db.migrations.serializer.BaseSequenceSerializer
value
Public Attributes inherited from django.db.migrations.serializer.BaseSerializer
value
Protected Member Functions inherited from django.db.migrations.serializer.BaseSequenceSerializer
_format (self)
Constructor & Destructor Documentation
__init__()
django.db.migrations.serializer.BaseUnorderedSequenceSerializer.__init__ (self, value)
Reimplemented from django.db.migrations.serializer.BaseSerializer.
References django.db.migrations.serializer.BaseUnorderedSequenceSerializer.__init__().
Referenced by django.db.migrations.serializer.BaseUnorderedSequenceSerializer.__init__(), setuptools._vendor.typing_extensions._ProtocolMeta.__init__(), pip._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.ordered_set.OrderedSet.__setstate__(), and django.db.models.expressions.Expression.identity().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/django/db/migrations/serializer.py