Django Project: pkg_resources.EggProvider Class Reference
pkg_resources.EggProvider Class Reference
Public Member Functions
__init__ (self, module)
Public Member Functions inherited from pkg_resources.NullProvider
get_resource_filename (self, manager, resource_name)
get_resource_stream (self, manager, resource_name)
get_resource_string (self, manager, resource_name)
has_resource (self, resource_name)
has_metadata (self, name)
get_metadata (self, name)
get_metadata_lines (self, name)
resource_isdir (self, resource_name)
metadata_isdir (self, name)
resource_listdir (self, resource_name)
metadata_listdir (self, name)
run_script (self, script_name, namespace)
Public Attributes
egg_name
egg_info
egg_root
Public Attributes inherited from pkg_resources.NullProvider
module_path
Protected Member Functions
_setup_prefix (self)
_set_egg (self, path)
Protected Member Functions inherited from pkg_resources.NullProvider
_get_metadata_path (self, name)
_has (self, path)
_isdir (self, path)
_listdir (self, path)
_fn (self, base, resource_name)
_get (self, path)
Additional Inherited Members
Static Public Attributes inherited from pkg_resources.NullProvider
egg_name = None
egg_info = None
loader = None
Static Protected Member Functions inherited from pkg_resources.NullProvider
_validate_resource_path (path)
Detailed Description
Provider based on a virtual filesystem
Constructor & Destructor Documentation
__init__()
pkg_resources.EggProvider.__init__ (self, module)
Reimplemented from pkg_resources.NullProvider.
Reimplemented in pkg_resources.EggMetadata, pkg_resources.PathMetadata, and pkg_resources.ZipProvider.
Referenced by setuptools._vendor.typing_extensions._ProtocolMeta.__init__(), pip._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.ordered_set.OrderedSet.__setstate__(), and django.db.models.expressions.Expression.identity().
Member Function Documentation
_set_egg()
pkg_resources.EggProvider._set_egg (self, path) protected
_setup_prefix()
pkg_resources.EggProvider._setup_prefix (self) protected
Member Data Documentation
egg_info
pkg_resources.EggProvider.egg_info
Referenced by setuptools.command.egg_info.egg_info.check_broken_egg_info(), setuptools.command.bdist_egg.bdist_egg.copy_metadata_to(), setuptools.command.egg_info.egg_info.egg_info, setuptools.command.egg_info.egg_info.finalize_options(), setuptools.command.egg_info.egg_info.find_sources(), setuptools.command.dist_info.dist_info.run(), and setuptools.command.egg_info.egg_info.run().
egg_name
pkg_resources.EggProvider.egg_name
Referenced by setuptools.command.egg_info.egg_info.check_broken_egg_info(), and setuptools.command.egg_info.egg_info.finalize_options().
egg_root
pkg_resources.EggProvider.egg_root
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/pkg_resources/__init__.py