Django Project: django.middleware.cache.CacheMiddleware Class Reference
django.middleware.cache.CacheMiddleware Class Reference
Public Member Functions
__init__ (self, get_response, cache_timeout=None, page_timeout=None, **kwargs)
Public Member Functions inherited from django.middleware.cache.UpdateCacheMiddleware
cache (self)
process_response (self, request, response)
Public Member Functions inherited from django.utils.deprecation.MiddlewareMixin
__repr__ (self)
__call__ (self, request)
__acall__ (self, request)
Public Member Functions inherited from django.middleware.cache.FetchFromCacheMiddleware
cache (self)
process_request (self, request)
Public Attributes
key_prefix
cache_alias
cache_timeout
page_timeout
Public Attributes inherited from django.middleware.cache.UpdateCacheMiddleware
cache_timeout
page_timeout
key_prefix
cache_alias
Public Attributes inherited from django.utils.deprecation.MiddlewareMixin
get_response
Public Attributes inherited from django.middleware.cache.FetchFromCacheMiddleware
key_prefix
cache_alias
Additional Inherited Members
Static Public Attributes inherited from django.utils.deprecation.MiddlewareMixin
bool sync_capable = True
bool async_capable = True
Protected Member Functions inherited from django.middleware.cache.UpdateCacheMiddleware
_should_update_cache (self, request, response)
Protected Member Functions inherited from django.utils.deprecation.MiddlewareMixin
_async_check (self)
Detailed Description
Cache middleware that provides basic behavior for many simple sites.
Also used as the hook point for the cache decorator, which is generated
using the decorator-from-middleware utility.
Constructor & Destructor Documentation
__init__()
django.middleware.cache.CacheMiddleware.__init__ (self, get_response, cache_timeout = None, page_timeout = None, ** kwargs)
Reimplemented from django.middleware.cache.UpdateCacheMiddleware.
References django.middleware.cache.CacheMiddleware.__init__().
Referenced by django.middleware.cache.CacheMiddleware.__init__(), setuptools._vendor.typing_extensions._ProtocolMeta.__init__(), pip._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.ordered_set.OrderedSet.__setstate__(), and django.db.models.expressions.Expression.identity().
Member Data Documentation
cache_alias
django.middleware.cache.CacheMiddleware.cache_alias
Referenced by django.middleware.cache.FetchFromCacheMiddleware.cache(), and django.middleware.cache.UpdateCacheMiddleware.cache().
cache_timeout
django.middleware.cache.CacheMiddleware.cache_timeout
Referenced by django.middleware.cache.UpdateCacheMiddleware.process_response().
key_prefix
django.middleware.cache.CacheMiddleware.key_prefix
Referenced by django.core.cache.backends.base.BaseCache.make_key(), django.middleware.cache.FetchFromCacheMiddleware.process_request(), and django.middleware.cache.UpdateCacheMiddleware.process_response().
page_timeout
django.middleware.cache.CacheMiddleware.page_timeout
Referenced by django.middleware.cache.UpdateCacheMiddleware.process_response().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/django/middleware/cache.py