Django Project: django.contrib.gis.feeds.GeoAtom1Feed Class Reference
django.contrib.gis.feeds.GeoAtom1Feed Class Reference
Public Member Functions
root_attributes (self)
add_item_elements (self, handler, item)
add_root_elements (self, handler)
Public Member Functions inherited from django.utils.feedgenerator.Atom1Feed
write (self, outfile, encoding)
write_items (self, handler)
Public Member Functions inherited from django.utils.feedgenerator.SyndicationFeed
__init__ (self, title, link, description, language=None, author_email=None, author_name=None, author_link=None, subtitle=None, categories=None, feed_url=None, feed_copyright=None, feed_guid=None, ttl=None, **kwargs)
add_item (self, title, link, description, author_email=None, author_name=None, author_link=None, pubdate=None, comments=None, unique_id=None, unique_id_is_permalink=None, categories=(), item_copyright=None, ttl=None, updateddate=None, enclosures=None, **kwargs)
num_items (self)
item_attributes (self, item)
writeString (self, encoding)
latest_post_date (self)
Public Member Functions inherited from django.contrib.gis.feeds.GeoFeedMixin
georss_coords (self, coords)
add_georss_point (self, handler, coords, w3c_geo=False)
add_georss_element (self, handler, item, w3c_geo=False)
Public Attributes
feed
Public Attributes inherited from django.utils.feedgenerator.Atom1Feed
ns
items
Public Attributes inherited from django.utils.feedgenerator.SyndicationFeed
feed
items
Additional Inherited Members
Static Public Attributes inherited from django.utils.feedgenerator.Atom1Feed
str content_type = "application/atom+xml; charset=utf-8"
str ns = "http://www.w3.org/2005/Atom"
Member Function Documentation
add_item_elements()
django.contrib.gis.feeds.GeoAtom1Feed.add_item_elements (self, handler, item)
Add elements on each item (i.e. item/entry) element.
Reimplemented from django.utils.feedgenerator.Atom1Feed.
References django.contrib.gis.feeds.GeoFeedMixin.add_georss_element(), and django.contrib.gis.feeds.GeoAtom1Feed.add_item_elements().
Referenced by django.contrib.gis.feeds.GeoAtom1Feed.add_item_elements().
add_root_elements()
django.contrib.gis.feeds.GeoAtom1Feed.add_root_elements (self, handler)
Add elements in the root (i.e. feed/channel) element. Called
from write().
Reimplemented from django.utils.feedgenerator.Atom1Feed.
References django.contrib.gis.feeds.GeoAtom1Feed.add_root_elements().
Referenced by django.contrib.gis.feeds.GeoAtom1Feed.add_root_elements(), django.utils.feedgenerator.Atom1Feed.write(), and django.utils.feedgenerator.RssFeed.write().
root_attributes()
django.contrib.gis.feeds.GeoAtom1Feed.root_attributes (self)
Return extra attributes to place on the root (i.e. feed/channel) element.
Called from write().
Reimplemented from django.utils.feedgenerator.Atom1Feed.
References django.contrib.gis.feeds.GeoAtom1Feed.root_attributes().
Referenced by django.contrib.gis.feeds.GeoAtom1Feed.root_attributes(), django.utils.feedgenerator.Atom1Feed.write(), and django.utils.feedgenerator.RssFeed.write().
Member Data Documentation
feed
django.contrib.gis.feeds.GeoAtom1Feed.feed
Referenced by django.utils.feedgenerator.Atom1Feed.add_root_elements(), django.utils.feedgenerator.RssFeed.add_root_elements(), django.utils.feedgenerator.Atom1Feed.root_attributes(), and django.db.migrations.writer.OperationWriter.serialize().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/django/contrib/gis/feeds.py