Django Project: setuptools._vendor.typing_extensions.AsyncContextManager Class Reference
setuptools._vendor.typing_extensions.AsyncContextManager Class Reference
Public Member Functions
__aenter__ (self)
__aexit__ (self, exc_type, exc_value, traceback)
__subclasshook__ (cls, C)
Member Function Documentation
__aenter__()
setuptools._vendor.typing_extensions.AsyncContextManager.__aenter__ (self)
__aexit__()
setuptools._vendor.typing_extensions.AsyncContextManager.__aexit__ (self, exc_type, exc_value, traceback)
__subclasshook__()
setuptools._vendor.typing_extensions.AsyncContextManager.__subclasshook__ (cls, C)
Referenced by setuptools._vendor.typing_extensions._ProtocolMeta.__init__(), pip._vendor.typing_extensions.Protocol.__init_subclass__(), and setuptools._vendor.typing_extensions.Protocol.__init_subclass__().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/setuptools/_vendor/typing_extensions.py