Django Project: django.db.migrations.optimizer.MigrationOptimizer Class Reference
django.db.migrations.optimizer.MigrationOptimizer Class Reference
Public Member Functions
optimize (self, operations, app_label)
optimize_inner (self, operations, app_label)
Protected Attributes
_iterations
Detailed Description
Power the optimization process, where you provide a list of Operations
and you are returned a list of equal or shorter length - operations
are merged into one if possible.
For example, a CreateModel and an AddField can be optimized into a
new CreateModel, and CreateModel and DeleteModel can be optimized into
nothing.
Member Function Documentation
optimize()
django.db.migrations.optimizer.MigrationOptimizer.optimize (self, operations, app_label)
Main optimization entry point. Pass in a list of Operation instances,
get out a new list of Operation instances.
Unfortunately, due to the scope of the optimization (two combinable
operations might be separated by several hundred others), this can't be
done as a peephole optimization with checks/output implemented on
the Operations themselves; instead, the optimizer looks at each
individual operation and scans forwards in the list to see if there
are any matches, stopping at boundaries - operations which can't
be optimized over (RunSQL, operations on the same field/model, etc.)
The inner loop is run until the starting list is the same as the result
list, and then the result is returned. This means that operation
optimization must be stable and always return an equal or shorter list.
Referenced by setuptools._distutils.command.install_lib.install_lib._bytecode_filenames(), setuptools._distutils.command.build_py.build_py.byte_compile(), setuptools._distutils.command.install_lib.install_lib.byte_compile(), setuptools._distutils.command.install_lib.install_lib.finalize_options(), and setuptools._distutils.command.build_py.build_py.get_outputs().
optimize_inner()
django.db.migrations.optimizer.MigrationOptimizer.optimize_inner (self, operations, app_label)
Inner optimization loop.
Member Data Documentation
_iterations
django.db.migrations.optimizer.MigrationOptimizer._iterations protected
Referenced by cryptography.hazmat.primitives.kdf.pbkdf2.PBKDF2HMAC.derive().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/django/db/migrations/optimizer.py