Django Project: django.contrib.auth.models.AbstractUser.Meta Class Reference
django.contrib.auth.models.AbstractUser.Meta Class Reference
Static Public Attributes
verbose_name = _("user")
verbose_name_plural = _("users")
bool abstract = True
Member Data Documentation
abstract
bool django.contrib.auth.models.AbstractUser.Meta.abstract = True static
Referenced by django.db.models.options.Options._expire_cache().
verbose_name
django.contrib.auth.models.AbstractUser.Meta.verbose_name = _("user") static
Referenced by django.db.models.fields.Field.formfield(), django.contrib.admin.widgets.FilteredSelectMultiple.get_context(), django.db.models.fields.related.RelatedField.set_attributes_from_rel(), and django.db.models.options.Options.verbose_name_raw().
verbose_name_plural
django.contrib.auth.models.AbstractUser.Meta.verbose_name_plural = _("users") static
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/django/contrib/auth/models.py