Django Project: pip._vendor.pyproject_hooks._impl.UnsupportedOperation Class Reference
pip._vendor.pyproject_hooks._impl.UnsupportedOperation Class Reference
Public Member Functions
__init__ (self, traceback)
Public Attributes
traceback
Detailed Description
May be raised by build_sdist if the backend indicates that it can't.
Constructor & Destructor Documentation
__init__()
pip._vendor.pyproject_hooks._impl.UnsupportedOperation.__init__ (self, traceback)
Referenced by setuptools._vendor.typing_extensions._ProtocolMeta.__init__(), pip._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.ordered_set.OrderedSet.__setstate__(), and django.db.models.expressions.Expression.identity().
Member Data Documentation
traceback
pip._vendor.pyproject_hooks._impl.UnsupportedOperation.traceback
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/pip/_vendor/pyproject_hooks/_impl.py