Django Project: cryptography.x509.ocsp.OCSPRequest Class Reference
cryptography.x509.ocsp.OCSPRequest Class Reference
Public Member Functions
bytes issuer_key_hash (self)
bytes issuer_name_hash (self)
hashes.HashAlgorithm hash_algorithm (self)
int serial_number (self)
bytes public_bytes (self, serialization.Encoding encoding)
x509.Extensions extensions (self)
Member Function Documentation
extensions()
x509.Extensions cryptography.x509.ocsp.OCSPRequest.extensions (self)
The list of request extensions. Not single request extensions.
Referenced by setuptools._distutils.command.build_ext.build_ext._build_extensions_serial(), setuptools.command.build_ext.build_ext._get_output_mapping(), setuptools._distutils.command.build_ext.build_ext.build_extensions(), setuptools._distutils.command.build_ext.build_ext.finalize_options(), setuptools.command.build_ext.build_ext.finalize_options(), django.core.management.commands.makemessages.Command.find_files(), setuptools._distutils.command.build_ext.build_ext.get_outputs(), setuptools._distutils.command.build_ext.build_ext.get_source_files(), and setuptools._distutils.command.build_ext.build_ext.run().
hash_algorithm()
hashes.HashAlgorithm cryptography.x509.ocsp.OCSPRequest.hash_algorithm (self)
The hash algorithm used in the issuer name and key hashes
Referenced by django.test.runner.Shuffler._hash_text().
issuer_key_hash()
bytes cryptography.x509.ocsp.OCSPRequest.issuer_key_hash (self)
The hash of the issuer public key
issuer_name_hash()
bytes cryptography.x509.ocsp.OCSPRequest.issuer_name_hash (self)
The hash of the issuer name
public_bytes()
bytes cryptography.x509.ocsp.OCSPRequest.public_bytes (self, serialization.Encoding encoding)
Serializes the request to DER
serial_number()
int cryptography.x509.ocsp.OCSPRequest.serial_number (self)
The serial number of the cert whose status is being checked
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/cryptography/x509/ocsp.py