Django Project: setuptools._vendor.pyparsing.core.AtLineStart Class Reference
setuptools._vendor.pyparsing.core.AtLineStart Class Reference
Public Member Functions
__init__ (self, Union[ParserElement, str] expr)
parseImpl (self, instring, loc, doActions=True)
Public Member Functions inherited from setuptools._vendor.pyparsing.core.ParseElementEnhance
Sequence[ParserElement] recurse (self)
ParserElement leave_whitespace (self, bool recursive=True)
ParserElement ignore_whitespace (self, bool recursive=True)
ParserElement ignore (self, other)
ParserElement streamline (self)
None validate (self, validateTrace=None)
Public Member Functions inherited from setuptools._vendor.pyparsing.core.ParserElement
"ParserElement" suppress_warning (self, Diagnostics warning_type)
"ParserElement" copy (self)
"ParserElement" set_results_name (self, str name, bool list_all_matches=False, *, bool listAllMatches=False)
"ParserElement" set_break (self, bool break_flag=True)
"ParserElement" set_parse_action (self, *ParseAction fns, **kwargs)
"ParserElement" add_parse_action (self, *ParseAction fns, **kwargs)
"ParserElement" add_condition (self, *ParseCondition fns, **kwargs)
"ParserElement" set_fail_action (self, ParseFailAction fn)
preParse (self, instring, loc)
postParse (self, instring, loc, tokenlist)
int try_parse (self, str instring, int loc, bool raise_fatal=False)
bool can_parse_next (self, str instring, int loc)
ParseResults parse_string (self, str instring, bool parse_all=False, *, bool parseAll=False)
Generator[Tuple[ParseResults, int, int], None, None] scan_string (self, str instring, int max_matches=_MAX_INT, bool overlap=False, *, bool debug=False, int maxMatches=_MAX_INT)
str transform_string (self, str instring, *, bool debug=False)
ParseResults search_string (self, str instring, int max_matches=_MAX_INT, *, bool debug=False, int maxMatches=_MAX_INT)
Generator[str, None, None] split (self, str instring, int maxsplit=_MAX_INT, bool include_separators=False, *, includeSeparators=False)
"ParserElement" __add__ (self, other)
"ParserElement" __radd__ (self, other)
"ParserElement" __sub__ (self, other)
"ParserElement" __rsub__ (self, other)
"ParserElement" __mul__ (self, other)
"ParserElement" __rmul__ (self, other)
"ParserElement" __or__ (self, other)
"ParserElement" __ror__ (self, other)
"ParserElement" __xor__ (self, other)
"ParserElement" __rxor__ (self, other)
"ParserElement" __and__ (self, other)
"ParserElement" __rand__ (self, other)
"ParserElement" __invert__ (self)
__getitem__ (self, key)
"ParserElement" __call__ (self, str name=None)
"ParserElement" suppress (self)
"ParserElement" set_whitespace_chars (self, Union[Set[str], str] chars, bool copy_defaults=False)
"ParserElement" parse_with_tabs (self)
"ParserElement" set_debug_actions (self, DebugStartAction start_action, DebugSuccessAction success_action, DebugExceptionAction exception_action)
"ParserElement" set_debug (self, bool flag=True)
str default_name (self)
"ParserElement" set_name (self, str name)
str name (self)
str __str__ (self)
str __repr__ (self)
ParseResults parse_file (self, Union[str, Path, TextIO] file_or_filename, str encoding="utf-8", bool parse_all=False, *, bool parseAll=False)
__eq__ (self, other)
__hash__ (self)
bool matches (self, str test_string, bool parse_all=True, *, bool parseAll=True)
Tuple[bool, List[Tuple[str, Union[ParseResults, Exception]]]] run_tests (self, Union[str, List[str]] tests, bool parse_all=True, typing.Optional[Union["ParserElement", str]] comment="#", bool full_dump=True, bool print_results=True, bool failure_tests=False, Callable[[str, ParseResults], str] post_parse=None, typing.Optional[TextIO] file=None, bool with_line_numbers=False, *, bool parseAll=True, bool fullDump=True, bool printResults=True, bool failureTests=False, Callable[[str, ParseResults], str] postParse=None)
None create_diagram (self, Union[TextIO, Path, str] output_html, int vertical=3, bool show_results_names=False, bool show_groups=False, **kwargs)
Public Attributes
callPreparse
Public Attributes inherited from setuptools._vendor.pyparsing.core.ParseElementEnhance
expr
mayIndexError
mayReturnEmpty
skipWhitespace
saveAsList
callPreparse
ignoreExprs
Public Attributes inherited from setuptools._vendor.pyparsing.core.ParserElement
List[ParseAction] parseAction
typing.Optional[ParseFailAction] failAction
customName
resultsName
saveAsList
skipWhitespace
whiteChars
copyDefaultWhiteChars
mayReturnEmpty
keepTabs
List[] ignoreExprs
debug
streamlined
mayIndexError
errmsg
modalResults
debugActions
callPreparse
callDuringTry
List[Diagnostics] suppress_warnings_
Additional Inherited Members
Static Public Member Functions inherited from setuptools._vendor.pyparsing.core.ParserElement
None set_default_whitespace_chars (str chars)
None inline_literals_using (type cls)
None reset_cache ()
None disable_memoization ()
None enable_left_recursion (typing.Optional[int] cache_size_limit=None, *, force=False)
None enable_packrat (int cache_size_limit=128, *, bool force=False)
Static Public Attributes inherited from setuptools._vendor.pyparsing.core.ParseElementEnhance
ParserElement ignoreWhitespace = ignore_whitespace
ParserElement leaveWhitespace = leave_whitespace
Static Public Attributes inherited from setuptools._vendor.pyparsing.core.ParserElement
str DEFAULT_WHITE_CHARS = " \n\t\r"
bool verbose_stacktrace = False
recursion_lock = RLock()
dict recursion_memos = {}
tuple packrat_cache
packrat_cache_lock = RLock()
list packrat_cache_stats = [0, 0]
None setDefaultWhitespaceChars = set_default_whitespace_chars
None inlineLiteralsUsing = inline_literals_using
"ParserElement" setResultsName = set_results_name
"ParserElement" setBreak = set_break
"ParserElement" setParseAction = set_parse_action
"ParserElement" addParseAction = add_parse_action
"ParserElement" addCondition = add_condition
"ParserElement" setFailAction = set_fail_action
int tryParse = try_parse
bool canParseNext = can_parse_next
None resetCache = reset_cache
None enableLeftRecursion = enable_left_recursion
None enablePackrat = enable_packrat
ParseResults parseString = parse_string
Generator[Tuple[ParseResults, int, int], None, None] scanString = scan_string
ParseResults searchString = search_string
str transformString = transform_string
"ParserElement" setWhitespaceChars = set_whitespace_chars
"ParserElement" parseWithTabs = parse_with_tabs
"ParserElement" setDebugActions = set_debug_actions
"ParserElement" setDebug = set_debug
str defaultName = default_name
"ParserElement" setName = set_name
ParseResults parseFile = parse_file
Tuple[bool, List[Tuple[str, Union[ParseResults, Exception]]]] runTests = run_tests
"ParserElement" ignoreWhitespace = ignore_whitespace
"ParserElement" leaveWhitespace = leave_whitespace
Protected Member Functions inherited from setuptools._vendor.pyparsing.core.ParseElementEnhance
_checkRecursion (self, parseElementList)
_generateDefaultName (self)
Protected Member Functions inherited from setuptools._vendor.pyparsing.core.ParserElement
_setResultsName (self, name, listAllMatches=False)
_skipIgnorables (self, instring, loc)
Tuple[int, ParseResults] _parseNoCache (self, instring, loc, doActions=True, callPreParse=True)
Tuple[int, ParseResults] _parseCache (self, instring, loc, doActions=True, callPreParse=True)
Protected Attributes inherited from setuptools._vendor.pyparsing.core.ParseElementEnhance
_literalStringClass
Protected Attributes inherited from setuptools._vendor.pyparsing.core.ParserElement
_defaultName
_parse
Static Protected Attributes inherited from setuptools._vendor.pyparsing.core.ParserElement
typing _literalStringClass = None
Tuple[int, ParseResults] _parse = _parseNoCache
bool _packratEnabled = False
bool _left_recursion_enabled = False
Detailed Description
Matches if an expression matches at the beginning of a line within
the parse string
Example::
    test = '''\
    AAA this line
    AAA and this line
      AAA but not this one
    B AAA and definitely not this one
    '''
    for t in (AtLineStart('AAA') + restOfLine).search_string(test):
        print(t)
prints::
    ['AAA', ' this line']
    ['AAA', ' and this line']
Constructor & Destructor Documentation
__init__()
setuptools._vendor.pyparsing.core.AtLineStart.__init__ (self, Union[ParserElement, str] expr)
Reimplemented from setuptools._vendor.pyparsing.core.ParseElementEnhance.
References setuptools._vendor.pyparsing.core.AtLineStart.__init__().
Referenced by setuptools._vendor.pyparsing.core.AtLineStart.__init__(), setuptools._vendor.typing_extensions._ProtocolMeta.__init__(), pip._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.ordered_set.OrderedSet.__setstate__(), and django.db.models.expressions.Expression.identity().
Member Function Documentation
parseImpl()
setuptools._vendor.pyparsing.core.AtLineStart.parseImpl (self, instring, loc, doActions = True)
Reimplemented from setuptools._vendor.pyparsing.core.ParseElementEnhance.
References setuptools._vendor.pyparsing.core.AtLineStart.parseImpl().
Referenced by pip._vendor.pyparsing.core.ParserElement._parseNoCache(), pkg_resources._vendor.pyparsing.core.ParserElement._parseNoCache(), setuptools._vendor.pyparsing.core.ParserElement._parseNoCache(), and setuptools._vendor.pyparsing.core.AtLineStart.parseImpl().
Member Data Documentation
callPreparse
setuptools._vendor.pyparsing.core.AtLineStart.callPreparse
Referenced by pip._vendor.pyparsing.core.ParserElement._parseNoCache(), pkg_resources._vendor.pyparsing.core.ParserElement._parseNoCache(), setuptools._vendor.pyparsing.core.ParserElement._parseNoCache(), and pip._vendor.pyparsing.core.SkipTo.parseImpl().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/setuptools/_vendor/pyparsing/core.py