Django Project: setuptools.build_meta._ConfigSettingsTranslator Class Reference
setuptools.build_meta._ConfigSettingsTranslator Class Reference
Protected Member Functions
List[str] _get_config (self, str key, _ConfigSettings config_settings)
_valid_global_options (self)
Iterator[str] _global_args (self, _ConfigSettings config_settings)
Iterator[str] _editable_args (self, _ConfigSettings config_settings)
Iterator[str] _arbitrary_args (self, _ConfigSettings config_settings)
Detailed Description
Translate ``config_settings`` into distutils-style command arguments.
Only a limited number of options is currently supported.
Member Function Documentation
_arbitrary_args()
Iterator[str] setuptools.build_meta._ConfigSettingsTranslator._arbitrary_args (self, _ConfigSettings config_settings) protected
Users may expect to pass arbitrary lists of arguments to a command
via "--global-option" (example provided in PEP 517 of a "escape hatch").
>>> fn = _ConfigSettingsTranslator()._arbitrary_args
>>> list(fn(None))
[]
>>> list(fn({}))
[]
>>> list(fn({'--build-option': 'foo'}))
['foo']
>>> list(fn({'--build-option': ['foo']}))
['foo']
>>> list(fn({'--build-option': 'foo'}))
['foo']
>>> list(fn({'--build-option': 'foo bar'}))
['foo', 'bar']
>>> warnings.simplefilter('error', SetuptoolsDeprecationWarning)
>>> list(fn({'--global-option': 'foo'}))  # doctest: +IGNORE_EXCEPTION_DETAIL
Traceback (most recent call last):
SetuptoolsDeprecationWarning: ...arguments given via `--global-option`...
References setuptools.build_meta._ConfigSettingsTranslator._get_config(), and setuptools.build_meta._ConfigSettingsTranslator._valid_global_options().
Referenced by setuptools.build_meta._BuildMetaBackend._build_with_temp_dir(), and setuptools.build_meta._BuildMetaBackend._get_build_requires().
_editable_args()
Iterator[str] setuptools.build_meta._ConfigSettingsTranslator._editable_args (self, _ConfigSettings config_settings) protected
The ``editable_wheel`` command accepts ``editable-mode=strict``.
>>> fn = _ConfigSettingsTranslator()._editable_args
>>> list(fn(None))
[]
>>> list(fn({"editable-mode": "strict"}))
['--mode', 'strict']
Referenced by setuptools.build_meta._BuildMetaBackend.build_editable().
_get_config()
List[str] setuptools.build_meta._ConfigSettingsTranslator._get_config (self, str key, _ConfigSettings config_settings) protected
Get the value of a specific key in ``config_settings`` as a list of strings.
>>> fn = _ConfigSettingsTranslator()._get_config
>>> fn("--global-option", None)
[]
>>> fn("--global-option", {})
[]
>>> fn("--global-option", {'--global-option': 'foo'})
['foo']
>>> fn("--global-option", {'--global-option': ['foo']})
['foo']
>>> fn("--global-option", {'--global-option': 'foo'})
['foo']
>>> fn("--global-option", {'--global-option': 'foo bar'})
['foo', 'bar']
Referenced by setuptools.build_meta._ConfigSettingsTranslator._arbitrary_args(), and setuptools.build_meta._ConfigSettingsTranslator._global_args().
_global_args()
Iterator[str] setuptools.build_meta._ConfigSettingsTranslator._global_args (self, _ConfigSettings config_settings) protected
Let the user specify ``verbose`` or ``quiet`` + escape hatch via
``--global-option``.
Note: ``-v``, ``-vv``, ``-vvv`` have similar effects in setuptools,
so we just have to cover the basic scenario ``-v``.
>>> fn = _ConfigSettingsTranslator()._global_args
>>> list(fn(None))
[]
>>> list(fn({"verbose": "False"}))
['-q']
>>> list(fn({"verbose": "1"}))
['-v']
>>> list(fn({"--verbose": None}))
['-v']
>>> list(fn({"verbose": "true", "--global-option": "-q --no-user-cfg"}))
['-v', '-q', '--no-user-cfg']
>>> list(fn({"--quiet": None}))
['-q']
References setuptools.build_meta._ConfigSettingsTranslator._get_config(), and setuptools.build_meta._ConfigSettingsTranslator._valid_global_options().
Referenced by setuptools.build_meta._BuildMetaBackend._build_with_temp_dir(), setuptools.build_meta._BuildMetaBackend._get_build_requires(), and setuptools.build_meta._BuildMetaBackend.prepare_metadata_for_build_wheel().
_valid_global_options()
setuptools.build_meta._ConfigSettingsTranslator._valid_global_options (self) protected
Global options accepted by setuptools (e.g. quiet or verbose).
Referenced by setuptools.build_meta._ConfigSettingsTranslator._arbitrary_args(), and setuptools.build_meta._ConfigSettingsTranslator._global_args().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/setuptools/build_meta.py