Django Project: django.core.files.uploadhandler.StopUpload Class Reference
django.core.files.uploadhandler.StopUpload Class Reference
Public Member Functions
__init__ (self, connection_reset=False)
__str__ (self)
Public Attributes
connection_reset
Detailed Description
This exception is raised when an upload must abort.
Constructor & Destructor Documentation
__init__()
django.core.files.uploadhandler.StopUpload.__init__ (self, connection_reset = False)
If ``connection_reset`` is ``True``, Django knows will halt the upload
without consuming the rest of the upload. This will cause the browser to
show a "connection reset" error.
Referenced by setuptools._vendor.typing_extensions._ProtocolMeta.__init__(), pip._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.ordered_set.OrderedSet.__setstate__(), and django.db.models.expressions.Expression.identity().
Member Function Documentation
__str__()
django.core.files.uploadhandler.StopUpload.__str__ (self)
References django.core.files.uploadhandler.StopUpload.connection_reset.
Member Data Documentation
connection_reset
django.core.files.uploadhandler.StopUpload.connection_reset
Referenced by django.core.files.uploadhandler.StopUpload.__str__().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/django/core/files/uploadhandler.py