Django Project: cryptography.hazmat.primitives.ciphers.base.CipherContext Class Reference
cryptography.hazmat.primitives.ciphers.base.CipherContext Class Reference
Public Member Functions
bytes update (self, bytes data)
int update_into (self, bytes data, bytes buf)
bytes finalize (self)
Member Function Documentation
finalize()
bytes cryptography.hazmat.primitives.ciphers.base.CipherContext.finalize (self)
Returns the results of processing the final block as bytes.
Reimplemented in cryptography.hazmat.primitives.ciphers.base._AEADCipherContext, and cryptography.hazmat.primitives.ciphers.base._CipherContext.
Referenced by cryptography.hazmat.backends.openssl.ciphers._CipherContext.finalize_with_tag(), and _pytest.junitxml.LogXML.pytest_runtest_logreport().
update()
bytes cryptography.hazmat.primitives.ciphers.base.CipherContext.update (self, bytes data)
Processes the provided bytes through the cipher and returns the results
as bytes.
Reimplemented in cryptography.hazmat.primitives.ciphers.base._AEADCipherContext, and cryptography.hazmat.primitives.ciphers.base._CipherContext.
Referenced by pip._vendor.rich.progress.Progress.open(), pip._vendor.rich.progress.Progress.track(), and pip._vendor.rich.progress.Progress.wrap_file().
update_into()
int cryptography.hazmat.primitives.ciphers.base.CipherContext.update_into (self, bytes data, bytes buf)
Processes the provided bytes and writes the resulting data into the
provided buffer. Returns the number of bytes written.
Reimplemented in cryptography.hazmat.primitives.ciphers.base._AEADCipherContext, and cryptography.hazmat.primitives.ciphers.base._CipherContext.
Referenced by cryptography.hazmat.backends.openssl.ciphers._CipherContext.update().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/cryptography/hazmat/primitives/ciphers/base.py