Django Project: setuptools.namespaces.DevelopInstaller Class Reference
setuptools.namespaces.DevelopInstaller Class Reference
Public Attributes
egg_path
Public Attributes inherited from setuptools.namespaces.Installer
dry_run
Protected Member Functions
_get_root (self)
_get_target (self)
Protected Member Functions inherited from setuptools.namespaces.Installer
_gen_nspkg_line (self, pkg)
_get_all_ns_packages (self)
Additional Inherited Members
Public Member Functions inherited from setuptools.namespaces.Installer
install_namespaces (self)
uninstall_namespaces (self)
Static Public Attributes inherited from setuptools.namespaces.Installer
str nspkg_ext = '-nspkg.pth'
Static Protected Member Functions inherited from setuptools.namespaces.Installer
_pkg_names (pkg)
Protected Attributes inherited from setuptools.namespaces.Installer
_pkg_names
Static Protected Attributes inherited from setuptools.namespaces.Installer
tuple _nspkg_tmpl
tuple _nspkg_tmpl_multi
Member Function Documentation
_get_root()
setuptools.namespaces.DevelopInstaller._get_root (self) protected
Reimplemented from setuptools.namespaces.Installer.
Referenced by setuptools.namespaces.Installer._gen_nspkg_line().
_get_target()
setuptools.namespaces.DevelopInstaller._get_target (self) protected
Reimplemented from setuptools.namespaces.Installer.
References setuptools.command.develop.develop.egg_link.
Referenced by setuptools.namespaces.Installer.install_namespaces(), and setuptools.namespaces.Installer.uninstall_namespaces().
Member Data Documentation
egg_path
setuptools.namespaces.DevelopInstaller.egg_path
Referenced by setuptools.command.develop.develop.uninstall_link().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/setuptools/namespaces.py