Django Project: pip._vendor.tenacity.wait.wait_chain Class Reference
pip._vendor.tenacity.wait.wait_chain Class Reference
Public Member Functions
None __init__ (self, *wait_base strategies)
float __call__ (self, "RetryCallState" retry_state)
Public Member Functions inherited from pip._vendor.tenacity.wait.wait_base
"wait_combine" __add__ (self, "wait_base" other)
typing.Union["wait_combine", "wait_base"] __radd__ (self, "wait_base" other)
Public Attributes
strategies
Detailed Description
Chain two or more waiting strategies.
If all strategies are exhausted, the very last strategy is used
thereafter.
For example::
    @retry(wait=wait_chain(*[wait_fixed(1) for i in range(3)] +
                           [wait_fixed(2) for j in range(5)] +
                           [wait_fixed(5) for k in range(4)))
    def wait_chained():
        print("Wait 1s for 3 attempts, 2s for 5 attempts and 5s
               thereafter.")
Constructor & Destructor Documentation
__init__()
None pip._vendor.tenacity.wait.wait_chain.__init__ (self, *wait_base strategies)
Referenced by setuptools._vendor.typing_extensions._ProtocolMeta.__init__(), pip._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.ordered_set.OrderedSet.__setstate__(), and django.db.models.expressions.Expression.identity().
Member Function Documentation
__call__()
float pip._vendor.tenacity.wait.wait_chain.__call__ (self, "RetryCallState" retry_state)
Reimplemented from pip._vendor.tenacity.wait.wait_base.
References pip._vendor.tenacity.wait.wait_chain.strategies.
Referenced by asgiref.sync.AsyncToSync.__get__(), and asgiref.sync.SyncToAsync.__get__().
Member Data Documentation
strategies
pip._vendor.tenacity.wait.wait_chain.strategies
Referenced by pip._vendor.tenacity.wait.wait_chain.__call__().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/pip/_vendor/tenacity/wait.py