Django Project: graphviz.piping.Pipe Class Reference
graphviz.piping.Pipe Class Reference
Public Member Functions
bytes pipe (self, typing.Optional[str] format=..., typing.Optional[str] renderer=..., typing.Optional[str] formatter=..., typing.Union[bool, int, None] neato_no_op=..., bool quiet=..., *, typing.Optional[str] engine=..., None encoding=...)
str pipe (self, typing.Optional[str] format=..., typing.Optional[str] renderer=..., typing.Optional[str] formatter=..., typing.Union[bool, int, None] neato_no_op=..., bool quiet=..., *, typing.Optional[str] engine=..., str encoding)
typing.Union[bytes, str] pipe (self, typing.Optional[str] format=..., typing.Optional[str] renderer=..., typing.Optional[str] formatter=..., typing.Union[bool, int, None] neato_no_op=..., bool quiet=..., *, typing.Optional[str] engine=..., typing.Optional[str] encoding)
typing.Union[bytes, str] pipe (self, typing.Optional[str] format=None, typing.Optional[str] renderer=None, typing.Optional[str] formatter=None, typing.Union[bool, int, None] neato_no_op=None, bool quiet=False, *, typing.Optional[str] engine=None, typing.Optional[str] encoding=None)
Public Member Functions inherited from graphviz.encoding.Encoding
None __init__ (self, *, typing.Optional[str] encoding=DEFAULT_ENCODING, **kwargs)
str encoding (self)
None encoding (self, typing.Optional[str] encoding)
Public Member Functions inherited from graphviz.copying.CopyBase
copy (self)
Public Member Functions inherited from graphviz.base.Base
str source (self)
str __str__ (self)
Public Member Functions inherited from graphviz.base.LineIterable
typing.Iterator[str] __iter__ (self)
Public Member Functions inherited from graphviz.parameters.engines.Engine
None __init__ (self, *, typing.Optional[str] engine=None, **kwargs)
str engine (self)
None engine (self, str engine)
Public Member Functions inherited from graphviz.parameters.formats.Format
None __init__ (self, *, typing.Optional[str] format=None, **kwargs)
str format (self)
None format (self, str format)
Public Member Functions inherited from graphviz.parameters.renderers.Renderer
None __init__ (self, *, typing.Optional[str] renderer=None, **kwargs)
typing.Optional[str] renderer (self)
None renderer (self, typing.Optional[str] renderer)
Public Member Functions inherited from graphviz.parameters.formatters.Formatter
None __init__ (self, *, typing.Optional[str] formatter=None, **kwargs)
typing.Optional[str] formatter (self)
None formatter (self, typing.Optional[str] formatter)
Public Attributes
encoding
Public Attributes inherited from graphviz.encoding.Encoding
encoding
Public Attributes inherited from graphviz.parameters.engines.Engine
engine
Public Attributes inherited from graphviz.parameters.formats.Format
format
Public Attributes inherited from graphviz.parameters.renderers.Renderer
renderer
Public Attributes inherited from graphviz.parameters.formatters.Formatter
formatter
Protected Member Functions
typing.Union[bytes, str] _pipe_legacy (self, typing.Optional[str] format=None, typing.Optional[str] renderer=None, typing.Optional[str] formatter=None, typing.Union[bool, int, None] neato_no_op=None, bool quiet=False, *, typing.Optional[str] engine=None, typing.Optional[str] encoding=None)
typing.Union[bytes, str] _pipe_future (self, typing.Optional[str] format=None, *, typing.Optional[str] renderer=None, typing.Optional[str] formatter=None, typing.Union[bool, int, None] neato_no_op=None, bool quiet=False, typing.Optional[str] engine=None, typing.Optional[str] encoding=None)
Protected Member Functions inherited from graphviz.encoding.Encoding
_copy_kwargs (self, **kwargs)
Protected Member Functions inherited from graphviz.backend.mixins.Pipe
_get_pipe_parameters (self, **kwargs)
_pipe_lines (_)
_pipe_lines_string (_)
Protected Member Functions inherited from graphviz.parameters.mixins.Parameters
_get_parameters (self, *, typing.Optional[str] engine=None, typing.Optional[str] format=None, typing.Optional[str] renderer=None, typing.Optional[str] formatter=None, bool verify=False, **kwargs)
Protected Member Functions inherited from graphviz.parameters.engines.Engine
_copy_kwargs (self, **kwargs)
Protected Member Functions inherited from graphviz.parameters.base.ParameterBase
_getattr_from_dict (self, str attrname, *, default=None)
Protected Member Functions inherited from graphviz.parameters.formats.Format
_copy_kwargs (self, **kwargs)
Protected Member Functions inherited from graphviz.parameters.renderers.Renderer
_copy_kwargs (self, **kwargs)
Protected Member Functions inherited from graphviz.parameters.formatters.Formatter
_copy_kwargs (self, **kwargs)
Additional Inherited Members
Static Protected Attributes inherited from graphviz.encoding.Encoding
_encoding = DEFAULT_ENCODING
Static Protected Attributes inherited from graphviz.backend.mixins.Pipe
_get_format = staticmethod(rendering.get_format)
_get_filepath = staticmethod(rendering.get_filepath)
Static Protected Attributes inherited from graphviz.parameters.engines.Engine
_engine = DEFAULT_ENGINE
_verify_engine = staticmethod(verify_engine)
Static Protected Attributes inherited from graphviz.parameters.formats.Format
_format = DEFAULT_FORMAT
_verify_format = staticmethod(verify_format)
Static Protected Attributes inherited from graphviz.parameters.renderers.Renderer
_renderer = None
_verify_renderer = staticmethod(verify_renderer)
Static Protected Attributes inherited from graphviz.parameters.formatters.Formatter
_formatter = None
_verify_formatter = staticmethod(verify_formatter)
Detailed Description
Pipe source lines through the Graphviz layout command.
Member Function Documentation
_pipe_future()
typing.Union[bytes, str] graphviz.piping.Pipe._pipe_future (self, typing.Optional[str] format = None, * , typing.Optional[str] renderer = None, typing.Optional[str] formatter = None, typing.Union[bool, int, None] neato_no_op = None, bool quiet = False, typing.Optional[str] engine = None, typing.Optional[str] encoding = None) protected
References graphviz.backend.mixins.Pipe._get_pipe_parameters().
Referenced by graphviz.piping.Pipe._pipe_legacy().
_pipe_legacy()
typing.Union[bytes, str] graphviz.piping.Pipe._pipe_legacy (self, typing.Optional[str] format = None, typing.Optional[str] renderer = None, typing.Optional[str] formatter = None, typing.Union[bool, int, None] neato_no_op = None, bool quiet = False, * , typing.Optional[str] engine = None, typing.Optional[str] encoding = None) protected
References graphviz.piping.Pipe._pipe_future().
Referenced by graphviz.piping.Pipe.pipe().
pipe() [1/4]
bytes graphviz.piping.Pipe.pipe (self, typing.Optional[str] format = ..., typing.Optional[str] renderer = ..., typing.Optional[str] formatter = ..., typing.Union[bool, int, None] neato_no_op = ..., bool quiet = ..., * , typing.Optional[str] engine = ..., None encoding = ...)
Return bytes with default ``encoding=None``.
Referenced by graphviz.jupyter_integration.JupyterIntegration._repr_image_jpeg(), graphviz.jupyter_integration.JupyterIntegration._repr_image_png(), and graphviz.jupyter_integration.JupyterIntegration._repr_image_svg_xml().
pipe() [2/4]
str graphviz.piping.Pipe.pipe (self, typing.Optional[str] format = ..., typing.Optional[str] renderer = ..., typing.Optional[str] formatter = ..., typing.Union[bool, int, None] neato_no_op = ..., bool quiet = ..., * , typing.Optional[str] engine = ..., str encoding)
Return string when given encoding.
Referenced by graphviz.jupyter_integration.JupyterIntegration._repr_image_jpeg(), graphviz.jupyter_integration.JupyterIntegration._repr_image_png(), and graphviz.jupyter_integration.JupyterIntegration._repr_image_svg_xml().
pipe() [3/4]
typing.Union[bytes, str] graphviz.piping.Pipe.pipe (self, typing.Optional[str] format = ..., typing.Optional[str] renderer = ..., typing.Optional[str] formatter = ..., typing.Union[bool, int, None] neato_no_op = ..., bool quiet = ..., * , typing.Optional[str] engine = ..., typing.Optional[str] encoding)
Return bytes or string depending on encoding argument.
Referenced by graphviz.jupyter_integration.JupyterIntegration._repr_image_jpeg(), graphviz.jupyter_integration.JupyterIntegration._repr_image_png(), and graphviz.jupyter_integration.JupyterIntegration._repr_image_svg_xml().
pipe() [4/4]
typing.Union[bytes, str] graphviz.piping.Pipe.pipe (self, typing.Optional[str] format = None, typing.Optional[str] renderer = None, typing.Optional[str] formatter = None, typing.Union[bool, int, None] neato_no_op = None, bool quiet = False, * , typing.Optional[str] engine = None, typing.Optional[str] encoding = None)
Return the source piped through the Graphviz layout command.
Args:
    format: The output format used for rendering
        (``'pdf'``, ``'png'``, etc.).
    renderer: The output renderer used for rendering
        (``'cairo'``, ``'gd'``, ...).
    formatter: The output formatter used for rendering
        (``'cairo'``, ``'gd'``, ...).
    neato_no_op: Neato layout engine no-op flag.
    quiet (bool): Suppress ``stderr`` output
        from the layout subprocess.
    engine: Layout engine for rendering
        (``'dot'``, ``'neato'``, ...).
    encoding: Encoding for decoding the stdout.
Returns:
    Bytes or if encoding is given decoded string
        (stdout of the layout command).
Raises:
    ValueError: If ``engine``, ``format``, ``renderer``, or ``formatter``
        are unknown.
    graphviz.RequiredArgumentError: If ``formatter`` is given
        but ``renderer`` is None.
    graphviz.ExecutableNotFound: If the Graphviz ``dot`` executable
        is not found.
    graphviz.CalledProcessError: If the returncode (exit status)
        of the rendering ``dot`` subprocess is non-zero.
Example:
    >>> doctest_mark_exe()
    >>> import graphviz
    >>> source = 'graph { spam }'
    >>> graphviz.Source(source, format='svg').pipe()[:14]
    b'<?xml version='
    >>> graphviz.Source(source, format='svg').pipe(encoding='ascii')[:14]
    '<?xml version='
    >>> graphviz.Source(source, format='svg').pipe(encoding='utf-8')[:14]
    '<?xml version='
References graphviz.piping.Pipe._pipe_legacy().
Referenced by graphviz.jupyter_integration.JupyterIntegration._repr_image_jpeg(), graphviz.jupyter_integration.JupyterIntegration._repr_image_png(), and graphviz.jupyter_integration.JupyterIntegration._repr_image_svg_xml().
Member Data Documentation
encoding
graphviz.piping.Pipe.encoding
Referenced by django.http.request.QueryDict.__copy__(), django.http.request.QueryDict.__deepcopy__(), pip._vendor.pygments.formatters.other.TestcaseFormatter.__init__(), django.core.mail.message.SafeMIMEMultipart.__setitem__(), django.core.mail.message.SafeMIMEText.__setitem__(), django.http.request.QueryDict.__setitem__(), django.core.mail.message.EmailMultiAlternatives._create_alternatives(), django.core.mail.message.EmailMessage._create_attachments(), django.core.mail.message.EmailMessage._create_mime_attachment(), pip._vendor.pygments.formatters.html.HtmlFormatter._wrap_full(), django.http.request.QueryDict.appendlist(), pip._vendor.rich.console.ConsoleOptions.ascii_only(), pip._vendor.webencodings.IncrementalDecoder.decode(), django.contrib.gis.gdal.feature.Feature.fields(), pip._vendor.pygments.formatter.Formatter.format(), pip._vendor.pygments.formatters.other.NullFormatter.format(), pip._vendor.pygments.formatters.other.TestcaseFormatter.format(), pip._vendor.requests.models.Response.json(), django.core.mail.message.EmailMessage.message(), django.contrib.gis.gdal.datasource.DataSource.name(), pip._vendor.rich.console.Console.options(), graphviz.saving.Save.save(), django.http.request.QueryDict.setdefault(), django.http.request.QueryDict.setlist(), pip._vendor.requests.models.Response.text(), graphviz.unflattening.Unflatten.unflatten(), django.http.request.QueryDict.urlencode(), and django.contrib.gis.utils.layermapping.LayerMapping.verify_ogr_field().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/graphviz/piping.py