Django Project: pkg_resources._vendor.packaging._manylinux._ELFFileHeader Class Reference
pkg_resources._vendor.packaging._manylinux._ELFFileHeader Class Reference
Classes
class _InvalidELFFileHeader
Public Member Functions
None __init__ (self, IO[bytes] file)
Public Attributes
e_ident_magic
e_ident_class
ELFCLASS32
e_ident_data
ELFDATA2LSB
e_ident_version
e_ident_osabi
e_ident_abiversion
e_ident_pad
e_type
e_machine
e_version
e_entry
e_phoff
e_shoff
e_flags
e_ehsize
e_phentsize
e_phnum
e_shentsize
e_shnum
e_shstrndx
Static Public Attributes
ELF_MAGIC_NUMBER
int ELFCLASS32 = 1
int ELFCLASS64 = 2
int ELFDATA2LSB = 1
int ELFDATA2MSB = 2
int EM_386 = 3
int EM_S390 = 22
int EM_ARM = 40
int EM_X86_64 = 62
int EF_ARM_ABIMASK = 0xFF000000
int EF_ARM_ABI_VER5 = 0x05000000
int EF_ARM_ABI_FLOAT_HARD = 0x00000400
Constructor & Destructor Documentation
__init__()
None pkg_resources._vendor.packaging._manylinux._ELFFileHeader.__init__ (self, IO[bytes] file)
Referenced by setuptools._vendor.typing_extensions._ProtocolMeta.__init__(), pip._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.ordered_set.OrderedSet.__setstate__(), and django.db.models.expressions.Expression.identity().
Member Data Documentation
e_ehsize
pkg_resources._vendor.packaging._manylinux._ELFFileHeader.e_ehsize
e_entry
pkg_resources._vendor.packaging._manylinux._ELFFileHeader.e_entry
e_flags
pkg_resources._vendor.packaging._manylinux._ELFFileHeader.e_flags
e_ident_abiversion
pkg_resources._vendor.packaging._manylinux._ELFFileHeader.e_ident_abiversion
e_ident_class
pkg_resources._vendor.packaging._manylinux._ELFFileHeader.e_ident_class
e_ident_data
pkg_resources._vendor.packaging._manylinux._ELFFileHeader.e_ident_data
e_ident_magic
pkg_resources._vendor.packaging._manylinux._ELFFileHeader.e_ident_magic
e_ident_osabi
pkg_resources._vendor.packaging._manylinux._ELFFileHeader.e_ident_osabi
e_ident_pad
pkg_resources._vendor.packaging._manylinux._ELFFileHeader.e_ident_pad
e_ident_version
pkg_resources._vendor.packaging._manylinux._ELFFileHeader.e_ident_version
e_machine
pkg_resources._vendor.packaging._manylinux._ELFFileHeader.e_machine
e_phentsize
pkg_resources._vendor.packaging._manylinux._ELFFileHeader.e_phentsize
e_phnum
pkg_resources._vendor.packaging._manylinux._ELFFileHeader.e_phnum
e_phoff
pkg_resources._vendor.packaging._manylinux._ELFFileHeader.e_phoff
e_shentsize
pkg_resources._vendor.packaging._manylinux._ELFFileHeader.e_shentsize
e_shnum
pkg_resources._vendor.packaging._manylinux._ELFFileHeader.e_shnum
e_shoff
pkg_resources._vendor.packaging._manylinux._ELFFileHeader.e_shoff
e_shstrndx
pkg_resources._vendor.packaging._manylinux._ELFFileHeader.e_shstrndx
e_type
pkg_resources._vendor.packaging._manylinux._ELFFileHeader.e_type
e_version
pkg_resources._vendor.packaging._manylinux._ELFFileHeader.e_version
EF_ARM_ABI_FLOAT_HARD
int pkg_resources._vendor.packaging._manylinux._ELFFileHeader.EF_ARM_ABI_FLOAT_HARD = 0x00000400 static
EF_ARM_ABI_VER5
int pkg_resources._vendor.packaging._manylinux._ELFFileHeader.EF_ARM_ABI_VER5 = 0x05000000 static
EF_ARM_ABIMASK
int pkg_resources._vendor.packaging._manylinux._ELFFileHeader.EF_ARM_ABIMASK = 0xFF000000 static
ELF_MAGIC_NUMBER
pkg_resources._vendor.packaging._manylinux._ELFFileHeader.ELF_MAGIC_NUMBER static
ELFCLASS32 [1/2]
int pkg_resources._vendor.packaging._manylinux._ELFFileHeader.ELFCLASS32 = 1 static
ELFCLASS32 [2/2]
pkg_resources._vendor.packaging._manylinux._ELFFileHeader.ELFCLASS32
ELFCLASS64
int pkg_resources._vendor.packaging._manylinux._ELFFileHeader.ELFCLASS64 = 2 static
ELFDATA2LSB [1/2]
int pkg_resources._vendor.packaging._manylinux._ELFFileHeader.ELFDATA2LSB = 1 static
ELFDATA2LSB [2/2]
pkg_resources._vendor.packaging._manylinux._ELFFileHeader.ELFDATA2LSB
ELFDATA2MSB
int pkg_resources._vendor.packaging._manylinux._ELFFileHeader.ELFDATA2MSB = 2 static
EM_386
int pkg_resources._vendor.packaging._manylinux._ELFFileHeader.EM_386 = 3 static
EM_ARM
int pkg_resources._vendor.packaging._manylinux._ELFFileHeader.EM_ARM = 40 static
EM_S390
int pkg_resources._vendor.packaging._manylinux._ELFFileHeader.EM_S390 = 22 static
EM_X86_64
int pkg_resources._vendor.packaging._manylinux._ELFFileHeader.EM_X86_64 = 62 static
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/pkg_resources/_vendor/packaging/_manylinux.py