Django Project: _pytest.logging.PercentStyleMultiline Class Reference
_pytest.logging.PercentStyleMultiline Class Reference
Public Member Functions
None __init__ (self, str fmt, int|str|bool|None auto_indent)
str format (self, logging.LogRecord record)
Static Protected Member Functions
int _get_auto_indent (int|str|bool|None auto_indent_option)
Protected Attributes
_auto_indent
Detailed Description
A logging style with special support for multiline messages.
If the message of a record consists of multiple lines, this style
formats the message as if each line were logged separately.
Constructor & Destructor Documentation
__init__()
None _pytest.logging.PercentStyleMultiline.__init__ (self, str fmt, int | str | bool | None auto_indent)
References _pytest.logging.PercentStyleMultiline.__init__().
Referenced by _pytest.logging.PercentStyleMultiline.__init__(), setuptools._vendor.typing_extensions._ProtocolMeta.__init__(), pip._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.ordered_set.OrderedSet.__setstate__(), and django.db.models.expressions.Expression.identity().
Member Function Documentation
_get_auto_indent()
int _pytest.logging.PercentStyleMultiline._get_auto_indent (int | str | bool | None auto_indent_option) static protected
Determine the current auto indentation setting.
Specify auto indent behavior (on/off/fixed) by passing in
extra={"auto_indent": [value]} to the call to logging.log() or
using a --log-auto-indent [value] command line or the
log_auto_indent [value] config option.
Default behavior is auto-indent off.
Using the string "True" or "on" or the boolean True as the value
turns auto indent on, using the string "False" or "off" or the
boolean False or the int 0 turns it off, and specifying a
positive integer fixes the indentation position to the value
specified.
Any other values for the option are invalid, and will silently be
converted to the default.
:param None|bool|int|str auto_indent_option:
    User specified option for indentation from command line, config
    or extra kwarg. Accepts int, bool or str. str option accepts the
    same range of values as boolean config options, as well as
    positive integers represented in str form.
:returns:
    Indentation value, which can be
    -1 (automatically determine indentation) or
    0 (auto-indent turned off) or
    >0 (explicitly set indentation position).
Referenced by _pytest.logging.PercentStyleMultiline.format().
format()
str _pytest.logging.PercentStyleMultiline.format (self, logging.LogRecord record)
References _pytest.logging.PercentStyleMultiline._auto_indent, cryptography.hazmat.backends.openssl.backend.GetCipherByName._fmt, _pytest.logging.PercentStyleMultiline._get_auto_indent(), and _pytest.logging._remove_ansi_escape_sequences().
Referenced by graphviz.parameters.mixins.Parameters._get_parameters(), django.utils.log.AdminEmailHandler.emit(), pip._internal.utils.logging.RichPipStreamHandler.emit(), pip._vendor.rich.logging.RichHandler.emit(), setuptools._distutils.command.bdist_dumb.bdist_dumb.finalize_options(), setuptools.depends.Require.get_version(), django.core.management.commands.loaddata.Command.parse_name(), setuptools._distutils.command.bdist_dumb.bdist_dumb.run(), and setuptools.depends.Require.version_ok().
Member Data Documentation
_auto_indent
_pytest.logging.PercentStyleMultiline._auto_indent protected
Referenced by _pytest.logging.PercentStyleMultiline.format().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/_pytest/logging.py