Django Project: cryptography.hazmat.primitives.asymmetric.dsa.DSAPrivateKey Class Reference
cryptography.hazmat.primitives.asymmetric.dsa.DSAPrivateKey Class Reference
Public Member Functions
int key_size (self)
DSAPublicKey public_key (self)
DSAParameters parameters (self)
bytes sign (self, bytes data, asym_utils.Prehashed|hashes.HashAlgorithm algorithm)
DSAPrivateNumbers private_numbers (self)
bytes private_bytes (self, _serialization.Encoding encoding, _serialization.PrivateFormat format, _serialization.KeySerializationEncryption encryption_algorithm)
Member Function Documentation
key_size()
int cryptography.hazmat.primitives.asymmetric.dsa.DSAPrivateKey.key_size (self)
The bit length of the prime modulus.
parameters()
DSAParameters cryptography.hazmat.primitives.asymmetric.dsa.DSAPrivateKey.parameters (self)
The DSAParameters object associated with this private key.
Referenced by pip._vendor.rich.markup.Tag.__str__(), and pip._vendor.rich.markup.Tag.markup().
private_bytes()
bytes cryptography.hazmat.primitives.asymmetric.dsa.DSAPrivateKey.private_bytes (self, _serialization.Encoding encoding, _serialization.PrivateFormat format, _serialization.KeySerializationEncryption encryption_algorithm)
Returns the key serialized as bytes.
private_numbers()
DSAPrivateNumbers cryptography.hazmat.primitives.asymmetric.dsa.DSAPrivateKey.private_numbers (self)
Returns a DSAPrivateNumbers.
public_key()
DSAPublicKey cryptography.hazmat.primitives.asymmetric.dsa.DSAPrivateKey.public_key (self)
The DSAPublicKey associated with this private key.
sign()
bytes cryptography.hazmat.primitives.asymmetric.dsa.DSAPrivateKey.sign (self, bytes data, asym_utils.Prehashed | hashes.HashAlgorithm algorithm)
Signs the data
Referenced by setuptools._distutils.command.upload.upload.finalize_options(), django.core.signing.Signer.sign_object(), and setuptools._distutils.command.upload.upload.upload_file().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py