Django Project: _pytest.nodes.NodeMeta Class Reference
_pytest.nodes.NodeMeta Class Reference
Public Member Functions
NoReturn __call__ (cls, *k, **kw)
Protected Member Functions
_T _create (type[_T] cls, *k, **kw)
Detailed Description
Metaclass used by :class:`Node` to enforce that direct construction raises
:class:`Failed`.
This behaviour supports the indirection introduced with :meth:`Node.from_parent`,
the named constructor to be used instead of direct construction. The design
decision to enforce indirection with :class:`NodeMeta` was made as a
temporary aid for refactoring the collection tree, which was diagnosed to
have :class:`Node` objects whose creational patterns were overly entangled.
Once the refactoring is complete, this metaclass can be removed.
See https://github.com/pytest-dev/pytest/projects/3 for an overview of the
progress on detangling the :class:`Node` classes.
Member Function Documentation
__call__()
NoReturn _pytest.nodes.NodeMeta.__call__ (cls, * k, ** kw)
Referenced by asgiref.sync.AsyncToSync.__get__(), asgiref.sync.SyncToAsync.__get__(), and _pytest.nodes.NodeMeta._create().
_create()
_T _pytest.nodes.NodeMeta._create (type[_T] cls, * k, ** kw) protected
References _pytest.nodes.NodeMeta.__call__().
Referenced by _pytest.main.Session.from_config(), and _pytest.nodes.Node.from_parent().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/_pytest/nodes.py