Django Project: pycparser.c_parser.CParser Class Reference
pycparser.c_parser.CParser Class Reference
Public Member Functions
__init__ (self, lex_optimize=True, lexer=CLexer, lextab='pycparser.lextab', yacc_optimize=True, yacctab='pycparser.yacctab', yacc_debug=False, taboutputdir='')
parse (self, text, filename='', debug=False)
p_translation_unit_or_empty (self, p)
Grammar productions Implementation of the BNF defined in K&R2 A.13.
p_translation_unit_1 (self, p)
p_translation_unit_2 (self, p)
p_external_declaration_1 (self, p)
p_external_declaration_2 (self, p)
p_external_declaration_3 (self, p)
p_external_declaration_4 (self, p)
p_external_declaration_5 (self, p)
p_static_assert_declaration (self, p)
p_pp_directive (self, p)
p_pppragma_directive (self, p)
p_pppragma_directive_list (self, p)
p_function_definition_1 (self, p)
p_function_definition_2 (self, p)
p_statement (self, p)
p_pragmacomp_or_statement (self, p)
p_decl_body (self, p)
p_declaration (self, p)
p_declaration_list (self, p)
p_declaration_specifiers_no_type_1 (self, p)
p_declaration_specifiers_no_type_2 (self, p)
p_declaration_specifiers_no_type_3 (self, p)
p_declaration_specifiers_no_type_4 (self, p)
p_declaration_specifiers_no_type_5 (self, p)
p_declaration_specifiers_1 (self, p)
p_declaration_specifiers_2 (self, p)
p_declaration_specifiers_3 (self, p)
p_declaration_specifiers_4 (self, p)
p_declaration_specifiers_5 (self, p)
p_declaration_specifiers_6 (self, p)
p_declaration_specifiers_7 (self, p)
p_storage_class_specifier (self, p)
p_function_specifier (self, p)
p_type_specifier_no_typeid (self, p)
p_type_specifier (self, p)
p_atomic_specifier (self, p)
p_type_qualifier (self, p)
p_init_declarator_list (self, p)
p_init_declarator (self, p)
p_id_init_declarator_list (self, p)
p_id_init_declarator (self, p)
p_specifier_qualifier_list_1 (self, p)
p_specifier_qualifier_list_2 (self, p)
p_specifier_qualifier_list_3 (self, p)
p_specifier_qualifier_list_4 (self, p)
p_specifier_qualifier_list_5 (self, p)
p_specifier_qualifier_list_6 (self, p)
p_struct_or_union_specifier_1 (self, p)
p_struct_or_union_specifier_2 (self, p)
p_struct_or_union_specifier_3 (self, p)
p_struct_or_union (self, p)
p_struct_declaration_list (self, p)
p_struct_declaration_1 (self, p)
p_struct_declaration_2 (self, p)
p_struct_declaration_3 (self, p)
p_struct_declarator_list (self, p)
p_struct_declarator_1 (self, p)
p_struct_declarator_2 (self, p)
p_enum_specifier_1 (self, p)
p_enum_specifier_2 (self, p)
p_enum_specifier_3 (self, p)
p_enumerator_list (self, p)
p_alignment_specifier (self, p)
p_enumerator (self, p)
p_declarator (self, p)
p_xxx_declarator_1 (self, p)
p_xxx_declarator_2 (self, p)
p_direct_xxx_declarator_1 (self, p)
p_direct_xxx_declarator_2 (self, p)
p_direct_xxx_declarator_3 (self, p)
p_direct_xxx_declarator_4 (self, p)
p_direct_xxx_declarator_5 (self, p)
p_direct_xxx_declarator_6 (self, p)
p_pointer (self, p)
p_type_qualifier_list (self, p)
p_parameter_type_list (self, p)
p_parameter_list (self, p)
p_parameter_declaration_1 (self, p)
p_parameter_declaration_2 (self, p)
p_identifier_list (self, p)
p_initializer_1 (self, p)
p_initializer_2 (self, p)
p_initializer_list (self, p)
p_designation (self, p)
p_designator_list (self, p)
p_designator (self, p)
p_type_name (self, p)
p_abstract_declarator_1 (self, p)
p_abstract_declarator_2 (self, p)
p_abstract_declarator_3 (self, p)
p_direct_abstract_declarator_1 (self, p)
p_direct_abstract_declarator_2 (self, p)
p_direct_abstract_declarator_3 (self, p)
p_direct_abstract_declarator_4 (self, p)
p_direct_abstract_declarator_5 (self, p)
p_direct_abstract_declarator_6 (self, p)
p_direct_abstract_declarator_7 (self, p)
p_block_item (self, p)
p_block_item_list (self, p)
p_compound_statement_1 (self, p)
p_labeled_statement_1 (self, p)
p_labeled_statement_2 (self, p)
p_labeled_statement_3 (self, p)
p_selection_statement_1 (self, p)
p_selection_statement_2 (self, p)
p_selection_statement_3 (self, p)
p_iteration_statement_1 (self, p)
p_iteration_statement_2 (self, p)
p_iteration_statement_3 (self, p)
p_iteration_statement_4 (self, p)
p_jump_statement_1 (self, p)
p_jump_statement_2 (self, p)
p_jump_statement_3 (self, p)
p_jump_statement_4 (self, p)
p_expression_statement (self, p)
p_expression (self, p)
p_parenthesized_compound_expression (self, p)
p_typedef_name (self, p)
p_assignment_expression (self, p)
p_assignment_operator (self, p)
p_constant_expression (self, p)
p_conditional_expression (self, p)
p_binary_expression (self, p)
p_cast_expression_1 (self, p)
p_cast_expression_2 (self, p)
p_unary_expression_1 (self, p)
p_unary_expression_2 (self, p)
p_unary_expression_3 (self, p)
p_unary_operator (self, p)
p_postfix_expression_1 (self, p)
p_postfix_expression_2 (self, p)
p_postfix_expression_3 (self, p)
p_postfix_expression_4 (self, p)
p_postfix_expression_5 (self, p)
p_postfix_expression_6 (self, p)
p_primary_expression_1 (self, p)
p_primary_expression_2 (self, p)
p_primary_expression_3 (self, p)
p_primary_expression_4 (self, p)
p_primary_expression_5 (self, p)
p_offsetof_member_designator (self, p)
p_argument_expression_list (self, p)
p_identifier (self, p)
p_constant_1 (self, p)
p_constant_2 (self, p)
p_constant_3 (self, p)
p_unified_string_literal (self, p)
p_unified_wstring_literal (self, p)
p_brace_open (self, p)
p_brace_close (self, p)
p_empty (self, p)
p_error (self, p)
Public Attributes
clex
tokens
cparser
Static Public Attributes
tuple precedence
Precedence and associativity of operators.
Protected Member Functions
_push_scope (self)
– PRIVATE –######################
_pop_scope (self)
_add_typedef_name (self, name, coord)
_add_identifier (self, name, coord)
_is_type_in_scope (self, name)
_lex_error_func (self, msg, line, column)
_lex_on_lbrace_func (self)
_lex_on_rbrace_func (self)
_lex_type_lookup_func (self, name)
_get_yacc_lookahead_token (self)
_type_modify_decl (self, decl, modifier)
_fix_decl_name_type (self, decl, typename)
_add_declaration_specifier (self, declspec, newspec, kind, append=False)
_build_declarations (self, spec, decls, typedef_namespace=False)
_build_function_definition (self, spec, decl, param_decls, body)
_select_struct_union_class (self, token)
Protected Member Functions inherited from pycparser.plyparser.PLYParser
_create_opt_rule (self, rulename)
_coord (self, lineno, column=None)
_token_coord (self, p, token_idx)
_parse_error (self, msg, coord)
Protected Attributes
_scope_stack
_last_yielded_token
Constructor & Destructor Documentation
__init__()
pycparser.c_parser.CParser.__init__ (self, lex_optimize = True, lexer = CLexer, lextab = 'pycparser.lextab', yacc_optimize = True, yacctab = 'pycparser.yacctab', yacc_debug = False, taboutputdir = '')
 Create a new CParser.
    Some arguments for controlling the debug/optimization
    level of the parser are provided. The defaults are
    tuned for release/performance mode.
    The simple rules for using them are:
    *) When tweaking CParser/CLexer, set these to False
    *) When releasing a stable parser, set to True
    lex_optimize:
        Set to False when you're modifying the lexer.
        Otherwise, changes in the lexer won't be used, if
        some lextab.py file exists.
        When releasing with a stable lexer, set to True
        to save the re-generation of the lexer table on
        each run.
    lexer:
        Set this parameter to define the lexer to use if
        you're not using the default CLexer.
    lextab:
        Points to the lex table that's used for optimized
        mode. Only if you're modifying the lexer and want
        some tests to avoid re-generating the table, make
        this point to a local lex table file (that's been
        earlier generated with lex_optimize=True)
    yacc_optimize:
        Set to False when you're modifying the parser.
        Otherwise, changes in the parser won't be used, if
        some parsetab.py file exists.
        When releasing with a stable parser, set to True
        to save the re-generation of the parser table on
        each run.
    yacctab:
        Points to the yacc table that's used for optimized
        mode. Only if you're modifying the parser, make
        this point to a local yacc table file
    yacc_debug:
        Generate a parser.out file that explains how yacc
        built the parsing table from the grammar.
    taboutputdir:
        Set this parameter to control the location of generated
        lextab and yacctab files.
Referenced by setuptools._vendor.typing_extensions._ProtocolMeta.__init__(), pip._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.ordered_set.OrderedSet.__setstate__(), and django.db.models.expressions.Expression.identity().
Member Function Documentation
_add_declaration_specifier()
pycparser.c_parser.CParser._add_declaration_specifier (self, declspec, newspec, kind, append = False) protected
 Declaration specifiers are represented by a dictionary
    with the entries:
    * qual: a list of type qualifiers
    * storage: a list of storage type qualifiers
    * type: a list of type specifiers
    * function: a list of function specifiers
    * alignment: a list of alignment specifiers
    This method is given a declaration specifier, and a
    new specifier of a given kind.
    If `append` is True, the new specifier is added to the end of
    the specifiers list, otherwise it's added at the beginning.
    Returns the declaration specifier, with the new
    specifier incorporated.
Referenced by pycparser.c_parser.CParser.p_declaration_specifiers_1(), pycparser.c_parser.CParser.p_declaration_specifiers_2(), pycparser.c_parser.CParser.p_declaration_specifiers_3(), pycparser.c_parser.CParser.p_declaration_specifiers_4(), pycparser.c_parser.CParser.p_declaration_specifiers_5(), pycparser.c_parser.CParser.p_declaration_specifiers_6(), pycparser.c_parser.CParser.p_declaration_specifiers_7(), pycparser.c_parser.CParser.p_declaration_specifiers_no_type_1(), pycparser.c_parser.CParser.p_declaration_specifiers_no_type_2(), pycparser.c_parser.CParser.p_declaration_specifiers_no_type_3(), pycparser.c_parser.CParser.p_declaration_specifiers_no_type_4(), pycparser.c_parser.CParser.p_declaration_specifiers_no_type_5(), pycparser.c_parser.CParser.p_specifier_qualifier_list_1(), pycparser.c_parser.CParser.p_specifier_qualifier_list_2(), pycparser.c_parser.CParser.p_specifier_qualifier_list_3(), and pycparser.c_parser.CParser.p_specifier_qualifier_list_6().
_add_identifier()
pycparser.c_parser.CParser._add_identifier (self, name, coord) protected
 Add a new object, function, or enum member name (ie an ID) to the
    current scope
References pycparser.plyparser.PLYParser._parse_error(), and pycparser.c_parser.CParser._scope_stack.
Referenced by pycparser.c_parser.CParser._build_declarations(), pycparser.c_parser.CParser.p_direct_xxx_declarator_6(), and pycparser.c_parser.CParser.p_enumerator().
_add_typedef_name()
pycparser.c_parser.CParser._add_typedef_name (self, name, coord) protected
 Add a new typedef name (ie a TYPEID) to the current scope
References pycparser.plyparser.PLYParser._parse_error(), and pycparser.c_parser.CParser._scope_stack.
Referenced by pycparser.c_parser.CParser._build_declarations().
_build_declarations()
pycparser.c_parser.CParser._build_declarations (self, spec, decls, typedef_namespace = False) protected
 Builds a list of declarations all sharing the given specifiers.
    If typedef_namespace is true, each declared name is added
    to the "typedef namespace", which also includes objects,
    functions, and enum constants.
References pycparser.c_parser.CParser._add_identifier(), pycparser.c_parser.CParser._add_typedef_name(), pycparser.c_parser.CParser._fix_decl_name_type(), pycparser.c_parser.CParser._is_type_in_scope(), and pycparser.plyparser.PLYParser._parse_error().
Referenced by pycparser.c_parser.CParser._build_function_definition(), pycparser.c_parser.CParser.p_decl_body(), pycparser.c_parser.CParser.p_parameter_declaration_1(), pycparser.c_parser.CParser.p_parameter_declaration_2(), and pycparser.c_parser.CParser.p_struct_declaration_1().
_build_function_definition()
pycparser.c_parser.CParser._build_function_definition (self, spec, decl, param_decls, body) protected
 Builds a function definition.
References pycparser.c_parser.CParser._build_declarations(), and pycparser.plyparser.PLYParser._parse_error().
Referenced by pycparser.c_parser.CParser.p_function_definition_1(), and pycparser.c_parser.CParser.p_function_definition_2().
_fix_decl_name_type()
pycparser.c_parser.CParser._fix_decl_name_type (self, decl, typename) protected
 Fixes a declaration. Modifies decl.
References pycparser.plyparser.PLYParser._parse_error().
Referenced by pycparser.c_parser.CParser._build_declarations(), pycparser.c_parser.CParser.p_parameter_declaration_2(), and pycparser.c_parser.CParser.p_type_name().
_get_yacc_lookahead_token()
pycparser.c_parser.CParser._get_yacc_lookahead_token (self) protected
 We need access to yacc's lookahead token in certain cases.
    This is the last token yacc requested from the lexer, so we
    ask the lexer.
References pycparser.c_parser.CParser.clex.
Referenced by pycparser.c_parser.CParser.p_direct_xxx_declarator_6().
_is_type_in_scope()
pycparser.c_parser.CParser._is_type_in_scope (self, name) protected
 Is *name* a typedef-name in the current scope?
References pycparser.c_parser.CParser._scope_stack.
Referenced by pycparser.c_parser.CParser._build_declarations(), pycparser.c_parser.CParser._lex_type_lookup_func(), and pycparser.c_parser.CParser.p_parameter_declaration_2().
_lex_error_func()
pycparser.c_parser.CParser._lex_error_func (self, msg, line, column) protected
References pycparser.plyparser.PLYParser._coord(), and pycparser.plyparser.PLYParser._parse_error().
_lex_on_lbrace_func()
pycparser.c_parser.CParser._lex_on_lbrace_func (self) protected
References pycparser.c_parser.CParser._push_scope().
_lex_on_rbrace_func()
pycparser.c_parser.CParser._lex_on_rbrace_func (self) protected
References pycparser.c_parser.CParser._pop_scope().
_lex_type_lookup_func()
pycparser.c_parser.CParser._lex_type_lookup_func (self, name) protected
 Looks up types that were previously defined with
    typedef.
    Passed to the lexer for recognizing identifiers that
    are types.
References pycparser.c_parser.CParser._is_type_in_scope().
_pop_scope()
pycparser.c_parser.CParser._pop_scope (self) protected
References pycparser.c_parser.CParser._scope_stack.
Referenced by pycparser.c_parser.CParser._lex_on_rbrace_func().
_push_scope()
pycparser.c_parser.CParser._push_scope (self) protected
– PRIVATE –######################
References pycparser.c_parser.CParser._scope_stack.
Referenced by pycparser.c_parser.CParser._lex_on_lbrace_func().
_select_struct_union_class()
pycparser.c_parser.CParser._select_struct_union_class (self, token) protected
 Given a token (either STRUCT or UNION), selects the
    appropriate AST class.
Referenced by pycparser.c_parser.CParser.p_struct_or_union_specifier_1(), pycparser.c_parser.CParser.p_struct_or_union_specifier_2(), and pycparser.c_parser.CParser.p_struct_or_union_specifier_3().
_type_modify_decl()
pycparser.c_parser.CParser._type_modify_decl (self, decl, modifier) protected
 Tacks a type modifier on a declarator, and returns
    the modified declarator.
    Note: the declarator and modifier may be modified
Referenced by pycparser.c_parser.CParser.p_abstract_declarator_1(), pycparser.c_parser.CParser.p_abstract_declarator_2(), pycparser.c_parser.CParser.p_direct_abstract_declarator_2(), pycparser.c_parser.CParser.p_direct_abstract_declarator_4(), pycparser.c_parser.CParser.p_direct_abstract_declarator_6(), pycparser.c_parser.CParser.p_direct_xxx_declarator_3(), pycparser.c_parser.CParser.p_direct_xxx_declarator_4(), pycparser.c_parser.CParser.p_direct_xxx_declarator_5(), pycparser.c_parser.CParser.p_direct_xxx_declarator_6(), and pycparser.c_parser.CParser.p_xxx_declarator_2().
p_abstract_declarator_1()
pycparser.c_parser.CParser.p_abstract_declarator_1 (self, p)
 abstract_declarator     : pointer
References pycparser.c_parser.CParser._type_modify_decl().
p_abstract_declarator_2()
pycparser.c_parser.CParser.p_abstract_declarator_2 (self, p)
 abstract_declarator     : pointer direct_abstract_declarator
References pycparser.c_parser.CParser._type_modify_decl().
p_abstract_declarator_3()
pycparser.c_parser.CParser.p_abstract_declarator_3 (self, p)
 abstract_declarator     : direct_abstract_declarator
p_alignment_specifier()
pycparser.c_parser.CParser.p_alignment_specifier (self, p)
 alignment_specifier  : _ALIGNAS LPAREN type_name RPAREN
                         | _ALIGNAS LPAREN constant_expression RPAREN
References pycparser.plyparser.PLYParser._token_coord().
p_argument_expression_list()
pycparser.c_parser.CParser.p_argument_expression_list (self, p)
 argument_expression_list    : assignment_expression
                                | argument_expression_list COMMA assignment_expression
p_assignment_expression()
pycparser.c_parser.CParser.p_assignment_expression (self, p)
 assignment_expression   : conditional_expression
                            | unary_expression assignment_operator assignment_expression
p_assignment_operator()
pycparser.c_parser.CParser.p_assignment_operator (self, p)
 assignment_operator : EQUALS
                        | XOREQUAL
                        | TIMESEQUAL
                        | DIVEQUAL
                        | MODEQUAL
                        | PLUSEQUAL
                        | MINUSEQUAL
                        | LSHIFTEQUAL
                        | RSHIFTEQUAL
                        | ANDEQUAL
                        | OREQUAL
p_atomic_specifier()
pycparser.c_parser.CParser.p_atomic_specifier (self, p)
 atomic_specifier  : _ATOMIC LPAREN type_name RPAREN
p_binary_expression()
pycparser.c_parser.CParser.p_binary_expression (self, p)
 binary_expression   : cast_expression
                        | binary_expression TIMES binary_expression
                        | binary_expression DIVIDE binary_expression
                        | binary_expression MOD binary_expression
                        | binary_expression PLUS binary_expression
                        | binary_expression MINUS binary_expression
                        | binary_expression RSHIFT binary_expression
                        | binary_expression LSHIFT binary_expression
                        | binary_expression LT binary_expression
                        | binary_expression LE binary_expression
                        | binary_expression GE binary_expression
                        | binary_expression GT binary_expression
                        | binary_expression EQ binary_expression
                        | binary_expression NE binary_expression
                        | binary_expression AND binary_expression
                        | binary_expression OR binary_expression
                        | binary_expression XOR binary_expression
                        | binary_expression LAND binary_expression
                        | binary_expression LOR binary_expression
p_block_item()
pycparser.c_parser.CParser.p_block_item (self, p)
 block_item  : declaration
                | statement
p_block_item_list()
pycparser.c_parser.CParser.p_block_item_list (self, p)
 block_item_list : block_item
                    | block_item_list block_item
p_brace_close()
pycparser.c_parser.CParser.p_brace_close (self, p)
 brace_close :   RBRACE
p_brace_open()
pycparser.c_parser.CParser.p_brace_open (self, p)
 brace_open  :   LBRACE
p_cast_expression_1()
pycparser.c_parser.CParser.p_cast_expression_1 (self, p)
 cast_expression : unary_expression
p_cast_expression_2()
pycparser.c_parser.CParser.p_cast_expression_2 (self, p)
 cast_expression : LPAREN type_name RPAREN cast_expression
References pycparser.plyparser.PLYParser._token_coord().
p_compound_statement_1()
pycparser.c_parser.CParser.p_compound_statement_1 (self, p)
 compound_statement : brace_open block_item_list_opt brace_close
References pycparser.plyparser.PLYParser._token_coord().
p_conditional_expression()
pycparser.c_parser.CParser.p_conditional_expression (self, p)
 conditional_expression  : binary_expression
                            | binary_expression CONDOP expression COLON conditional_expression
p_constant_1()
pycparser.c_parser.CParser.p_constant_1 (self, p)
 constant    : INT_CONST_DEC
                | INT_CONST_OCT
                | INT_CONST_HEX
                | INT_CONST_BIN
                | INT_CONST_CHAR
References pycparser.plyparser.PLYParser._token_coord().
p_constant_2()
pycparser.c_parser.CParser.p_constant_2 (self, p)
 constant    : FLOAT_CONST
                | HEX_FLOAT_CONST
References pycparser.plyparser.PLYParser._token_coord().
p_constant_3()
pycparser.c_parser.CParser.p_constant_3 (self, p)
 constant    : CHAR_CONST
                | WCHAR_CONST
                | U8CHAR_CONST
                | U16CHAR_CONST
                | U32CHAR_CONST
References pycparser.plyparser.PLYParser._token_coord().
p_constant_expression()
pycparser.c_parser.CParser.p_constant_expression (self, p)
 constant_expression : conditional_expression
p_decl_body()
pycparser.c_parser.CParser.p_decl_body (self, p)
 decl_body : declaration_specifiers init_declarator_list_opt
              | declaration_specifiers_no_type id_init_declarator_list_opt
References pycparser.c_parser.CParser._build_declarations().
p_declaration()
pycparser.c_parser.CParser.p_declaration (self, p)
 declaration : decl_body SEMI
p_declaration_list()
pycparser.c_parser.CParser.p_declaration_list (self, p)
 declaration_list    : declaration
                        | declaration_list declaration
p_declaration_specifiers_1()
pycparser.c_parser.CParser.p_declaration_specifiers_1 (self, p)
 declaration_specifiers  : declaration_specifiers type_qualifier
References pycparser.c_parser.CParser._add_declaration_specifier().
p_declaration_specifiers_2()
pycparser.c_parser.CParser.p_declaration_specifiers_2 (self, p)
 declaration_specifiers  : declaration_specifiers storage_class_specifier
References pycparser.c_parser.CParser._add_declaration_specifier().
p_declaration_specifiers_3()
pycparser.c_parser.CParser.p_declaration_specifiers_3 (self, p)
 declaration_specifiers  : declaration_specifiers function_specifier
References pycparser.c_parser.CParser._add_declaration_specifier().
p_declaration_specifiers_4()
pycparser.c_parser.CParser.p_declaration_specifiers_4 (self, p)
 declaration_specifiers  : declaration_specifiers type_specifier_no_typeid
References pycparser.c_parser.CParser._add_declaration_specifier().
p_declaration_specifiers_5()
pycparser.c_parser.CParser.p_declaration_specifiers_5 (self, p)
 declaration_specifiers  : type_specifier
References pycparser.c_parser.CParser._add_declaration_specifier().
p_declaration_specifiers_6()
pycparser.c_parser.CParser.p_declaration_specifiers_6 (self, p)
 declaration_specifiers  : declaration_specifiers_no_type type_specifier
References pycparser.c_parser.CParser._add_declaration_specifier().
p_declaration_specifiers_7()
pycparser.c_parser.CParser.p_declaration_specifiers_7 (self, p)
 declaration_specifiers  : declaration_specifiers alignment_specifier
References pycparser.c_parser.CParser._add_declaration_specifier().
p_declaration_specifiers_no_type_1()
pycparser.c_parser.CParser.p_declaration_specifiers_no_type_1 (self, p)
 declaration_specifiers_no_type  : type_qualifier declaration_specifiers_no_type_opt
References pycparser.c_parser.CParser._add_declaration_specifier().
p_declaration_specifiers_no_type_2()
pycparser.c_parser.CParser.p_declaration_specifiers_no_type_2 (self, p)
 declaration_specifiers_no_type  : storage_class_specifier declaration_specifiers_no_type_opt
References pycparser.c_parser.CParser._add_declaration_specifier().
p_declaration_specifiers_no_type_3()
pycparser.c_parser.CParser.p_declaration_specifiers_no_type_3 (self, p)
 declaration_specifiers_no_type  : function_specifier declaration_specifiers_no_type_opt
References pycparser.c_parser.CParser._add_declaration_specifier().
p_declaration_specifiers_no_type_4()
pycparser.c_parser.CParser.p_declaration_specifiers_no_type_4 (self, p)
 declaration_specifiers_no_type  : atomic_specifier declaration_specifiers_no_type_opt
References pycparser.c_parser.CParser._add_declaration_specifier().
p_declaration_specifiers_no_type_5()
pycparser.c_parser.CParser.p_declaration_specifiers_no_type_5 (self, p)
 declaration_specifiers_no_type  : alignment_specifier declaration_specifiers_no_type_opt
References pycparser.c_parser.CParser._add_declaration_specifier().
p_declarator()
pycparser.c_parser.CParser.p_declarator (self, p)
 declarator  : id_declarator
                | typeid_declarator
p_designation()
pycparser.c_parser.CParser.p_designation (self, p)
 designation : designator_list EQUALS
p_designator()
pycparser.c_parser.CParser.p_designator (self, p)
 designator  : LBRACKET constant_expression RBRACKET
                | PERIOD identifier
p_designator_list()
pycparser.c_parser.CParser.p_designator_list (self, p)
 designator_list : designator
                    | designator_list designator
p_direct_abstract_declarator_1()
pycparser.c_parser.CParser.p_direct_abstract_declarator_1 (self, p)
 direct_abstract_declarator  : LPAREN abstract_declarator RPAREN
p_direct_abstract_declarator_2()
pycparser.c_parser.CParser.p_direct_abstract_declarator_2 (self, p)
 direct_abstract_declarator  : direct_abstract_declarator LBRACKET assignment_expression_opt RBRACKET
References pycparser.c_parser.CParser._type_modify_decl().
p_direct_abstract_declarator_3()
pycparser.c_parser.CParser.p_direct_abstract_declarator_3 (self, p)
 direct_abstract_declarator  : LBRACKET type_qualifier_list_opt assignment_expression_opt RBRACKET
References pycparser.plyparser.PLYParser._token_coord().
p_direct_abstract_declarator_4()
pycparser.c_parser.CParser.p_direct_abstract_declarator_4 (self, p)
 direct_abstract_declarator  : direct_abstract_declarator LBRACKET TIMES RBRACKET
References pycparser.plyparser.PLYParser._token_coord(), and pycparser.c_parser.CParser._type_modify_decl().
p_direct_abstract_declarator_5()
pycparser.c_parser.CParser.p_direct_abstract_declarator_5 (self, p)
 direct_abstract_declarator  : LBRACKET TIMES RBRACKET
References pycparser.plyparser.PLYParser._token_coord().
p_direct_abstract_declarator_6()
pycparser.c_parser.CParser.p_direct_abstract_declarator_6 (self, p)
 direct_abstract_declarator  : direct_abstract_declarator LPAREN parameter_type_list_opt RPAREN
References pycparser.c_parser.CParser._type_modify_decl().
p_direct_abstract_declarator_7()
pycparser.c_parser.CParser.p_direct_abstract_declarator_7 (self, p)
 direct_abstract_declarator  : LPAREN parameter_type_list_opt RPAREN
References pycparser.plyparser.PLYParser._token_coord().
p_direct_xxx_declarator_1()
pycparser.c_parser.CParser.p_direct_xxx_declarator_1 (self, p)
 direct_xxx_declarator   : yyy
References pycparser.plyparser.PLYParser._token_coord().
p_direct_xxx_declarator_2()
pycparser.c_parser.CParser.p_direct_xxx_declarator_2 (self, p)
 direct_xxx_declarator   : LPAREN xxx_declarator RPAREN
p_direct_xxx_declarator_3()
pycparser.c_parser.CParser.p_direct_xxx_declarator_3 (self, p)
 direct_xxx_declarator   : direct_xxx_declarator LBRACKET type_qualifier_list_opt assignment_expression_opt RBRACKET
References pycparser.c_parser.CParser._type_modify_decl().
p_direct_xxx_declarator_4()
pycparser.c_parser.CParser.p_direct_xxx_declarator_4 (self, p)
 direct_xxx_declarator   : direct_xxx_declarator LBRACKET STATIC type_qualifier_list_opt assignment_expression RBRACKET
                            | direct_xxx_declarator LBRACKET type_qualifier_list STATIC assignment_expression RBRACKET
References pycparser.c_parser.CParser._type_modify_decl().
p_direct_xxx_declarator_5()
pycparser.c_parser.CParser.p_direct_xxx_declarator_5 (self, p)
 direct_xxx_declarator   : direct_xxx_declarator LBRACKET type_qualifier_list_opt TIMES RBRACKET
References pycparser.plyparser.PLYParser._token_coord(), and pycparser.c_parser.CParser._type_modify_decl().
p_direct_xxx_declarator_6()
pycparser.c_parser.CParser.p_direct_xxx_declarator_6 (self, p)
 direct_xxx_declarator   : direct_xxx_declarator LPAREN parameter_type_list RPAREN
                            | direct_xxx_declarator LPAREN identifier_list_opt RPAREN
References pycparser.c_parser.CParser._add_identifier(), pycparser.c_parser.CParser._get_yacc_lookahead_token(), and pycparser.c_parser.CParser._type_modify_decl().
p_empty()
pycparser.c_parser.CParser.p_empty (self, p)
p_enum_specifier_1()
pycparser.c_parser.CParser.p_enum_specifier_1 (self, p)
 enum_specifier  : ENUM ID
                    | ENUM TYPEID
References pycparser.plyparser.PLYParser._token_coord().
p_enum_specifier_2()
pycparser.c_parser.CParser.p_enum_specifier_2 (self, p)
 enum_specifier  : ENUM brace_open enumerator_list brace_close
References pycparser.plyparser.PLYParser._token_coord().
p_enum_specifier_3()
pycparser.c_parser.CParser.p_enum_specifier_3 (self, p)
 enum_specifier  : ENUM ID brace_open enumerator_list brace_close
                    | ENUM TYPEID brace_open enumerator_list brace_close
References pycparser.plyparser.PLYParser._token_coord().
p_enumerator()
pycparser.c_parser.CParser.p_enumerator (self, p)
 enumerator  : ID
                | ID EQUALS constant_expression
References pycparser.c_parser.CParser._add_identifier(), and pycparser.plyparser.PLYParser._token_coord().
p_enumerator_list()
pycparser.c_parser.CParser.p_enumerator_list (self, p)
 enumerator_list : enumerator
                    | enumerator_list COMMA
                    | enumerator_list COMMA enumerator
p_error()
pycparser.c_parser.CParser.p_error (self, p)
References pycparser.plyparser.PLYParser._coord(), pycparser.plyparser.PLYParser._parse_error(), and pycparser.c_parser.CParser.clex.
p_expression()
pycparser.c_parser.CParser.p_expression (self, p)
 expression  : assignment_expression
                | expression COMMA assignment_expression
p_expression_statement()
pycparser.c_parser.CParser.p_expression_statement (self, p)
 expression_statement : expression_opt SEMI
References pycparser.plyparser.PLYParser._token_coord().
p_external_declaration_1()
pycparser.c_parser.CParser.p_external_declaration_1 (self, p)
 external_declaration    : function_definition
p_external_declaration_2()
pycparser.c_parser.CParser.p_external_declaration_2 (self, p)
 external_declaration    : declaration
p_external_declaration_3()
pycparser.c_parser.CParser.p_external_declaration_3 (self, p)
 external_declaration    : pp_directive
                            | pppragma_directive
p_external_declaration_4()
pycparser.c_parser.CParser.p_external_declaration_4 (self, p)
 external_declaration    : SEMI
p_external_declaration_5()
pycparser.c_parser.CParser.p_external_declaration_5 (self, p)
 external_declaration    : static_assert
p_function_definition_1()
pycparser.c_parser.CParser.p_function_definition_1 (self, p)
 function_definition : id_declarator declaration_list_opt compound_statement
References pycparser.c_parser.CParser._build_function_definition(), and pycparser.plyparser.PLYParser._token_coord().
p_function_definition_2()
pycparser.c_parser.CParser.p_function_definition_2 (self, p)
 function_definition : declaration_specifiers id_declarator declaration_list_opt compound_statement
References pycparser.c_parser.CParser._build_function_definition().
p_function_specifier()
pycparser.c_parser.CParser.p_function_specifier (self, p)
 function_specifier  : INLINE
                        | _NORETURN
p_id_init_declarator()
pycparser.c_parser.CParser.p_id_init_declarator (self, p)
 id_init_declarator : id_declarator
                       | id_declarator EQUALS initializer
p_id_init_declarator_list()
pycparser.c_parser.CParser.p_id_init_declarator_list (self, p)
 id_init_declarator_list    : id_init_declarator
                               | id_init_declarator_list COMMA init_declarator
p_identifier()
pycparser.c_parser.CParser.p_identifier (self, p)
 identifier  : ID
References pycparser.plyparser.PLYParser._token_coord().
p_identifier_list()
pycparser.c_parser.CParser.p_identifier_list (self, p)
 identifier_list : identifier
                    | identifier_list COMMA identifier
p_init_declarator()
pycparser.c_parser.CParser.p_init_declarator (self, p)
 init_declarator : declarator
                    | declarator EQUALS initializer
p_init_declarator_list()
pycparser.c_parser.CParser.p_init_declarator_list (self, p)
 init_declarator_list    : init_declarator
                            | init_declarator_list COMMA init_declarator
p_initializer_1()
pycparser.c_parser.CParser.p_initializer_1 (self, p)
 initializer : assignment_expression
p_initializer_2()
pycparser.c_parser.CParser.p_initializer_2 (self, p)
 initializer : brace_open initializer_list_opt brace_close
                | brace_open initializer_list COMMA brace_close
References pycparser.plyparser.PLYParser._token_coord().
p_initializer_list()
pycparser.c_parser.CParser.p_initializer_list (self, p)
 initializer_list    : designation_opt initializer
                        | initializer_list COMMA designation_opt initializer
p_iteration_statement_1()
pycparser.c_parser.CParser.p_iteration_statement_1 (self, p)
 iteration_statement : WHILE LPAREN expression RPAREN pragmacomp_or_statement
References pycparser.plyparser.PLYParser._token_coord().
p_iteration_statement_2()
pycparser.c_parser.CParser.p_iteration_statement_2 (self, p)
 iteration_statement : DO pragmacomp_or_statement WHILE LPAREN expression RPAREN SEMI
References pycparser.plyparser.PLYParser._token_coord().
p_iteration_statement_3()
pycparser.c_parser.CParser.p_iteration_statement_3 (self, p)
 iteration_statement : FOR LPAREN expression_opt SEMI expression_opt SEMI expression_opt RPAREN pragmacomp_or_statement
References pycparser.plyparser.PLYParser._token_coord().
p_iteration_statement_4()
pycparser.c_parser.CParser.p_iteration_statement_4 (self, p)
 iteration_statement : FOR LPAREN declaration expression_opt SEMI expression_opt RPAREN pragmacomp_or_statement
References pycparser.plyparser.PLYParser._token_coord().
p_jump_statement_1()
pycparser.c_parser.CParser.p_jump_statement_1 (self, p)
 jump_statement  : GOTO ID SEMI
References pycparser.plyparser.PLYParser._token_coord().
p_jump_statement_2()
pycparser.c_parser.CParser.p_jump_statement_2 (self, p)
 jump_statement  : BREAK SEMI
References pycparser.plyparser.PLYParser._token_coord().
p_jump_statement_3()
pycparser.c_parser.CParser.p_jump_statement_3 (self, p)
 jump_statement  : CONTINUE SEMI
References pycparser.plyparser.PLYParser._token_coord().
p_jump_statement_4()
pycparser.c_parser.CParser.p_jump_statement_4 (self, p)
 jump_statement  : RETURN expression SEMI
                    | RETURN SEMI
References pycparser.plyparser.PLYParser._token_coord().
p_labeled_statement_1()
pycparser.c_parser.CParser.p_labeled_statement_1 (self, p)
 labeled_statement : ID COLON pragmacomp_or_statement
References pycparser.plyparser.PLYParser._token_coord().
p_labeled_statement_2()
pycparser.c_parser.CParser.p_labeled_statement_2 (self, p)
 labeled_statement : CASE constant_expression COLON pragmacomp_or_statement
References pycparser.plyparser.PLYParser._token_coord().
p_labeled_statement_3()
pycparser.c_parser.CParser.p_labeled_statement_3 (self, p)
 labeled_statement : DEFAULT COLON pragmacomp_or_statement
References pycparser.plyparser.PLYParser._token_coord().
p_offsetof_member_designator()
pycparser.c_parser.CParser.p_offsetof_member_designator (self, p)
 offsetof_member_designator : identifier
                                 | offsetof_member_designator PERIOD identifier
                                 | offsetof_member_designator LBRACKET expression RBRACKET
p_parameter_declaration_1()
pycparser.c_parser.CParser.p_parameter_declaration_1 (self, p)
 parameter_declaration   : declaration_specifiers id_declarator
                            | declaration_specifiers typeid_noparen_declarator
References pycparser.c_parser.CParser._build_declarations(), and pycparser.plyparser.PLYParser._token_coord().
p_parameter_declaration_2()
pycparser.c_parser.CParser.p_parameter_declaration_2 (self, p)
 parameter_declaration   : declaration_specifiers abstract_declarator_opt
References pycparser.c_parser.CParser._build_declarations(), pycparser.c_parser.CParser._fix_decl_name_type(), pycparser.c_parser.CParser._is_type_in_scope(), and pycparser.plyparser.PLYParser._token_coord().
p_parameter_list()
pycparser.c_parser.CParser.p_parameter_list (self, p)
 parameter_list  : parameter_declaration
                    | parameter_list COMMA parameter_declaration
p_parameter_type_list()
pycparser.c_parser.CParser.p_parameter_type_list (self, p)
 parameter_type_list : parameter_list
                        | parameter_list COMMA ELLIPSIS
References pycparser.plyparser.PLYParser._token_coord().
p_parenthesized_compound_expression()
pycparser.c_parser.CParser.p_parenthesized_compound_expression (self, p)
 assignment_expression : LPAREN compound_statement RPAREN
p_pointer()
pycparser.c_parser.CParser.p_pointer (self, p)
 pointer : TIMES type_qualifier_list_opt
            | TIMES type_qualifier_list_opt pointer
References pycparser.plyparser.PLYParser._token_coord().
p_postfix_expression_1()
pycparser.c_parser.CParser.p_postfix_expression_1 (self, p)
 postfix_expression  : primary_expression
p_postfix_expression_2()
pycparser.c_parser.CParser.p_postfix_expression_2 (self, p)
 postfix_expression  : postfix_expression LBRACKET expression RBRACKET
p_postfix_expression_3()
pycparser.c_parser.CParser.p_postfix_expression_3 (self, p)
 postfix_expression  : postfix_expression LPAREN argument_expression_list RPAREN
                        | postfix_expression LPAREN RPAREN
p_postfix_expression_4()
pycparser.c_parser.CParser.p_postfix_expression_4 (self, p)
 postfix_expression  : postfix_expression PERIOD ID
                        | postfix_expression PERIOD TYPEID
                        | postfix_expression ARROW ID
                        | postfix_expression ARROW TYPEID
References pycparser.plyparser.PLYParser._token_coord().
p_postfix_expression_5()
pycparser.c_parser.CParser.p_postfix_expression_5 (self, p)
 postfix_expression  : postfix_expression PLUSPLUS
                        | postfix_expression MINUSMINUS
p_postfix_expression_6()
pycparser.c_parser.CParser.p_postfix_expression_6 (self, p)
 postfix_expression  : LPAREN type_name RPAREN brace_open initializer_list brace_close
                        | LPAREN type_name RPAREN brace_open initializer_list COMMA brace_close
p_pp_directive()
pycparser.c_parser.CParser.p_pp_directive (self, p)
 pp_directive  : PPHASH
References pycparser.plyparser.PLYParser._parse_error(), and pycparser.plyparser.PLYParser._token_coord().
p_pppragma_directive()
pycparser.c_parser.CParser.p_pppragma_directive (self, p)
 pppragma_directive      : PPPRAGMA
                            | PPPRAGMA PPPRAGMASTR
                            | _PRAGMA LPAREN unified_string_literal RPAREN
References pycparser.plyparser.PLYParser._token_coord().
p_pppragma_directive_list()
pycparser.c_parser.CParser.p_pppragma_directive_list (self, p)
 pppragma_directive_list : pppragma_directive
                            | pppragma_directive_list pppragma_directive
p_pragmacomp_or_statement()
pycparser.c_parser.CParser.p_pragmacomp_or_statement (self, p)
 pragmacomp_or_statement     : pppragma_directive_list statement
                                | statement
References pycparser.plyparser.PLYParser._token_coord().
p_primary_expression_1()
pycparser.c_parser.CParser.p_primary_expression_1 (self, p)
 primary_expression  : identifier
p_primary_expression_2()
pycparser.c_parser.CParser.p_primary_expression_2 (self, p)
 primary_expression  : constant
p_primary_expression_3()
pycparser.c_parser.CParser.p_primary_expression_3 (self, p)
 primary_expression  : unified_string_literal
                        | unified_wstring_literal
p_primary_expression_4()
pycparser.c_parser.CParser.p_primary_expression_4 (self, p)
 primary_expression  : LPAREN expression RPAREN
p_primary_expression_5()
pycparser.c_parser.CParser.p_primary_expression_5 (self, p)
 primary_expression  : OFFSETOF LPAREN type_name COMMA offsetof_member_designator RPAREN
References pycparser.plyparser.PLYParser._token_coord().
p_selection_statement_1()
pycparser.c_parser.CParser.p_selection_statement_1 (self, p)
 selection_statement : IF LPAREN expression RPAREN pragmacomp_or_statement
References pycparser.plyparser.PLYParser._token_coord().
p_selection_statement_2()
pycparser.c_parser.CParser.p_selection_statement_2 (self, p)
 selection_statement : IF LPAREN expression RPAREN statement ELSE pragmacomp_or_statement
References pycparser.plyparser.PLYParser._token_coord().
p_selection_statement_3()
pycparser.c_parser.CParser.p_selection_statement_3 (self, p)
 selection_statement : SWITCH LPAREN expression RPAREN pragmacomp_or_statement
References pycparser.plyparser.PLYParser._token_coord().
p_specifier_qualifier_list_1()
pycparser.c_parser.CParser.p_specifier_qualifier_list_1 (self, p)
 specifier_qualifier_list    : specifier_qualifier_list type_specifier_no_typeid
References pycparser.c_parser.CParser._add_declaration_specifier().
p_specifier_qualifier_list_2()
pycparser.c_parser.CParser.p_specifier_qualifier_list_2 (self, p)
 specifier_qualifier_list    : specifier_qualifier_list type_qualifier
References pycparser.c_parser.CParser._add_declaration_specifier().
p_specifier_qualifier_list_3()
pycparser.c_parser.CParser.p_specifier_qualifier_list_3 (self, p)
 specifier_qualifier_list  : type_specifier
References pycparser.c_parser.CParser._add_declaration_specifier().
p_specifier_qualifier_list_4()
pycparser.c_parser.CParser.p_specifier_qualifier_list_4 (self, p)
 specifier_qualifier_list  : type_qualifier_list type_specifier
p_specifier_qualifier_list_5()
pycparser.c_parser.CParser.p_specifier_qualifier_list_5 (self, p)
 specifier_qualifier_list  : alignment_specifier
p_specifier_qualifier_list_6()
pycparser.c_parser.CParser.p_specifier_qualifier_list_6 (self, p)
 specifier_qualifier_list  : specifier_qualifier_list alignment_specifier
References pycparser.c_parser.CParser._add_declaration_specifier().
p_statement()
pycparser.c_parser.CParser.p_statement (self, p)
 statement   : labeled_statement
                | expression_statement
                | compound_statement
                | selection_statement
                | iteration_statement
                | jump_statement
                | pppragma_directive
                | static_assert
p_static_assert_declaration()
pycparser.c_parser.CParser.p_static_assert_declaration (self, p)
 static_assert           : _STATIC_ASSERT LPAREN constant_expression COMMA unified_string_literal RPAREN
                            | _STATIC_ASSERT LPAREN constant_expression RPAREN
References pycparser.plyparser.PLYParser._token_coord().
p_storage_class_specifier()
pycparser.c_parser.CParser.p_storage_class_specifier (self, p)
 storage_class_specifier : AUTO
                            | REGISTER
                            | STATIC
                            | EXTERN
                            | TYPEDEF
                            | _THREAD_LOCAL
p_struct_declaration_1()
pycparser.c_parser.CParser.p_struct_declaration_1 (self, p)
 struct_declaration : specifier_qualifier_list struct_declarator_list_opt SEMI
References pycparser.c_parser.CParser._build_declarations().
p_struct_declaration_2()
pycparser.c_parser.CParser.p_struct_declaration_2 (self, p)
 struct_declaration : SEMI
p_struct_declaration_3()
pycparser.c_parser.CParser.p_struct_declaration_3 (self, p)
 struct_declaration : pppragma_directive
p_struct_declaration_list()
pycparser.c_parser.CParser.p_struct_declaration_list (self, p)
 struct_declaration_list     : struct_declaration
                                | struct_declaration_list struct_declaration
p_struct_declarator_1()
pycparser.c_parser.CParser.p_struct_declarator_1 (self, p)
 struct_declarator : declarator
p_struct_declarator_2()
pycparser.c_parser.CParser.p_struct_declarator_2 (self, p)
 struct_declarator   : declarator COLON constant_expression
                        | COLON constant_expression
p_struct_declarator_list()
pycparser.c_parser.CParser.p_struct_declarator_list (self, p)
 struct_declarator_list  : struct_declarator
                            | struct_declarator_list COMMA struct_declarator
p_struct_or_union()
pycparser.c_parser.CParser.p_struct_or_union (self, p)
 struct_or_union : STRUCT
                    | UNION
p_struct_or_union_specifier_1()
pycparser.c_parser.CParser.p_struct_or_union_specifier_1 (self, p)
 struct_or_union_specifier   : struct_or_union ID
                                | struct_or_union TYPEID
References pycparser.c_parser.CParser._select_struct_union_class(), and pycparser.plyparser.PLYParser._token_coord().
p_struct_or_union_specifier_2()
pycparser.c_parser.CParser.p_struct_or_union_specifier_2 (self, p)
 struct_or_union_specifier : struct_or_union brace_open struct_declaration_list brace_close
                              | struct_or_union brace_open brace_close
References pycparser.c_parser.CParser._select_struct_union_class(), and pycparser.plyparser.PLYParser._token_coord().
p_struct_or_union_specifier_3()
pycparser.c_parser.CParser.p_struct_or_union_specifier_3 (self, p)
 struct_or_union_specifier   : struct_or_union ID brace_open struct_declaration_list brace_close
                                | struct_or_union ID brace_open brace_close
                                | struct_or_union TYPEID brace_open struct_declaration_list brace_close
                                | struct_or_union TYPEID brace_open brace_close
References pycparser.c_parser.CParser._select_struct_union_class(), and pycparser.plyparser.PLYParser._token_coord().
p_translation_unit_1()
pycparser.c_parser.CParser.p_translation_unit_1 (self, p)
 translation_unit    : external_declaration
p_translation_unit_2()
pycparser.c_parser.CParser.p_translation_unit_2 (self, p)
 translation_unit    : translation_unit external_declaration
p_translation_unit_or_empty()
pycparser.c_parser.CParser.p_translation_unit_or_empty (self, p)
Grammar productions Implementation of the BNF defined in K&R2 A.13.
 translation_unit_or_empty   : translation_unit
                                | empty
p_type_name()
pycparser.c_parser.CParser.p_type_name (self, p)
 type_name   : specifier_qualifier_list abstract_declarator_opt
References pycparser.c_parser.CParser._fix_decl_name_type(), and pycparser.plyparser.PLYParser._token_coord().
p_type_qualifier()
pycparser.c_parser.CParser.p_type_qualifier (self, p)
 type_qualifier  : CONST
                    | RESTRICT
                    | VOLATILE
                    | _ATOMIC
p_type_qualifier_list()
pycparser.c_parser.CParser.p_type_qualifier_list (self, p)
 type_qualifier_list : type_qualifier
                        | type_qualifier_list type_qualifier
p_type_specifier()
pycparser.c_parser.CParser.p_type_specifier (self, p)
 type_specifier  : typedef_name
                    | enum_specifier
                    | struct_or_union_specifier
                    | type_specifier_no_typeid
                    | atomic_specifier
p_type_specifier_no_typeid()
pycparser.c_parser.CParser.p_type_specifier_no_typeid (self, p)
 type_specifier_no_typeid  : VOID
                              | _BOOL
                              | CHAR
                              | SHORT
                              | INT
                              | LONG
                              | FLOAT
                              | DOUBLE
                              | _COMPLEX
                              | SIGNED
                              | UNSIGNED
                              | __INT128
References pycparser.plyparser.PLYParser._token_coord().
p_typedef_name()
pycparser.c_parser.CParser.p_typedef_name (self, p)
 typedef_name : TYPEID
References pycparser.plyparser.PLYParser._token_coord().
p_unary_expression_1()
pycparser.c_parser.CParser.p_unary_expression_1 (self, p)
 unary_expression    : postfix_expression
p_unary_expression_2()
pycparser.c_parser.CParser.p_unary_expression_2 (self, p)
 unary_expression    : PLUSPLUS unary_expression
                        | MINUSMINUS unary_expression
                        | unary_operator cast_expression
p_unary_expression_3()
pycparser.c_parser.CParser.p_unary_expression_3 (self, p)
 unary_expression    : SIZEOF unary_expression
                        | SIZEOF LPAREN type_name RPAREN
                        | _ALIGNOF LPAREN type_name RPAREN
References pycparser.plyparser.PLYParser._token_coord().
p_unary_operator()
pycparser.c_parser.CParser.p_unary_operator (self, p)
 unary_operator  : AND
                    | TIMES
                    | PLUS
                    | MINUS
                    | NOT
                    | LNOT
p_unified_string_literal()
pycparser.c_parser.CParser.p_unified_string_literal (self, p)
 unified_string_literal  : STRING_LITERAL
                            | unified_string_literal STRING_LITERAL
References pycparser.plyparser.PLYParser._token_coord().
p_unified_wstring_literal()
pycparser.c_parser.CParser.p_unified_wstring_literal (self, p)
 unified_wstring_literal : WSTRING_LITERAL
                            | U8STRING_LITERAL
                            | U16STRING_LITERAL
                            | U32STRING_LITERAL
                            | unified_wstring_literal WSTRING_LITERAL
                            | unified_wstring_literal U8STRING_LITERAL
                            | unified_wstring_literal U16STRING_LITERAL
                            | unified_wstring_literal U32STRING_LITERAL
References pycparser.plyparser.PLYParser._token_coord().
p_xxx_declarator_1()
pycparser.c_parser.CParser.p_xxx_declarator_1 (self, p)
 xxx_declarator  : direct_xxx_declarator
p_xxx_declarator_2()
pycparser.c_parser.CParser.p_xxx_declarator_2 (self, p)
 xxx_declarator  : pointer direct_xxx_declarator
References pycparser.c_parser.CParser._type_modify_decl().
parse()
pycparser.c_parser.CParser.parse (self, text, filename = '', debug = False)
 Parses C code and returns an AST.
    text:
        A string containing the C source code
    filename:
        Name of the file being parsed (for meaningful
        error messages)
    debug:
        Debug flag to YACC
References pycparser.c_parser.CParser._last_yielded_token, pycparser.c_parser.CParser._scope_stack, pycparser.c_parser.CParser.clex, and pycparser.c_parser.CParser.cparser.
Referenced by setuptools._distutils.version.Version.__init__(), pkg_resources._vendor.jaraco.text.WordSet.from_class_name(), setuptools._vendor.jaraco.text.WordSet.from_class_name(), pip._vendor.rich.style.Style.normalize(), _pytest.config.argparsing.Parser.parse_setoption(), and _pytest.config.Config.pytest_cmdline_parse().
Member Data Documentation
_last_yielded_token
pycparser.c_parser.CParser._last_yielded_token protected
Referenced by pycparser.c_parser.CParser.parse().
_scope_stack
pycparser.c_parser.CParser._scope_stack protected
Referenced by pycparser.c_parser.CParser._add_identifier(), pycparser.c_parser.CParser._add_typedef_name(), pycparser.c_parser.CParser._is_type_in_scope(), pycparser.c_parser.CParser._pop_scope(), pycparser.c_parser.CParser._push_scope(), and pycparser.c_parser.CParser.parse().
clex
pycparser.c_parser.CParser.clex
Referenced by pycparser.plyparser.PLYParser._coord(), pycparser.c_parser.CParser._get_yacc_lookahead_token(), pycparser.c_parser.CParser.p_error(), and pycparser.c_parser.CParser.parse().
cparser
pycparser.c_parser.CParser.cparser
Referenced by pycparser.c_parser.CParser.parse().
precedence
tuple pycparser.c_parser.CParser.precedence static
Initial value:
=  (
        ('left', 'LOR'),
        ('left', 'LAND'),
        ('left', 'OR'),
        ('left', 'XOR'),
        ('left', 'AND'),
        ('left', 'EQ', 'NE'),
        ('left', 'GT', 'GE', 'LT', 'LE'),
        ('left', 'RSHIFT', 'LSHIFT'),
        ('left', 'PLUS', 'MINUS'),
        ('left', 'TIMES', 'DIVIDE', 'MOD')
    )
Precedence and associativity of operators.
If this changes, c_generator.CGenerator.precedence_map needs to change as well
tokens
pycparser.c_parser.CParser.tokens
Referenced by sqlparse.sql.TokenList.__getitem__(), sqlparse.sql.TokenList.__iter__(), django.template.base.Parser.__repr__(), sqlparse.sql.TokenList._get_first_name(), sqlparse.sql.Parenthesis._groupable_tokens(), sqlparse.sql.SquareBrackets._groupable_tokens(), sqlparse.sql.TokenList._groupable_tokens(), sqlparse.sql.TokenList._pprint_tree(), sqlparse.sql.TokenList._token_matching(), _pytest.mark.expression.Scanner.accept(), django.template.base.Parser.delete_first_token(), sqlparse.sql.TokenList.flatten(), sqlparse.sql.TokenList.get_sublists(), pycparser.ply.lex.LexerReflect.get_tokens(), pycparser.ply.yacc.ParserReflect.get_tokens(), sqlparse.sql.TokenList.group_tokens(), sqlparse.sql.TokenList.insert_after(), sqlparse.sql.TokenList.insert_before(), sqlparse.sql.Comment.is_multiline(), sqlparse.sql.Comparison.left(), django.template.base.Parser.next_token(), django.template.smartif.IfParser.next_token(), django.template.base.Parser.parse(), django.template.base.Parser.prepend_token(), sqlparse.engine.statement_splitter.StatementSplitter.process(), pip._vendor.pygments.lexer.RegexLexerMeta.process_tokendef(), sqlparse.sql.Comparison.right(), django.template.base.Parser.skip_past(), sqlparse.sql.TokenList.token_index(), pycparser.ply.lex.LexerReflect.validate_rules(), pycparser.ply.lex.LexerReflect.validate_tokens(), and pycparser.ply.yacc.ParserReflect.validate_tokens().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/pycparser/c_parser.py