Django Project: pip._vendor.rich.abc.RichRenderable Class Reference
pip._vendor.rich.abc.RichRenderable Class Reference
Public Member Functions
bool __subclasshook__ (cls, type other)
Detailed Description
An abstract base class for Rich renderables.
Note that there is no need to extend this class, the intended use is to check if an
object supports the Rich renderable protocol. For example::
    if isinstance(my_object, RichRenderable):
        console.print(my_object)
Member Function Documentation
__subclasshook__()
bool pip._vendor.rich.abc.RichRenderable.__subclasshook__ (cls, type other)
Check if this class supports the rich render protocol.
Referenced by setuptools._vendor.typing_extensions._ProtocolMeta.__init__(), pip._vendor.typing_extensions.Protocol.__init_subclass__(), and setuptools._vendor.typing_extensions.Protocol.__init_subclass__().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/pip/_vendor/rich/abc.py