Django Project: setuptools._vendor.zipp.CompleteDirs Class Reference
setuptools._vendor.zipp.CompleteDirs Class Reference
Public Member Functions
namelist (self)
resolve_dir (self, name)
make (cls, source)
Protected Member Functions
_name_set (self)
Static Protected Member Functions
_implied_dirs (names)
Detailed Description
A ZipFile subclass that ensures that implied directories
are always included in the namelist.
Member Function Documentation
_implied_dirs()
setuptools._vendor.zipp.CompleteDirs._implied_dirs (names) static protected
_name_set()
setuptools._vendor.zipp.CompleteDirs._name_set (self) protected
Reimplemented in setuptools._vendor.zipp.FastLookup.
make()
setuptools._vendor.zipp.CompleteDirs.make (cls, source)
Given a source (filename or zipfile), return an
appropriate CompleteDirs subclass.
Referenced by pip._vendor.distlib.scripts.ScriptMaker.make_multiple().
namelist()
setuptools._vendor.zipp.CompleteDirs.namelist (self)
Reimplemented in setuptools._vendor.zipp.FastLookup.
Referenced by django.core.management.commands.loaddata.SingleZipReader.__init__(), and django.core.management.commands.loaddata.SingleZipReader.read().
resolve_dir()
setuptools._vendor.zipp.CompleteDirs.resolve_dir (self, name)
If the name represents a directory, return that name
as a directory (with the trailing slash).
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/setuptools/_vendor/zipp.py