Django Project: pip._internal.index.package_finder.BestCandidateResult Class Reference
pip._internal.index.package_finder.BestCandidateResult Class Reference
Public Member Functions
None __init__ (self, List[InstallationCandidate] candidates, List[InstallationCandidate] applicable_candidates, Optional[InstallationCandidate] best_candidate)
Iterable[InstallationCandidate] iter_all (self)
Iterable[InstallationCandidate] iter_applicable (self)
Public Attributes
best_candidate
Protected Attributes
_applicable_candidates
_candidates
Detailed Description
A collection of candidates, returned by `PackageFinder.find_best_candidate`.
This class is only intended to be instantiated by CandidateEvaluator's
`compute_best_candidate()` method.
Constructor & Destructor Documentation
__init__()
None pip._internal.index.package_finder.BestCandidateResult.__init__ (self, List[InstallationCandidate] candidates, List[InstallationCandidate] applicable_candidates, Optional[InstallationCandidate] best_candidate)
:param candidates: A sequence of all available candidates found.
:param applicable_candidates: The applicable candidates.
:param best_candidate: The most preferred candidate found, or None
    if no applicable candidates were found.
Referenced by setuptools._vendor.typing_extensions._ProtocolMeta.__init__(), pip._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.ordered_set.OrderedSet.__setstate__(), and django.db.models.expressions.Expression.identity().
Member Function Documentation
iter_all()
Iterable[InstallationCandidate] pip._internal.index.package_finder.BestCandidateResult.iter_all (self)
Iterate through all candidates.
References pip._internal.index.package_finder.BestCandidateResult._candidates.
iter_applicable()
Iterable[InstallationCandidate] pip._internal.index.package_finder.BestCandidateResult.iter_applicable (self)
Iterate through the applicable candidates.
References pip._internal.index.package_finder.BestCandidateResult._applicable_candidates.
Member Data Documentation
_applicable_candidates
pip._internal.index.package_finder.BestCandidateResult._applicable_candidates protected
Referenced by pip._internal.index.package_finder.BestCandidateResult.iter_applicable().
_candidates
pip._internal.index.package_finder.BestCandidateResult._candidates protected
Referenced by pip._internal.index.package_finder.BestCandidateResult.iter_all().
best_candidate
pip._internal.index.package_finder.BestCandidateResult.best_candidate
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/pip/_internal/index/package_finder.py