Django Project: pip._vendor.rich.highlighter.JSONHighlighter Class Reference
pip._vendor.rich.highlighter.JSONHighlighter Class Reference
Public Member Functions
None highlight (self, Text text)
Public Member Functions inherited from pip._vendor.rich.highlighter.Highlighter
Text __call__ (self, Union[str, Text] text)
Public Attributes
JSON_STR
Static Public Attributes
str JSON_STR = r"(?<![\\\w])(?P<str>b?\".*?(?<!\\‍)\")"
dict JSON_WHITESPACE = {" ", "\n", "\r", "\t"}
str base_style = "json."
list highlights
Static Public Attributes inherited from pip._vendor.rich.highlighter.RegexHighlighter
list highlights = []
str base_style = ""
Detailed Description
Highlights JSON
Member Function Documentation
highlight()
None pip._vendor.rich.highlighter.JSONHighlighter.highlight (self, Text text)
Highlight :class:`rich.text.Text` using regular expressions.
Args:
    text (~Text): Text to highlighted.
Reimplemented from pip._vendor.rich.highlighter.RegexHighlighter.
References pip._vendor.rich.highlighter.JSONHighlighter.JSON_WHITESPACE.
Referenced by pip._vendor.rich.highlighter.Highlighter.__call__(), pip._vendor.rich.panel.Panel.__rich_console__(), pip._vendor.rich.table.Table.__rich_console__(), pip._vendor.rich.tree.Tree.__rich_console__(), pip._vendor.rich.syntax.Syntax._get_syntax(), and pip._vendor.rich.tree.Tree.add().
Member Data Documentation
base_style
str pip._vendor.rich.highlighter.JSONHighlighter.base_style = "json." static
Referenced by pip._vendor.rich.highlighter.RegexHighlighter.highlight().
highlights
list pip._vendor.rich.highlighter.JSONHighlighter.highlights static
Initial value:
=  [
        _combine_regex(
            r"(?P<brace>[\{\[\‍(\‍)\]\}])",
            r"\b(?P<bool_true>true)\b|\b(?P<bool_false>false)\b|\b(?P<null>null)\b",
            r"(?P<number>(?<!\w)\-?[0-9]+\.?[0-9]*(e[\-\+]?\d+?)?\b|0x[0-9a-fA-F]*)",
            JSON_STR,
        ),
    ]
Referenced by pip._vendor.rich.highlighter.RegexHighlighter.highlight().
JSON_STR [1/2]
str pip._vendor.rich.highlighter.JSONHighlighter.JSON_STR = r"(?<![\\\w])(?P<str>b?\".*?(?<!\\‍)\")" static
JSON_STR [2/2]
pip._vendor.rich.highlighter.JSONHighlighter.JSON_STR
JSON_WHITESPACE
dict pip._vendor.rich.highlighter.JSONHighlighter.JSON_WHITESPACE = {" ", "\n", "\r", "\t"} static
Referenced by pip._vendor.rich.highlighter.JSONHighlighter.highlight().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/pip/_vendor/rich/highlighter.py