Django Project: django.contrib.sessions.models.Session Class Reference
django.contrib.sessions.models.Session Class Reference
Classes
class Meta
Public Member Functions
get_session_store_class (cls)
Public Member Functions inherited from django.contrib.sessions.base_session.AbstractBaseSession
__str__ (self)
get_decoded (self)
Static Public Attributes
objects = SessionManager()
Static Public Attributes inherited from django.contrib.sessions.base_session.AbstractBaseSession
session_key = models.CharField(_("session key"), max_length=40, primary_key=True)
session_data = models.TextField(_("session data"))
expire_date = models.DateTimeField(_("expire date"), db_index=True)
objects = BaseSessionManager()
Detailed Description
Django provides full support for anonymous sessions. The session
framework lets you store and retrieve arbitrary data on a
per-site-visitor basis. It stores data on the server side and
abstracts the sending and receiving of cookies. Cookies contain a
session ID -- not the data itself.
The Django sessions framework is entirely cookie-based. It does
not fall back to putting session IDs in URLs. This is an intentional
design decision. Not only does that behavior make URLs ugly, it makes
your site vulnerable to session-ID theft via the "Referer" header.
For complete documentation on using Sessions in your code, consult
the sessions documentation that is shipped with Django (also available
on the Django web site).
Member Function Documentation
get_session_store_class()
django.contrib.sessions.models.Session.get_session_store_class (cls)
Reimplemented from django.contrib.sessions.base_session.AbstractBaseSession.
Referenced by django.contrib.sessions.base_session.AbstractBaseSession.get_decoded().
Member Data Documentation
objects
django.contrib.sessions.models.Session.objects = SessionManager() static
Referenced by setuptools._distutils.ccompiler.CCompiler.add_link_object(), django.core.serializers.python.Serializer.end_object(), django.core.serializers.python.Serializer.getvalue(), setuptools._distutils.unixccompiler.UnixCCompiler.link(), and setuptools._distutils.ccompiler.CCompiler.set_link_objects().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/django/contrib/sessions/models.py