Django Project: _pytest.config.argparsing.DropShorterLongHelpFormatter Class Reference
_pytest.config.argparsing.DropShorterLongHelpFormatter Class Reference
Public Member Functions
None __init__ (self, *Any args, **Any kwargs)
Protected Member Functions
str _format_action_invocation (self, argparse.Action action)
_split_lines (self, text, width)
Detailed Description
Shorten help for long options that differ only in extra hyphens.
- Collapse **long** options that are the same except for extra hyphens.
- Shortcut if there are only two options and one of them is a short one.
- Cache result on the action object as this is called at least 2 times.
Constructor & Destructor Documentation
__init__()
None _pytest.config.argparsing.DropShorterLongHelpFormatter.__init__ (self, *Any args, **Any kwargs)
References _pytest.config.argparsing.DropShorterLongHelpFormatter.__init__().
Referenced by _pytest.config.argparsing.DropShorterLongHelpFormatter.__init__(), setuptools._vendor.typing_extensions._ProtocolMeta.__init__(), pip._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.ordered_set.OrderedSet.__setstate__(), and django.db.models.expressions.Expression.identity().
Member Function Documentation
_format_action_invocation()
str _pytest.config.argparsing.DropShorterLongHelpFormatter._format_action_invocation (self, argparse.Action action) protected
References _pytest.config.argparsing.DropShorterLongHelpFormatter._format_action_invocation().
Referenced by _pytest.config.argparsing.DropShorterLongHelpFormatter._format_action_invocation().
_split_lines()
_pytest.config.argparsing.DropShorterLongHelpFormatter._split_lines (self, text, width) protected
Wrap lines after splitting on original newlines.
This allows to have explicit line breaks in the help text.
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/_pytest/config/argparsing.py