Django Project: setuptools._vendor.typing_extensions.Annotated Class Reference
setuptools._vendor.typing_extensions.Annotated Class Reference
Public Member Functions
__new__ (cls, *args, **kwargs)
__class_getitem__ (cls, params)
__init_subclass__ (cls, *args, **kwargs)
Public Member Functions inherited from setuptools._vendor.typing_extensions.AnnotatedMeta
__metadata__ (self)
__getitem__ (self, params)
__call__ (self, *args, **kwargs)
__getattr__ (self, attr)
__setattr__ (self, attr, value)
__instancecheck__ (self, obj)
__subclasscheck__ (self, cls)
Additional Inherited Members
Protected Member Functions inherited from setuptools._vendor.typing_extensions.AnnotatedMeta
_tree_repr (self, tree)
_subs_tree (self, tvars=None, args=None)
_get_cons (self)
Detailed Description
Add context specific metadata to a type.
Example: Annotated[int, runtime_check.Unsigned] indicates to the
hypothetical runtime_check module that this type is an unsigned int.
Every other consumer of this type can ignore this metadata and treat
this type as int.
The first argument to Annotated must be a valid type (and will be in
the __origin__ field), the remaining arguments are kept as a tuple in
the __extra__ field.
Details:
- It's an error to call `Annotated` with less than two arguments.
- Nested Annotated are flattened::
    Annotated[Annotated[T, Ann1, Ann2], Ann3] == Annotated[T, Ann1, Ann2, Ann3]
- Instantiating an annotated type is equivalent to instantiating the
underlying type::
    Annotated[C, Ann1](5) == C(5)
- Annotated can be used as a generic type alias::
    Optimized = Annotated[T, runtime.Optimize()]
    Optimized[int] == Annotated[int, runtime.Optimize()]
    OptimizedList = Annotated[List[T], runtime.Optimize()]
    OptimizedList[int] == Annotated[List[int], runtime.Optimize()]
Add context specific metadata to a type.
Example: Annotated[int, runtime_check.Unsigned] indicates to the
hypothetical runtime_check module that this type is an unsigned int.
Every other consumer of this type can ignore this metadata and treat
this type as int.
The first argument to Annotated must be a valid type, the remaining
arguments are kept as a tuple in the __metadata__ field.
Details:
- It's an error to call `Annotated` with less than two arguments.
- Nested Annotated are flattened::
    Annotated[Annotated[T, Ann1, Ann2], Ann3] == Annotated[T, Ann1, Ann2, Ann3]
- Instantiating an annotated type is equivalent to instantiating the
underlying type::
    Annotated[C, Ann1](5) == C(5)
- Annotated can be used as a generic type alias::
    Optimized = Annotated[T, runtime.Optimize()]
    Optimized[int] == Annotated[int, runtime.Optimize()]
    OptimizedList = Annotated[List[T], runtime.Optimize()]
    OptimizedList[int] == Annotated[List[int], runtime.Optimize()]
Member Function Documentation
__class_getitem__()
setuptools._vendor.typing_extensions.Annotated.__class_getitem__ (cls, params)
__init_subclass__()
setuptools._vendor.typing_extensions.Annotated.__init_subclass__ (cls, * args, ** kwargs)
__new__()
setuptools._vendor.typing_extensions.Annotated.__new__ (cls, * args, ** kwargs)
Reimplemented from setuptools._vendor.typing_extensions.AnnotatedMeta.
Referenced by django.test.selenium.SeleniumTestCaseBase.__new__(), pip._vendor.rich.style.Style._add(), cffi.backend_ctypes.CTypesBaseStructOrUnion._from_ctypes(), cryptography.x509.general_name.DNSName._init_without_validation(), cryptography.x509.general_name.RFC822Name._init_without_validation(), cryptography.x509.general_name.UniformResourceIdentifier._init_without_validation(), cffi.backend_ctypes.CTypesGenericPtr._new_pointer_at(), pip._vendor.rich.style.Style.clear_meta_and_links(), pip._vendor.rich.style.Style.copy(), pip._vendor.rich.style.Style.from_color(), pip._vendor.rich.json.JSON.from_data(), pip._vendor.rich.style.Style.from_meta(), pip._vendor.rich.style.Style.update_link(), and pip._vendor.rich.style.Style.without_color().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/setuptools/_vendor/typing_extensions.py