Django Project: django.contrib.admin.widgets.AdminSplitDateTime Class Reference
django.contrib.admin.widgets.AdminSplitDateTime Class Reference
Public Member Functions
__init__ (self, attrs=None)
get_context (self, name, value, attrs)
Public Member Functions inherited from django.forms.widgets.SplitDateTimeWidget
decompress (self, value)
Public Member Functions inherited from django.forms.widgets.MultiWidget
is_hidden (self)
id_for_label (self, id_)
value_from_datadict (self, data, files, name)
value_omitted_from_data (self, data, files, name)
__deepcopy__ (self, memo)
needs_multipart_form (self)
Public Member Functions inherited from django.forms.widgets.Widget
subwidgets (self, name, value, attrs=None)
format_value (self, value)
render (self, name, value, attrs=None, renderer=None)
build_attrs (self, base_attrs, extra_attrs=None)
use_required_attribute (self, initial)
Public Member Functions inherited from django.forms.widgets.MediaDefiningClass
__new__ (mcs, name, bases, attrs)
Static Public Attributes
str template_name = "admin/widgets/split_datetime.html"
Static Public Attributes inherited from django.forms.widgets.SplitDateTimeWidget
bool supports_microseconds = False
str template_name = "django/forms/widgets/splitdatetime.html"
Static Public Attributes inherited from django.forms.widgets.MultiWidget
str template_name = "django/forms/widgets/multiwidget.html"
bool use_fieldset = True
Static Public Attributes inherited from django.forms.widgets.Widget
bool is_localized = False
bool is_required = False
bool supports_microseconds = True
bool use_fieldset = False
Additional Inherited Members
Public Attributes inherited from django.forms.widgets.MultiWidget
widgets_names
widgets
is_localized
Public Attributes inherited from django.forms.widgets.Widget
attrs
input_type
is_required
template_name
Protected Member Functions inherited from django.forms.widgets.MultiWidget
_get_media (self)
Protected Member Functions inherited from django.forms.widgets.Widget
_render (self, template_name, context, renderer=None)
Properties inherited from django.forms.widgets.MultiWidget
media = property(_get_media)
Detailed Description
A SplitDateTime Widget that has some admin-specific styling.
Constructor & Destructor Documentation
__init__()
django.contrib.admin.widgets.AdminSplitDateTime.__init__ (self, attrs = None)
Reimplemented from django.forms.widgets.SplitDateTimeWidget.
Referenced by setuptools._vendor.typing_extensions._ProtocolMeta.__init__(), pip._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.ordered_set.OrderedSet.__setstate__(), and django.db.models.expressions.Expression.identity().
Member Function Documentation
get_context()
django.contrib.admin.widgets.AdminSplitDateTime.get_context (self, name, value, attrs)
Reimplemented from django.forms.widgets.MultiWidget.
References django.contrib.admin.widgets.AdminSplitDateTime.get_context().
Referenced by django.contrib.admin.widgets.AdminSplitDateTime.get_context(), django.forms.utils.RenderableMixin.render(), django.forms.widgets.Widget.render(), and django.forms.widgets.Widget.subwidgets().
Member Data Documentation
template_name
str django.contrib.admin.widgets.AdminSplitDateTime.template_name = "admin/widgets/split_datetime.html" static
Referenced by django.views.generic.base.TemplateResponseMixin.get_template_names(), django.contrib.admin.templatetags.base.InclusionAdminNode.render(), django.forms.utils.RenderableMixin.render(), django.forms.widgets.Widget.render(), django.template.response.SimpleTemplateResponse.rendered_content(), django.test.testcases._AssertTemplateNotUsedContext.test(), and django.test.testcases._AssertTemplateUsedContext.test().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/django/contrib/admin/widgets.py