Django Project: django.views.generic.list.MultipleObjectTemplateResponseMixin Class Reference
django.views.generic.list.MultipleObjectTemplateResponseMixin Class Reference
Public Member Functions
get_template_names (self)
Public Member Functions inherited from django.views.generic.base.TemplateResponseMixin
render_to_response (self, context, **response_kwargs)
Public Attributes
object_list
template_name_suffix
Static Public Attributes
str template_name_suffix = "_list"
Static Public Attributes inherited from django.views.generic.base.TemplateResponseMixin
template_name = None
template_engine = None
response_class = TemplateResponse
content_type = None
Detailed Description
Mixin for responding with a template and list of objects.
Member Function Documentation
get_template_names()
django.views.generic.list.MultipleObjectTemplateResponseMixin.get_template_names (self)
Return a list of template names to be used for the request. Must return
a list. May not be called if render_to_response is overridden.
Reimplemented from django.views.generic.base.TemplateResponseMixin.
References django.views.generic.list.MultipleObjectTemplateResponseMixin.get_template_names().
Referenced by django.views.generic.list.MultipleObjectTemplateResponseMixin.get_template_names(), and django.views.generic.base.TemplateResponseMixin.render_to_response().
Member Data Documentation
object_list
django.views.generic.list.MultipleObjectTemplateResponseMixin.object_list
Referenced by django.core.paginator.Page.__getitem__(), django.core.paginator.Page.__len__(), django.core.paginator.Paginator._check_object_list_is_ordered(), django.core.paginator.Paginator.count(), django.views.generic.list.MultipleObjectMixin.get_context_data(), and django.core.paginator.Paginator.page().
template_name_suffix [1/2]
str django.views.generic.list.MultipleObjectTemplateResponseMixin.template_name_suffix = "_list" static
template_name_suffix [2/2]
django.views.generic.list.MultipleObjectTemplateResponseMixin.template_name_suffix
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/django/views/generic/list.py