Django Project: _pytest._py.error.ErrorMaker Class Reference
_pytest._py.error.ErrorMaker Class Reference
Public Member Functions
type[Error] __getattr__ (self, str name)
R checked_call (self, Callable[P, R] func, *P.args args, **P.kwargs kwargs)
Protected Member Functions
type[Error] _geterrnoclass (self, int eno)
Static Protected Attributes
dict _errno2class = {}
Detailed Description
lazily provides Exception classes for each possible POSIX errno
(as defined per the 'errno' module).  All such instances
subclass EnvironmentError.
Member Function Documentation
__getattr__()
type[Error] _pytest._py.error.ErrorMaker.__getattr__ (self, str name)
References _pytest._py.error.ErrorMaker._geterrnoclass().
Referenced by django.conf.LazySettings.DEFAULT_FILE_STORAGE(), and django.conf.LazySettings.STATICFILES_STORAGE().
_geterrnoclass()
type[Error] _pytest._py.error.ErrorMaker._geterrnoclass (self, int eno) protected
References _pytest._py.error.ErrorMaker._errno2class.
Referenced by _pytest._py.error.ErrorMaker.__getattr__(), and _pytest._py.error.ErrorMaker.checked_call().
checked_call()
R _pytest._py.error.ErrorMaker.checked_call (self, Callable[P, R] func, *P.args args, **P.kwargs kwargs)
Call a function and raise an errno-exception if applicable.
References _pytest._py.error.ErrorMaker._geterrnoclass().
Member Data Documentation
_errno2class
dict _pytest._py.error.ErrorMaker._errno2class = {} static protected
Referenced by _pytest._py.error.ErrorMaker._geterrnoclass().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/_pytest/_py/error.py