Django Project: cryptography.hazmat.primitives.asymmetric.ec.EllipticCurvePrivateKey Class Reference
cryptography.hazmat.primitives.asymmetric.ec.EllipticCurvePrivateKey Class Reference
Public Member Functions
bytes exchange (self, ECDH algorithm, EllipticCurvePublicKey peer_public_key)
EllipticCurvePublicKey public_key (self)
EllipticCurve curve (self)
int key_size (self)
bytes sign (self, bytes data, EllipticCurveSignatureAlgorithm signature_algorithm)
EllipticCurvePrivateNumbers private_numbers (self)
bytes private_bytes (self, _serialization.Encoding encoding, _serialization.PrivateFormat format, _serialization.KeySerializationEncryption encryption_algorithm)
Member Function Documentation
curve()
EllipticCurve cryptography.hazmat.primitives.asymmetric.ec.EllipticCurvePrivateKey.curve (self)
The EllipticCurve that this key is on.
Referenced by cryptography.hazmat.primitives.serialization.ssh._SSHFormatECDSA.load_private(), and cryptography.hazmat.primitives.serialization.ssh._SSHFormatECDSA.load_public().
exchange()
bytes cryptography.hazmat.primitives.asymmetric.ec.EllipticCurvePrivateKey.exchange (self, ECDH algorithm, EllipticCurvePublicKey peer_public_key)
Performs a key exchange operation using the provided algorithm with the
provided peer's public key.
key_size()
int cryptography.hazmat.primitives.asymmetric.ec.EllipticCurvePrivateKey.key_size (self)
Bit size of a secret scalar for the curve.
private_bytes()
bytes cryptography.hazmat.primitives.asymmetric.ec.EllipticCurvePrivateKey.private_bytes (self, _serialization.Encoding encoding, _serialization.PrivateFormat format, _serialization.KeySerializationEncryption encryption_algorithm)
Returns the key serialized as bytes.
private_numbers()
EllipticCurvePrivateNumbers cryptography.hazmat.primitives.asymmetric.ec.EllipticCurvePrivateKey.private_numbers (self)
Returns an EllipticCurvePrivateNumbers.
public_key()
EllipticCurvePublicKey cryptography.hazmat.primitives.asymmetric.ec.EllipticCurvePrivateKey.public_key (self)
The EllipticCurvePublicKey for this private key.
sign()
bytes cryptography.hazmat.primitives.asymmetric.ec.EllipticCurvePrivateKey.sign (self, bytes data, EllipticCurveSignatureAlgorithm signature_algorithm)
Signs the data
Referenced by setuptools._distutils.command.upload.upload.finalize_options(), django.core.signing.Signer.sign_object(), and setuptools._distutils.command.upload.upload.upload_file().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/cryptography/hazmat/primitives/asymmetric/ec.py