Django Project: pip._vendor.chardet.hebrewprober.HebrewProber Class Reference
pip._vendor.chardet.hebrewprober.HebrewProber Class Reference
General ideas of the Hebrew charset recognition ###.
Public Member Functions
None __init__ (self)
None reset (self)
None set_model_probers (self, SingleByteCharSetProber logical_prober, SingleByteCharSetProber visual_prober)
bool is_final (self, int c)
bool is_non_final (self, int c)
ProbingState feed (self, Union[bytes, bytearray] byte_str)
str charset_name (self)
str language (self)
ProbingState state (self)
Public Member Functions inherited from pip._vendor.chardet.charsetprober.CharSetProber
float get_confidence (self)
Public Attributes
FINAL_KAF
FINAL_MEM
FINAL_NUN
FINAL_PE
FINAL_TSADI
NORMAL_KAF
NORMAL_MEM
NORMAL_NUN
state
Public Attributes inherited from pip._vendor.chardet.charsetprober.CharSetProber
active
lang_filter
logger
Static Public Attributes
int SPACE = 0x20
int FINAL_KAF = 0xEA
int NORMAL_KAF = 0xEB
int FINAL_MEM = 0xED
int NORMAL_MEM = 0xEE
int FINAL_NUN = 0xEF
int NORMAL_NUN = 0xF0
int FINAL_PE = 0xF3
int NORMAL_PE = 0xF4
int FINAL_TSADI = 0xF5
int NORMAL_TSADI = 0xF6
int MIN_FINAL_CHAR_DISTANCE = 5
float MIN_MODEL_DISTANCE = 0.01
str VISUAL_HEBREW_NAME = "ISO-8859-8"
str LOGICAL_HEBREW_NAME = "windows-1255"
Static Public Attributes inherited from pip._vendor.chardet.charsetprober.CharSetProber
float SHORTCUT_THRESHOLD = 0.95
Protected Attributes
_final_char_logical_score
_final_char_visual_score
_prev
_before_prev
Optional[SingleByteCharSetProber] _logical_prober
Optional[SingleByteCharSetProber] _visual_prober
Protected Attributes inherited from pip._vendor.chardet.charsetprober.CharSetProber
_state
Additional Inherited Members
Static Public Member Functions inherited from pip._vendor.chardet.charsetprober.CharSetProber
bytes filter_high_byte_only (Union[bytes, bytearray] buf)
bytearray filter_international_words (Union[bytes, bytearray] buf)
bytes remove_xml_tags (Union[bytes, bytearray] buf)
Detailed Description
General ideas of the Hebrew charset recognition ###.
Four main charsets exist in Hebrew: "ISO-8859-8" - Visual Hebrew "windows-1255" - Logical Hebrew "ISO-8859-8-I" - Logical Hebrew "x-mac-hebrew" - ?? Logical Hebrew ??
Both "ISO" charsets use a completely identical set of code points, whereas "windows-1255" and "x-mac-hebrew" are two different proper supersets of these code points. windows-1255 defines additional characters in the range 0x80-0x9F as some misc punctuation marks as well as some Hebrew-specific diacritics and additional 'Yiddish' ligature letters in the range 0xc0-0xd6. x-mac-hebrew defines similar additional code points but with a different mapping.
As far as an average Hebrew text with no diacritics is concerned, all four charsets are identical with respect to code points. Meaning that for the main Hebrew alphabet, all four map the same values to all 27 Hebrew letters (including final letters).
The dominant difference between these charsets is their directionality. "Visual" directionality means that the text is ordered as if the renderer is not aware of a BIDI rendering algorithm. The renderer sees the text and draws it from left to right. The text itself when ordered naturally is read backwards. A buffer of Visual Hebrew generally looks like so: "[last word of first line spelled backwards] [whole line ordered backwards and spelled backwards] [first word of first line spelled backwards] [end of line] [last word of second line] ... etc' " adding punctuation marks, numbers and English text to visual text is naturally also "visual" and from left to right.
"Logical" directionality means the text is ordered "naturally" according to the order it is read. It is the responsibility of the renderer to display the text from right to left. A BIDI algorithm is used to place general punctuation marks, numbers and English text in the text.
Texts in x-mac-hebrew are almost impossible to find on the Internet. From what little evidence I could find, it seems that its general directionality is Logical.
To sum up all of the above, the Hebrew probing mechanism knows about two charsets: Visual Hebrew - "ISO-8859-8" - backwards text - Words and sentences are backwards while line order is natural. For charset recognition purposes the line order is unimportant (In fact, for this implementation, even word order is unimportant). Logical Hebrew - "windows-1255" - normal, naturally ordered text.
"ISO-8859-8-I" is a subset of windows-1255 and doesn't need to be specifically identified. "x-mac-hebrew" is also identified as windows-1255. A text in x-mac-hebrew that contain special punctuation marks or diacritics is displayed with some unconverted characters showing as question marks. This problem might be corrected using another model prober for x-mac-hebrew. Due to the fact that x-mac-hebrew texts are so rare, writing another model prober isn't worth the effort and performance hit.
The Prober ####
The prober is divided between two SBCharSetProbers and a HebrewProber, all of which are managed, created, fed data, inquired and deleted by the SBCSGroupProber. The two SBCharSetProbers identify that the text is in fact some kind of Hebrew, Logical or Visual. The final decision about which one is it is made by the HebrewProber by combining final-letter scores with the scores of the two SBCharSetProbers to produce a final answer.
The SBCSGroupProber is responsible for stripping the original text of HTML tags, English characters, numbers, low-ASCII punctuation characters, spaces and new lines. It reduces any sequence of such characters to a single space. The buffer fed to each prober in the SBCS group prober is pure text in high-ASCII. The two SBCharSetProbers (model probers) share the same language model: Win1255Model. The first SBCharSetProber uses the model normally as any other SBCharSetProber does, to recognize windows-1255, upon which this model was built. The second SBCharSetProber is told to make the pair-of-letter lookup in the language model backwards. This in practice exactly simulates a visual Hebrew model using the windows-1255 logical Hebrew model.
The HebrewProber is not using any language model. All it does is look for final-letter evidence suggesting the text is either logical Hebrew or visual Hebrew. Disjointed from the model probers, the results of the HebrewProber alone are meaningless. HebrewProber always returns 0.00 as confidence since it never identifies a charset by itself. Instead, the pointer to the HebrewProber is passed to the model probers as a helper "Name Prober". When the Group prober receives a positive identification from any prober, it asks for the name of the charset identified. If the prober queried is a Hebrew model prober, the model prober forwards the call to the HebrewProber to make the final decision. In the HebrewProber, the decision is made according to the final-letters scores maintained and Both model probers scores. The answer is returned in the form of the name of the charset identified, either "windows-1255" or "ISO-8859-8".
Constructor & Destructor Documentation
__init__()
None pip._vendor.chardet.hebrewprober.HebrewProber.__init__ (self)
Reimplemented from pip._vendor.chardet.charsetprober.CharSetProber.
References pip._vendor.chardet.hebrewprober.HebrewProber.__init__().
Referenced by pip._vendor.chardet.hebrewprober.HebrewProber.__init__(), setuptools._vendor.typing_extensions._ProtocolMeta.__init__(), pip._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.ordered_set.OrderedSet.__setstate__(), and django.db.models.expressions.Expression.identity().
Member Function Documentation
charset_name()
str pip._vendor.chardet.hebrewprober.HebrewProber.charset_name (self)
Reimplemented from pip._vendor.chardet.charsetprober.CharSetProber.
References pip._vendor.chardet.hebrewprober.HebrewProber._final_char_logical_score, pip._vendor.chardet.hebrewprober.HebrewProber._final_char_visual_score, pip._vendor.chardet.hebrewprober.HebrewProber._logical_prober, pip._vendor.chardet.hebrewprober.HebrewProber._visual_prober, pip._vendor.chardet.charsetprober.CharSetProber.get_confidence(), pip._vendor.chardet.hebrewprober.HebrewProber.LOGICAL_HEBREW_NAME, pip._vendor.chardet.hebrewprober.HebrewProber.MIN_FINAL_CHAR_DISTANCE, pip._vendor.chardet.hebrewprober.HebrewProber.MIN_MODEL_DISTANCE, and pip._vendor.chardet.hebrewprober.HebrewProber.VISUAL_HEBREW_NAME.
feed()
ProbingState pip._vendor.chardet.hebrewprober.HebrewProber.feed (self, Union[bytes, bytearray] byte_str)
Reimplemented from pip._vendor.chardet.charsetprober.CharSetProber.
Referenced by django.utils.feedgenerator.Atom1Feed.add_root_elements(), django.utils.feedgenerator.RssFeed.add_root_elements(), django.utils.feedgenerator.Atom1Feed.root_attributes(), and django.db.migrations.writer.OperationWriter.serialize().
is_final()
bool pip._vendor.chardet.hebrewprober.HebrewProber.is_final (self, int c)
is_non_final()
bool pip._vendor.chardet.hebrewprober.HebrewProber.is_non_final (self, int c)
language()
str pip._vendor.chardet.hebrewprober.HebrewProber.language (self)
Reimplemented from pip._vendor.chardet.charsetprober.CharSetProber.
Referenced by setuptools.extension.Extension._convert_pyx_sources_to_lang(), django.contrib.syndication.views.Feed.get_feed(), and django.templatetags.i18n.LanguageNode.render().
reset()
None pip._vendor.chardet.hebrewprober.HebrewProber.reset (self)
Reimplemented from pip._vendor.chardet.charsetprober.CharSetProber.
References pip._vendor.chardet.hebrewprober.HebrewProber._before_prev, pip._vendor.chardet.hebrewprober.HebrewProber._final_char_logical_score, pip._vendor.chardet.hebrewprober.HebrewProber._final_char_visual_score, pip._vendor.chardet.hebrewprober.HebrewProber._prev, and pip._vendor.chardet.hebrewprober.HebrewProber.SPACE.
Referenced by django.utils.html.MLStripper.__init__().
set_model_probers()
None pip._vendor.chardet.hebrewprober.HebrewProber.set_model_probers (self, SingleByteCharSetProber logical_prober, SingleByteCharSetProber visual_prober)
References pip._vendor.chardet.hebrewprober.HebrewProber._logical_prober, and pip._vendor.chardet.hebrewprober.HebrewProber._visual_prober.
state()
ProbingState pip._vendor.chardet.hebrewprober.HebrewProber.state (self)
Reimplemented from pip._vendor.chardet.charsetprober.CharSetProber.
References pip._vendor.chardet.hebrewprober.HebrewProber._logical_prober, and pip._vendor.chardet.hebrewprober.HebrewProber._visual_prober.
Referenced by pip._vendor.resolvelib.resolvers.Resolution._attempt_to_pin_criterion(), pip._vendor.resolvelib.resolvers.Resolution._backjump(), pip._vendor.resolvelib.resolvers.Resolution._get_preference(), pip._vendor.resolvelib.resolvers.Resolution._get_updated_criteria(), pip._vendor.resolvelib.resolvers.Resolution._is_current_pin_satisfying(), pip._vendor.chardet.escprober.EscCharSetProber.feed(), pip._vendor.chardet.sbcharsetprober.SingleByteCharSetProber.feed(), pip._vendor.chardet.utf1632prober.UTF1632Prober.feed(), pip._vendor.chardet.charsetgroupprober.CharSetGroupProber.get_confidence(), django.utils.jslex.Lexer.lex(), pycparser.ply.yacc.LRParser.parseopt(), pycparser.ply.yacc.LRParser.parseopt_notrack(), and pip._vendor.resolvelib.resolvers.Resolution.resolve().
Member Data Documentation
_before_prev
pip._vendor.chardet.hebrewprober.HebrewProber._before_prev protected
Referenced by pip._vendor.chardet.hebrewprober.HebrewProber.reset().
_final_char_logical_score
pip._vendor.chardet.hebrewprober.HebrewProber._final_char_logical_score protected
Referenced by pip._vendor.chardet.hebrewprober.HebrewProber.charset_name(), and pip._vendor.chardet.hebrewprober.HebrewProber.reset().
_final_char_visual_score
pip._vendor.chardet.hebrewprober.HebrewProber._final_char_visual_score protected
Referenced by pip._vendor.chardet.hebrewprober.HebrewProber.charset_name(), and pip._vendor.chardet.hebrewprober.HebrewProber.reset().
_logical_prober
Optional[SingleByteCharSetProber] pip._vendor.chardet.hebrewprober.HebrewProber._logical_prober protected
Referenced by pip._vendor.chardet.hebrewprober.HebrewProber.charset_name(), pip._vendor.chardet.hebrewprober.HebrewProber.set_model_probers(), and pip._vendor.chardet.hebrewprober.HebrewProber.state().
_prev
pip._vendor.chardet.hebrewprober.HebrewProber._prev protected
Referenced by pip._vendor.chardet.hebrewprober.HebrewProber.reset().
_visual_prober
Optional[SingleByteCharSetProber] pip._vendor.chardet.hebrewprober.HebrewProber._visual_prober protected
Referenced by pip._vendor.chardet.hebrewprober.HebrewProber.charset_name(), pip._vendor.chardet.hebrewprober.HebrewProber.set_model_probers(), and pip._vendor.chardet.hebrewprober.HebrewProber.state().
FINAL_KAF [1/2]
int pip._vendor.chardet.hebrewprober.HebrewProber.FINAL_KAF = 0xEA static
FINAL_KAF [2/2]
pip._vendor.chardet.hebrewprober.HebrewProber.FINAL_KAF
FINAL_MEM [1/2]
int pip._vendor.chardet.hebrewprober.HebrewProber.FINAL_MEM = 0xED static
FINAL_MEM [2/2]
pip._vendor.chardet.hebrewprober.HebrewProber.FINAL_MEM
FINAL_NUN [1/2]
int pip._vendor.chardet.hebrewprober.HebrewProber.FINAL_NUN = 0xEF static
FINAL_NUN [2/2]
pip._vendor.chardet.hebrewprober.HebrewProber.FINAL_NUN
FINAL_PE [1/2]
int pip._vendor.chardet.hebrewprober.HebrewProber.FINAL_PE = 0xF3 static
FINAL_PE [2/2]
pip._vendor.chardet.hebrewprober.HebrewProber.FINAL_PE
FINAL_TSADI [1/2]
int pip._vendor.chardet.hebrewprober.HebrewProber.FINAL_TSADI = 0xF5 static
FINAL_TSADI [2/2]
pip._vendor.chardet.hebrewprober.HebrewProber.FINAL_TSADI
LOGICAL_HEBREW_NAME
str pip._vendor.chardet.hebrewprober.HebrewProber.LOGICAL_HEBREW_NAME = "windows-1255" static
Referenced by pip._vendor.chardet.hebrewprober.HebrewProber.charset_name().
MIN_FINAL_CHAR_DISTANCE
int pip._vendor.chardet.hebrewprober.HebrewProber.MIN_FINAL_CHAR_DISTANCE = 5 static
Referenced by pip._vendor.chardet.hebrewprober.HebrewProber.charset_name().
MIN_MODEL_DISTANCE
float pip._vendor.chardet.hebrewprober.HebrewProber.MIN_MODEL_DISTANCE = 0.01 static
Referenced by pip._vendor.chardet.hebrewprober.HebrewProber.charset_name().
NORMAL_KAF [1/2]
int pip._vendor.chardet.hebrewprober.HebrewProber.NORMAL_KAF = 0xEB static
NORMAL_KAF [2/2]
pip._vendor.chardet.hebrewprober.HebrewProber.NORMAL_KAF
NORMAL_MEM [1/2]
int pip._vendor.chardet.hebrewprober.HebrewProber.NORMAL_MEM = 0xEE static
NORMAL_MEM [2/2]
pip._vendor.chardet.hebrewprober.HebrewProber.NORMAL_MEM
NORMAL_NUN [1/2]
int pip._vendor.chardet.hebrewprober.HebrewProber.NORMAL_NUN = 0xF0 static
NORMAL_NUN [2/2]
pip._vendor.chardet.hebrewprober.HebrewProber.NORMAL_NUN
NORMAL_PE
int pip._vendor.chardet.hebrewprober.HebrewProber.NORMAL_PE = 0xF4 static
NORMAL_TSADI
int pip._vendor.chardet.hebrewprober.HebrewProber.NORMAL_TSADI = 0xF6 static
SPACE
int pip._vendor.chardet.hebrewprober.HebrewProber.SPACE = 0x20 static
Referenced by pip._vendor.chardet.hebrewprober.HebrewProber.reset().
state
pip._vendor.chardet.hebrewprober.HebrewProber.state
Referenced by pip._vendor.resolvelib.resolvers.Resolution._attempt_to_pin_criterion(), pip._vendor.resolvelib.resolvers.Resolution._backjump(), pip._vendor.resolvelib.resolvers.Resolution._get_preference(), pip._vendor.resolvelib.resolvers.Resolution._get_updated_criteria(), pip._vendor.resolvelib.resolvers.Resolution._is_current_pin_satisfying(), pip._vendor.chardet.escprober.EscCharSetProber.feed(), pip._vendor.chardet.sbcharsetprober.SingleByteCharSetProber.feed(), pip._vendor.chardet.utf1632prober.UTF1632Prober.feed(), pip._vendor.chardet.charsetgroupprober.CharSetGroupProber.get_confidence(), django.utils.jslex.Lexer.lex(), pycparser.ply.yacc.LRParser.parseopt(), pycparser.ply.yacc.LRParser.parseopt_notrack(), and pip._vendor.resolvelib.resolvers.Resolution.resolve().
VISUAL_HEBREW_NAME
str pip._vendor.chardet.hebrewprober.HebrewProber.VISUAL_HEBREW_NAME = "ISO-8859-8" static
Referenced by pip._vendor.chardet.hebrewprober.HebrewProber.charset_name().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/pip/_vendor/chardet/hebrewprober.py