Django Project: setuptools._distutils._collections.DictStack Class Reference
setuptools._distutils._collections.DictStack Class Reference
Public Member Functions
__iter__ (self)
__getitem__ (self, key)
__contains__ (self, other)
__len__ (self)
Static Public Attributes
push = list.append
Detailed Description
A stack of dictionaries that behaves as a view on those dictionaries,
giving preference to the last.
>>> stack = DictStack([dict(a=1, c=2), dict(b=2, a=2)])
>>> stack['a']
2
>>> stack['b']
2
>>> stack['c']
2
>>> len(stack)
3
>>> stack.push(dict(a=3))
>>> stack['a']
3
>>> set(stack.keys()) == set(['a', 'b', 'c'])
True
>>> set(stack.items()) == set([('a', 3), ('b', 2), ('c', 2)])
True
>>> dict(**stack) == dict(stack) == dict(a=3, c=2, b=2)
True
>>> d = stack.pop()
>>> stack['a']
2
>>> d = stack.pop()
>>> stack['a']
1
>>> stack.get('b', None)
>>> 'c' in stack
True
Member Function Documentation
__contains__()
setuptools._distutils._collections.DictStack.__contains__ (self, other)
__getitem__()
setuptools._distutils._collections.DictStack.__getitem__ (self, key)
Referenced by django.test.utils.ContextList.get().
__iter__()
setuptools._distutils._collections.DictStack.__iter__ (self)
Referenced by django.db.models.query.BaseIterable._async_generator().
__len__()
setuptools._distutils._collections.DictStack.__len__ (self)
Referenced by waitress.buffers.OverflowableBuffer.__bool__().
Member Data Documentation
push
setuptools._distutils._collections.DictStack.push = list.append static
Referenced by django.template.context.RenderContext.push_state().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/setuptools/_distutils/_collections.py