Django Project: pkg_resources.Environment Class Reference
pkg_resources.Environment Class Reference
Public Member Functions
__init__ (self, search_path=None, platform=get_supported_platform(), python=PY_MAJOR)
can_add (self, dist)
remove (self, dist)
scan (self, search_path=None)
__getitem__ (self, project_name)
add (self, dist)
best_match (self, req, working_set, installer=None, replace_conflicting=False)
obtain (self, requirement, installer=None)
__iter__ (self)
__iadd__ (self, other)
__add__ (self, other)
Public Attributes
platform
python
Protected Attributes
_distmap
Detailed Description
Searchable snapshot of distributions on a search path
Constructor & Destructor Documentation
__init__()
pkg_resources.Environment.__init__ (self, search_path = None, platform = get_supported_platform(), python = PY_MAJOR)
Snapshot distributions available on a search path
Any distributions found on `search_path` are added to the environment.
`search_path` should be a sequence of ``sys.path`` items.  If not
supplied, ``sys.path`` is used.
`platform` is an optional string specifying the name of the platform
that platform-specific distributions must be compatible with.  If
unspecified, it defaults to the current platform.  `python` is an
optional string naming the desired version of Python (e.g. ``'3.6'``);
it defaults to the current version.
You may explicitly set `platform` (and/or `python`) to ``None`` if you
wish to map *all* distributions, not just those compatible with the
running platform or Python version.
Reimplemented in setuptools.command.easy_install.PthDistributions, and setuptools.package_index.PackageIndex.
Referenced by setuptools._vendor.typing_extensions._ProtocolMeta.__init__(), pip._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.ordered_set.OrderedSet.__setstate__(), and django.db.models.expressions.Expression.identity().
Member Function Documentation
__add__()
pkg_resources.Environment.__add__ (self, other)
Add an environment or distribution to an environment
Referenced by pip._vendor.tenacity.wait.wait_base.__radd__().
__getitem__()
pkg_resources.Environment.__getitem__ (self, project_name)
Return a newest-to-oldest list of distributions for `project_name`
Uses case-insensitive `project_name` comparison, assuming all the
project's distributions use their project's name converted to all
lowercase as their key.
Referenced by django.test.utils.ContextList.get().
__iadd__()
pkg_resources.Environment.__iadd__ (self, other)
In-place addition of a distribution or environment
Referenced by pip._vendor.pyparsing.results.ParseResults.extend(), pkg_resources._vendor.pyparsing.results.ParseResults.extend(), and setuptools._vendor.pyparsing.results.ParseResults.extend().
__iter__()
pkg_resources.Environment.__iter__ (self)
Yield the unique project names of the available distributions
Referenced by django.db.models.query.BaseIterable._async_generator().
add()
pkg_resources.Environment.add (self, dist)
Add `dist` if we ``can_add()`` it and it has not already been added
Reimplemented in setuptools.command.easy_install.PthDistributions, and setuptools.package_index.PackageIndex.
Referenced by setuptools._distutils.filelist._UniqueDirs.__call__(), pip._internal.req.req_uninstall.UninstallPathSet.add(), pip._vendor.distlib.manifest.Manifest.add_many(), django.db.models.deletion.Collector.collect(), pip._vendor.urllib3._collections.HTTPHeaderDict.extend(), django.core.cache.backends.base.BaseCache.get_or_set(), setuptools.package_index.PackageIndex.process_filename(), setuptools.package_index.PackageIndex.scan_egg_link(), pip._internal.operations.build.build_tracker.BuildTracker.track(), and setuptools._vendor.ordered_set.OrderedSet.update().
best_match()
pkg_resources.Environment.best_match (self, req, working_set, installer = None, replace_conflicting = False)
Find distribution best matching `req` and usable on `working_set`
This calls the ``find(req)`` method of the `working_set` to see if a
suitable distribution is already active.  (This may raise
``VersionConflict`` if an unsuitable version of the project is already
active in the specified `working_set`.)  If a suitable distribution
isn't active, this method returns the newest distribution in the
environment that meets the ``Requirement`` in `req`.  If no suitable
distribution is found, and `installer` is supplied, then the result of
calling the environment's ``obtain(req, installer)`` method will be
returned.
Referenced by pip._vendor.pygments.formatters.terminal256.Terminal256Formatter._color_index().
can_add()
pkg_resources.Environment.can_add (self, dist)
Is distribution `dist` acceptable for this environment?
The distribution must match the platform and python version
requirements specified when this environment was created, or False
is returned.
obtain()
pkg_resources.Environment.obtain (self, requirement, installer = None)
Obtain a distribution matching `requirement` (e.g. via download)
Obtain a distro that matches requirement (e.g. via download).  In the
base ``Environment`` class, this routine just returns
``installer(requirement)``, unless `installer` is None, in which case
None is returned instead.  This method is a hook that allows subclasses
to attempt other ways of obtaining a distribution before falling back
to the `installer` argument.
Reimplemented in setuptools.package_index.PackageIndex.
Referenced by pip._internal.vcs.versioncontrol.VersionControl.unpack().
remove()
pkg_resources.Environment.remove (self, dist)
Remove `dist` from the environment
Reimplemented in setuptools.command.easy_install.PthDistributions.
Referenced by pip._internal.operations.build.build_tracker.BuildTracker.cleanup(), django.utils.datastructures.OrderedSet.discard(), setuptools.command.alias.alias.finalize_options(), setuptools.command.setopt.setopt.finalize_options(), _pytest._py.path.LocalPath.move(), pip._vendor.distlib.util.Sequencer.remove_node(), setuptools.command.alias.alias.run(), and pip._internal.operations.build.build_tracker.BuildTracker.track().
scan()
pkg_resources.Environment.scan (self, search_path = None)
Scan `search_path` for distributions usable in this environment
Any distributions found are added to the environment.
`search_path` should be a sequence of ``sys.path`` items.  If not
supplied, ``sys.path`` is used.  Only distributions conforming to
the platform/python version defined at initialization are added.
Referenced by pip._vendor.pygments.scanner.Scanner.get_char().
Member Data Documentation
_distmap
pkg_resources.Environment._distmap protected
platform
pkg_resources.Environment.platform
Referenced by setuptools.wheel.Wheel.egg_name(), and setuptools.wheel.Wheel.tags().
python
pkg_resources.Environment.python
Referenced by setuptools._distutils.command.bdist_rpm.bdist_rpm._make_spec_file(), setuptools._distutils.command.bdist_rpm.bdist_rpm.finalize_options(), and setuptools._distutils.command.bdist_rpm.bdist_rpm.run().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/pkg_resources/__init__.py