Django Project: django.core.servers.basehttp.ThreadedWSGIServer Class Reference
django.core.servers.basehttp.ThreadedWSGIServer Class Reference
Public Member Functions
__init__ (self, *args, connections_override=None, **kwargs)
process_request_thread (self, request, client_address)
close_request (self, request)
Public Member Functions inherited from django.core.servers.basehttp.WSGIServer
handle_error (self, request, client_address)
Public Attributes
connections_override
Public Attributes inherited from django.core.servers.basehttp.WSGIServer
address_family
allow_reuse_address
Static Public Attributes
bool daemon_threads = True
Static Public Attributes inherited from django.core.servers.basehttp.WSGIServer
int request_queue_size = 10
Protected Member Functions
_close_connections (self)
Detailed Description
A threaded version of the WSGIServer
Constructor & Destructor Documentation
__init__()
django.core.servers.basehttp.ThreadedWSGIServer.__init__ (self, * args, connections_override = None, ** kwargs)
Reimplemented from django.core.servers.basehttp.WSGIServer.
Referenced by setuptools._vendor.typing_extensions._ProtocolMeta.__init__(), pip._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.ordered_set.OrderedSet.__setstate__(), and django.db.models.expressions.Expression.identity().
Member Function Documentation
_close_connections()
django.core.servers.basehttp.ThreadedWSGIServer._close_connections (self) protected
close_request()
django.core.servers.basehttp.ThreadedWSGIServer.close_request (self, request)
process_request_thread()
django.core.servers.basehttp.ThreadedWSGIServer.process_request_thread (self, request, client_address)
Member Data Documentation
connections_override
django.core.servers.basehttp.ThreadedWSGIServer.connections_override
Referenced by django.test.testcases.LiveServerThread.run().
daemon_threads
bool django.core.servers.basehttp.ThreadedWSGIServer.daemon_threads = True static
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/django/core/servers/basehttp.py