Django Project: _pytest.monkeypatch.MonkeyPatch Class Reference
_pytest.monkeypatch.MonkeyPatch Class Reference
Public Member Functions
None __init__ (self)
Generator[MonkeyPatch, None, None] context (cls)
None setattr (self, str target, object name, Notset value=..., bool raising=...)
None setattr (self, object target, str name, object value, bool raising=...)
None setattr (self, str|object target, object|str name, object value=notset, bool raising=True)
None delattr (self, object|str target, str|Notset name=notset, bool raising=True)
None setitem (self, Mapping[K, V] dic, K name, V value)
None delitem (self, Mapping[K, V] dic, K name, bool raising=True)
None setenv (self, str name, str value, str|None prepend=None)
None delenv (self, str name, bool raising=True)
None syspath_prepend (self, path)
None chdir (self, str|os.PathLike[str] path)
None undo (self)
Protected Attributes
list[tuple[object, str, object]] _setattr
list[tuple[Mapping[Any, Any], object, object]] _setitem
str|None _cwd
list[str]|None _savesyspath
_setattr
_setitem
_cwd
Detailed Description
Helper to conveniently monkeypatch attributes/items/environment
variables/syspath.
Returned by the :fixture:`monkeypatch` fixture.
.. versionchanged:: 6.2
    Can now also be used directly as `pytest.MonkeyPatch()`, for when
    the fixture is not available. In this case, use
    :meth:`with MonkeyPatch.context() as mp: <context>` or remember to call
    :meth:`undo` explicitly.
Constructor & Destructor Documentation
__init__()
None _pytest.monkeypatch.MonkeyPatch.__init__ (self)
Referenced by setuptools._vendor.typing_extensions._ProtocolMeta.__init__(), pip._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.ordered_set.OrderedSet.__setstate__(), and django.db.models.expressions.Expression.identity().
Member Function Documentation
chdir()
None _pytest.monkeypatch.MonkeyPatch.chdir (self, str | os.PathLike[str] path)
Change the current working directory to the specified path.
:param path:
    The path to change into.
References _pytest.monkeypatch.MonkeyPatch._cwd.
Referenced by _pytest._py.path.LocalPath.as_cwd(), and gunicorn.app.base.Application.load_config().
context()
Generator[MonkeyPatch, None, None] _pytest.monkeypatch.MonkeyPatch.context (cls)
Context manager that returns a new :class:`MonkeyPatch` object
which undoes any patching done inside the ``with`` block upon exit.
Example:
.. code-block:: python
    import functools
    def test_partial(monkeypatch):
        with monkeypatch.context() as m:
            m.setattr(functools, "partial", 3)
Useful in situations where it is desired to undo some patches before the test ends,
such as mocking ``stdlib`` functions that might break pytest itself if mocked (for examples
of this see :issue:`3290`).
Referenced by django.template.context.ContextDict.__exit__(), pip._internal.exceptions.DiagnosticPipError.__rich_console__(), pip._vendor.urllib3.contrib.securetransport.WrappedSocket._evaluate_trust(), pip._vendor.distlib.database.Distribution._get_requirements(), pip._vendor.urllib3.contrib.securetransport.WrappedSocket._set_alpn_protocols(), pip._vendor.urllib3.contrib.securetransport.WrappedSocket._set_ciphers(), pip._vendor.urllib3.contrib.securetransport.WrappedSocket.close(), pip._vendor.urllib3.contrib.securetransport.WrappedSocket.getpeercert(), pip._vendor.urllib3.contrib.securetransport.WrappedSocket.handshake(), django.test.testcases._AssertTemplateUsedContext.on_template_render(), pip._vendor.urllib3.contrib.securetransport.WrappedSocket.recv_into(), pip._vendor.urllib3.contrib.securetransport.WrappedSocket.send(), pip._vendor.urllib3.contrib.securetransport.WrappedSocket.shutdown(), django.template.loader_tags.BlockNode.super(), django.db.models.fields.DecimalField.to_python(), and pip._vendor.urllib3.contrib.securetransport.WrappedSocket.version().
delattr()
None _pytest.monkeypatch.MonkeyPatch.delattr (self, object | str target, str | Notset name = notset, bool raising = True)
Delete attribute ``name`` from ``target``.
If no ``name`` is specified and ``target`` is a string
it will be interpreted as a dotted import path with the
last part being the attribute name.
Raises AttributeError it the attribute does not exist, unless
``raising`` is set to False.
References _pytest.monkeypatch.MonkeyPatch._setattr, _pytest.monkeypatch.MonkeyPatch.delattr(), and _pytest.monkeypatch.derive_importpath().
Referenced by _pytest.monkeypatch.MonkeyPatch.delattr().
delenv()
None _pytest.monkeypatch.MonkeyPatch.delenv (self, str name, bool raising = True)
Delete ``name`` from the environment.
Raises ``KeyError`` if it does not exist, unless ``raising`` is set to
False.
References _pytest.monkeypatch.MonkeyPatch.delitem().
delitem()
None _pytest.monkeypatch.MonkeyPatch.delitem (self, Mapping[K, V] dic, K name, bool raising = True)
Delete ``name`` from dict.
Raises ``KeyError`` if it doesn't exist, unless ``raising`` is set to
False.
References _pytest.monkeypatch.MonkeyPatch._setitem.
Referenced by _pytest.monkeypatch.MonkeyPatch.delenv().
setattr() [1/3]
None _pytest.monkeypatch.MonkeyPatch.setattr (self, object target, str name, object value, bool raising = ...)
setattr() [2/3]
None _pytest.monkeypatch.MonkeyPatch.setattr (self, str target, object name, Notset value = ..., bool raising = ...)
Referenced by _pytest.monkeypatch.MonkeyPatch.setattr().
setattr() [3/3]
None _pytest.monkeypatch.MonkeyPatch.setattr (self, str | object target, object | str name, object value = notset, bool raising = True)
Set attribute value on target, memorizing the old value.
For example:
.. code-block:: python
    import os
    monkeypatch.setattr(os, "getcwd", lambda: "/")
The code above replaces the :func:`os.getcwd` function by a ``lambda`` which
always returns ``"/"``.
For convenience, you can specify a string as ``target`` which
will be interpreted as a dotted import path, with the last part
being the attribute name:
.. code-block:: python
    monkeypatch.setattr("os.getcwd", lambda: "/")
Raises :class:`AttributeError` if the attribute does not exist, unless
``raising`` is set to False.
**Where to patch**
``monkeypatch.setattr`` works by (temporarily) changing the object that a name points to with another one.
There can be many names pointing to any individual object, so for patching to work you must ensure
that you patch the name used by the system under test.
See the section :ref:`Where to patch <python:where-to-patch>` in the :mod:`unittest.mock`
docs for a complete explanation, which is meant for :func:`unittest.mock.patch` but
applies to ``monkeypatch.setattr`` as well.
References _pytest.monkeypatch.MonkeyPatch._setattr, _pytest.monkeypatch.derive_importpath(), and _pytest.monkeypatch.MonkeyPatch.setattr().
setenv()
None _pytest.monkeypatch.MonkeyPatch.setenv (self, str name, str value, str | None prepend = None)
Set environment variable ``name`` to ``value``.
If ``prepend`` is a character, read the current environment variable
value and prepend the ``value`` adjoined with the ``prepend``
character.
References _pytest.monkeypatch.MonkeyPatch.setitem().
setitem()
None _pytest.monkeypatch.MonkeyPatch.setitem (self, Mapping[K, V] dic, K name, V value)
Set dictionary entry ``name`` to value.
References _pytest.monkeypatch.MonkeyPatch._setitem.
Referenced by _pytest.monkeypatch.MonkeyPatch.setenv().
syspath_prepend()
None _pytest.monkeypatch.MonkeyPatch.syspath_prepend (self, path)
Prepend ``path`` to ``sys.path`` list of import locations.
References _pytest.monkeypatch.MonkeyPatch._savesyspath.
undo()
None _pytest.monkeypatch.MonkeyPatch.undo (self)
Undo previous changes.
This call consumes the undo stack. Calling it a second time has no
effect unless you do more monkeypatching after the undo call.
There is generally no need to call `undo()`, since it is
called automatically during tear-down.
.. note::
    The same `monkeypatch` fixture is used across a
    single test function invocation. If `monkeypatch` is used both by
    the test function itself and one of the test fixtures,
    calling `undo()` will undo all of the changes made in
    both functions.
    Prefer to use :meth:`context() <pytest.MonkeyPatch.context>` instead.
Member Data Documentation
_cwd [1/2]
str | None _pytest.monkeypatch.MonkeyPatch._cwd protected
Referenced by _pytest.monkeypatch.MonkeyPatch.chdir().
_cwd [2/2]
_pytest.monkeypatch.MonkeyPatch._cwd protected
Referenced by _pytest.monkeypatch.MonkeyPatch.chdir().
_savesyspath
list[str] | None _pytest.monkeypatch.MonkeyPatch._savesyspath protected
Referenced by _pytest.monkeypatch.MonkeyPatch.syspath_prepend().
_setattr [1/2]
list[tuple[object, str, object]] _pytest.monkeypatch.MonkeyPatch._setattr protected
Referenced by _pytest.monkeypatch.MonkeyPatch.delattr(), and _pytest.monkeypatch.MonkeyPatch.setattr().
_setattr [2/2]
_pytest.monkeypatch.MonkeyPatch._setattr protected
Referenced by _pytest.monkeypatch.MonkeyPatch.delattr(), and _pytest.monkeypatch.MonkeyPatch.setattr().
_setitem [1/2]
list[tuple[Mapping[Any, Any], object, object]] _pytest.monkeypatch.MonkeyPatch._setitem protected
Referenced by _pytest.monkeypatch.MonkeyPatch.delitem(), and _pytest.monkeypatch.MonkeyPatch.setitem().
_setitem [2/2]
_pytest.monkeypatch.MonkeyPatch._setitem protected
Referenced by _pytest.monkeypatch.MonkeyPatch.delitem(), and _pytest.monkeypatch.MonkeyPatch.setitem().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/_pytest/monkeypatch.py