Django Project: examples.models.Book Class Reference
examples.models.Book Class Reference
Static Public Attributes
int HARDCOVER = 1
int PAPERBACK = 2
int EBOOK = 3
tuple BOOK_TYPES
title = models.CharField(max_length=50)
publication_date = models.DateField(null=True)
author = models.CharField(max_length=30, blank=True)
price = models.DecimalField(max_digits=5, decimal_places=2)
pages = models.IntegerField(blank=True, null=True)
book_type = models.PositiveSmallIntegerField(choices=BOOK_TYPES)
timestamp = models.DateField(auto_now_add=True, auto_now=False)
Member Data Documentation
author
examples.models.Book.author = models.CharField(max_length=30, blank=True) static
Referenced by setuptools._distutils.dist.DistributionMetadata.get_author(), setuptools._distutils.dist.DistributionMetadata.get_contact(), and setuptools._distutils.dist.DistributionMetadata.read_pkg_file().
book_type
examples.models.Book.book_type = models.PositiveSmallIntegerField(choices=BOOK_TYPES) static
BOOK_TYPES
tuple examples.models.Book.BOOK_TYPES static
Initial value:
=  (
        (HARDCOVER, 'Hardcover'),
        (PAPERBACK, 'Paperback'),
        (EBOOK, 'E-book'),
    )
EBOOK
int examples.models.Book.EBOOK = 3 static
HARDCOVER
int examples.models.Book.HARDCOVER = 1 static
pages
examples.models.Book.pages = models.IntegerField(blank=True, null=True) static
PAPERBACK
int examples.models.Book.PAPERBACK = 2 static
price
examples.models.Book.price = models.DecimalField(max_digits=5, decimal_places=2) static
publication_date
examples.models.Book.publication_date = models.DateField(null=True) static
timestamp
examples.models.Book.timestamp = models.DateField(auto_now_add=True, auto_now=False) static
Referenced by django.core.signing.TimestampSigner.sign().
title
examples.models.Book.title = models.CharField(max_length=50) static
Referenced by pip._vendor.rich._inspect.Inspect.__rich__(), pip._vendor.rich.columns.Columns.__rich_console__(), pip._vendor.rich.rule.Rule.__rich_console__(), pip._vendor.rich.table.Table.__rich_console__(), django.contrib.flatpages.models.FlatPage.__str__(), pip._vendor.rich.panel.Panel._title(), and pip._vendor.pygments.formatters.html.HtmlFormatter._wrap_full().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/examples/models.py