Django Project: pip._internal.utils.temp_dir.TempDirectoryTypeRegistry Class Reference
pip._internal.utils.temp_dir.TempDirectoryTypeRegistry Class Reference
Public Member Functions
None __init__ (self)
None set_delete (self, str kind, bool value)
bool get_delete (self, str kind)
Protected Attributes
Dict[str, bool] _should_delete
Static Protected Attributes
Optional _tempdir_registry = None
Detailed Description
Manages temp directory behavior
Constructor & Destructor Documentation
__init__()
None pip._internal.utils.temp_dir.TempDirectoryTypeRegistry.__init__ (self)
Referenced by setuptools._vendor.typing_extensions._ProtocolMeta.__init__(), pip._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.ordered_set.OrderedSet.__setstate__(), and django.db.models.expressions.Expression.identity().
Member Function Documentation
get_delete()
bool pip._internal.utils.temp_dir.TempDirectoryTypeRegistry.get_delete (self, str kind)
Get configured auto-delete flag for a given TempDirectory type,
default True.
set_delete()
None pip._internal.utils.temp_dir.TempDirectoryTypeRegistry.set_delete (self, str kind, bool value)
Indicate whether a TempDirectory of the given kind should be
auto-deleted.
Member Data Documentation
_should_delete
Dict[str, bool] pip._internal.utils.temp_dir.TempDirectoryTypeRegistry._should_delete protected
_tempdir_registry
Optional pip._internal.utils.temp_dir.TempDirectoryTypeRegistry._tempdir_registry = None static protected
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/pip/_internal/utils/temp_dir.py