Django Project: setuptools._distutils.cygwinccompiler.Mingw32CCompiler Class Reference
setuptools._distutils.cygwinccompiler.Mingw32CCompiler Class Reference
Public Member Functions
__init__ (self, verbose=0, dry_run=0, force=0)
runtime_library_dir_option (self, dir)
Public Member Functions inherited from setuptools._distutils.cygwinccompiler.CygwinCCompiler
gcc_version (self)
link (self, target_desc, objects, output_filename, output_dir=None, libraries=None, library_dirs=None, runtime_library_dirs=None, export_symbols=None, debug=0, extra_preargs=None, extra_postargs=None, build_temp=None, target_lang=None)
out_extensions (self)
Public Attributes
cc
dll_libraries
Public Attributes inherited from setuptools._distutils.cygwinccompiler.CygwinCCompiler
cc
cxx
linker_dll
dll_libraries
Static Public Attributes
str compiler_type = 'mingw32'
Static Public Attributes inherited from setuptools._distutils.cygwinccompiler.CygwinCCompiler
str compiler_type = 'cygwin'
str obj_extension = ".o"
str static_lib_extension = ".a"
str shared_lib_extension = ".dll.a"
str dylib_lib_extension = ".dll"
str static_lib_format = "lib%s%s"
str shared_lib_format = "lib%s%s"
str dylib_lib_format = "cyg%s%s"
str exe_extension = ".exe"
Additional Inherited Members
Protected Member Functions inherited from setuptools._distutils.cygwinccompiler.CygwinCCompiler
_compile (self, obj, src, ext, cc_args, extra_postargs, pp_opts)
_make_out_path (self, output_dir, strip_dir, src_name)
Detailed Description
Handles the Mingw32 port of the GNU C compiler to Windows.
Constructor & Destructor Documentation
__init__()
setuptools._distutils.cygwinccompiler.Mingw32CCompiler.__init__ (self, verbose = 0, dry_run = 0, force = 0)
Reimplemented from setuptools._distutils.cygwinccompiler.CygwinCCompiler.
References setuptools._distutils.cygwinccompiler.Mingw32CCompiler.__init__().
Referenced by setuptools._distutils.cygwinccompiler.Mingw32CCompiler.__init__(), setuptools._vendor.typing_extensions._ProtocolMeta.__init__(), pip._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.ordered_set.OrderedSet.__setstate__(), and django.db.models.expressions.Expression.identity().
Member Function Documentation
runtime_library_dir_option()
setuptools._distutils.cygwinccompiler.Mingw32CCompiler.runtime_library_dir_option (self, dir)
Reimplemented from setuptools._distutils.cygwinccompiler.CygwinCCompiler.
Member Data Documentation
cc
setuptools._distutils.cygwinccompiler.Mingw32CCompiler.cc
Referenced by setuptools._distutils._msvccompiler.MSVCCompiler.compile(), setuptools._distutils.bcppcompiler.BCPPCompiler.compile(), setuptools._distutils.msvc9compiler.MSVCCompiler.compile(), setuptools._distutils.msvccompiler.MSVCCompiler.compile(), django.core.mail.message.EmailMessage.message(), and django.core.mail.message.EmailMessage.recipients().
compiler_type
str setuptools._distutils.cygwinccompiler.Mingw32CCompiler.compiler_type = 'mingw32' static
dll_libraries
setuptools._distutils.cygwinccompiler.Mingw32CCompiler.dll_libraries
Referenced by setuptools._distutils.cygwinccompiler.CygwinCCompiler.link().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/setuptools/_distutils/cygwinccompiler.py