Django Project: _pytest.logging.DatetimeFormatter Class Reference
_pytest.logging.DatetimeFormatter Class Reference
Public Member Functions
str formatTime (self, LogRecord record, str|None datefmt=None)
Detailed Description
A logging formatter which formats record with
:func:`datetime.datetime.strftime` formatter instead of
:func:`time.strftime` in case of microseconds in format string.
Member Function Documentation
formatTime()
str _pytest.logging.DatetimeFormatter.formatTime (self, LogRecord record, str | None datefmt = None)
References _pytest.logging.DatetimeFormatter.formatTime().
Referenced by django.utils.log.ServerFormatter.format(), and _pytest.logging.DatetimeFormatter.formatTime().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/_pytest/logging.py