Django Project: django.db.models.fields.reverse_related.OneToOneRel Class Reference
django.db.models.fields.reverse_related.OneToOneRel Class Reference
Public Member Functions
__init__ (self, field, to, field_name, related_name=None, related_query_name=None, limit_choices_to=None, parent_link=False, on_delete=None)
Public Member Functions inherited from django.db.models.fields.reverse_related.ManyToOneRel
__getstate__ (self)
identity (self)
get_related_field (self)
set_field_name (self)
Public Member Functions inherited from django.db.models.fields.reverse_related.ForeignObjectRel
hidden (self)
name (self)
remote_field (self)
target_field (self)
related_model (self)
many_to_many (self)
many_to_one (self)
one_to_many (self)
one_to_one (self)
get_lookup (self, lookup_name)
get_lookups (self)
get_transform (self, name)
get_internal_type (self)
db_type (self)
__repr__ (self)
__eq__ (self, other)
__hash__ (self)
get_choices (self, include_blank=True, blank_choice=BLANK_CHOICE_DASH, limit_choices_to=None, ordering=())
is_hidden (self)
get_joining_columns (self)
get_joining_fields (self)
get_extra_restriction (self, alias, related_alias)
get_accessor_name (self, model=None)
get_path_info (self, filtered_relation=None)
path_infos (self)
get_cache_name (self)
Public Member Functions inherited from django.db.models.fields.mixins.FieldCacheMixin
get_cached_value (self, instance, default=NOT_PROVIDED)
is_cached (self, instance)
set_cached_value (self, instance, value)
delete_cached_value (self, instance)
Public Attributes
multiple
Public Attributes inherited from django.db.models.fields.reverse_related.ManyToOneRel
field_name
Public Attributes inherited from django.db.models.fields.reverse_related.ForeignObjectRel
field
model
related_name
related_query_name
limit_choices_to
parent_link
on_delete
symmetrical
multiple
field_name
Additional Inherited Members
Static Public Attributes inherited from django.db.models.fields.reverse_related.ForeignObjectRel
bool auto_created = True
bool concrete = False
bool editable = False
bool is_relation = True
bool null = True
bool empty_strings_allowed = False
Detailed Description
Used by OneToOneField to store information about the relation.
``_meta.get_fields()`` returns this class to provide access to the field
flags for the reverse relation.
Constructor & Destructor Documentation
__init__()
django.db.models.fields.reverse_related.OneToOneRel.__init__ (self, field, to, field_name, related_name = None, related_query_name = None, limit_choices_to = None, parent_link = False, on_delete = None)
Reimplemented from django.db.models.fields.reverse_related.ManyToOneRel.
References django.db.models.fields.reverse_related.OneToOneRel.__init__().
Referenced by django.db.models.fields.reverse_related.OneToOneRel.__init__(), setuptools._vendor.typing_extensions._ProtocolMeta.__init__(), pip._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.ordered_set.OrderedSet.__setstate__(), and django.db.models.expressions.Expression.identity().
Member Data Documentation
multiple
django.db.models.fields.reverse_related.OneToOneRel.multiple
Referenced by django.db.models.fields.reverse_related.ForeignObjectRel.get_accessor_name(), and django.db.models.fields.reverse_related.ForeignObjectRel.identity().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/django/db/models/fields/reverse_related.py