Django Project: django_cryptography.utils.crypto.Fernet Class Reference
django_cryptography.utils.crypto.Fernet Class Reference
Public Member Functions
__init__ (self, key)
decrypt (self, token, ttl=None)
Public Member Functions inherited from django_cryptography.utils.crypto.FernetBytes
encrypt (self, data)
Protected Member Functions
_encrypt_from_parts (self, data, iv)
Additional Inherited Members
Protected Attributes inherited from django_cryptography.utils.crypto.FernetBytes
_backend
_encryption_key
_signer
Constructor & Destructor Documentation
__init__()
django_cryptography.utils.crypto.Fernet.__init__ (self, key)
Reimplemented from django_cryptography.utils.crypto.FernetBytes.
References django_cryptography.utils.crypto.Fernet.__init__().
Referenced by django_cryptography.utils.crypto.Fernet.__init__(), setuptools._vendor.typing_extensions._ProtocolMeta.__init__(), pip._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.ordered_set.OrderedSet.__setstate__(), and django.db.models.expressions.Expression.identity().
Member Function Documentation
_encrypt_from_parts()
django_cryptography.utils.crypto.Fernet._encrypt_from_parts (self, data, iv) protected
:type data: bytes
:type iv: bytes
:rtype: any
Reimplemented from django_cryptography.utils.crypto.FernetBytes.
References django_cryptography.utils.crypto.Fernet._encrypt_from_parts().
Referenced by django_cryptography.utils.crypto.Fernet._encrypt_from_parts(), django_cryptography.utils.crypto.FernetBytes.encrypt(), and cryptography.fernet.Fernet.encrypt_at_time().
decrypt()
django_cryptography.utils.crypto.Fernet.decrypt (self, data, ttl = None)
:type data: bytes
:type ttl: int
:rtype: bytes
Reimplemented from django_cryptography.utils.crypto.FernetBytes.
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/django_cryptography/utils/crypto.py