Django Project: cryptography.hazmat.primitives.asymmetric.ed25519.Ed25519PublicKey Class Reference
cryptography.hazmat.primitives.asymmetric.ed25519.Ed25519PublicKey Class Reference
Public Member Functions
Ed25519PublicKey from_public_bytes (cls, bytes data)
bytes public_bytes (self, _serialization.Encoding encoding, _serialization.PublicFormat format)
bytes public_bytes_raw (self)
None verify (self, bytes signature, bytes data)
bool __eq__ (self, object other)
Member Function Documentation
__eq__()
bool cryptography.hazmat.primitives.asymmetric.ed25519.Ed25519PublicKey.__eq__ (self, object other)
Checks equality.
Referenced by _pytest.python_api.ApproxScalar.__eq__(), pip._vendor.distlib.version.Version.__ge__(), pip._vendor.distlib.version.Version.__gt__(), pip._vendor.distlib.version.Version.__le__(), pip._vendor.distlib.version.Matcher.__ne__(), pip._vendor.distlib.version.Version.__ne__(), pip._vendor.msgpack.ext.Timestamp.__ne__(), and pip._vendor.urllib3._collections.HTTPHeaderDict.__ne__().
from_public_bytes()
Ed25519PublicKey cryptography.hazmat.primitives.asymmetric.ed25519.Ed25519PublicKey.from_public_bytes (cls, bytes data)
public_bytes()
bytes cryptography.hazmat.primitives.asymmetric.ed25519.Ed25519PublicKey.public_bytes (self, _serialization.Encoding encoding, _serialization.PublicFormat format)
The serialized bytes of the public key.
public_bytes_raw()
bytes cryptography.hazmat.primitives.asymmetric.ed25519.Ed25519PublicKey.public_bytes_raw (self)
The raw bytes of the public key.
Equivalent to public_bytes(Raw, Raw).
verify()
None cryptography.hazmat.primitives.asymmetric.ed25519.Ed25519PublicKey.verify (self, bytes signature, bytes data)
Verify the signature.
Referenced by pip._vendor.requests.sessions.Session.merge_environment_settings(), and pip._vendor.requests.sessions.Session.send().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/cryptography/hazmat/primitives/asymmetric/ed25519.py