Django Project: _pytest.mark.structures._XfailMarkDecorator Class Reference
_pytest.mark.structures._XfailMarkDecorator Class Reference
Public Member Functions
Markable __call__ (self, Markable arg)
MarkDecorator __call__ (self, str|bool condition=False, *str|bool conditions, str reason=..., bool run=..., None|type[BaseException]|tuple[type[BaseException],...] raises=..., bool strict=...)
Public Member Functions inherited from _pytest.mark.structures.MarkDecorator
None __init__ (self, Mark mark, *, bool _ispytest=False)
str name (self)
tuple[Any,...] args (self)
Mapping[str, Any] kwargs (self)
str markname (self)
MarkDecorator with_args (self, *object args, **object kwargs)
Additional Inherited Members
Public Attributes inherited from _pytest.mark.structures.MarkDecorator
mark
Member Function Documentation
__call__() [1/2]
Markable _pytest.mark.structures._XfailMarkDecorator.__call__ (self, Markable arg)
Reimplemented from _pytest.mark.structures.MarkDecorator.
Referenced by asgiref.sync.AsyncToSync.__get__(), and asgiref.sync.SyncToAsync.__get__().
__call__() [2/2]
MarkDecorator _pytest.mark.structures._XfailMarkDecorator.__call__ (self, str | bool condition = False, *str | bool conditions, str reason = ..., bool run = ..., None | type[BaseException] | tuple[type[BaseException], ...] raises = ..., bool strict = ...)
Reimplemented from _pytest.mark.structures.MarkDecorator.
Referenced by asgiref.sync.AsyncToSync.__get__(), and asgiref.sync.SyncToAsync.__get__().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/_pytest/mark/structures.py