Django Project: graphviz.jupyter_integration.JupyterIntegration Class Reference
graphviz.jupyter_integration.JupyterIntegration Class Reference
Protected Member Functions
typing.Dict[str, typing.Union[bytes, str]] _repr_mimebundle_ (self, typing.Optional[typing.Iterable[str]] include=None, typing.Optional[typing.Iterable[str]] exclude=None, **_)
bytes _repr_image_jpeg (self)
bytes _repr_image_png (self)
str _repr_image_svg_xml (self)
Protected Member Functions inherited from graphviz.piping.Pipe
typing.Union[bytes, str] _pipe_legacy (self, typing.Optional[str] format=None, typing.Optional[str] renderer=None, typing.Optional[str] formatter=None, typing.Union[bool, int, None] neato_no_op=None, bool quiet=False, *, typing.Optional[str] engine=None, typing.Optional[str] encoding=None)
typing.Union[bytes, str] _pipe_future (self, typing.Optional[str] format=None, *, typing.Optional[str] renderer=None, typing.Optional[str] formatter=None, typing.Union[bool, int, None] neato_no_op=None, bool quiet=False, typing.Optional[str] engine=None, typing.Optional[str] encoding=None)
Protected Member Functions inherited from graphviz.encoding.Encoding
_copy_kwargs (self, **kwargs)
Protected Member Functions inherited from graphviz.backend.mixins.Pipe
_get_pipe_parameters (self, **kwargs)
_pipe_lines (_)
_pipe_lines_string (_)
Protected Member Functions inherited from graphviz.parameters.mixins.Parameters
_get_parameters (self, *, typing.Optional[str] engine=None, typing.Optional[str] format=None, typing.Optional[str] renderer=None, typing.Optional[str] formatter=None, bool verify=False, **kwargs)
Protected Member Functions inherited from graphviz.parameters.engines.Engine
_copy_kwargs (self, **kwargs)
Protected Member Functions inherited from graphviz.parameters.base.ParameterBase
_getattr_from_dict (self, str attrname, *, default=None)
Protected Member Functions inherited from graphviz.parameters.formats.Format
_copy_kwargs (self, **kwargs)
Protected Member Functions inherited from graphviz.parameters.renderers.Renderer
_copy_kwargs (self, **kwargs)
Protected Member Functions inherited from graphviz.parameters.formatters.Formatter
_copy_kwargs (self, **kwargs)
Static Protected Attributes
_jupyter_mimetype = get_jupyter_format_mimetype(DEFAULT_JUPYTER_FORMAT)
Static Protected Attributes inherited from graphviz.encoding.Encoding
_encoding = DEFAULT_ENCODING
Static Protected Attributes inherited from graphviz.backend.mixins.Pipe
_get_format = staticmethod(rendering.get_format)
_get_filepath = staticmethod(rendering.get_filepath)
Static Protected Attributes inherited from graphviz.parameters.engines.Engine
_engine = DEFAULT_ENGINE
_verify_engine = staticmethod(verify_engine)
Static Protected Attributes inherited from graphviz.parameters.formats.Format
_format = DEFAULT_FORMAT
_verify_format = staticmethod(verify_format)
Static Protected Attributes inherited from graphviz.parameters.renderers.Renderer
_renderer = None
_verify_renderer = staticmethod(verify_renderer)
Static Protected Attributes inherited from graphviz.parameters.formatters.Formatter
_formatter = None
_verify_formatter = staticmethod(verify_formatter)
Additional Inherited Members
Public Member Functions inherited from graphviz.piping.Pipe
bytes pipe (self, typing.Optional[str] format=..., typing.Optional[str] renderer=..., typing.Optional[str] formatter=..., typing.Union[bool, int, None] neato_no_op=..., bool quiet=..., *, typing.Optional[str] engine=..., None encoding=...)
str pipe (self, typing.Optional[str] format=..., typing.Optional[str] renderer=..., typing.Optional[str] formatter=..., typing.Union[bool, int, None] neato_no_op=..., bool quiet=..., *, typing.Optional[str] engine=..., str encoding)
typing.Union[bytes, str] pipe (self, typing.Optional[str] format=..., typing.Optional[str] renderer=..., typing.Optional[str] formatter=..., typing.Union[bool, int, None] neato_no_op=..., bool quiet=..., *, typing.Optional[str] engine=..., typing.Optional[str] encoding)
typing.Union[bytes, str] pipe (self, typing.Optional[str] format=None, typing.Optional[str] renderer=None, typing.Optional[str] formatter=None, typing.Union[bool, int, None] neato_no_op=None, bool quiet=False, *, typing.Optional[str] engine=None, typing.Optional[str] encoding=None)
Public Member Functions inherited from graphviz.encoding.Encoding
None __init__ (self, *, typing.Optional[str] encoding=DEFAULT_ENCODING, **kwargs)
str encoding (self)
None encoding (self, typing.Optional[str] encoding)
Public Member Functions inherited from graphviz.copying.CopyBase
copy (self)
Public Member Functions inherited from graphviz.base.Base
str source (self)
str __str__ (self)
Public Member Functions inherited from graphviz.base.LineIterable
typing.Iterator[str] __iter__ (self)
Public Member Functions inherited from graphviz.parameters.engines.Engine
None __init__ (self, *, typing.Optional[str] engine=None, **kwargs)
str engine (self)
None engine (self, str engine)
Public Member Functions inherited from graphviz.parameters.formats.Format
None __init__ (self, *, typing.Optional[str] format=None, **kwargs)
str format (self)
None format (self, str format)
Public Member Functions inherited from graphviz.parameters.renderers.Renderer
None __init__ (self, *, typing.Optional[str] renderer=None, **kwargs)
typing.Optional[str] renderer (self)
None renderer (self, typing.Optional[str] renderer)
Public Member Functions inherited from graphviz.parameters.formatters.Formatter
None __init__ (self, *, typing.Optional[str] formatter=None, **kwargs)
typing.Optional[str] formatter (self)
None formatter (self, typing.Optional[str] formatter)
Public Attributes inherited from graphviz.piping.Pipe
encoding
Public Attributes inherited from graphviz.encoding.Encoding
encoding
Public Attributes inherited from graphviz.parameters.engines.Engine
engine
Public Attributes inherited from graphviz.parameters.formats.Format
format
Public Attributes inherited from graphviz.parameters.renderers.Renderer
renderer
Public Attributes inherited from graphviz.parameters.formatters.Formatter
formatter
Detailed Description
Display rendered graph as SVG in Jupyter Notebooks and QtConsole.
Member Function Documentation
_repr_image_jpeg()
bytes graphviz.jupyter_integration.JupyterIntegration._repr_image_jpeg (self) protected
Return the rendered graph as JPEG bytes.
References graphviz.piping.Pipe.pipe(), graphviz.piping.Pipe.pipe(), graphviz.piping.Pipe.pipe(), and graphviz.piping.Pipe.pipe().
_repr_image_png()
bytes graphviz.jupyter_integration.JupyterIntegration._repr_image_png (self) protected
Return the rendered graph as PNG bytes.
References graphviz.piping.Pipe.pipe(), graphviz.piping.Pipe.pipe(), graphviz.piping.Pipe.pipe(), and graphviz.piping.Pipe.pipe().
_repr_image_svg_xml()
str graphviz.jupyter_integration.JupyterIntegration._repr_image_svg_xml (self) protected
Return the rendered graph as SVG string.
References graphviz.piping.Pipe.pipe(), graphviz.piping.Pipe.pipe(), graphviz.piping.Pipe.pipe(), and graphviz.piping.Pipe.pipe().
_repr_mimebundle_()
typing.Dict[str, typing.Union[bytes, str]] graphviz.jupyter_integration.JupyterIntegration._repr_mimebundle_ (self, typing.Optional[typing.Iterable[str]] include = None, typing.Optional[typing.Iterable[str]] exclude = None, ** _) protected
Return the rendered graph as IPython mimebundle.
    Args:
        include: Iterable of mimetypes to include in the result.
            If not given or ``None``: ``['image/sxg+xml']``.
        exclude: Iterable of minetypes to exclude from the result.
            Overrides ``include``.
    Returns:
        Mapping from mimetypes to data.
    Example:
        >>> doctest_mark_exe()
        >>> import graphviz
        >>> dot = graphviz.Graph()
        >>> dot._repr_mimebundle_()  # doctest: +ELLIPSIS
        {'image/svg+xml': '<?xml version=...
        >>> dot._repr_mimebundle_(include=['image/png'])  # doctest: +ELLIPSIS
        {'image/png': b'\x89PNG...
        >>> dot._repr_mimebundle_(include=[])
        {}
        >>> dot._repr_mimebundle_(include=['image/svg+xml', 'image/jpeg'],
        ...                       exclude=['image/svg+xml'])  # doctest: +ELLIPSIS
        {'image/jpeg': b'\xff...
        >>> list(dot._repr_mimebundle_(include=['image/png', 'image/jpeg']))
        ['image/jpeg', 'image/png']
    See also:
        IPython documentation:
        - https://ipython.readthedocs.io/en/stable/api/generated/IPython.display.html#functions
        - https://ipython.readthedocs.io/en/stable/config/integrating.html#MyObject._repr_mimebundle_  # noqa: E501
        - https://nbviewer.org/github/ipython/ipython/blob/master/examples/IPython%20Kernel/Custom%20Display%20Logic.ipynb#Custom-Mimetypes-with-_repr_mimebundle_  # noqa: E501
References graphviz.jupyter_integration.JupyterIntegration._jupyter_mimetype.
Member Data Documentation
_jupyter_mimetype
graphviz.jupyter_integration.JupyterIntegration._jupyter_mimetype = get_jupyter_format_mimetype(DEFAULT_JUPYTER_FORMAT) static protected
Referenced by graphviz.jupyter_integration.JupyterIntegration._repr_mimebundle_().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/graphviz/jupyter_integration.py