Django Project: cryptography.x509.base.CertificateSigningRequest Class Reference
cryptography.x509.base.CertificateSigningRequest Class Reference
Public Member Functions
bool __eq__ (self, object other)
int __hash__ (self)
CertificatePublicKeyTypes public_key (self)
Name subject (self)
hashes.HashAlgorithm|None signature_hash_algorithm (self)
ObjectIdentifier signature_algorithm_oid (self)
None|padding.PSS|padding.PKCS1v15|ec.ECDSA signature_algorithm_parameters (self)
Extensions extensions (self)
Attributes attributes (self)
bytes public_bytes (self, serialization.Encoding encoding)
bytes signature (self)
bytes tbs_certrequest_bytes (self)
bool is_signature_valid (self)
bytes get_attribute_for_oid (self, ObjectIdentifier oid)
Member Function Documentation
__eq__()
bool cryptography.x509.base.CertificateSigningRequest.__eq__ (self, object other)
Checks equality.
Referenced by _pytest.python_api.ApproxScalar.__eq__(), pip._vendor.distlib.version.Version.__ge__(), pip._vendor.distlib.version.Version.__gt__(), pip._vendor.distlib.version.Version.__le__(), pip._vendor.distlib.version.Matcher.__ne__(), pip._vendor.distlib.version.Version.__ne__(), pip._vendor.msgpack.ext.Timestamp.__ne__(), and pip._vendor.urllib3._collections.HTTPHeaderDict.__ne__().
__hash__()
int cryptography.x509.base.CertificateSigningRequest.__hash__ (self)
Computes a hash.
Referenced by pip._vendor.rich.style.Style.__eq__(), and pip._vendor.rich.style.Style.__ne__().
attributes()
Attributes cryptography.x509.base.CertificateSigningRequest.attributes (self)
Returns an Attributes object.
Referenced by django.test.html.Element.__eq__(), django.test.html.Element.__hash__(), and django.test.html.Element.__str__().
extensions()
Extensions cryptography.x509.base.CertificateSigningRequest.extensions (self)
Returns the extensions in the signing request.
Referenced by setuptools._distutils.command.build_ext.build_ext._build_extensions_serial(), setuptools.command.build_ext.build_ext._get_output_mapping(), setuptools._distutils.command.build_ext.build_ext.build_extensions(), setuptools._distutils.command.build_ext.build_ext.finalize_options(), setuptools.command.build_ext.build_ext.finalize_options(), django.core.management.commands.makemessages.Command.find_files(), setuptools._distutils.command.build_ext.build_ext.get_outputs(), setuptools._distutils.command.build_ext.build_ext.get_source_files(), and setuptools._distutils.command.build_ext.build_ext.run().
get_attribute_for_oid()
bytes cryptography.x509.base.CertificateSigningRequest.get_attribute_for_oid (self, ObjectIdentifier oid)
Get the attribute value for a given OID.
is_signature_valid()
bool cryptography.x509.base.CertificateSigningRequest.is_signature_valid (self)
Verifies signature of signing request.
public_bytes()
bytes cryptography.x509.base.CertificateSigningRequest.public_bytes (self, serialization.Encoding encoding)
Encodes the request to PEM or DER format.
public_key()
CertificatePublicKeyTypes cryptography.x509.base.CertificateSigningRequest.public_key (self)
Returns the public key
signature()
bytes cryptography.x509.base.CertificateSigningRequest.signature (self)
Returns the signature bytes.
Referenced by django.core.signing.Signer.sign(), django_cryptography.core.signing.BytesSigner.sign(), django_cryptography.core.signing.FernetSigner.sign(), django.core.signing.Signer.unsign(), django_cryptography.core.signing.BytesSigner.unsign(), django_cryptography.core.signing.FernetSigner.unsign(), and django_cryptography.core.signing.Signer.unsign().
signature_algorithm_oid()
ObjectIdentifier cryptography.x509.base.CertificateSigningRequest.signature_algorithm_oid (self)
Returns the ObjectIdentifier of the signature algorithm.
signature_algorithm_parameters()
None | padding.PSS | padding.PKCS1v15 | ec.ECDSA cryptography.x509.base.CertificateSigningRequest.signature_algorithm_parameters (self)
Returns the signature algorithm parameters.
signature_hash_algorithm()
hashes.HashAlgorithm | None cryptography.x509.base.CertificateSigningRequest.signature_hash_algorithm (self)
Returns a HashAlgorithm corresponding to the type of the digest signed
in the certificate.
subject()
Name cryptography.x509.base.CertificateSigningRequest.subject (self)
Returns the subject name object.
Referenced by django.core.mail.message.EmailMessage.message().
tbs_certrequest_bytes()
bytes cryptography.x509.base.CertificateSigningRequest.tbs_certrequest_bytes (self)
Returns the PKCS#10 CertificationRequestInfo bytes as defined in RFC
2986.
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/cryptography/x509/base.py