Django Project: django.forms.widgets.SelectDateWidget Class Reference
django.forms.widgets.SelectDateWidget Class Reference
Public Member Functions
__init__ (self, attrs=None, years=None, months=None, empty_label=None)
get_context (self, name, value, attrs)
format_value (self, value)
id_for_label (self, id_)
value_from_datadict (self, data, files, name)
value_omitted_from_data (self, data, files, name)
Public Member Functions inherited from django.forms.widgets.Widget
__deepcopy__ (self, memo)
is_hidden (self)
subwidgets (self, name, value, attrs=None)
render (self, name, value, attrs=None, renderer=None)
build_attrs (self, base_attrs, extra_attrs=None)
use_required_attribute (self, initial)
Public Member Functions inherited from django.forms.widgets.MediaDefiningClass
__new__ (mcs, name, bases, attrs)
Public Attributes
attrs
years
months
year_none_value
month_none_value
day_none_value
is_required
Public Attributes inherited from django.forms.widgets.Widget
attrs
input_type
is_hidden
is_required
template_name
Static Public Attributes
tuple none_value = ("", "---")
str month_field = "%s_month"
str day_field = "%s_day"
str year_field = "%s_year"
str template_name = "django/forms/widgets/select_date.html"
str input_type = "select"
select_widget = Select
date_re = _lazy_re_compile(r"(\d{4}|0)-(\d\d?)-(\d\d?)$")
bool use_fieldset = True
Static Public Attributes inherited from django.forms.widgets.Widget
bool needs_multipart_form = False
bool is_localized = False
bool is_required = False
bool supports_microseconds = True
bool use_fieldset = False
Static Protected Member Functions
_parse_date_fmt ()
Additional Inherited Members
Protected Member Functions inherited from django.forms.widgets.Widget
_render (self, template_name, context, renderer=None)
Detailed Description
A widget that splits date input into three <select> boxes.
This also serves as an example of a Widget that has more than one HTML
element and hence implements value_from_datadict.
Constructor & Destructor Documentation
__init__()
django.forms.widgets.SelectDateWidget.__init__ (self, attrs = None, years = None, months = None, empty_label = None)
Reimplemented from django.forms.widgets.Widget.
Referenced by setuptools._vendor.typing_extensions._ProtocolMeta.__init__(), pip._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.ordered_set.OrderedSet.__setstate__(), and django.db.models.expressions.Expression.identity().
Member Function Documentation
_parse_date_fmt()
django.forms.widgets.SelectDateWidget._parse_date_fmt () static protected
Referenced by django.forms.widgets.SelectDateWidget.id_for_label().
format_value()
django.forms.widgets.SelectDateWidget.format_value (self, value)
Return a dict containing the year, month, and day of the current value.
Use dict instead of a datetime to allow invalid dates such as February
31 to display correctly.
Reimplemented from django.forms.widgets.Widget.
References django.forms.widgets.SelectDateWidget.date_re.
Referenced by django.forms.widgets.ChoiceWidget.subwidgets().
get_context()
django.forms.widgets.SelectDateWidget.get_context (self, name, value, attrs)
Reimplemented from django.forms.widgets.Widget.
References django.forms.widgets.SelectDateWidget.get_context(), and django.forms.widgets.SelectDateWidget.years.
Referenced by django.forms.widgets.SelectDateWidget.get_context(), django.forms.utils.RenderableMixin.render(), django.forms.widgets.Widget.render(), and django.forms.widgets.Widget.subwidgets().
id_for_label()
django.forms.widgets.SelectDateWidget.id_for_label (self, id_)
Return the HTML ID attribute of this Widget for use by a <label>, given
the ID of the field. Return an empty string if no ID is available.
This hook is necessary because some widgets have multiple HTML
elements and, thus, multiple IDs. In that case, this method should
return an ID value that corresponds to the first ID in the widget's
tags.
Reimplemented from django.forms.widgets.Widget.
References django.forms.widgets.SelectDateWidget._parse_date_fmt().
value_from_datadict()
django.forms.widgets.SelectDateWidget.value_from_datadict (self, data, files, name)
Given a dictionary of data and this widget's name, return the value
of this widget or None if it's not provided.
Reimplemented from django.forms.widgets.Widget.
References django.forms.widgets.SelectDateWidget.day_field, django.forms.widgets.SelectDateWidget.month_field, and django.forms.widgets.SelectDateWidget.year_field.
value_omitted_from_data()
django.forms.widgets.SelectDateWidget.value_omitted_from_data (self, data, files, name)
Reimplemented from django.forms.widgets.Widget.
Member Data Documentation
attrs
django.forms.widgets.SelectDateWidget.attrs
Referenced by django.forms.widgets.ChoiceWidget.__deepcopy__(), django.forms.widgets.Widget.__deepcopy__(), django.contrib.gis.forms.widgets.OSMWidget.__init__(), _pytest.junitxml._NodeReporter.add_attribute(), _pytest.junitxml._NodeReporter.record_testreport(), and _pytest.junitxml._NodeReporter.to_xml().
date_re
django.forms.widgets.SelectDateWidget.date_re = _lazy_re_compile(r"(\d{4}|0)-(\d\d?)-(\d\d?)$") static
Referenced by django.forms.widgets.SelectDateWidget.format_value().
day_field
str django.forms.widgets.SelectDateWidget.day_field = "%s_day" static
Referenced by django.forms.widgets.SelectDateWidget.value_from_datadict().
day_none_value
django.forms.widgets.SelectDateWidget.day_none_value
input_type
str django.forms.widgets.SelectDateWidget.input_type = "select" static
Referenced by django.forms.widgets.Input.__init__(), and django.forms.widgets.Input.get_context().
is_required
django.forms.widgets.SelectDateWidget.is_required
Referenced by django.forms.widgets.MultipleHiddenInput.get_context(), and django.forms.widgets.ClearableFileInput.value_from_datadict().
month_field
str django.forms.widgets.SelectDateWidget.month_field = "%s_month" static
Referenced by django.forms.widgets.SelectDateWidget.value_from_datadict().
month_none_value
django.forms.widgets.SelectDateWidget.month_none_value
months
django.forms.widgets.SelectDateWidget.months
none_value
tuple django.forms.widgets.SelectDateWidget.none_value = ("", "---") static
select_widget
django.forms.widgets.SelectDateWidget.select_widget = Select static
template_name
str django.forms.widgets.SelectDateWidget.template_name = "django/forms/widgets/select_date.html" static
Referenced by django.views.generic.base.TemplateResponseMixin.get_template_names(), django.contrib.admin.templatetags.base.InclusionAdminNode.render(), django.forms.utils.RenderableMixin.render(), django.forms.widgets.Widget.render(), django.template.response.SimpleTemplateResponse.rendered_content(), django.test.testcases._AssertTemplateNotUsedContext.test(), and django.test.testcases._AssertTemplateUsedContext.test().
use_fieldset
bool django.forms.widgets.SelectDateWidget.use_fieldset = True static
year_field
str django.forms.widgets.SelectDateWidget.year_field = "%s_year" static
Referenced by django.forms.widgets.SelectDateWidget.value_from_datadict().
year_none_value
django.forms.widgets.SelectDateWidget.year_none_value
years
django.forms.widgets.SelectDateWidget.years
Referenced by django.forms.widgets.SelectDateWidget.get_context().
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/django/forms/widgets.py