Django Project: pkg_resources.ZipProvider Class Reference
pkg_resources.ZipProvider Class Reference
Public Member Functions
__init__ (self, module)
zipinfo (self)
get_resource_filename (self, manager, resource_name)
Public Member Functions inherited from pkg_resources.NullProvider
get_resource_stream (self, manager, resource_name)
get_resource_string (self, manager, resource_name)
has_resource (self, resource_name)
has_metadata (self, name)
get_metadata (self, name)
get_metadata_lines (self, name)
resource_isdir (self, resource_name)
metadata_isdir (self, name)
resource_listdir (self, resource_name)
metadata_listdir (self, name)
run_script (self, script_name, namespace)
Public Attributes
zip_pre
egg_root
egg_name
zipinfo
module_path
Public Attributes inherited from pkg_resources.EggProvider
egg_name
egg_info
egg_root
Public Attributes inherited from pkg_resources.NullProvider
module_path
Static Public Attributes
eagers = None
Static Public Attributes inherited from pkg_resources.NullProvider
egg_name = None
egg_info = None
loader = None
Protected Member Functions
_zipinfo_name (self, fspath)
_parts (self, zip_path)
_extract_resource (self, manager, zip_path)
_is_current (self, file_path, zip_path)
_get_eager_resources (self)
_index (self)
_has (self, fspath)
_isdir (self, fspath)
_listdir (self, fspath)
_eager_to_zip (self, resource_name)
_resource_to_zip (self, resource_name)
Protected Member Functions inherited from pkg_resources.EggProvider
_setup_prefix (self)
_set_egg (self, path)
Protected Member Functions inherited from pkg_resources.NullProvider
_get_metadata_path (self, name)
_fn (self, base, resource_name)
_get (self, path)
Static Protected Member Functions
_get_date_and_size (zip_stat)
Static Protected Member Functions inherited from pkg_resources.NullProvider
_validate_resource_path (path)
Protected Attributes
_dirindex
Static Protected Attributes
_zip_manifests = MemoizedZipManifests()
Detailed Description
Resource support for zips and eggs
Constructor & Destructor Documentation
__init__()
pkg_resources.ZipProvider.__init__ (self, module)
Reimplemented from pkg_resources.EggProvider.
Reimplemented in pkg_resources.EggMetadata.
Referenced by setuptools._vendor.typing_extensions._ProtocolMeta.__init__(), pip._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.ordered_set.OrderedSet.__setstate__(), and django.db.models.expressions.Expression.identity().
Member Function Documentation
_eager_to_zip()
pkg_resources.ZipProvider._eager_to_zip (self, resource_name) protected
_extract_resource()
pkg_resources.ZipProvider._extract_resource (self, manager, zip_path) protected
_get_date_and_size()
pkg_resources.ZipProvider._get_date_and_size (zip_stat) static protected
_get_eager_resources()
pkg_resources.ZipProvider._get_eager_resources (self) protected
_has()
pkg_resources.ZipProvider._has (self, fspath) protected
Reimplemented from pkg_resources.NullProvider.
_index()
pkg_resources.ZipProvider._index (self) protected
Referenced by pkg_resources._vendor.more_itertools.more.seekable.__next__(), setuptools._vendor.more_itertools.more.seekable.__next__(), django.contrib.gis.gdal.field.Field.as_datetime(), django.contrib.gis.gdal.field.Field.as_double(), django.contrib.gis.gdal.field.Field.as_int(), django.contrib.gis.gdal.field.Field.is_set(), pkg_resources._vendor.more_itertools.more.seekable.peek(), setuptools._vendor.more_itertools.more.seekable.peek(), pkg_resources._vendor.more_itertools.more.seekable.seek(), and setuptools._vendor.more_itertools.more.seekable.seek().
_is_current()
pkg_resources.ZipProvider._is_current (self, file_path, zip_path) protected
Return True if the file_path is current for this zip_path
_isdir()
pkg_resources.ZipProvider._isdir (self, fspath) protected
Reimplemented from pkg_resources.NullProvider.
_listdir()
pkg_resources.ZipProvider._listdir (self, fspath) protected
Reimplemented from pkg_resources.NullProvider.
_parts()
pkg_resources.ZipProvider._parts (self, zip_path) protected
Referenced by pip._vendor.distlib.version.Matcher.__eq__(), pip._vendor.distlib.version.Version.__eq__(), pip._vendor.distlib.version.Matcher.__hash__(), pip._vendor.distlib.version.Version.__hash__(), pip._vendor.distlib.version.Version.__lt__(), pip._vendor.distlib.version.Matcher.exact_version(), pip._vendor.distlib.version.NormalizedVersion.is_prerelease(), pip._vendor.distlib.version.SemanticVersion.is_prerelease(), and pip._vendor.distlib.version.Matcher.match().
_resource_to_zip()
pkg_resources.ZipProvider._resource_to_zip (self, resource_name) protected
_zipinfo_name()
pkg_resources.ZipProvider._zipinfo_name (self, fspath) protected
get_resource_filename()
pkg_resources.ZipProvider.get_resource_filename (self, manager, resource_name)
Reimplemented from pkg_resources.NullProvider.
zipinfo()
pkg_resources.ZipProvider.zipinfo (self)
Member Data Documentation
_dirindex
pkg_resources.ZipProvider._dirindex protected
_zip_manifests
pkg_resources.ZipProvider._zip_manifests = MemoizedZipManifests() static protected
eagers
pkg_resources.ZipProvider.eagers = None static
egg_name
pkg_resources.ZipProvider.egg_name
Referenced by setuptools.command.egg_info.egg_info.check_broken_egg_info(), and setuptools.command.egg_info.egg_info.finalize_options().
egg_root
pkg_resources.ZipProvider.egg_root
module_path
pkg_resources.ZipProvider.module_path
Referenced by _pytest.assertion.rewrite.AssertionRewriter.visit_Assert().
zip_pre
pkg_resources.ZipProvider.zip_pre
zipinfo
pkg_resources.ZipProvider.zipinfo
The documentation for this class was generated from the following file:
C:/Users/LukeMabie/documents/Development/Password_Saver_Using_Django-master/venv/Lib/site-packages/pkg_resources/__init__.py