Django Project: setuptools.build_meta Namespace Reference
setuptools.build_meta Namespace Reference
Classes
class _BuildMetaBackend
class _BuildMetaLegacyBackend
class _ConfigSettingsTranslator
class Distribution
class SetupRequirementsError
Functions
no_install_setup_requires ()
_get_immediate_subdirectories (a_dir)
_file_with_extension (directory, extension)
_open_setup_script (setup_script)
suppress_known_deprecation ()
Variables
SETUPTOOLS_ENABLE_FEATURES = os.getenv("SETUPTOOLS_ENABLE_FEATURES", "").lower()
str LEGACY_EDITABLE = "legacy-editable" in SETUPTOOLS_ENABLE_FEATURES.replace("_", "-")
_ConfigSettings = Optional[Dict[str, Union[str, List[str], None]]]
_BACKEND = _BuildMetaBackend()
get_requires_for_build_wheel = _BACKEND.get_requires_for_build_wheel
get_requires_for_build_sdist = _BACKEND.get_requires_for_build_sdist
prepare_metadata_for_build_wheel = _BACKEND.prepare_metadata_for_build_wheel
build_wheel = _BACKEND.build_wheel
build_sdist = _BACKEND.build_sdist
get_requires_for_build_editable = _BACKEND.get_requires_for_build_editable
prepare_metadata_for_build_editable = _BACKEND.prepare_metadata_for_build_editable
build_editable = _BACKEND.build_editable
Detailed Description
A PEP 517 interface to setuptools
Previously, when a user or a command line tool (let's call it a "frontend")
needed to make a request of setuptools to take a certain action, for
example, generating a list of installation requirements, the frontend would
would call "setup.py egg_info" or "setup.py bdist_wheel" on the command line.
PEP 517 defines a different method of interfacing with setuptools. Rather
than calling "setup.py" directly, the frontend should:
  1. Set the current directory to the directory with a setup.py file
  2. Import this module into a safe python interpreter (one in which
     setuptools can potentially set global variables or crash hard).
  3. Call one of the functions defined in PEP 517.
What each function does is defined in PEP 517. However, here is a "casual"
definition of the functions (this definition should not be relied on for
bug reports or API stability):
  - `build_wheel`: build a wheel in the folder and return the basename
  - `get_requires_for_build_wheel`: get the `setup_requires` to build
  - `prepare_metadata_for_build_wheel`: get the `install_requires`
  - `build_sdist`: build an sdist in the folder and return the basename
  - `get_requires_for_build_sdist`: get the `setup_requires` to build
Again, this is not a formal definition! Just a "taste" of the module.
Function Documentation
_file_with_extension()
setuptools.build_meta._file_with_extension (directory, extension) protected
Referenced by setuptools.build_meta._BuildMetaBackend._build_with_temp_dir().
_get_immediate_subdirectories()
setuptools.build_meta._get_immediate_subdirectories (a_dir) protected
_open_setup_script()
setuptools.build_meta._open_setup_script (setup_script) protected
Referenced by setuptools.build_meta._BuildMetaBackend.run_setup().
no_install_setup_requires()
setuptools.build_meta.no_install_setup_requires ()
Temporarily disable installing setup_requires
Under PEP 517, the backend reports build dependencies to the frontend,
and the frontend is responsible for ensuring they're installed.
So setuptools (acting as a backend) should not try to install them.
Referenced by setuptools.build_meta._BuildMetaBackend._build_with_temp_dir(), and setuptools.build_meta._BuildMetaBackend.prepare_metadata_for_build_wheel().
suppress_known_deprecation()
setuptools.build_meta.suppress_known_deprecation ()
Variable Documentation
_BACKEND
setuptools.build_meta._BACKEND = _BuildMetaBackend() protected
_ConfigSettings
setuptools.build_meta._ConfigSettings = Optional[Dict[str, Union[str, List[str], None]]] protected
build_editable
setuptools.build_meta.build_editable = _BACKEND.build_editable
build_sdist
setuptools.build_meta.build_sdist = _BACKEND.build_sdist
build_wheel
setuptools.build_meta.build_wheel = _BACKEND.build_wheel
get_requires_for_build_editable
setuptools.build_meta.get_requires_for_build_editable = _BACKEND.get_requires_for_build_editable
get_requires_for_build_sdist
setuptools.build_meta.get_requires_for_build_sdist = _BACKEND.get_requires_for_build_sdist
get_requires_for_build_wheel
setuptools.build_meta.get_requires_for_build_wheel = _BACKEND.get_requires_for_build_wheel
LEGACY_EDITABLE
str setuptools.build_meta.LEGACY_EDITABLE = "legacy-editable" in SETUPTOOLS_ENABLE_FEATURES.replace("_", "-")
prepare_metadata_for_build_editable
setuptools.build_meta.prepare_metadata_for_build_editable = _BACKEND.prepare_metadata_for_build_editable
prepare_metadata_for_build_wheel
setuptools.build_meta.prepare_metadata_for_build_wheel = _BACKEND.prepare_metadata_for_build_wheel
SETUPTOOLS_ENABLE_FEATURES
setuptools.build_meta.SETUPTOOLS_ENABLE_FEATURES = os.getenv("SETUPTOOLS_ENABLE_FEATURES", "").lower()