Django Project: django.contrib.postgres.signals Namespace Reference
django.contrib.postgres.signals Namespace Reference
Functions
get_type_oids (connection_alias, type_name)
get_hstore_oids (connection_alias)
get_citext_oids (connection_alias)
register_type_handlers (connection, **kwargs)
Function Documentation
get_citext_oids()
django.contrib.postgres.signals.get_citext_oids (connection_alias)
Return citext and citext array OIDs.
References django.contrib.postgres.signals.get_type_oids().
get_hstore_oids()
django.contrib.postgres.signals.get_hstore_oids (connection_alias)
Return hstore and hstore array OIDs.
References django.contrib.postgres.signals.get_type_oids().
get_type_oids()
django.contrib.postgres.signals.get_type_oids (connection_alias, type_name)
Referenced by django.contrib.postgres.signals.get_citext_oids(), and django.contrib.postgres.signals.get_hstore_oids().
register_type_handlers()
django.contrib.postgres.signals.register_type_handlers (connection, ** kwargs)