Django Project: gunicorn.glogging Namespace Reference
gunicorn.glogging Namespace Reference
Classes
class Logger
class SafeAtoms
Functions
loggers ()
parse_syslog_address (addr)
Variables
emittedNoHandlerWarning
dict SYSLOG_FACILITIES
dict CONFIG_DEFAULTS
Function Documentation
loggers()
gunicorn.glogging.loggers ()
 get list of all loggers
Referenced by gunicorn.glogging.Logger.close_on_exec(), and gunicorn.glogging.Logger.reopen_files().
parse_syslog_address()
gunicorn.glogging.parse_syslog_address (addr)
Referenced by gunicorn.glogging.Logger._set_syslog_handler().
Variable Documentation
CONFIG_DEFAULTS
dict gunicorn.glogging.CONFIG_DEFAULTS
emittedNoHandlerWarning
gunicorn.glogging.emittedNoHandlerWarning
SYSLOG_FACILITIES
dict gunicorn.glogging.SYSLOG_FACILITIES
Initial value:
=  {
    "auth": 4,
    "authpriv": 10,
    "cron": 9,
    "daemon": 3,
    "ftp": 11,
    "kern": 0,
    "lpr": 6,
    "mail": 2,
    "news": 7,
    "security": 4,  # DEPRECATED
    "syslog": 5,
    "user": 1,
    "uucp": 8,
    "local0": 16,
    "local1": 17,
    "local2": 18,
    "local3": 19,
    "local4": 20,
    "local5": 21,
    "local6": 22,
    "local7": 23
}