Django Project: graphviz.backend.rendering Namespace Reference
graphviz.backend.rendering Namespace Reference
Functions
str get_format (pathlib.Path outfile, *, typing.Optional[str] format)
typing.List[str] get_supported_suffixes ()
typing.List[str] get_supported_formats ()
str infer_format (pathlib.Path outfile)
pathlib.Path get_outfile (typing.Union[os.PathLike, str] filepath, *, str format, typing.Optional[str] renderer=None, typing.Optional[str] formatter=None)
pathlib.Path get_filepath (typing.Union[os.PathLike, str] outfile)
str render (str engine, str format, typing.Union[os.PathLike, str] filepath, typing.Optional[str] renderer=..., typing.Optional[str] formatter=..., typing.Union[bool, int, None] neato_no_op=..., bool quiet=..., *, typing.Union[os.PathLike, str, None] outfile=..., bool raise_if_result_exists=..., bool overwrite_filepath=...)
str render (str engine, typing.Optional[str] format=..., typing.Union[os.PathLike, str, None] filepath=..., typing.Optional[str] renderer=..., typing.Optional[str] formatter=..., typing.Union[bool, int, None] neato_no_op=..., bool quiet=False, *, typing.Union[os.PathLike, str, None] outfile=..., bool raise_if_result_exists=..., bool overwrite_filepath=...)
Detailed Description
Render DOT source files with Graphviz ``dot``.
Function Documentation
get_filepath()
pathlib.Path graphviz.backend.rendering.get_filepath (typing.Union[os.PathLike, str] outfile)
Return ``outfile.with_suffix('.gv')``.
Referenced by graphviz.backend.rendering.render().
get_format()
str graphviz.backend.rendering.get_format (pathlib.Path outfile, * , typing.Optional[str] format)
Return format inferred from outfile suffix and/or given ``format``.
Args:
    outfile: Path for the rendered output file.
    format: Output format for rendering (``'pdf'``, ``'png'``, ...).
Returns:
    The given ``format`` falling back to the inferred format.
Warns:
    graphviz.UnknownSuffixWarning: If the suffix of ``outfile``
        is empty/unknown.
    graphviz.FormatSuffixMismatchWarning: If the suffix of ``outfile``
        does not match the given ``format``.
References graphviz.backend.rendering.infer_format().
get_outfile()
pathlib.Path graphviz.backend.rendering.get_outfile (typing.Union[os.PathLike, str] filepath, * , str format, typing.Optional[str] renderer = None, typing.Optional[str] formatter = None)
Return ``filepath`` + ``[[.formatter].renderer].format``.
See also:
    https://www.graphviz.org/doc/info/command.html#-O
Referenced by graphviz.backend.rendering.render().
get_supported_formats()
typing.List[str] graphviz.backend.rendering.get_supported_formats ()
Return a sorted list of supported formats for exception/warning messages.
>>> get_supported_formats()  # doctest: +ELLIPSIS
['bmp', ...]
Referenced by graphviz.backend.rendering.get_supported_suffixes().
get_supported_suffixes()
typing.List[str] graphviz.backend.rendering.get_supported_suffixes ()
Return a sorted list of supported outfile suffixes for exception/warning messages.
>>> get_supported_suffixes()  # doctest: +ELLIPSIS
['.bmp', ...]
References graphviz.backend.rendering.get_supported_formats().
infer_format()
str graphviz.backend.rendering.infer_format (pathlib.Path outfile)
Return format inferred from outfile suffix.
Args:
    outfile: Path for the rendered output file.
Returns:
    The inferred format.
Raises:
    ValueError: If the suffix of ``outfile`` is empty/unknown.
>>> infer_format(pathlib.Path('spam.pdf'))  # doctest: +NO_EXE
'pdf'
>>> infer_format(pathlib.Path('spam.gv.svg'))
'svg'
>>> infer_format(pathlib.Path('spam.PNG'))
'png'
>>> infer_format(pathlib.Path('spam'))
Traceback (most recent call last):
    ...
ValueError: cannot infer rendering format from outfile: 'spam' (missing suffix)
>>> infer_format(pathlib.Path('spam.wav'))  # doctest: +ELLIPSIS +NORMALIZE_WHITESPACE
Traceback (most recent call last):
    ...
ValueError: cannot infer rendering format from suffix '.wav' of outfile: 'spam.wav'
(unknown format: 'wav', provide outfile with a suffix from ['.bmp', ...])
Referenced by graphviz.backend.rendering.get_format().
render() [1/2]
str graphviz.backend.rendering.render (str engine, str format, typing.Union[os.PathLike, str] filepath, typing.Optional[str] renderer = ..., typing.Optional[str] formatter = ..., typing.Union[bool, int, None] neato_no_op = ..., bool quiet = ..., * , typing.Union[os.PathLike, str, None] outfile = ..., bool raise_if_result_exists = ..., bool overwrite_filepath = ...)
Require ``format`` and ``filepath`` with default ``outfile=None``.
render() [2/2]
str graphviz.backend.rendering.render (str engine, typing.Optional[str] format = ..., typing.Union[os.PathLike, str, None] filepath = ..., typing.Optional[str] renderer = ..., typing.Optional[str] formatter = ..., typing.Union[bool, int, None] neato_no_op = ..., bool quiet = False, * , typing.Union[os.PathLike, str, None] outfile = ..., bool raise_if_result_exists = ..., bool overwrite_filepath = ...)
Optional ``format`` and ``filepath`` with given ``outfile``.
Required/optional ``format`` and ``filepath`` depending on ``outfile``.
Render file with ``engine`` into ``format`` and return result filename.
Args:
    engine: Layout engine for rendering (``'dot'``, ``'neato'``, ...).
    format: Output format for rendering (``'pdf'``, ``'png'``, ...).
        Can be omitted if an ``outfile`` with a known ``format`` is given,
        i.e. if ``outfile`` ends  with a known ``.{format}`` suffix.
    filepath: Path to the DOT source file to render.
        Can be omitted if ``outfile`` is given,
        in which case it defaults to ``outfile.with_suffix('.gv')``.
    renderer: Output renderer (``'cairo'``, ``'gd'``, ...).
    formatter: Output formatter (``'cairo'``, ``'gd'``, ...).
    neato_no_op: Neato layout engine no-op flag.
    quiet: Suppress ``stderr`` output from the layout subprocess.
    outfile: Path for the rendered output file.
    raise_if_result_exists: Raise :exc:`graphviz.FileExistsError`
        if the result file exists.
    overwrite_filepath: Allow ``dot`` to write to the file it reads from.
        Incompatible with ``raise_if_result_exists``.
Returns:
    The (possibly relative) path of the rendered file.
Raises:
    ValueError: If ``engine``, ``format``, ``renderer``, or ``formatter``
        are unknown.
    graphviz.RequiredArgumentError: If ``format`` or ``filepath`` are None
        unless ``outfile`` is given.
    graphviz.RequiredArgumentError: If ``formatter`` is given
        but ``renderer`` is None.
    ValueError: If ``outfile`` and ``filename`` are the same file
        unless ``overwite_filepath=True``.
    graphviz.ExecutableNotFound: If the Graphviz ``dot`` executable
        is not found.
    graphviz.CalledProcessError: If the returncode (exit status)
        of the rendering ``dot`` subprocess is non-zero.
    graphviz.FileExistsError: If ``raise_if_exists``
        and the result file exists.
Warns:
    graphviz.UnknownSuffixWarning: If the suffix of ``outfile``
        is empty or unknown.
    graphviz.FormatSuffixMismatchWarning: If the suffix of ``outfile``
        does not match the given ``format``.
Example:
    >>> doctest_mark_exe()
    >>> import pathlib
    >>> import graphviz
    >>> assert pathlib.Path('doctest-output/spam.gv').write_text('graph { spam }') == 14
    >>> graphviz.render('dot', 'png', 'doctest-output/spam.gv').replace('\\', '/')
    'doctest-output/spam.gv.png'
    >>> graphviz.render('dot', filepath='doctest-output/spam.gv',
    ...                 outfile='doctest-output/spam.png').replace('\\', '/')
    'doctest-output/spam.png'
    >>> graphviz.render('dot', outfile='doctest-output/spam.pdf').replace('\\', '/')
    'doctest-output/spam.pdf'
Note:
    The layout command is started from the directory of ``filepath``,
    so that references to external files
    (e.g. ``[image=images/camelot.png]``)
    can be given as paths relative to the DOT source file.
See also:
    Upstream docs: https://www.graphviz.org/doc/info/command.html
References graphviz.backend.rendering.get_filepath(), and graphviz.backend.rendering.get_outfile().