Django Project: pluggy._callers Namespace Reference
pluggy._callers Namespace Reference
Functions
NoReturn _raise_wrapfail ((Generator[None, Result[object], None]|Generator[None, object, object]) wrap_controller, str msg)
None _warn_teardown_exception (str hook_name, HookImpl hook_impl, BaseException e)
object|list[object] _multicall (str hook_name, Sequence[HookImpl] hook_impls, Mapping[str, object] caller_kwargs, bool firstresult)
Variables
Teardown
Detailed Description
Call loop machinery
Function Documentation
_multicall()
object | list[object] pluggy._callers._multicall (str hook_name, Sequence[HookImpl] hook_impls, Mapping[str, object] caller_kwargs, bool firstresult) protected
Execute a call into multiple python functions/methods and return the
result(s).
``caller_kwargs`` comes from HookCaller.__call__().
References pluggy._callers._raise_wrapfail(), and pluggy._callers._warn_teardown_exception().
_raise_wrapfail()
NoReturn pluggy._callers._raise_wrapfail ((Generator[None, Result[object], None] | Generator[None, object, object]) wrap_controller, str msg) protected
Referenced by pluggy._callers._multicall().
_warn_teardown_exception()
None pluggy._callers._warn_teardown_exception (str hook_name, HookImpl hook_impl, BaseException e) protected
Referenced by pluggy._callers._multicall().
Variable Documentation
Teardown
pluggy._callers.Teardown
Initial value:
=  Union[
    Tuple[Generator[None, Result[object], None], HookImpl],
    Generator[None, object, object],
]