Django Project: _pytest.capture Namespace Reference
_pytest.capture Namespace Reference
Classes
class CaptureBase
class CaptureFixture
class CaptureIO
class CaptureManager
class CaptureResult
class DontReadFromInput
class EncodedFile
class FDCapture
class FDCaptureBase
class FDCaptureBinary
class MultiCapture
class NoCapture
class SysCapture
class SysCaptureBase
class SysCaptureBinary
class TeeCaptureIO
Functions
None pytest_addoption (Parser parser)
None _colorama_workaround ()
None _windowsconsoleio_workaround (TextIO stream)
Generator[None, None, None] pytest_load_initial_conftests (Config early_config)
MultiCapture[str] _get_multicapture (_CaptureMethod method)
Generator[CaptureFixture[str], None, None] capsys (SubRequest request)
Generator[CaptureFixture[bytes], None, None] capsysbinary (SubRequest request)
Generator[CaptureFixture[str], None, None] capfd (SubRequest request)
Generator[CaptureFixture[bytes], None, None] capfdbinary (SubRequest request)
Variables
_CaptureMethod = Literal["fd", "sys", "no", "tee-sys"]
dict patchsysdict = {0: "stdin", 1: "stdout", 2: "stderr"}
Detailed Description
Per-test stdout/stderr capturing mechanism.
Function Documentation
_colorama_workaround()
None _pytest.capture._colorama_workaround () protected
Ensure colorama is imported so that it attaches to the correct stdio
handles on Windows.
colorama uses the terminal on import time. So if something does the
first import of colorama while I/O capture is active, colorama will
fail in various ways.
Referenced by _pytest.capture.pytest_load_initial_conftests().
_get_multicapture()
MultiCapture[str] _pytest.capture._get_multicapture (_CaptureMethod method) protected
_windowsconsoleio_workaround()
None _pytest.capture._windowsconsoleio_workaround (TextIO stream) protected
Workaround for Windows Unicode console handling.
Python 3.6 implemented Unicode console handling for Windows. This works
by reading/writing to the raw console handle using
``{Read,Write}ConsoleW``.
The problem is that we are going to ``dup2`` over the stdio file
descriptors when doing ``FDCapture`` and this will ``CloseHandle`` the
handles used by Python to write to the console. Though there is still some
weirdness and the console handle seems to only be closed randomly and not
on the first call to ``CloseHandle``, or maybe it gets reopened with the
same handle value when we suspend capturing.
The workaround in this case will reopen stdio with a different fd which
also means a different handle by replicating the logic in
"Py_lifecycle.c:initstdio/create_stdio".
:param stream:
    In practice ``sys.stdout`` or ``sys.stderr``, but given
    here as parameter for unittesting purposes.
See https://github.com/pytest-dev/py/issues/103.
Referenced by _pytest.capture.pytest_load_initial_conftests().
capfd()
Generator[CaptureFixture[str], None, None] _pytest.capture.capfd (SubRequest request)
Enable text capturing of writes to file descriptors ``1`` and ``2``.
The captured output is made available via ``capfd.readouterr()`` method
calls, which return a ``(out, err)`` namedtuple.
``out`` and ``err`` will be ``text`` objects.
Returns an instance of :class:`CaptureFixture[str] <pytest.CaptureFixture>`.
Example:
.. code-block:: python
def test_system_echo(capfd):
os.system('echo "hello"')
captured = capfd.readouterr()
assert captured.out == "hello\n"
capfdbinary()
Generator[CaptureFixture[bytes], None, None] _pytest.capture.capfdbinary (SubRequest request)
Enable bytes capturing of writes to file descriptors ``1`` and ``2``.
The captured output is made available via ``capfd.readouterr()`` method
calls, which return a ``(out, err)`` namedtuple.
``out`` and ``err`` will be ``byte`` objects.
Returns an instance of :class:`CaptureFixture[bytes] <pytest.CaptureFixture>`.
Example:
.. code-block:: python
def test_system_echo(capfdbinary):
os.system('echo "hello"')
captured = capfdbinary.readouterr()
assert captured.out == b"hello\n"
capsys()
Generator[CaptureFixture[str], None, None] _pytest.capture.capsys (SubRequest request)
Enable text capturing of writes to ``sys.stdout`` and ``sys.stderr``.
The captured output is made available via ``capsys.readouterr()`` method
calls, which return a ``(out, err)`` namedtuple.
``out`` and ``err`` will be ``text`` objects.
Returns an instance of :class:`CaptureFixture[str] <pytest.CaptureFixture>`.
Example:
.. code-block:: python
def test_output(capsys):
print("hello")
captured = capsys.readouterr()
assert captured.out == "hello\n"
capsysbinary()
Generator[CaptureFixture[bytes], None, None] _pytest.capture.capsysbinary (SubRequest request)
Enable bytes capturing of writes to ``sys.stdout`` and ``sys.stderr``.
The captured output is made available via ``capsysbinary.readouterr()``
method calls, which return a ``(out, err)`` namedtuple.
``out`` and ``err`` will be ``bytes`` objects.
Returns an instance of :class:`CaptureFixture[bytes] <pytest.CaptureFixture>`.
Example:
.. code-block:: python
def test_output(capsysbinary):
print("hello")
captured = capsysbinary.readouterr()
assert captured.out == b"hello\n"
pytest_addoption()
None _pytest.capture.pytest_addoption (Parser parser)
pytest_load_initial_conftests()
Generator[None, None, None] _pytest.capture.pytest_load_initial_conftests (Config early_config)
References _pytest.capture._colorama_workaround(), and _pytest.capture._windowsconsoleio_workaround().
Variable Documentation
_CaptureMethod
_pytest.capture._CaptureMethod = Literal["fd", "sys", "no", "tee-sys"] protected
patchsysdict
dict _pytest.capture.patchsysdict = {0: "stdin", 1: "stdout", 2: "stderr"}