Django Project: pip._vendor.pyparsing.diagram Namespace Reference
pip._vendor.pyparsing.diagram Namespace Reference
Classes
class AnnotatedItem
class ConverterState
class EachItem
class EditablePartial
class ElementState
Functions
str railroad_to_html (List[NamedDiagram] diagrams, embed=False, **kwargs)
T resolve_partial ("EditablePartial[T]" partial)
List[NamedDiagram] to_railroad (pyparsing.ParserElement element, typing.Optional[dict] diagram_kwargs=None, int vertical=3, bool show_results_names=False, bool show_groups=False)
bool _should_vertical (int specification, Iterable[pyparsing.ParserElement] exprs)
bool _worth_extracting (pyparsing.ParserElement element)
_apply_diagram_item_enhancements (fn)
_visible_exprs (Iterable[pyparsing.ParserElement] exprs)
typing.Optional[EditablePartial] _to_diagram_element (pyparsing.ParserElement element, typing.Optional[EditablePartial] parent, ConverterState lookup=None, int vertical=None, int index=0, str name_hint=None, bool show_results_names=False, bool show_groups=False)
Variables
str jinja2_template_source
template = Template(jinja2_template_source)
NamedDiagram
T = TypeVar("T")
Function Documentation
_apply_diagram_item_enhancements()
pip._vendor.pyparsing.diagram._apply_diagram_item_enhancements (fn) protected
decorator to ensure enhancements to a diagram item (such as results name annotations)
get applied on return from _to_diagram_element (we do this since there are several
returns in _to_diagram_element)
_should_vertical()
bool pip._vendor.pyparsing.diagram._should_vertical (int specification, Iterable[pyparsing.ParserElement] exprs) protected
Returns true if we should return a vertical list of elements
References pip._vendor.pyparsing.diagram._visible_exprs().
Referenced by pip._vendor.pyparsing.diagram._to_diagram_element().
_to_diagram_element()
typing.Optional[EditablePartial] pip._vendor.pyparsing.diagram._to_diagram_element (pyparsing.ParserElement element, typing.Optional[EditablePartial] parent, ConverterState lookup = None, int vertical = None, int index = 0, str name_hint = None, bool show_results_names = False, bool show_groups = False) protected
Recursively converts a PyParsing Element to a railroad Element
:param lookup: The shared converter state that keeps track of useful things
:param index: The index of this element within the parent
:param parent: The parent of this element in the output tree
:param vertical: Controls at what point we make a list of elements vertical. If this is an integer (the default),
it sets the threshold of the number of items before we go vertical. If True, always go vertical, if False, never
do so
:param name_hint: If provided, this will override the generated name
:param show_results_names: bool flag indicating whether to add annotations for results names
:returns: The converted version of the input element, but as a Partial that hasn't yet been constructed
:param show_groups: bool flag indicating whether to show groups using bounding box
References pip._vendor.pyparsing.diagram._should_vertical(), pip._vendor.pyparsing.diagram._to_diagram_element(), and pip._vendor.pyparsing.diagram._worth_extracting().
Referenced by pip._vendor.pyparsing.diagram._to_diagram_element(), and pip._vendor.pyparsing.diagram.to_railroad().
_visible_exprs()
pip._vendor.pyparsing.diagram._visible_exprs (Iterable[pyparsing.ParserElement] exprs) protected
Referenced by pip._vendor.pyparsing.diagram._should_vertical().
_worth_extracting()
bool pip._vendor.pyparsing.diagram._worth_extracting (pyparsing.ParserElement element) protected
Returns true if this element is worth having its own sub-diagram. Simply, if any of its children
themselves have children, then its complex enough to extract
Referenced by pip._vendor.pyparsing.diagram._to_diagram_element().
railroad_to_html()
str pip._vendor.pyparsing.diagram.railroad_to_html (List[NamedDiagram] diagrams, embed = False, ** kwargs)
Given a list of NamedDiagram, produce a single HTML string that visualises those diagrams
:params kwargs: kwargs to be passed in to the template
resolve_partial()
T pip._vendor.pyparsing.diagram.resolve_partial ("EditablePartial[T]" partial)
Recursively resolves a collection of Partials into whatever type they are
References pip._vendor.pyparsing.diagram.resolve_partial().
Referenced by pip._vendor.pyparsing.diagram.resolve_partial(), and pip._vendor.pyparsing.diagram.to_railroad().
to_railroad()
List[NamedDiagram] pip._vendor.pyparsing.diagram.to_railroad (pyparsing.ParserElement element, typing.Optional[dict] diagram_kwargs = None, int vertical = 3, bool show_results_names = False, bool show_groups = False)
Convert a pyparsing element tree into a list of diagrams. This is the recommended entrypoint to diagram
creation if you want to access the Railroad tree before it is converted to HTML
:param element: base element of the parser being diagrammed
:param diagram_kwargs: kwargs to pass to the Diagram() constructor
:param vertical: (optional) - int - limit at which number of alternatives should be
   shown vertically instead of horizontally
:param show_results_names - bool to indicate whether results name annotations should be
   included in the diagram
:param show_groups - bool to indicate whether groups should be highlighted with an unlabeled
   surrounding box
References pip._vendor.pyparsing.diagram._to_diagram_element(), and pip._vendor.pyparsing.diagram.resolve_partial().
Variable Documentation
jinja2_template_source
str pip._vendor.pyparsing.diagram.jinja2_template_source
NamedDiagram
pip._vendor.pyparsing.diagram.NamedDiagram
Initial value:
=  NamedTuple(
    "NamedDiagram",
    [("name", str), ("diagram", typing.Optional[railroad.DiagramItem]), ("index", int)],
)
T
pip._vendor.pyparsing.diagram.T = TypeVar("T")
template
pip._vendor.pyparsing.diagram.template = Template(jinja2_template_source)