Django Project: gunicorn.sock Namespace Reference
gunicorn.sock Namespace Reference
Classes
class BaseSocket
class TCP6Socket
class TCPSocket
class UnixSocket
Functions
_sock_type (addr)
create_sockets (conf, log, fds=None)
close_sockets (listeners, unlink=True)
ssl_context (conf)
ssl_wrap_socket (sock, conf)
Function Documentation
_sock_type()
gunicorn.sock._sock_type (addr) protected
Referenced by gunicorn.sock.close_sockets(), and gunicorn.sock.create_sockets().
close_sockets()
gunicorn.sock.close_sockets (listeners, unlink = True)
References gunicorn.sock._sock_type().
create_sockets()
gunicorn.sock.create_sockets (conf, log, fds = None)
Create a new socket for the configured addresses or file descriptors.
If a configured address is a tuple then a TCP socket is created.
If it is a string, a Unix socket is created. Otherwise, a TypeError is
raised.
References gunicorn.sock._sock_type().
ssl_context()
gunicorn.sock.ssl_context (conf)
ssl_wrap_socket()
gunicorn.sock.ssl_wrap_socket (sock, conf)