Django Project: setuptools.config._apply_pyprojecttoml Namespace Reference
setuptools.config._apply_pyprojecttoml Namespace Reference
Classes
class _WouldIgnoreField
Functions
"Distribution" apply ("Distribution" dist, dict config, _Path filename)
_apply_project_table ("Distribution" dist, dict config, _Path root_dir)
_apply_tool_table ("Distribution" dist, dict config, _Path filename)
_handle_missing_dynamic ("Distribution" dist, dict project_table)
str json_compatible_key (str key)
_set_config ("Distribution" dist, str field, Any value)
Optional[str] _guess_content_type (str file)
_long_description ("Distribution" dist, _DictOrStr val, _Path root_dir)
_license ("Distribution" dist, dict val, _Path root_dir)
_people ("Distribution" dist, List[dict] val, _Path _root_dir, str kind)
_project_urls ("Distribution" dist, dict val, _root_dir)
_python_requires ("Distribution" dist, dict val, _root_dir)
_dependencies ("Distribution" dist, list val, _root_dir)
_optional_dependencies ("Distribution" dist, dict val, _root_dir)
_unify_entry_points (dict project_table)
_copy_command_options (dict pyproject, "Distribution" dist, _Path filename)
Dict[str, Set[str]] _valid_command_options (Mapping cmdclass=EMPTY)
Optional[Tuple[str, Type]] _load_ep ("metadata.EntryPoint" ep)
str _normalise_cmd_option_key (str name)
Set[str] _normalise_cmd_options (List[Tuple[str, Optional[str], str]] desc)
_attrgetter (attr)
_some_attrgetter (*items)
Variables
Mapping EMPTY = MappingProxyType({})
_Path = Union[os.PathLike, str]
_DictOrStr = Union[dict, str]
_CorrespFn = Callable[["Distribution", Any, _Path], None]
_Correspondence = Union[str, _CorrespFn]
_logger = logging.getLogger(__name__)
dict _CONTENT_TYPES
dict PYPROJECT_CORRESPONDENCE
dict TOOL_TABLE_RENAMES = {"script_files": "scripts"}
dict TOOL_TABLE_DEPRECATIONS
dict SETUPTOOLS_PATCHES
dict _PREVIOUSLY_DEFINED
Detailed Description
Translation layer between pyproject config and setuptools distribution and
metadata objects.
The distribution and metadata objects are modeled after (an old version of)
core metadata, therefore configs in the format specified for ``pyproject.toml``
need to be processed before being applied.
**PRIVATE MODULE**: API reserved for setuptools internal usage only.
Function Documentation
_apply_project_table()
setuptools.config._apply_pyprojecttoml._apply_project_table ("Distribution" dist, dict config, _Path root_dir) protected
References setuptools.config._apply_pyprojecttoml._handle_missing_dynamic(), setuptools.config._apply_pyprojecttoml._set_config(), setuptools.config._apply_pyprojecttoml._unify_entry_points(), and setuptools.config._apply_pyprojecttoml.json_compatible_key().
Referenced by setuptools.config._apply_pyprojecttoml.apply().
_apply_tool_table()
setuptools.config._apply_pyprojecttoml._apply_tool_table ("Distribution" dist, dict config, _Path filename) protected
References setuptools.config._apply_pyprojecttoml._copy_command_options(), setuptools.config._apply_pyprojecttoml._set_config(), and setuptools.config._apply_pyprojecttoml.json_compatible_key().
Referenced by setuptools.config._apply_pyprojecttoml.apply().
_attrgetter()
setuptools.config._apply_pyprojecttoml._attrgetter (attr) protected
Similar to ``operator.attrgetter`` but returns None if ``attr`` is not found
>>> from types import SimpleNamespace
>>> obj = SimpleNamespace(a=42, b=SimpleNamespace(c=13))
>>> _attrgetter("a")(obj)
42
>>> _attrgetter("b.c")(obj)
13
>>> _attrgetter("d")(obj) is None
True
Referenced by setuptools.config._apply_pyprojecttoml._some_attrgetter().
_copy_command_options()
setuptools.config._apply_pyprojecttoml._copy_command_options (dict pyproject, "Distribution" dist, _Path filename) protected
References setuptools.config._apply_pyprojecttoml._valid_command_options(), and setuptools.config._apply_pyprojecttoml.json_compatible_key().
Referenced by setuptools.config._apply_pyprojecttoml._apply_tool_table().
_dependencies()
setuptools.config._apply_pyprojecttoml._dependencies ("Distribution" dist, list val, _root_dir) protected
References setuptools.config._apply_pyprojecttoml._set_config().
_guess_content_type()
Optional[str] setuptools.config._apply_pyprojecttoml._guess_content_type (str file) protected
Referenced by setuptools.config._apply_pyprojecttoml._long_description().
_handle_missing_dynamic()
setuptools.config._apply_pyprojecttoml._handle_missing_dynamic ("Distribution" dist, dict project_table) protected
Be temporarily forgiving with ``dynamic`` fields not listed in ``dynamic``
Referenced by setuptools.config._apply_pyprojecttoml._apply_project_table().
_license()
setuptools.config._apply_pyprojecttoml._license ("Distribution" dist, dict val, _Path root_dir) protected
References setuptools.config._apply_pyprojecttoml._set_config().
_load_ep()
Optional[Tuple[str, Type]] setuptools.config._apply_pyprojecttoml._load_ep ("metadata.EntryPoint" ep) protected
Referenced by setuptools.config._apply_pyprojecttoml._valid_command_options().
_long_description()
setuptools.config._apply_pyprojecttoml._long_description ("Distribution" dist, _DictOrStr val, _Path root_dir) protected
References setuptools.config._apply_pyprojecttoml._guess_content_type(), and setuptools.config._apply_pyprojecttoml._set_config().
_normalise_cmd_option_key()
str setuptools.config._apply_pyprojecttoml._normalise_cmd_option_key (str name) protected
References setuptools.config._apply_pyprojecttoml.json_compatible_key().
Referenced by setuptools.config._apply_pyprojecttoml._normalise_cmd_options().
_normalise_cmd_options()
Set[str] setuptools.config._apply_pyprojecttoml._normalise_cmd_options (List[Tuple[str, Optional[str], str]] desc) protected
References setuptools.config._apply_pyprojecttoml._normalise_cmd_option_key().
Referenced by setuptools.config._apply_pyprojecttoml._valid_command_options().
_optional_dependencies()
setuptools.config._apply_pyprojecttoml._optional_dependencies ("Distribution" dist, dict val, _root_dir) protected
References setuptools.config._apply_pyprojecttoml._set_config().
_people()
setuptools.config._apply_pyprojecttoml._people ("Distribution" dist, List[dict] val, _Path _root_dir, str kind) protected
References setuptools.config._apply_pyprojecttoml._set_config().
_project_urls()
setuptools.config._apply_pyprojecttoml._project_urls ("Distribution" dist, dict val, _root_dir) protected
References setuptools.config._apply_pyprojecttoml._set_config().
_python_requires()
setuptools.config._apply_pyprojecttoml._python_requires ("Distribution" dist, dict val, _root_dir) protected
References setuptools.config._apply_pyprojecttoml._set_config().
_set_config()
setuptools.config._apply_pyprojecttoml._set_config ("Distribution" dist, str field, Any value) protected
Referenced by setuptools.config._apply_pyprojecttoml._apply_project_table(), setuptools.config._apply_pyprojecttoml._apply_tool_table(), setuptools.config._apply_pyprojecttoml._dependencies(), setuptools.config._apply_pyprojecttoml._license(), setuptools.config._apply_pyprojecttoml._long_description(), setuptools.config._apply_pyprojecttoml._optional_dependencies(), setuptools.config._apply_pyprojecttoml._people(), setuptools.config._apply_pyprojecttoml._project_urls(), and setuptools.config._apply_pyprojecttoml._python_requires().
_some_attrgetter()
setuptools.config._apply_pyprojecttoml._some_attrgetter (* items) protected
Return the first "truth-y" attribute or None
>>> from types import SimpleNamespace
>>> obj = SimpleNamespace(a=42, b=SimpleNamespace(c=13))
>>> _some_attrgetter("d", "a", "b.c")(obj)
42
>>> _some_attrgetter("d", "e", "b.c", "a")(obj)
13
>>> _some_attrgetter("d", "e", "f")(obj) is None
True
References setuptools.config._apply_pyprojecttoml._attrgetter().
_unify_entry_points()
setuptools.config._apply_pyprojecttoml._unify_entry_points (dict project_table) protected
References setuptools.config._apply_pyprojecttoml.json_compatible_key().
Referenced by setuptools.config._apply_pyprojecttoml._apply_project_table().
_valid_command_options()
Dict[str, Set[str]] setuptools.config._apply_pyprojecttoml._valid_command_options (Mapping cmdclass = EMPTY) protected
References setuptools.config._apply_pyprojecttoml._load_ep(), and setuptools.config._apply_pyprojecttoml._normalise_cmd_options().
Referenced by setuptools.config._apply_pyprojecttoml._copy_command_options().
apply()
"Distribution" setuptools.config._apply_pyprojecttoml.apply ("Distribution" dist, dict config, _Path filename)
Apply configuration dict read with :func:`read_configuration`
References setuptools.config._apply_pyprojecttoml._apply_project_table(), and setuptools.config._apply_pyprojecttoml._apply_tool_table().
json_compatible_key()
str setuptools.config._apply_pyprojecttoml.json_compatible_key (str key)
As defined in :pep:`566#json-compatible-metadata`
Referenced by setuptools.config._apply_pyprojecttoml._apply_project_table(), setuptools.config._apply_pyprojecttoml._apply_tool_table(), setuptools.config._apply_pyprojecttoml._copy_command_options(), setuptools.config._apply_pyprojecttoml._normalise_cmd_option_key(), and setuptools.config._apply_pyprojecttoml._unify_entry_points().
Variable Documentation
_CONTENT_TYPES
dict setuptools.config._apply_pyprojecttoml._CONTENT_TYPES protected
Initial value:
=  {
    ".md": "text/markdown",
    ".rst": "text/x-rst",
    ".txt": "text/plain",
}
_CorrespFn
setuptools.config._apply_pyprojecttoml._CorrespFn = Callable[["Distribution", Any, _Path], None] protected
_Correspondence
setuptools.config._apply_pyprojecttoml._Correspondence = Union[str, _CorrespFn] protected
_DictOrStr
setuptools.config._apply_pyprojecttoml._DictOrStr = Union[dict, str] protected
_logger
setuptools.config._apply_pyprojecttoml._logger = logging.getLogger(__name__) protected
_Path
setuptools.config._apply_pyprojecttoml._Path = Union[os.PathLike, str] protected
_PREVIOUSLY_DEFINED
dict setuptools.config._apply_pyprojecttoml._PREVIOUSLY_DEFINED protected
Initial value:
=  {
    "name": _attrgetter("metadata.name"),
    "version": _attrgetter("metadata.version"),
    "description": _attrgetter("metadata.description"),
    "readme": _attrgetter("metadata.long_description"),
    "requires-python": _some_attrgetter("python_requires", "metadata.python_requires"),
    "license": _attrgetter("metadata.license"),
    "authors": _some_attrgetter("metadata.author", "metadata.author_email"),
    "maintainers": _some_attrgetter("metadata.maintainer", "metadata.maintainer_email"),
    "keywords": _attrgetter("metadata.keywords"),
    "classifiers": _attrgetter("metadata.classifiers"),
    "urls": _attrgetter("metadata.project_urls"),
    "entry-points": _attrgetter("entry_points"),
    "dependencies": _some_attrgetter("_orig_install_requires", "install_requires"),
    "optional-dependencies": _some_attrgetter("_orig_extras_require", "extras_require"),
}
EMPTY
Mapping setuptools.config._apply_pyprojecttoml.EMPTY = MappingProxyType({})
PYPROJECT_CORRESPONDENCE
dict setuptools.config._apply_pyprojecttoml.PYPROJECT_CORRESPONDENCE
Initial value:
=  {
    "readme": _long_description,
    "license": _license,
    "authors": partial(_people, kind="author"),
    "maintainers": partial(_people, kind="maintainer"),
    "urls": _project_urls,
    "dependencies": _dependencies,
    "optional_dependencies": _optional_dependencies,
    "requires_python": _python_requires,
}
SETUPTOOLS_PATCHES
dict setuptools.config._apply_pyprojecttoml.SETUPTOOLS_PATCHES
Initial value:
=  {"long_description_content_type", "project_urls",
                      "provides_extras", "license_file", "license_files"}
TOOL_TABLE_DEPRECATIONS
dict setuptools.config._apply_pyprojecttoml.TOOL_TABLE_DEPRECATIONS
Initial value:
=  {
    "namespace_packages": "consider using implicit namespaces instead (PEP 420)."
}
TOOL_TABLE_RENAMES
dict setuptools.config._apply_pyprojecttoml.TOOL_TABLE_RENAMES = {"script_files": "scripts"}