Django Project: pkg_resources._vendor.jaraco.context Namespace Reference
pkg_resources._vendor.jaraco.context Namespace Reference
Classes
class ExceptionTrap
class suppress
Functions
pushd (dir)
tarball_context (url, target_dir=None, runner=None, pushd=pushd)
infer_compression (url)
temp_dir (remover=shutil.rmtree)
repo_context (url, branch=None, quiet=True, dest_ctx=temp_dir)
null ()
Function Documentation
infer_compression()
pkg_resources._vendor.jaraco.context.infer_compression (url)
Given a URL or filename, infer the compression code for tar.
Referenced by pkg_resources._vendor.jaraco.context.tarball_context().
null()
pkg_resources._vendor.jaraco.context.null ()
pushd()
pkg_resources._vendor.jaraco.context.pushd (dir)
Referenced by pkg_resources._vendor.jaraco.context.tarball_context().
repo_context()
pkg_resources._vendor.jaraco.context.repo_context (url, branch = None, quiet = True, dest_ctx = temp_dir)
Check out the repo indicated by url.
If dest_ctx is supplied, it should be a context manager
to yield the target directory for the check out.
tarball_context()
pkg_resources._vendor.jaraco.context.tarball_context (url, target_dir = None, runner = None, pushd = pushd)
Get a tarball, extract it, change to that directory, yield, then
clean up.
`runner` is the function to invoke commands.
`pushd` is a context manager for changing the directory.
References pkg_resources._vendor.jaraco.context.infer_compression(), and pkg_resources._vendor.jaraco.context.pushd().
temp_dir()
pkg_resources._vendor.jaraco.context.temp_dir (remover = shutil.rmtree)
Create a temporary directory context. Pass a custom remover
to override the removal behavior.