Django Project: packaging.tags Namespace Reference
packaging.tags Namespace Reference
Classes
class Tag
Functions
frozenset[Tag] parse_tag (str tag)
int|str|None _get_config_var (str name, bool warn=False)
str _normalize_string (str string)
bool _is_threaded_cpython (list[str] abis)
bool _abi3_applies (PythonVersion python_version, bool threading)
list[str] _cpython_abis (PythonVersion py_version, bool warn=False)
Iterator[Tag] cpython_tags (PythonVersion|None python_version=None, Iterable[str]|None abis=None, Iterable[str]|None platforms=None, *, bool warn=False)
list[str] _generic_abi ()
Iterator[Tag] generic_tags (str|None interpreter=None, Iterable[str]|None abis=None, Iterable[str]|None platforms=None, *, bool warn=False)
Iterator[str] _py_interpreter_range (PythonVersion py_version)
Iterator[Tag] compatible_tags (PythonVersion|None python_version=None, str|None interpreter=None, Iterable[str]|None platforms=None)
str _mac_arch (str arch, bool is_32bit=_32_BIT_INTERPRETER)
list[str] _mac_binary_formats (MacVersion version, str cpu_arch)
Iterator[str] mac_platforms (MacVersion|None version=None, str|None arch=None)
Iterator[str] _linux_platforms (bool is_32bit=_32_BIT_INTERPRETER)
Iterator[str] _generic_platforms ()
Iterator[str] platform_tags ()
str interpreter_name ()
str interpreter_version (*, bool warn=False)
str _version_nodot (PythonVersion version)
Iterator[Tag] sys_tags (*, bool warn=False)
Variables
logger = logging.getLogger(__name__)
PythonVersion = Sequence[int]
MacVersion = Tuple[int, int]
dict INTERPRETER_SHORT_NAMES
int _32_BIT_INTERPRETER = 4
Function Documentation
_abi3_applies()
bool packaging.tags._abi3_applies (PythonVersion python_version, bool threading) protected
Determine if the Python version supports abi3.
PEP 384 was first implemented in Python 3.2. The threaded (`--disable-gil`)
builds do not support abi3.
Referenced by packaging.tags.cpython_tags().
_cpython_abis()
list[str] packaging.tags._cpython_abis (PythonVersion py_version, bool warn = False) protected
References packaging.tags._get_config_var(), and packaging.tags._version_nodot().
Referenced by packaging.tags._generic_abi(), and packaging.tags.cpython_tags().
_generic_abi()
list[str] packaging.tags._generic_abi () protected
Return the ABI tag based on EXT_SUFFIX.
References packaging.tags._cpython_abis(), packaging.tags._get_config_var(), and packaging.tags._normalize_string().
Referenced by packaging.tags.generic_tags().
_generic_platforms()
Iterator[str] packaging.tags._generic_platforms () protected
References packaging.tags._normalize_string().
Referenced by packaging.tags.platform_tags().
_get_config_var()
int | str | None packaging.tags._get_config_var (str name, bool warn = False) protected
Referenced by packaging.tags._cpython_abis(), packaging.tags._generic_abi(), and packaging.tags.interpreter_version().
_is_threaded_cpython()
bool packaging.tags._is_threaded_cpython (list[str] abis) protected
Determine if the ABI corresponds to a threaded (`--disable-gil`) build.
The threaded builds are indicated by a "t" in the abiflags.
Referenced by packaging.tags.cpython_tags().
_linux_platforms()
Iterator[str] packaging.tags._linux_platforms (bool is_32bit = _32_BIT_INTERPRETER) protected
References packaging.tags._normalize_string().
Referenced by packaging.tags.platform_tags().
_mac_arch()
str packaging.tags._mac_arch (str arch, bool is_32bit = _32_BIT_INTERPRETER) protected
Referenced by packaging.tags.mac_platforms().
_mac_binary_formats()
list[str] packaging.tags._mac_binary_formats (MacVersion version, str cpu_arch) protected
Referenced by packaging.tags.mac_platforms().
_normalize_string()
str packaging.tags._normalize_string (str string) protected
Referenced by packaging.tags._generic_abi(), packaging.tags._generic_platforms(), and packaging.tags._linux_platforms().
_py_interpreter_range()
Iterator[str] packaging.tags._py_interpreter_range (PythonVersion py_version) protected
Yields Python versions in descending order.
After the latest version, the major-only version will be yielded, and then
all previous versions of that major version.
Referenced by packaging.tags.compatible_tags().
_version_nodot()
str packaging.tags._version_nodot (PythonVersion version) protected
Referenced by packaging.tags._cpython_abis(), packaging.tags.cpython_tags(), and packaging.tags.interpreter_version().
compatible_tags()
Iterator[Tag] packaging.tags.compatible_tags (PythonVersion | None python_version = None, str | None interpreter = None, Iterable[str] | None platforms = None)
Yields the sequence of tags that are compatible with a specific version of Python.
The tags consist of:
- py*-none-<platform>
- <interpreter>-none-any  # ... if `interpreter` is provided.
- py*-none-any
References packaging.tags._py_interpreter_range(), and packaging.tags.platform_tags().
cpython_tags()
Iterator[Tag] packaging.tags.cpython_tags (PythonVersion | None python_version = None, Iterable[str] | None abis = None, Iterable[str] | None platforms = None, * , bool warn = False)
Yields the tags for a CPython interpreter.
The tags consist of:
- cp<python_version>-<abi>-<platform>
- cp<python_version>-abi3-<platform>
- cp<python_version>-none-<platform>
- cp<less than python_version>-abi3-<platform>  # Older Python versions down to 3.2.
If python_version only specifies a major version then user-provided ABIs and
the 'none' ABItag will be used.
If 'abi3' or 'none' are specified in 'abis' then they will be yielded at
their normal position and not at the beginning.
References packaging.tags._abi3_applies(), packaging.tags._cpython_abis(), packaging.tags._is_threaded_cpython(), packaging.tags._version_nodot(), and packaging.tags.platform_tags().
generic_tags()
Iterator[Tag] packaging.tags.generic_tags (str | None interpreter = None, Iterable[str] | None abis = None, Iterable[str] | None platforms = None, * , bool warn = False)
Yields the tags for a generic interpreter.
The tags consist of:
- <interpreter>-<abi>-<platform>
The "none" ABI will be added if it was not explicitly provided.
References packaging.tags._generic_abi(), and packaging.tags.platform_tags().
interpreter_name()
str packaging.tags.interpreter_name ()
Returns the name of the running interpreter.
Some implementations have a reserved, two-letter abbreviation which will
be returned when appropriate.
interpreter_version()
str packaging.tags.interpreter_version (* , bool warn = False)
Returns the version of the running interpreter.
References packaging.tags._get_config_var(), and packaging.tags._version_nodot().
mac_platforms()
Iterator[str] packaging.tags.mac_platforms (MacVersion | None version = None, str | None arch = None)
Yields the platform tags for a macOS system.
The `version` parameter is a two-item tuple specifying the macOS version to
generate platform tags for. The `arch` parameter is the CPU architecture to
generate platform tags for. Both parameters default to the appropriate value
for the current system.
References packaging.tags._mac_arch(), and packaging.tags._mac_binary_formats().
parse_tag()
frozenset[Tag] packaging.tags.parse_tag (str tag)
Parses the provided tag (e.g. `py3-none-any`) into a frozenset of Tag instances.
Returning a set is required due to the possibility that the tag is a
compressed tag set.
platform_tags()
Iterator[str] packaging.tags.platform_tags ()
Provides the platform tags for this installation.
References packaging.tags._generic_platforms(), and packaging.tags._linux_platforms().
Referenced by packaging.tags.compatible_tags(), packaging.tags.cpython_tags(), and packaging.tags.generic_tags().
sys_tags()
Iterator[Tag] packaging.tags.sys_tags (* , bool warn = False)
Returns the sequence of tag triples for the running interpreter.
The order of the sequence corresponds to priority order for the
interpreter, from most to least important.
Variable Documentation
_32_BIT_INTERPRETER
int packaging.tags._32_BIT_INTERPRETER = 4 protected
INTERPRETER_SHORT_NAMES
dict packaging.tags.INTERPRETER_SHORT_NAMES
Initial value:
=  {
    "python": "py",  # Generic.
    "cpython": "cp",
    "pypy": "pp",
    "ironpython": "ip",
    "jython": "jy",
}
logger
packaging.tags.logger = logging.getLogger(__name__)
MacVersion
packaging.tags.MacVersion = Tuple[int, int]
PythonVersion
packaging.tags.PythonVersion = Sequence[int]