Django Project: _pytest.warnings Namespace Reference
_pytest.warnings Namespace Reference
Functions
None pytest_configure (Config config)
Generator[None, None, None] catch_warnings_for_item (Config config, ihook, Literal["config", "collect", "runtest"] when, Item|None item)
str warning_record_to_str (warnings.WarningMessage warning_message)
Generator[None, object, object] pytest_runtest_protocol (Item item)
Generator[None, object, object] pytest_collection (Session session)
Generator[None, None, None] pytest_terminal_summary (TerminalReporter terminalreporter)
Generator[None, None, None] pytest_sessionfinish (Session session)
Generator[None, None, None] pytest_load_initial_conftests (Config early_config)
Function Documentation
catch_warnings_for_item()
Generator[None, None, None] _pytest.warnings.catch_warnings_for_item (Config config, ihook, Literal["config", "collect", "runtest"] when, Item | None item)
Context manager that catches warnings generated in the contained execution block.
``item`` can be None if we are not in the context of an item execution.
Each warning captured triggers the ``pytest_warning_recorded`` hook.
Referenced by _pytest.warnings.pytest_collection(), _pytest.warnings.pytest_load_initial_conftests(), _pytest.warnings.pytest_runtest_protocol(), _pytest.warnings.pytest_sessionfinish(), and _pytest.warnings.pytest_terminal_summary().
pytest_collection()
Generator[None, object, object] _pytest.warnings.pytest_collection (Session session)
References _pytest.warnings.catch_warnings_for_item().
pytest_configure()
None _pytest.warnings.pytest_configure (Config config)
pytest_load_initial_conftests()
Generator[None, None, None] _pytest.warnings.pytest_load_initial_conftests (Config early_config)
References _pytest.warnings.catch_warnings_for_item().
pytest_runtest_protocol()
Generator[None, object, object] _pytest.warnings.pytest_runtest_protocol (Item item)
References _pytest.warnings.catch_warnings_for_item().
pytest_sessionfinish()
Generator[None, None, None] _pytest.warnings.pytest_sessionfinish (Session session)
References _pytest.warnings.catch_warnings_for_item().
pytest_terminal_summary()
Generator[None, None, None] _pytest.warnings.pytest_terminal_summary (TerminalReporter terminalreporter)
References _pytest.warnings.catch_warnings_for_item().
warning_record_to_str()
str _pytest.warnings.warning_record_to_str (warnings.WarningMessage warning_message)
Convert a warnings.WarningMessage to a string.