Django Project: _pytest._py.path Namespace Reference
_pytest._py.path Namespace Reference
Classes
class Checkers
class FNMatcher
class LocalPath
class NeverRaised
class Stat
class Visitor
Functions
map_as_list (func, iter)
getuserid (user)
getgroupid (group)
copymode (src, dest)
copystat (src, dest)
copychunked (src, dest)
isimportable (name)
Variables
str iswin32 = "win32" or (getattr(os, "_name", False) == "nt")
local = LocalPath
Detailed Description
local path implementation.
Function Documentation
copychunked()
_pytest._py.path.copychunked (src, dest)
Referenced by _pytest._py.path.LocalPath.copy().
copymode()
_pytest._py.path.copymode (src, dest)
Copy permission from src to dst.
copystat()
_pytest._py.path.copystat (src, dest)
Copy permission,  last modification time,
last access time, and flags from src to dst.
getgroupid()
_pytest._py.path.getgroupid (group)
Referenced by _pytest._py.path.LocalPath.chown().
getuserid()
_pytest._py.path.getuserid (user)
Referenced by _pytest._py.path.LocalPath.chown().
isimportable()
_pytest._py.path.isimportable (name)
Referenced by _pytest._py.path.LocalPath.pypkgpath().
map_as_list()
_pytest._py.path.map_as_list (func, iter)
Variable Documentation
iswin32
str _pytest._py.path.iswin32 = "win32" or (getattr(os, "_name", False) == "nt")
local
_pytest._py.path.local = LocalPath
Referenced by _pytest._py.path.LocalPath.get_temproot(), and _pytest._py.path.LocalPath.sysfind().