Django Project: pkg_resources._vendor.packaging._manylinux Namespace Reference
pkg_resources._vendor.packaging._manylinux Namespace Reference
Classes
class _ELFFileHeader
class _GLibCVersion
Functions
Optional[_ELFFileHeader] _get_elf_header ()
bool _is_linux_armhf ()
bool _is_linux_i686 ()
bool _have_compatible_abi (str arch)
Optional[str] _glibc_version_string_confstr ()
Optional[str] _glibc_version_string_ctypes ()
Optional[str] _glibc_version_string ()
Tuple[int, int] _parse_glibc_version (str version_str)
Tuple[int, int] _get_glibc_version ()
bool _is_compatible (str name, str arch, _GLibCVersion version)
Iterator[str] platform_tags (str linux, str arch)
Variables
Dict _LAST_GLIBC_MINOR = collections.defaultdict(lambda: 50)
dict _LEGACY_MANYLINUX_MAP
Function Documentation
_get_elf_header()
Optional[_ELFFileHeader] pkg_resources._vendor.packaging._manylinux._get_elf_header () protected
Referenced by pkg_resources._vendor.packaging._manylinux._is_linux_armhf(), and pkg_resources._vendor.packaging._manylinux._is_linux_i686().
_get_glibc_version()
Tuple[int, int] pkg_resources._vendor.packaging._manylinux._get_glibc_version () protected
References pkg_resources._vendor.packaging._manylinux._glibc_version_string(), and pkg_resources._vendor.packaging._manylinux._parse_glibc_version().
Referenced by pkg_resources._vendor.packaging._manylinux._is_compatible(), and pkg_resources._vendor.packaging._manylinux.platform_tags().
_glibc_version_string()
Optional[str] pkg_resources._vendor.packaging._manylinux._glibc_version_string () protected
Returns glibc version string, or None if not using glibc.
References pkg_resources._vendor.packaging._manylinux._glibc_version_string_confstr(), and pkg_resources._vendor.packaging._manylinux._glibc_version_string_ctypes().
Referenced by pkg_resources._vendor.packaging._manylinux._get_glibc_version().
_glibc_version_string_confstr()
Optional[str] pkg_resources._vendor.packaging._manylinux._glibc_version_string_confstr () protected
Primary implementation of glibc_version_string using os.confstr.
Referenced by pkg_resources._vendor.packaging._manylinux._glibc_version_string().
_glibc_version_string_ctypes()
Optional[str] pkg_resources._vendor.packaging._manylinux._glibc_version_string_ctypes () protected
Fallback implementation of glibc_version_string using ctypes.
Referenced by pkg_resources._vendor.packaging._manylinux._glibc_version_string().
_have_compatible_abi()
bool pkg_resources._vendor.packaging._manylinux._have_compatible_abi (str arch) protected
References pkg_resources._vendor.packaging._manylinux._is_linux_armhf(), and pkg_resources._vendor.packaging._manylinux._is_linux_i686().
Referenced by pkg_resources._vendor.packaging._manylinux.platform_tags().
_is_compatible()
bool pkg_resources._vendor.packaging._manylinux._is_compatible (str name, str arch, _GLibCVersion version) protected
References pkg_resources._vendor.packaging._manylinux._get_glibc_version().
Referenced by pkg_resources._vendor.packaging._manylinux.platform_tags().
_is_linux_armhf()
bool pkg_resources._vendor.packaging._manylinux._is_linux_armhf () protected
References pkg_resources._vendor.packaging._manylinux._get_elf_header().
Referenced by pkg_resources._vendor.packaging._manylinux._have_compatible_abi().
_is_linux_i686()
bool pkg_resources._vendor.packaging._manylinux._is_linux_i686 () protected
References pkg_resources._vendor.packaging._manylinux._get_elf_header().
Referenced by pkg_resources._vendor.packaging._manylinux._have_compatible_abi().
_parse_glibc_version()
Tuple[int, int] pkg_resources._vendor.packaging._manylinux._parse_glibc_version (str version_str) protected
Parse glibc version.
We use a regexp instead of str.split because we want to discard any
random junk that might come after the minor version -- this might happen
in patched/forked versions of glibc (e.g. Linaro's version of glibc
uses version strings like "2.20-2014.11"). See gh-3588.
Referenced by pkg_resources._vendor.packaging._manylinux._get_glibc_version().
platform_tags()
Iterator[str] pkg_resources._vendor.packaging._manylinux.platform_tags (str linux, str arch)
References pkg_resources._vendor.packaging._manylinux._get_glibc_version(), pkg_resources._vendor.packaging._manylinux._have_compatible_abi(), and pkg_resources._vendor.packaging._manylinux._is_compatible().
Variable Documentation
_LAST_GLIBC_MINOR
Dict pkg_resources._vendor.packaging._manylinux._LAST_GLIBC_MINOR = collections.defaultdict(lambda: 50) protected
_LEGACY_MANYLINUX_MAP
dict pkg_resources._vendor.packaging._manylinux._LEGACY_MANYLINUX_MAP protected
Initial value:
=  {
    # CentOS 7 w/ glibc 2.17 (PEP 599)
    (2, 17): "manylinux2014",
    # CentOS 6 w/ glibc 2.12 (PEP 571)
    (2, 12): "manylinux2010",
    # CentOS 5 w/ glibc 2.5 (PEP 513)
    (2, 5): "manylinux1",
}