Django Project: pkg_resources._vendor.packaging.tags Namespace Reference
pkg_resources._vendor.packaging.tags Namespace Reference
Classes
class Tag
Functions
FrozenSet[Tag] parse_tag (str tag)
Union[int, str, None] _get_config_var (str name, bool warn=False)
str _normalize_string (str string)
bool _abi3_applies (PythonVersion python_version)
List[str] _cpython_abis (PythonVersion py_version, bool warn=False)
Iterator[Tag] cpython_tags (Optional[PythonVersion] python_version=None, Optional[Iterable[str]] abis=None, Optional[Iterable[str]] platforms=None, *, bool warn=False)
Iterator[str] _generic_abi ()
Iterator[Tag] generic_tags (Optional[str] interpreter=None, Optional[Iterable[str]] abis=None, Optional[Iterable[str]] platforms=None, *, bool warn=False)
Iterator[str] _py_interpreter_range (PythonVersion py_version)
Iterator[Tag] compatible_tags (Optional[PythonVersion] python_version=None, Optional[str] interpreter=None, Optional[Iterable[str]] platforms=None)
str _mac_arch (str arch, bool is_32bit=_32_BIT_INTERPRETER)
List[str] _mac_binary_formats (MacVersion version, str cpu_arch)
Iterator[str] mac_platforms (Optional[MacVersion] version=None, Optional[str] arch=None)
Iterator[str] _linux_platforms (bool is_32bit=_32_BIT_INTERPRETER)
Iterator[str] _generic_platforms ()
Iterator[str] platform_tags ()
str interpreter_name ()
str interpreter_version (*, bool warn=False)
str _version_nodot (PythonVersion version)
Iterator[Tag] sys_tags (*, bool warn=False)
Variables
logger = logging.getLogger(__name__)
PythonVersion = Sequence[int]
MacVersion = Tuple[int, int]
dict INTERPRETER_SHORT_NAMES
int _32_BIT_INTERPRETER = 2 ** 32
Function Documentation
_abi3_applies()
bool pkg_resources._vendor.packaging.tags._abi3_applies (PythonVersion python_version) protected
Determine if the Python version supports abi3.
PEP 384 was first implemented in Python 3.2.
Referenced by pkg_resources._vendor.packaging.tags.cpython_tags().
_cpython_abis()
List[str] pkg_resources._vendor.packaging.tags._cpython_abis (PythonVersion py_version, bool warn = False) protected
References pkg_resources._vendor.packaging.tags._get_config_var(), and pkg_resources._vendor.packaging.tags._version_nodot().
Referenced by pkg_resources._vendor.packaging.tags.cpython_tags().
_generic_abi()
Iterator[str] pkg_resources._vendor.packaging.tags._generic_abi () protected
References pkg_resources._vendor.packaging.tags._normalize_string().
Referenced by pkg_resources._vendor.packaging.tags.generic_tags().
_generic_platforms()
Iterator[str] pkg_resources._vendor.packaging.tags._generic_platforms () protected
References pkg_resources._vendor.packaging.tags._normalize_string().
Referenced by pkg_resources._vendor.packaging.tags.platform_tags().
_get_config_var()
Union[int, str, None] pkg_resources._vendor.packaging.tags._get_config_var (str name, bool warn = False) protected
Referenced by pkg_resources._vendor.packaging.tags._cpython_abis(), and pkg_resources._vendor.packaging.tags.interpreter_version().
_linux_platforms()
Iterator[str] pkg_resources._vendor.packaging.tags._linux_platforms (bool is_32bit = _32_BIT_INTERPRETER) protected
References pkg_resources._vendor.packaging.tags._normalize_string().
Referenced by pkg_resources._vendor.packaging.tags.platform_tags().
_mac_arch()
str pkg_resources._vendor.packaging.tags._mac_arch (str arch, bool is_32bit = _32_BIT_INTERPRETER) protected
Referenced by pkg_resources._vendor.packaging.tags.mac_platforms().
_mac_binary_formats()
List[str] pkg_resources._vendor.packaging.tags._mac_binary_formats (MacVersion version, str cpu_arch) protected
Referenced by pkg_resources._vendor.packaging.tags.mac_platforms().
_normalize_string()
str pkg_resources._vendor.packaging.tags._normalize_string (str string) protected
Referenced by pkg_resources._vendor.packaging.tags._generic_abi(), pkg_resources._vendor.packaging.tags._generic_platforms(), and pkg_resources._vendor.packaging.tags._linux_platforms().
_py_interpreter_range()
Iterator[str] pkg_resources._vendor.packaging.tags._py_interpreter_range (PythonVersion py_version) protected
Yields Python versions in descending order.
After the latest version, the major-only version will be yielded, and then
all previous versions of that major version.
Referenced by pkg_resources._vendor.packaging.tags.compatible_tags().
_version_nodot()
str pkg_resources._vendor.packaging.tags._version_nodot (PythonVersion version) protected
Referenced by pkg_resources._vendor.packaging.tags._cpython_abis(), pkg_resources._vendor.packaging.tags.cpython_tags(), and pkg_resources._vendor.packaging.tags.interpreter_version().
compatible_tags()
Iterator[Tag] pkg_resources._vendor.packaging.tags.compatible_tags (Optional[PythonVersion] python_version = None, Optional[str] interpreter = None, Optional[Iterable[str]] platforms = None)
Yields the sequence of tags that are compatible with a specific version of Python.
The tags consist of:
- py*-none-<platform>
- <interpreter>-none-any  # ... if `interpreter` is provided.
- py*-none-any
References pkg_resources._vendor.packaging.tags._py_interpreter_range(), and pkg_resources._vendor.packaging.tags.platform_tags().
cpython_tags()
Iterator[Tag] pkg_resources._vendor.packaging.tags.cpython_tags (Optional[PythonVersion] python_version = None, Optional[Iterable[str]] abis = None, Optional[Iterable[str]] platforms = None, * , bool warn = False)
Yields the tags for a CPython interpreter.
The tags consist of:
- cp<python_version>-<abi>-<platform>
- cp<python_version>-abi3-<platform>
- cp<python_version>-none-<platform>
- cp<less than python_version>-abi3-<platform>  # Older Python versions down to 3.2.
If python_version only specifies a major version then user-provided ABIs and
the 'none' ABItag will be used.
If 'abi3' or 'none' are specified in 'abis' then they will be yielded at
their normal position and not at the beginning.
References pkg_resources._vendor.packaging.tags._abi3_applies(), pkg_resources._vendor.packaging.tags._cpython_abis(), pkg_resources._vendor.packaging.tags._version_nodot(), and pkg_resources._vendor.packaging.tags.platform_tags().
generic_tags()
Iterator[Tag] pkg_resources._vendor.packaging.tags.generic_tags (Optional[str] interpreter = None, Optional[Iterable[str]] abis = None, Optional[Iterable[str]] platforms = None, * , bool warn = False)
Yields the tags for a generic interpreter.
The tags consist of:
- <interpreter>-<abi>-<platform>
The "none" ABI will be added if it was not explicitly provided.
References pkg_resources._vendor.packaging.tags._generic_abi(), and pkg_resources._vendor.packaging.tags.platform_tags().
interpreter_name()
str pkg_resources._vendor.packaging.tags.interpreter_name ()
Returns the name of the running interpreter.
interpreter_version()
str pkg_resources._vendor.packaging.tags.interpreter_version (* , bool warn = False)
Returns the version of the running interpreter.
References pkg_resources._vendor.packaging.tags._get_config_var(), and pkg_resources._vendor.packaging.tags._version_nodot().
mac_platforms()
Iterator[str] pkg_resources._vendor.packaging.tags.mac_platforms (Optional[MacVersion] version = None, Optional[str] arch = None)
Yields the platform tags for a macOS system.
The `version` parameter is a two-item tuple specifying the macOS version to
generate platform tags for. The `arch` parameter is the CPU architecture to
generate platform tags for. Both parameters default to the appropriate value
for the current system.
References pkg_resources._vendor.packaging.tags._mac_arch(), and pkg_resources._vendor.packaging.tags._mac_binary_formats().
parse_tag()
FrozenSet[Tag] pkg_resources._vendor.packaging.tags.parse_tag (str tag)
Parses the provided tag (e.g. `py3-none-any`) into a frozenset of Tag instances.
Returning a set is required due to the possibility that the tag is a
compressed tag set.
platform_tags()
Iterator[str] pkg_resources._vendor.packaging.tags.platform_tags ()
Provides the platform tags for this installation.
References pkg_resources._vendor.packaging.tags._generic_platforms(), and pkg_resources._vendor.packaging.tags._linux_platforms().
Referenced by pkg_resources._vendor.packaging.tags.compatible_tags(), pkg_resources._vendor.packaging.tags.cpython_tags(), and pkg_resources._vendor.packaging.tags.generic_tags().
sys_tags()
Iterator[Tag] pkg_resources._vendor.packaging.tags.sys_tags (* , bool warn = False)
Returns the sequence of tag triples for the running interpreter.
The order of the sequence corresponds to priority order for the
interpreter, from most to least important.
Variable Documentation
_32_BIT_INTERPRETER
int pkg_resources._vendor.packaging.tags._32_BIT_INTERPRETER = 2 ** 32 protected
INTERPRETER_SHORT_NAMES
dict pkg_resources._vendor.packaging.tags.INTERPRETER_SHORT_NAMES
Initial value:
=  {
    "python": "py",  # Generic.
    "cpython": "cp",
    "pypy": "pp",
    "ironpython": "ip",
    "jython": "jy",
}
logger
pkg_resources._vendor.packaging.tags.logger = logging.getLogger(__name__)
MacVersion
pkg_resources._vendor.packaging.tags.MacVersion = Tuple[int, int]
PythonVersion
pkg_resources._vendor.packaging.tags.PythonVersion = Sequence[int]