Django Project: pycparser.ply.lex Namespace Reference
pycparser.ply.lex Namespace Reference
Classes
class Lexer
class LexerReflect
class LexError
class LexToken
class NullLogger
class PlyLogger
Functions
_get_regex (func)
get_caller_module_dict (levels)
_funcs_to_names (funclist, namelist)
_names_to_funcs (namelist, fdict)
_form_master_re (relist, reflags, ldict, toknames)
_statetoken (s, names)
lex (module=None, object=None, debug=False, optimize=False, lextab='lextab', reflags=int(re.VERBOSE), nowarn=False, outputdir=None, debuglog=None, errorlog=None)
runmain (lexer=None, data=None)
TOKEN (r)
Variables
tuple StringTypes = (types.StringType, types.UnicodeType)
_is_identifier = re.compile(r'^[a-zA-Z0-9_]+$')
Token = TOKEN
Function Documentation
_form_master_re()
pycparser.ply.lex._form_master_re (relist, reflags, ldict, toknames) protected
References pycparser.ply.lex._form_master_re().
Referenced by pycparser.ply.lex._form_master_re(), and pycparser.ply.lex.lex().
_funcs_to_names()
pycparser.ply.lex._funcs_to_names (funclist, namelist) protected
Referenced by pycparser.ply.lex.Lexer.writetab().
_get_regex()
pycparser.ply.lex._get_regex (func) protected
Referenced by pycparser.ply.lex.lex(), pycparser.ply.lex.TOKEN(), and pycparser.ply.lex.LexerReflect.validate_rules().
_names_to_funcs()
pycparser.ply.lex._names_to_funcs (namelist, fdict) protected
_statetoken()
pycparser.ply.lex._statetoken (s, names) protected
get_caller_module_dict()
pycparser.ply.lex.get_caller_module_dict (levels)
Referenced by pycparser.ply.lex.lex().
lex()
pycparser.ply.lex.lex (module = None, object = None, debug = False, optimize = False, lextab = 'lextab', reflags = int(re.VERBOSE), nowarn = False, outputdir = None, debuglog = None, errorlog = None)
References pycparser.ply.lex._form_master_re(), pycparser.ply.lex._get_regex(), and pycparser.ply.lex.get_caller_module_dict().
runmain()
pycparser.ply.lex.runmain (lexer = None, data = None)
TOKEN()
pycparser.ply.lex.TOKEN (r)
References pycparser.ply.lex._get_regex().
Variable Documentation
_is_identifier
pycparser.ply.lex._is_identifier = re.compile(r'^[a-zA-Z0-9_]+$') protected
StringTypes
tuple pycparser.ply.lex.StringTypes = (types.StringType, types.UnicodeType)
Token
pycparser.ply.lex.Token = TOKEN