Django Project: setuptools.msvc Namespace Reference
setuptools.msvc Namespace Reference
Classes
class EnvironmentInfo
class PlatformInfo
class RegistryInfo
class SystemInfo
class winreg
Functions
_msvc14_find_vc2015 ()
_msvc14_find_vc2017 ()
_msvc14_find_vcvarsall (plat_spec)
_msvc14_get_vc_env (plat_spec)
msvc14_get_vc_env (plat_spec)
msvc14_gen_lib_options (*args, **kwargs)
_augment_exception (exc, version, arch='')
Variables
environ
dict PLAT_SPEC_TO_RUNTIME
Detailed Description
Improved support for Microsoft Visual C++ compilers.
Known supported compilers:
--------------------------
Microsoft Visual C++ 14.X:
    Microsoft Visual C++ Build Tools 2015 (x86, x64, arm)
    Microsoft Visual Studio Build Tools 2017 (x86, x64, arm, arm64)
    Microsoft Visual Studio Build Tools 2019 (x86, x64, arm, arm64)
This may also support compilers shipped with compatible Visual Studio versions.
Function Documentation
_augment_exception()
setuptools.msvc._augment_exception (exc, version, arch = '') protected
Add details to the exception message to help guide the user
as to what action will resolve it.
Referenced by setuptools.msvc.msvc14_get_vc_env().
_msvc14_find_vc2015()
setuptools.msvc._msvc14_find_vc2015 () protected
Python 3.8 "distutils/_msvccompiler.py" backport
Referenced by setuptools.msvc._msvc14_find_vcvarsall().
_msvc14_find_vc2017()
setuptools.msvc._msvc14_find_vc2017 () protected
Python 3.8 "distutils/_msvccompiler.py" backport
Returns "15, path" based on the result of invoking vswhere.exe
If no install is found, returns "None, None"
The version is returned to avoid unnecessarily changing the function
result. It may be ignored when the path is not None.
If vswhere.exe is not available, by definition, VS 2017 is not
installed.
Referenced by setuptools.msvc._msvc14_find_vcvarsall().
_msvc14_find_vcvarsall()
setuptools.msvc._msvc14_find_vcvarsall (plat_spec) protected
Python 3.8 "distutils/_msvccompiler.py" backport
References setuptools.msvc._msvc14_find_vc2015(), and setuptools.msvc._msvc14_find_vc2017().
Referenced by setuptools.msvc._msvc14_get_vc_env().
_msvc14_get_vc_env()
setuptools.msvc._msvc14_get_vc_env (plat_spec) protected
Python 3.8 "distutils/_msvccompiler.py" backport
References setuptools.msvc._msvc14_find_vcvarsall().
Referenced by setuptools.msvc.msvc14_get_vc_env().
msvc14_gen_lib_options()
setuptools.msvc.msvc14_gen_lib_options (* args, ** kwargs)
Patched "distutils._msvccompiler.gen_lib_options" for fix
compatibility between "numpy.distutils" and "distutils._msvccompiler"
(for Numpy < 1.11.2)
msvc14_get_vc_env()
setuptools.msvc.msvc14_get_vc_env (plat_spec)
Patched "distutils._msvccompiler._get_vc_env" for support extra
Microsoft Visual C++ 14.X compilers.
Set environment without use of "vcvarsall.bat".
Parameters
----------
plat_spec: str
    Target architecture.
Return
------
dict
    environment
References setuptools.msvc._augment_exception(), and setuptools.msvc._msvc14_get_vc_env().
Variable Documentation
environ
setuptools.msvc.environ
PLAT_SPEC_TO_RUNTIME
dict setuptools.msvc.PLAT_SPEC_TO_RUNTIME
Initial value:
=  {
    'x86': 'x86',
    'x86_amd64': 'x64',
    'x86_arm': 'arm',
    'x86_arm64': 'arm64'
}