Django Project: setuptools._vendor.typing_extensions Namespace Reference
setuptools._vendor.typing_extensions Namespace Reference
Classes
class _AnnotatedAlias
class _ConcatenateAliasBase
class _ConcatenateAliasMeta
class _ConcatenateForm
class _ConcatenateGenericAlias
class _ExtensionsGenericMeta
class _ExtensionsSpecialForm
class _Final
class _FinalForm
class _Immutable
class _Literal
class _LiteralForm
class _MaybeRequired
class _NoReturn
class _NotRequired
class _ProtocolMeta
class _Required
class _RequiredForm
class _Self
class _SpecialForm
class _TypeAliasBase
class _TypeAliasForm
class _TypeAliasMeta
class _TypedDictMeta
class _TypeGuard
class _TypeGuardForm
class Annotated
class AnnotatedMeta
class AsyncContextManager
class AsyncGenerator
class ChainMap
class Counter
class Deque
class OrderedDict
class ParamSpec
class ParamSpecArgs
class ParamSpecKwargs
class Protocol
class SupportsIndex
Functions
_no_slots_copy (dct)
_check_generic (cls, parameters)
final (f)
IntVar (name)
_gorg (cls)
_get_protocol_attrs (cls)
_is_callable_members_only (cls)
_no_init (self, *args, **kwargs)
runtime_checkable (cls)
_check_fails (cls, other)
_dict_new (*args, **kwargs)
_typeddict_new (*args, total=True, **kwargs)
_strip_annotations (t)
get_type_hints (obj, globalns=None, localns=None, include_extras=False)
_is_dunder (name)
get_origin (tp)
get_args (tp)
TypeAlias (self, parameters)
_concatenate_getitem (self, parameters)
Concatenate (self, parameters)
TypeGuard (self, parameters)
Self (self, params)
Required (self, parameters)
NotRequired (self, parameters)
Variables
tuple PEP_560 = (3, 7, 0)
GenericMeta = type
NoReturn = typing.NoReturn
_root
T = typing.TypeVar('T')
KT = typing.TypeVar('KT')
VT = typing.TypeVar('VT')
T_co = typing.TypeVar('T_co', covariant=True)
T_contra = typing.TypeVar('T_contra', contravariant=True)
ClassVar = typing.ClassVar
Final = typing.Final
doc
final = typing.final
Literal = typing.Literal
_overload_dummy = typing._overload_dummy
overload = typing.overload
Type = typing.Type
Awaitable = typing.Awaitable
Coroutine = typing.Coroutine
AsyncIterable = typing.AsyncIterable
AsyncIterator = typing.AsyncIterator
Deque = typing.Deque
ContextManager = typing.ContextManager
AsyncContextManager = typing.AsyncContextManager
DefaultDict = typing.DefaultDict
OrderedDict = typing.OrderedDict
Counter = typing.Counter
ChainMap = typing.ChainMap
AsyncGenerator = typing.AsyncGenerator
NewType = typing.NewType
Text = typing.Text
TYPE_CHECKING = typing.TYPE_CHECKING
list _PROTO_WHITELIST
Protocol = typing.Protocol
runtime_checkable = typing.runtime_checkable
runtime = runtime_checkable
SupportsIndex = typing.SupportsIndex
TypedDict = typing.TypedDict
Annotated = typing.Annotated
get_type_hints = typing.get_type_hints
_AnnotatedAlias = typing._AnnotatedAlias
get_origin = typing.get_origin
get_args = typing.get_args
_BaseGenericAlias = typing._GenericAlias
GenericAlias = typing._GenericAlias
TypeAlias = typing.TypeAlias
ParamSpecArgs = typing.ParamSpecArgs
ParamSpecKwargs = typing.ParamSpecKwargs
ParamSpec = typing.ParamSpec
Concatenate = typing.Concatenate
_ConcatenateGenericAlias = typing._ConcatenateGenericAlias
TypeGuard = typing.TypeGuard
Self = typing.Self
Required = typing.Required
NotRequired = typing.NotRequired
_is_protocol
_is_runtime_protocol
Function Documentation
_check_fails()
setuptools._vendor.typing_extensions._check_fails (cls, other) protected
_check_generic()
setuptools._vendor.typing_extensions._check_generic (cls, parameters) protected
Referenced by setuptools._vendor.typing_extensions.Protocol.__class_getitem__(), and setuptools._vendor.typing_extensions._ProtocolMeta.__getitem__().
_concatenate_getitem()
setuptools._vendor.typing_extensions._concatenate_getitem (self, parameters) protected
Referenced by setuptools._vendor.typing_extensions._ConcatenateAliasBase.__getitem__(), setuptools._vendor.typing_extensions._ConcatenateForm.__getitem__(), and setuptools._vendor.typing_extensions.Concatenate().
_dict_new()
setuptools._vendor.typing_extensions._dict_new (* args, ** kwargs) protected
_get_protocol_attrs()
setuptools._vendor.typing_extensions._get_protocol_attrs (cls) protected
Referenced by setuptools._vendor.typing_extensions._ProtocolMeta.__init__(), setuptools._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.typing_extensions._ProtocolMeta.__instancecheck__(), and setuptools._vendor.typing_extensions._is_callable_members_only().
_gorg()
setuptools._vendor.typing_extensions._gorg (cls) protected
This function exists for compatibility with old typing versions.
Referenced by setuptools._vendor.typing_extensions._ProtocolMeta.__getitem__(), setuptools._vendor.typing_extensions._ProtocolMeta.__new__(), and setuptools._vendor.typing_extensions.Protocol.__new__().
_is_callable_members_only()
setuptools._vendor.typing_extensions._is_callable_members_only (cls) protected
References setuptools._vendor.typing_extensions._get_protocol_attrs().
Referenced by setuptools._vendor.typing_extensions.Protocol.__init_subclass__(), setuptools._vendor.typing_extensions._ProtocolMeta.__instancecheck__(), setuptools._vendor.typing_extensions._ProtocolMeta.__instancecheck__(), and setuptools._vendor.typing_extensions._ProtocolMeta.__subclasscheck__().
_is_dunder()
setuptools._vendor.typing_extensions._is_dunder (name) protected
Returns True if name is a __dunder_variable_name__.
Referenced by setuptools._vendor.typing_extensions.AnnotatedMeta.__getattr__(), and setuptools._vendor.typing_extensions.AnnotatedMeta.__setattr__().
_no_init()
setuptools._vendor.typing_extensions._no_init (self, * args, ** kwargs) protected
_no_slots_copy()
setuptools._vendor.typing_extensions._no_slots_copy (dct) protected
Referenced by setuptools._vendor.typing_extensions._ProtocolMeta.__getitem__(), and setuptools._vendor.typing_extensions.AnnotatedMeta.__getitem__().
_strip_annotations()
setuptools._vendor.typing_extensions._strip_annotations (t) protected
Strips the annotations from a given type.
References setuptools._vendor.typing_extensions._strip_annotations().
Referenced by setuptools._vendor.typing_extensions._strip_annotations(), and setuptools._vendor.typing_extensions.get_type_hints().
_typeddict_new()
setuptools._vendor.typing_extensions._typeddict_new (* args, total = True, ** kwargs) protected
Concatenate()
setuptools._vendor.typing_extensions.Concatenate (self, parameters)
Used in conjunction with ``ParamSpec`` and ``Callable`` to represent a
higher order function which adds, removes or transforms parameters of a
callable.
For example::
   Callable[Concatenate[int, P], int]
See PEP 612 for detailed information.
References setuptools._vendor.typing_extensions._concatenate_getitem().
final()
setuptools._vendor.typing_extensions.final (f)
This decorator can be used to indicate to type checkers that
the decorated method cannot be overridden, and decorated class
cannot be subclassed. For example:
    class Base:
        @final
        def done(self) -> None:
            ...
    class Sub(Base):
        def done(self) -> None:  # Error reported by type checker
            ...
    @final
    class Leaf:
        ...
    class Other(Leaf):  # Error reported by type checker
        ...
There is no runtime checking of these properties.
get_args()
setuptools._vendor.typing_extensions.get_args (tp)
Get type arguments with all substitutions performed.
For unions, basic simplifications used by Union constructor are performed.
Examples::
    get_args(Dict[str, int]) == (str, int)
    get_args(int) == ()
    get_args(Union[int, Union[T, int], str][int]) == (int, str)
    get_args(Union[int, Tuple[T, int]][str]) == (int, Tuple[str, int])
    get_args(Callable[[], T][int]) == ([], int)
References setuptools._vendor.typing_extensions.get_origin.
get_origin()
setuptools._vendor.typing_extensions.get_origin (tp)
Get the unsubscripted version of a type.
This supports generic types, Callable, Tuple, Union, Literal, Final, ClassVar
and Annotated. Return None for unsupported types. Examples::
    get_origin(Literal[42]) is Literal
    get_origin(int) is None
    get_origin(ClassVar[int]) is ClassVar
    get_origin(Generic) is Generic
    get_origin(Generic[T]) is Generic
    get_origin(Union[T, int]) is Union
    get_origin(List[Tuple[T, T]][int]) == list
    get_origin(P.args) is P
get_type_hints()
setuptools._vendor.typing_extensions.get_type_hints (obj, globalns = None, localns = None, include_extras = False)
Return type hints for an object.
This is often the same as obj.__annotations__, but it handles
forward references encoded as string literals, adds Optional[t] if a
default value equal to None is set and recursively replaces all
'Annotated[T, ...]' with 'T' (unless 'include_extras=True').
The argument may be a module, class, method, or function. The annotations
are returned as a dictionary. For classes, annotations include also
inherited members.
TypeError is raised if the argument is not of a type that can contain
annotations, and an empty dictionary is returned if no annotations are
present.
BEWARE -- the behavior of globalns and localns is counterintuitive
(unless you are familiar with how eval() and exec() work).  The
search order is locals first, then globals.
- If no dict arguments are passed, an attempt is made to use the
  globals from obj (or the respective module's globals for classes),
  and these are also used as the locals.  If the object does not appear
  to have globals, an empty dictionary is used.
- If one dict argument is passed, it is used for both globals and
  locals.
- If two dict arguments are passed, they specify globals and
  locals, respectively.
References setuptools._vendor.typing_extensions._strip_annotations().
IntVar()
setuptools._vendor.typing_extensions.IntVar (name)
NotRequired()
setuptools._vendor.typing_extensions.NotRequired (self, parameters)
A special typing construct to mark a key of a TypedDict as
potentially missing. For example:
    class Movie(TypedDict):
        title: str
        year: NotRequired[int]
    m = Movie(
        title='The Matrix',  # typechecker error if key is omitted
        year=1999,
    )
Required()
setuptools._vendor.typing_extensions.Required (self, parameters)
A special typing construct to mark a key of a total=False TypedDict
as required. For example:
    class Movie(TypedDict, total=False):
        title: Required[str]
        year: int
    m = Movie(
        title='The Matrix',  # typechecker error if key is omitted
        year=1999,
    )
There is no runtime checking that a required key is actually provided
when instantiating a related TypedDict.
runtime_checkable()
setuptools._vendor.typing_extensions.runtime_checkable (cls)
Mark a protocol class as a runtime protocol, so that it
can be used with isinstance() and issubclass(). Raise TypeError
if applied to a non-protocol class.
This allows a simple-minded structural check very similar to the
one-offs in collections.abc such as Hashable.
Self()
setuptools._vendor.typing_extensions.Self (self, params)
Used to spell the type of "self" in classes.
Example::
  from typing import Self
  class ReturnsSelf:
      def parse(self, data: bytes) -> Self:
          ...
          return self
TypeAlias()
setuptools._vendor.typing_extensions.TypeAlias (self, parameters)
Special marker indicating that an assignment should
be recognized as a proper type alias definition by type
checkers.
For example::
    Predicate: TypeAlias = Callable[..., bool]
It's invalid when used anywhere except as in the example above.
TypeGuard()
setuptools._vendor.typing_extensions.TypeGuard (self, parameters)
Special typing form used to annotate the return type of a user-defined
type guard function.  ``TypeGuard`` only accepts a single type argument.
At runtime, functions marked this way should return a boolean.
``TypeGuard`` aims to benefit *type narrowing* -- a technique used by static
type checkers to determine a more precise type of an expression within a
program's code flow.  Usually type narrowing is done by analyzing
conditional code flow and applying the narrowing to a block of code.  The
conditional expression here is sometimes referred to as a "type guard".
Sometimes it would be convenient to use a user-defined boolean function
as a type guard.  Such a function should use ``TypeGuard[...]`` as its
return type to alert static type checkers to this intention.
Using  ``-> TypeGuard`` tells the static type checker that for a given
function:
1. The return value is a boolean.
2. If the return value is ``True``, the type of its argument
is the type inside ``TypeGuard``.
For example::
    def is_str(val: Union[str, float]):
        # "isinstance" type guard
        if isinstance(val, str):
            # Type of ``val`` is narrowed to ``str``
            ...
        else:
            # Else, type of ``val`` is narrowed to ``float``.
            ...
Strict type narrowing is not enforced -- ``TypeB`` need not be a narrower
form of ``TypeA`` (it can even be a wider form) and this may lead to
type-unsafe results.  The main reason is to allow for things like
narrowing ``List[object]`` to ``List[str]`` even though the latter is not
a subtype of the former, since ``List`` is invariant.  The responsibility of
writing type-safe type guards is left to the user.
``TypeGuard`` also works with type variables.  For more information, see
PEP 647 (User-Defined Type Guards).
Variable Documentation
_AnnotatedAlias
setuptools._vendor.typing_extensions._AnnotatedAlias = typing._AnnotatedAlias protected
_BaseGenericAlias
setuptools._vendor.typing_extensions._BaseGenericAlias = typing._GenericAlias protected
_ConcatenateGenericAlias
setuptools._vendor.typing_extensions._ConcatenateGenericAlias = typing._ConcatenateGenericAlias protected
_is_protocol
setuptools._vendor.typing_extensions._is_protocol protected
_is_runtime_protocol
setuptools._vendor.typing_extensions._is_runtime_protocol protected
_overload_dummy
setuptools._vendor.typing_extensions._overload_dummy = typing._overload_dummy protected
_PROTO_WHITELIST
list setuptools._vendor.typing_extensions._PROTO_WHITELIST protected
Initial value:
=  ['Callable', 'Awaitable',
                    'Iterable', 'Iterator', 'AsyncIterable', 'AsyncIterator',
                    'Hashable', 'Sized', 'Container', 'Collection', 'Reversible',
                    'ContextManager', 'AsyncContextManager']
_root
setuptools._vendor.typing_extensions._root protected
Annotated
setuptools._vendor.typing_extensions.Annotated = typing.Annotated
AsyncContextManager
setuptools._vendor.typing_extensions.AsyncContextManager = typing.AsyncContextManager
AsyncGenerator
setuptools._vendor.typing_extensions.AsyncGenerator = typing.AsyncGenerator
AsyncIterable
setuptools._vendor.typing_extensions.AsyncIterable = typing.AsyncIterable
AsyncIterator
setuptools._vendor.typing_extensions.AsyncIterator = typing.AsyncIterator
Awaitable
setuptools._vendor.typing_extensions.Awaitable = typing.Awaitable
ChainMap
setuptools._vendor.typing_extensions.ChainMap = typing.ChainMap
ClassVar
setuptools._vendor.typing_extensions.ClassVar = typing.ClassVar
Concatenate
setuptools._vendor.typing_extensions.Concatenate = typing.Concatenate
ContextManager
setuptools._vendor.typing_extensions.ContextManager = typing.ContextManager
Coroutine
setuptools._vendor.typing_extensions.Coroutine = typing.Coroutine
Counter
setuptools._vendor.typing_extensions.Counter = typing.Counter
DefaultDict
setuptools._vendor.typing_extensions.DefaultDict = typing.DefaultDict
Deque
setuptools._vendor.typing_extensions.Deque = typing.Deque
doc
setuptools._vendor.typing_extensions.doc
Final
setuptools._vendor.typing_extensions.Final = typing.Final
final
setuptools._vendor.typing_extensions.final = typing.final
GenericAlias
setuptools._vendor.typing_extensions.GenericAlias = typing._GenericAlias
GenericMeta
setuptools._vendor.typing_extensions.GenericMeta = type
get_args
setuptools._vendor.typing_extensions.get_args = typing.get_args
get_origin
setuptools._vendor.typing_extensions.get_origin = typing.get_origin
Referenced by setuptools._vendor.typing_extensions.get_args().
get_type_hints
setuptools._vendor.typing_extensions.get_type_hints = typing.get_type_hints
KT
setuptools._vendor.typing_extensions.KT = typing.TypeVar('KT')
Literal
setuptools._vendor.typing_extensions.Literal = typing.Literal
NewType
setuptools._vendor.typing_extensions.NewType = typing.NewType
NoReturn
setuptools._vendor.typing_extensions.NoReturn = typing.NoReturn
NotRequired
setuptools._vendor.typing_extensions.NotRequired = typing.NotRequired
OrderedDict
setuptools._vendor.typing_extensions.OrderedDict = typing.OrderedDict
overload
setuptools._vendor.typing_extensions.overload = typing.overload
ParamSpec
setuptools._vendor.typing_extensions.ParamSpec = typing.ParamSpec
ParamSpecArgs
setuptools._vendor.typing_extensions.ParamSpecArgs = typing.ParamSpecArgs
ParamSpecKwargs
setuptools._vendor.typing_extensions.ParamSpecKwargs = typing.ParamSpecKwargs
PEP_560
tuple setuptools._vendor.typing_extensions.PEP_560 = (3, 7, 0)
Protocol
setuptools._vendor.typing_extensions.Protocol = typing.Protocol
Required
setuptools._vendor.typing_extensions.Required = typing.Required
runtime
setuptools._vendor.typing_extensions.runtime = runtime_checkable
runtime_checkable
setuptools._vendor.typing_extensions.runtime_checkable = typing.runtime_checkable
Self
setuptools._vendor.typing_extensions.Self = typing.Self
SupportsIndex
setuptools._vendor.typing_extensions.SupportsIndex = typing.SupportsIndex
T
setuptools._vendor.typing_extensions.T = typing.TypeVar('T')
T_co
setuptools._vendor.typing_extensions.T_co = typing.TypeVar('T_co', covariant=True)
T_contra
setuptools._vendor.typing_extensions.T_contra = typing.TypeVar('T_contra', contravariant=True)
Text
setuptools._vendor.typing_extensions.Text = typing.Text
Type
setuptools._vendor.typing_extensions.Type = typing.Type
TYPE_CHECKING
setuptools._vendor.typing_extensions.TYPE_CHECKING = typing.TYPE_CHECKING
TypeAlias
setuptools._vendor.typing_extensions.TypeAlias = typing.TypeAlias
TypedDict
setuptools._vendor.typing_extensions.TypedDict = typing.TypedDict
TypeGuard
setuptools._vendor.typing_extensions.TypeGuard = typing.TypeGuard
VT
setuptools._vendor.typing_extensions.VT = typing.TypeVar('VT')