Django Project: pkg_resources._vendor.packaging.specifiers Namespace Reference
pkg_resources._vendor.packaging.specifiers Namespace Reference
Classes
class _IndividualSpecifier
class BaseSpecifier
class InvalidSpecifier
class LegacySpecifier
class Specifier
class SpecifierSet
Functions
Callable[["Specifier", ParsedVersion, str], bool] _require_version_compare (Callable[["Specifier", ParsedVersion, str], bool] fn)
List[str] _version_split (str version)
bool _is_not_suffix (str segment)
Tuple[List[str], List[str]] _pad_version (List[str] left, List[str] right)
Variables
ParsedVersion = Union[Version, LegacyVersion]
UnparsedVersion = Union[Version, LegacyVersion, str]
VersionTypeVar = TypeVar("VersionTypeVar", bound=UnparsedVersion)
CallableOperator = Callable[[ParsedVersion, str], bool]
_prefix_regex = re.compile(r"^([0-9]+)((?:a|b|c|rc)[0-9]+)$")
Function Documentation
_is_not_suffix()
bool pkg_resources._vendor.packaging.specifiers._is_not_suffix (str segment) protected
_pad_version()
Tuple[List[str], List[str]] pkg_resources._vendor.packaging.specifiers._pad_version (List[str] left, List[str] right) protected
Referenced by pkg_resources._vendor.packaging.specifiers.Specifier._compare_equal().
_require_version_compare()
Callable[["Specifier", ParsedVersion, str], bool] pkg_resources._vendor.packaging.specifiers._require_version_compare (Callable[["Specifier", ParsedVersion, str], bool] fn) protected
_version_split()
List[str] pkg_resources._vendor.packaging.specifiers._version_split (str version) protected
Referenced by pkg_resources._vendor.packaging.specifiers.Specifier._compare_compatible(), and pkg_resources._vendor.packaging.specifiers.Specifier._compare_equal().
Variable Documentation
_prefix_regex
pkg_resources._vendor.packaging.specifiers._prefix_regex = re.compile(r"^([0-9]+)((?:a|b|c|rc)[0-9]+)$") protected
CallableOperator
pkg_resources._vendor.packaging.specifiers.CallableOperator = Callable[[ParsedVersion, str], bool]
ParsedVersion
pkg_resources._vendor.packaging.specifiers.ParsedVersion = Union[Version, LegacyVersion]
UnparsedVersion
pkg_resources._vendor.packaging.specifiers.UnparsedVersion = Union[Version, LegacyVersion, str]
VersionTypeVar
pkg_resources._vendor.packaging.specifiers.VersionTypeVar = TypeVar("VersionTypeVar", bound=UnparsedVersion)