Django Project: setuptools._distutils.msvccompiler Namespace Reference
setuptools._distutils.msvccompiler Namespace Reference
Classes
class MacroExpander
class MSVCCompiler
Functions
read_keys (base, key)
read_values (base, key)
convert_mbcs (s)
get_build_version ()
get_build_architecture ()
normalize_and_reduce_paths (paths)
Variables
bool _can_read_reg = False
hkey_mod = winreg
RegOpenKeyEx = winreg.OpenKeyEx
RegEnumKey = winreg.EnumKey
RegEnumValue = winreg.EnumValue
RegError = winreg.error
tuple HKEYS
OldMSVCCompiler = MSVCCompiler
Detailed Description
distutils.msvccompiler
Contains MSVCCompiler, an implementation of the abstract CCompiler class
for the Microsoft Visual Studio.
Function Documentation
convert_mbcs()
setuptools._distutils.msvccompiler.convert_mbcs (s)
Referenced by setuptools._distutils.msvccompiler.read_values().
get_build_architecture()
setuptools._distutils.msvccompiler.get_build_architecture ()
Return the processor architecture.
Possible results are "Intel" or "AMD64".
Referenced by setuptools._distutils.msvccompiler.MSVCCompiler.__init__().
get_build_version()
setuptools._distutils.msvccompiler.get_build_version ()
Return the version of MSVC that was used to build Python.
For Python 2.3 and up, the version number is included in
sys.version.  For earlier versions, assume the compiler is MSVC 6.
Referenced by setuptools._distutils.msvccompiler.MSVCCompiler.__init__(), and setuptools._distutils.msvccompiler.MSVCCompiler.set_path_env_var().
normalize_and_reduce_paths()
setuptools._distutils.msvccompiler.normalize_and_reduce_paths (paths)
Return a list of normalized paths with duplicates removed.
The current order of paths is maintained.
read_keys()
setuptools._distutils.msvccompiler.read_keys (base, key)
Return list of registry keys.
References setuptools._distutils.msvccompiler.RegEnumKey, and setuptools._distutils.msvccompiler.RegOpenKeyEx.
read_values()
setuptools._distutils.msvccompiler.read_values (base, key)
Return dict of registry keys and values.
All names are converted to lowercase.
References setuptools._distutils.msvccompiler.convert_mbcs(), setuptools._distutils.msvccompiler.RegEnumValue, and setuptools._distutils.msvccompiler.RegOpenKeyEx.
Referenced by setuptools._distutils.msvccompiler.MSVCCompiler.get_msvc_paths(), setuptools._distutils.msvccompiler.MacroExpander.load_macros(), and setuptools._distutils.msvccompiler.MacroExpander.set_macro().
Variable Documentation
_can_read_reg
bool setuptools._distutils.msvccompiler._can_read_reg = False protected
hkey_mod
setuptools._distutils.msvccompiler.hkey_mod = winreg
HKEYS
tuple setuptools._distutils.msvccompiler.HKEYS
Initial value:
=  (
        hkey_mod.HKEY_USERS,
        hkey_mod.HKEY_CURRENT_USER,
        hkey_mod.HKEY_LOCAL_MACHINE,
        hkey_mod.HKEY_CLASSES_ROOT,
    )
OldMSVCCompiler
setuptools._distutils.msvccompiler.OldMSVCCompiler = MSVCCompiler
RegEnumKey
setuptools._distutils.msvccompiler.RegEnumKey = winreg.EnumKey
Referenced by setuptools._distutils.msvccompiler.MacroExpander.load_macros(), and setuptools._distutils.msvccompiler.read_keys().
RegEnumValue
setuptools._distutils.msvccompiler.RegEnumValue = winreg.EnumValue
Referenced by setuptools._distutils.msvccompiler.read_values().
RegError
setuptools._distutils.msvccompiler.RegError = winreg.error
RegOpenKeyEx
setuptools._distutils.msvccompiler.RegOpenKeyEx = winreg.OpenKeyEx
Referenced by setuptools._distutils.msvccompiler.MacroExpander.load_macros(), setuptools._distutils.msvccompiler.read_keys(), and setuptools._distutils.msvccompiler.read_values().