Django Project: setuptools.config.expand Namespace Reference
setuptools.config.expand Namespace Reference
Classes
class EnsurePackagesDiscovered
class LazyMappingProxy
class StaticModule
Functions
List[str] glob_relative (Iterable[str] patterns, Optional[_Path] root_dir=None)
str read_files (Union[str, bytes, Iterable[_Path]] filepaths, root_dir=None)
Iterator[_Path] _filter_existing_files (Iterable[_Path] filepaths)
str _read_file (Union[bytes, _Path] filepath)
_assert_local (_Path filepath, str root_dir)
read_attr (str attr_desc, Optional[Mapping[str, str]] package_dir=None, Optional[_Path] root_dir=None)
ModuleSpec _find_spec (str module_name, Optional[_Path] module_path)
ModuleType _load_spec (ModuleSpec spec, str module_name)
Tuple[_Path, Optional[str], str] _find_module (str module_name, Optional[Mapping[str, str]] package_dir, _Path root_dir)
Callable resolve_class (str qualified_class_name, Optional[Mapping[str, str]] package_dir=None, Optional[_Path] root_dir=None)
Dict[str, Callable] cmdclass (Dict[str, str] values, Optional[Mapping[str, str]] package_dir=None, Optional[_Path] root_dir=None)
List[str] find_packages (*, namespaces=True, Optional[Dict[str, str]] fill_package_dir=None, Optional[_Path] root_dir=None, **kwargs)
str _nest_path (_Path parent, _Path path)
str version (Union[Callable, Iterable[Union[str, int]], str] value)
dict canonic_package_data (dict package_data)
List[Tuple[str, List[str]]] canonic_data_files (Union[list, dict] data_files, Optional[_Path] root_dir=None)
Dict[str, dict] entry_points (str text, text_source="entry-points")
Variables
chain_iter = chain.from_iterable
_Path = Union[str, os.PathLike]
_K = TypeVar("_K")
_V = TypeVar("_V", covariant=True)
Detailed Description
Utility functions to expand configuration directives or special values
(such glob patterns).
We can split the process of interpreting configuration files into 2 steps:
1. The parsing the file contents from strings to value objects
   that can be understand by Python (for example a string with a comma
   separated list of keywords into an actual Python list of strings).
2. The expansion (or post-processing) of these values according to the
   semantics ``setuptools`` assign to them (for example a configuration field
   with the ``file:`` directive should be expanded from a list of file paths to
   a single string with the contents of those files concatenated)
This module focus on the second step, and therefore allow sharing the expansion
functions among several configuration file formats.
**PRIVATE MODULE**: API reserved for setuptools internal usage only.
Function Documentation
_assert_local()
setuptools.config.expand._assert_local (_Path filepath, str root_dir) protected
Referenced by setuptools.config.expand.read_files().
_filter_existing_files()
Iterator[_Path] setuptools.config.expand._filter_existing_files (Iterable[_Path] filepaths) protected
Referenced by setuptools.config.expand.read_files().
_find_module()
Tuple[_Path, Optional[str], str] setuptools.config.expand._find_module (str module_name, Optional[Mapping[str, str]] package_dir, _Path root_dir) protected
Given a module (that could normally be imported by ``module_name``
after the build is complete), find the path to the parent directory where
it is contained and the canonical name that could be used to import it
considering the ``package_dir`` in the build configuration and ``root_dir``
Referenced by setuptools.config.expand.read_attr(), and setuptools.config.expand.resolve_class().
_find_spec()
ModuleSpec setuptools.config.expand._find_spec (str module_name, Optional[_Path] module_path) protected
Referenced by setuptools.config.expand.read_attr(), and setuptools.config.expand.resolve_class().
_load_spec()
ModuleType setuptools.config.expand._load_spec (ModuleSpec spec, str module_name) protected
Referenced by setuptools.config.expand.read_attr(), and setuptools.config.expand.resolve_class().
_nest_path()
str setuptools.config.expand._nest_path (_Path parent, _Path path) protected
Referenced by setuptools.config.expand.find_packages().
_read_file()
str setuptools.config.expand._read_file (Union[bytes, _Path] filepath) protected
Referenced by setuptools.config.expand.read_files().
canonic_data_files()
List[Tuple[str, List[str]]] setuptools.config.expand.canonic_data_files (Union[list, dict] data_files, Optional[_Path] root_dir = None)
For compatibility with ``setup.py``, ``data_files`` should be a list
of pairs instead of a dict.
This function also expands glob patterns.
References setuptools.config.expand.glob_relative().
canonic_package_data()
dict setuptools.config.expand.canonic_package_data (dict package_data)
cmdclass()
Dict[str, Callable] setuptools.config.expand.cmdclass (Dict[str, str] values, Optional[Mapping[str, str]] package_dir = None, Optional[_Path] root_dir = None)
Given a dictionary mapping command names to strings for qualified class
names, apply :func:`resolve_class` to the dict values.
References setuptools.config.expand.resolve_class().
entry_points()
Dict[str, dict] setuptools.config.expand.entry_points (str text, text_source = "entry-points")
Given the contents of entry-points file,
process it into a 2-level dictionary (``dict[str, dict[str, str]]``).
The first level keys are entry-point groups, the second level keys are
entry-point names, and the second level values are references to objects
(that correspond to the entry-point value).
find_packages()
List[str] setuptools.config.expand.find_packages (* , namespaces = True, Optional[Dict[str, str]] fill_package_dir = None, Optional[_Path] root_dir = None, ** kwargs)
Works similarly to :func:`setuptools.find_packages`, but with all
arguments given as keyword arguments. Moreover, ``where`` can be given
as a list (the results will be simply concatenated).
When the additional keyword argument ``namespaces`` is ``True``, it will
behave like :func:`setuptools.find_namespace_packages`` (i.e. include
implicit namespaces as per :pep:`420`).
The ``where`` argument will be considered relative to ``root_dir`` (or the current
working directory when ``root_dir`` is not given).
If the ``fill_package_dir`` argument is passed, this function will consider it as a
similar data structure to the ``package_dir`` configuration parameter add fill-in
any missing package location.
:rtype: list
References setuptools.config.expand._nest_path().
glob_relative()
List[str] setuptools.config.expand.glob_relative (Iterable[str] patterns, Optional[_Path] root_dir = None)
Expand the list of glob patterns, but preserving relative paths.
:param list[str] patterns: List of glob patterns
:param str root_dir: Path to which globs should be relative
                     (current directory by default)
:rtype: list
Referenced by setuptools.config.expand.canonic_data_files().
read_attr()
setuptools.config.expand.read_attr (str attr_desc, Optional[Mapping[str, str]] package_dir = None, Optional[_Path] root_dir = None)
Reads the value of an attribute from a module.
This function will try to read the attributed statically first
(via :func:`ast.literal_eval`), and only evaluate the module if it fails.
Examples:
    read_attr("package.attr")
    read_attr("package.module.attr")
:param str attr_desc: Dot-separated string describing how to reach the
    attribute (see examples above)
:param dict[str, str] package_dir: Mapping of package names to their
    location in disk (represented by paths relative to ``root_dir``).
:param str root_dir: Path to directory containing all the packages in
    ``package_dir`` (current directory by default).
:rtype: str
References setuptools.config.expand._find_module(), setuptools.config.expand._find_spec(), and setuptools.config.expand._load_spec().
read_files()
str setuptools.config.expand.read_files (Union[str, bytes, Iterable[_Path]] filepaths, root_dir = None)
Return the content of the files concatenated using ``\n`` as str
This function is sandboxed and won't reach anything outside ``root_dir``
(By default ``root_dir`` is the current directory).
References setuptools.config.expand._assert_local(), setuptools.config.expand._filter_existing_files(), and setuptools.config.expand._read_file().
resolve_class()
Callable setuptools.config.expand.resolve_class (str qualified_class_name, Optional[Mapping[str, str]] package_dir = None, Optional[_Path] root_dir = None)
Given a qualified class name, return the associated class object
References setuptools.config.expand._find_module(), setuptools.config.expand._find_spec(), and setuptools.config.expand._load_spec().
Referenced by setuptools.config.expand.cmdclass().
version()
str setuptools.config.expand.version (Union[Callable, Iterable[Union[str, int]], str] value)
When getting the version directly from an attribute,
it should be normalised to string.
Variable Documentation
_K
setuptools.config.expand._K = TypeVar("_K") protected
_Path
setuptools.config.expand._Path = Union[str, os.PathLike] protected
_V
setuptools.config.expand._V = TypeVar("_V", covariant=True) protected
chain_iter
setuptools.config.expand.chain_iter = chain.from_iterable