Django Project: pkg_resources._vendor.importlib_resources._common Namespace Reference
pkg_resources._vendor.importlib_resources._common Namespace Reference
Functions
files (package)
get_resource_reader (package)
resolve (cand)
get_package (package)
from_package (package)
_tempfile (reader, suffix='')
as_file (path)
_ (path)
Variables
Package = Union[types.ModuleType, str]
Function Documentation
_()
pkg_resources._vendor.importlib_resources._common._ (path) protected
Degenerate behavior for pathlib.Path objects.
_tempfile()
pkg_resources._vendor.importlib_resources._common._tempfile (reader, suffix = '') protected
Referenced by pkg_resources._vendor.importlib_resources._common.as_file().
as_file()
pkg_resources._vendor.importlib_resources._common.as_file (path)
Given a Traversable object, return that object as a
path on the local file system in a context manager.
References pkg_resources._vendor.importlib_resources._common._tempfile().
files()
pkg_resources._vendor.importlib_resources._common.files (package)
Get a Traversable resource from a package
References pkg_resources._vendor.importlib_resources._common.from_package(), and pkg_resources._vendor.importlib_resources._common.get_package().
from_package()
pkg_resources._vendor.importlib_resources._common.from_package (package)
Return a Traversable object for the given package.
Referenced by pkg_resources._vendor.importlib_resources._common.files().
get_package()
pkg_resources._vendor.importlib_resources._common.get_package (package)
Take a package name or module object and return the module.
Raise an exception if the resolved module is not a package.
Referenced by pkg_resources._vendor.importlib_resources._common.files().
get_resource_reader()
pkg_resources._vendor.importlib_resources._common.get_resource_reader (package)
Return the package's loader if it's a ResourceReader.
resolve()
pkg_resources._vendor.importlib_resources._common.resolve (cand)
Variable Documentation
Package
pkg_resources._vendor.importlib_resources._common.Package = Union[types.ModuleType, str]