Django Project: setuptools._distutils.sysconfig Namespace Reference
setuptools._distutils.sysconfig Namespace Reference
Functions
_is_python_source_dir (d)
_is_parent (dir_a, dir_b)
_fix_pcbuild (d)
_python_build ()
get_python_version ()
get_python_inc (plat_specific=0, prefix=None)
_get_python_inc_posix (prefix, spec_prefix, plat_specific)
_get_python_inc_posix_python (plat_specific)
_get_python_inc_from_config (plat_specific, spec_prefix)
_get_python_inc_posix_prefix (prefix)
_get_python_inc_nt (prefix, spec_prefix, plat_specific)
_posix_lib (standard_lib, libpython, early_prefix, prefix)
get_python_lib (plat_specific=0, standard_lib=0, prefix=None)
customize_compiler (compiler)
get_config_h_filename ()
get_makefile_filename ()
parse_config_h (fp, g=None)
parse_makefile (fn, g=None)
expand_makefile_vars (s, vars)
get_config_vars (*args)
get_config_var (name)
Variables
str IS_PYPY = '__pypy__' in sys.builtin_module_names
PREFIX = os.path.normpath(sys.prefix)
EXEC_PREFIX = os.path.normpath(sys.exec_prefix)
BASE_PREFIX = os.path.normpath(sys.base_prefix)
BASE_EXEC_PREFIX = os.path.normpath(sys.base_exec_prefix)
project_base = os.path.abspath(os.environ["_PYTHON_PROJECT_BASE"])
_sys_home = getattr(sys, '_home', None)
python_build = _python_build()
str build_flags = ''
_variable_rx = re.compile(r"([a-zA-Z][a-zA-Z0-9_]+)\s*=\s*(.*)")
_findvar1_rx = re.compile(r"\$\(([A-Za-z][A-Za-z0-9_]*)\‍)")
_findvar2_rx = re.compile(r"\${([A-Za-z][A-Za-z0-9_]*)}")
_config_vars = None
Detailed Description
Provide access to Python's configuration information.  The specific
configuration variables available depend heavily on the platform and
configuration.  The values may be retrieved using
get_config_var(name), and the list of variables is available via
get_config_vars().keys().  Additional convenience functions are also
available.
Written by:   Fred L. Drake, Jr.
Email:        <fdrake@acm.org>
Function Documentation
_fix_pcbuild()
setuptools._distutils.sysconfig._fix_pcbuild (d) protected
References setuptools._distutils.sysconfig._fix_pcbuild(), and setuptools._distutils.sysconfig._is_parent().
Referenced by setuptools._distutils.sysconfig._fix_pcbuild().
_get_python_inc_from_config()
setuptools._distutils.sysconfig._get_python_inc_from_config (plat_specific, spec_prefix) protected
If no prefix was explicitly specified, provide the include
directory from the config vars. Useful when
cross-compiling, since the config vars may come from
the host
platform Python installation, while the current Python
executable is from the build platform installation.
>>> monkeypatch = getfixture('monkeypatch')
>>> gpifc = _get_python_inc_from_config
>>> monkeypatch.setitem(gpifc.__globals__, 'get_config_var', str.lower)
>>> gpifc(False, '/usr/bin/')
>>> gpifc(False, '')
>>> gpifc(False, None)
'includepy'
>>> gpifc(True, None)
'confincludepy'
Referenced by setuptools._distutils.sysconfig._get_python_inc_posix().
_get_python_inc_nt()
setuptools._distutils.sysconfig._get_python_inc_nt (prefix, spec_prefix, plat_specific) protected
_get_python_inc_posix()
setuptools._distutils.sysconfig._get_python_inc_posix (prefix, spec_prefix, plat_specific) protected
References setuptools._distutils.sysconfig._get_python_inc_from_config(), setuptools._distutils.sysconfig._get_python_inc_posix_prefix(), and setuptools._distutils.sysconfig._get_python_inc_posix_python().
_get_python_inc_posix_prefix()
setuptools._distutils.sysconfig._get_python_inc_posix_prefix (prefix) protected
Referenced by setuptools._distutils.sysconfig._get_python_inc_posix().
_get_python_inc_posix_python()
setuptools._distutils.sysconfig._get_python_inc_posix_python (plat_specific) protected
Assume the executable is in the build directory. The
pyconfig.h file should be in the same directory. Since
the build directory may not be the source directory,
use "srcdir" from the makefile to find the "Include"
directory.
Referenced by setuptools._distutils.sysconfig._get_python_inc_posix().
_is_parent()
setuptools._distutils.sysconfig._is_parent (dir_a, dir_b) protected
Return True if a is a parent of b.
Referenced by setuptools._distutils.sysconfig._fix_pcbuild().
_is_python_source_dir()
setuptools._distutils.sysconfig._is_python_source_dir (d) protected
Return True if the target directory appears to point to an
un-installed Python.
Referenced by setuptools._distutils.sysconfig._python_build().
_posix_lib()
setuptools._distutils.sysconfig._posix_lib (standard_lib, libpython, early_prefix, prefix) protected
Referenced by setuptools._distutils.sysconfig.get_python_lib().
_python_build()
setuptools._distutils.sysconfig._python_build () protected
References setuptools._distutils.sysconfig._is_python_source_dir().
customize_compiler()
setuptools._distutils.sysconfig.customize_compiler (compiler)
Do any platform-specific customization of a CCompiler instance.
Mainly needed on Unix, so we can plug in the information that
varies across Unices and is stored in Python's Makefile.
expand_makefile_vars()
setuptools._distutils.sysconfig.expand_makefile_vars (s, vars)
Expand Makefile-style variables -- "${foo}" or "$(foo)" -- in
'string' according to 'vars' (a dictionary mapping variable names to
values).  Variables not present in 'vars' are silently expanded to the
empty string.  The variable values in 'vars' should not contain further
variable expansions; if 'vars' is the output of 'parse_makefile()',
you're fine.  Returns a variable-expanded version of 's'.
get_config_h_filename()
setuptools._distutils.sysconfig.get_config_h_filename ()
Return full pathname of installed pyconfig.h file.
get_config_var()
setuptools._distutils.sysconfig.get_config_var (name)
Return the value of a single variable using the dictionary
returned by 'get_config_vars()'.  Equivalent to
get_config_vars().get(name)
get_config_vars()
setuptools._distutils.sysconfig.get_config_vars (* args)
With no arguments, return a dictionary of all configuration
variables relevant for the current platform.  Generally this includes
everything needed to build extensions and install both pure modules and
extensions.  On Unix, this means every variable defined in Python's
installed Makefile; on Windows it's a much smaller set.
With arguments, return a list of values that result from looking up
each argument in the configuration variable dictionary.
get_makefile_filename()
setuptools._distutils.sysconfig.get_makefile_filename ()
Return full pathname of installed Makefile from the Python build.
get_python_inc()
setuptools._distutils.sysconfig.get_python_inc (plat_specific = 0, prefix = None)
Return the directory containing installed Python header files.
If 'plat_specific' is false (the default), this is the path to the
non-platform-specific header files, i.e. Python.h and so on;
otherwise, this is the path to platform-specific header files
(namely pyconfig.h).
If 'prefix' is supplied, use it instead of sys.base_prefix or
sys.base_exec_prefix -- i.e., ignore 'plat_specific'.
get_python_lib()
setuptools._distutils.sysconfig.get_python_lib (plat_specific = 0, standard_lib = 0, prefix = None)
Return the directory containing the Python library (standard or
site additions).
If 'plat_specific' is true, return the directory containing
platform-specific modules, i.e. any module from a non-pure-Python
module distribution; otherwise, return the platform-shared library
directory.  If 'standard_lib' is true, return the directory
containing standard Python library modules; otherwise, return the
directory for site-specific modules.
If 'prefix' is supplied, use it instead of sys.base_prefix or
sys.base_exec_prefix -- i.e., ignore 'plat_specific'.
References setuptools._distutils.sysconfig._posix_lib().
get_python_version()
setuptools._distutils.sysconfig.get_python_version ()
Return a string containing the major and minor Python version,
leaving off the patchlevel.  Sample return values could be '1.5'
or '2.2'.
parse_config_h()
setuptools._distutils.sysconfig.parse_config_h (fp, g = None)
Parse a config.h-style file.
A dictionary containing name/value pairs is returned.  If an
optional dictionary is passed in as the second argument, it is
used instead of a new dictionary.
parse_makefile()
setuptools._distutils.sysconfig.parse_makefile (fn, g = None)
Parse a Makefile-style file.
A dictionary containing name/value pairs is returned.  If an
optional dictionary is passed in as the second argument, it is
used instead of a new dictionary.
Variable Documentation
_config_vars
setuptools._distutils.sysconfig._config_vars = None protected
_findvar1_rx
setuptools._distutils.sysconfig._findvar1_rx = re.compile(r"\$\(([A-Za-z][A-Za-z0-9_]*)\‍)") protected
_findvar2_rx
setuptools._distutils.sysconfig._findvar2_rx = re.compile(r"\${([A-Za-z][A-Za-z0-9_]*)}") protected
_sys_home
setuptools._distutils.sysconfig._sys_home = getattr(sys, '_home', None) protected
_variable_rx
setuptools._distutils.sysconfig._variable_rx = re.compile(r"([a-zA-Z][a-zA-Z0-9_]+)\s*=\s*(.*)") protected
BASE_EXEC_PREFIX
setuptools._distutils.sysconfig.BASE_EXEC_PREFIX = os.path.normpath(sys.base_exec_prefix)
BASE_PREFIX
setuptools._distutils.sysconfig.BASE_PREFIX = os.path.normpath(sys.base_prefix)
build_flags
setuptools._distutils.sysconfig.build_flags = ''
EXEC_PREFIX
setuptools._distutils.sysconfig.EXEC_PREFIX = os.path.normpath(sys.exec_prefix)
IS_PYPY
str setuptools._distutils.sysconfig.IS_PYPY = '__pypy__' in sys.builtin_module_names
PREFIX
setuptools._distutils.sysconfig.PREFIX = os.path.normpath(sys.prefix)
project_base
setuptools._distutils.sysconfig.project_base = os.path.abspath(os.environ["_PYTHON_PROJECT_BASE"])
python_build
setuptools._distutils.sysconfig.python_build = _python_build()