Django Project: waitress.utilities Namespace Reference
waitress.utilities Namespace Reference
Classes
class BadRequest
class Error
class InternalServerError
class RequestEntityTooLarge
class RequestHeaderFieldsTooLarge
class ServerNotImplemented
Functions
find_double_newline (s)
concat (*args)
join (seq, field=" ")
group (s)
unpack_rfc822 (m)
unpack_rfc850 (m)
build_http_date (when)
parse_http_date (d)
undquote (value)
cleanup_unix_socket (path)
Variables
logger = logging.getLogger("waitress")
queue_logger = logging.getLogger("waitress.queue")
list short_days = ["sun", "mon", "tue", "wed", "thu", "fri", "sat"]
list long_days
short_day_reg = group(join(short_days, "|"))
long_day_reg = group(join(long_days, "|"))
dict daymap = {}
hms_reg = join(3 * [group("[0-9][0-9]")], ":")
list months
dict monmap = {}
months_reg = group(join(months, "|"))
rfc822_date
rfc822_reg = re.compile(rfc822_date)
rfc850_date
rfc850_reg = re.compile(rfc850_date)
list weekdayname = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
list monthname
Function Documentation
build_http_date()
waitress.utilities.build_http_date (when)
cleanup_unix_socket()
waitress.utilities.cleanup_unix_socket (path)
concat()
waitress.utilities.concat (* args)
find_double_newline()
waitress.utilities.find_double_newline (s)
Returns the position just after a double newline in the given string.
group()
waitress.utilities.group (s)
join()
waitress.utilities.join (seq, field = " ")
parse_http_date()
waitress.utilities.parse_http_date (d)
References waitress.utilities.unpack_rfc822(), and waitress.utilities.unpack_rfc850().
undquote()
waitress.utilities.undquote (value)
unpack_rfc822()
waitress.utilities.unpack_rfc822 (m)
Referenced by waitress.utilities.parse_http_date().
unpack_rfc850()
waitress.utilities.unpack_rfc850 (m)
Referenced by waitress.utilities.parse_http_date().
Variable Documentation
daymap
dict waitress.utilities.daymap = {}
hms_reg
waitress.utilities.hms_reg = join(3 * [group("[0-9][0-9]")], ":")
logger
waitress.utilities.logger = logging.getLogger("waitress")
long_day_reg
waitress.utilities.long_day_reg = group(join(long_days, "|"))
long_days
list waitress.utilities.long_days
Initial value:
=  [
    "sunday",
    "monday",
    "tuesday",
    "wednesday",
    "thursday",
    "friday",
    "saturday",
]
monmap
dict waitress.utilities.monmap = {}
monthname
list waitress.utilities.monthname
Initial value:
=  [
    None,
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
]
months
list waitress.utilities.months
Initial value:
=  [
    "jan",
    "feb",
    "mar",
    "apr",
    "may",
    "jun",
    "jul",
    "aug",
    "sep",
    "oct",
    "nov",
    "dec",
]
months_reg
waitress.utilities.months_reg = group(join(months, "|"))
queue_logger
waitress.utilities.queue_logger = logging.getLogger("waitress.queue")
rfc822_date
waitress.utilities.rfc822_date
Initial value:
=  join(
    [
        concat(short_day_reg, ","),  # day
        group("[0-9][0-9]?"),  # date
        months_reg,  # month
        group("[0-9]+"),  # year
        hms_reg,  # hour minute second
        "gmt",
    ],
    " ",
)
rfc822_reg
waitress.utilities.rfc822_reg = re.compile(rfc822_date)
rfc850_date
waitress.utilities.rfc850_date
Initial value:
=  join(
    [
        concat(long_day_reg, ","),
        join([group("[0-9][0-9]?"), months_reg, group("[0-9]+")], "-"),
        hms_reg,
        "gmt",
    ],
    " ",
)
rfc850_reg
waitress.utilities.rfc850_reg = re.compile(rfc850_date)
short_day_reg
waitress.utilities.short_day_reg = group(join(short_days, "|"))
short_days
list waitress.utilities.short_days = ["sun", "mon", "tue", "wed", "thu", "fri", "sat"]
weekdayname
list waitress.utilities.weekdayname = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]