Django Project: setuptools.monkey Namespace Reference
setuptools.monkey Namespace Reference
Functions
_get_mro (cls)
get_unpatched (item)
get_unpatched_class (cls)
patch_all ()
_patch_distribution_metadata ()
patch_func (replacement, target_mod, func_name)
get_unpatched_function (candidate)
patch_for_msvc_specialized_compiler ()
Detailed Description
Monkey patching of distutils.
Function Documentation
_get_mro()
setuptools.monkey._get_mro (cls) protected
Returns the bases classes for cls sorted by the MRO.
Works around an issue on Jython where inspect.getmro will not return all
base classes if multiple classes share the same name. Instead, this
function will return a tuple containing the class itself, and the contents
of cls.__bases__. See https://github.com/pypa/setuptools/issues/1024.
Referenced by setuptools.monkey.get_unpatched_class().
_patch_distribution_metadata()
setuptools.monkey._patch_distribution_metadata () protected
Patch write_pkg_file and read_pkg_file for higher metadata standards
Referenced by setuptools.monkey.patch_all().
get_unpatched()
setuptools.monkey.get_unpatched (item)
get_unpatched_class()
setuptools.monkey.get_unpatched_class (cls)
Protect against re-patching the distutils if reloaded
Also ensures that no other distutils extension monkeypatched the distutils
first.
References setuptools.monkey._get_mro().
get_unpatched_function()
setuptools.monkey.get_unpatched_function (candidate)
patch_all()
setuptools.monkey.patch_all ()
References setuptools.monkey._patch_distribution_metadata(), and setuptools.monkey.patch_for_msvc_specialized_compiler().
patch_for_msvc_specialized_compiler()
setuptools.monkey.patch_for_msvc_specialized_compiler ()
Patch functions in distutils to use standalone Microsoft Visual C++
compilers.
References setuptools.monkey.patch_func().
Referenced by setuptools.monkey.patch_all().
patch_func()
setuptools.monkey.patch_func (replacement, target_mod, func_name)
Patch func_name in target_mod with replacement
Important - original must be resolved by name to avoid
patching an already patched function.
Referenced by setuptools.monkey.patch_for_msvc_specialized_compiler().