Django Project: setuptools.config.setupcfg Namespace Reference
setuptools.config.setupcfg Namespace Reference
Classes
class ConfigHandler
class ConfigMetadataHandler
class ConfigOptionsHandler
Functions
dict read_configuration (_Path filepath, find_others=False, ignore_option_errors=False)
"Distribution" apply_configuration ("Distribution" dist, _Path filepath)
Tuple["ConfigHandler",...] _apply ("Distribution" dist, _Path filepath, Iterable[_Path] other_files=(), bool ignore_option_errors=False)
_get_option (Target target_obj, str key)
dict configuration_to_dict (Tuple["ConfigHandler",...] handlers)
Tuple["ConfigMetadataHandler", "ConfigOptionsHandler"] parse_configuration ("Distribution" distribution, AllCommandOptions command_options, ignore_option_errors=False)
_warn_accidental_env_marker_misconfig (str label, str orig_value, list parsed)
Variables
_Path = Union[str, os.PathLike]
SingleCommandOptions = Dict["str", Tuple["str", Any]]
AllCommandOptions = Dict["str", SingleCommandOptions]
Target = TypeVar("Target", bound=Union["Distribution", "DistributionMetadata"])
Detailed Description
Load setuptools configuration from ``setup.cfg`` files.
**API will be made private in the future**
Function Documentation
_apply()
Tuple["ConfigHandler", ...] setuptools.config.setupcfg._apply ("Distribution" dist, _Path filepath, Iterable[_Path] other_files = (), bool ignore_option_errors = False) protected
Read configuration from ``filepath`` and applies to the ``dist`` object.
References setuptools.config.parse_configuration.
Referenced by setuptools.config.setupcfg.apply_configuration(), and setuptools.config.setupcfg.read_configuration().
_get_option()
setuptools.config.setupcfg._get_option (Target target_obj, str key) protected
Given a target object and option key, get that option from
the target object, either through a get_{key} method or
from an attribute directly.
Referenced by setuptools.config.setupcfg.configuration_to_dict().
_warn_accidental_env_marker_misconfig()
setuptools.config.setupcfg._warn_accidental_env_marker_misconfig (str label, str orig_value, list parsed) protected
Because users sometimes misinterpret this configuration:
[options.extras_require]
foo = bar;python_version<"4"
It looks like one requirement with an environment marker
but because there is no newline, it's parsed as two requirements
with a semicolon as separator.
Therefore, if:
    * input string does not contain a newline AND
    * parsed result contains two requirements AND
    * parsing of the two parts from the result ("<first>;<second>")
    leads in a valid Requirement with a valid marker
a UserWarning is shown to inform the user about the possible problem.
Referenced by setuptools.config.setupcfg.ConfigOptionsHandler._parse_requirements_list().
apply_configuration()
"Distribution" setuptools.config.setupcfg.apply_configuration ("Distribution" dist, _Path filepath)
Apply the configuration from a ``setup.cfg`` file into an existing
distribution object.
References setuptools.config.setupcfg._apply().
configuration_to_dict()
dict setuptools.config.setupcfg.configuration_to_dict (Tuple["ConfigHandler", ...] handlers)
Returns configuration data gathered by given handlers as a dict.
:param list[ConfigHandler] handlers: Handlers list,
    usually from parse_configuration()
:rtype: dict
References setuptools.config.setupcfg._get_option().
Referenced by setuptools.config.setupcfg.read_configuration().
parse_configuration()
Tuple["ConfigMetadataHandler", "ConfigOptionsHandler"] setuptools.config.setupcfg.parse_configuration ("Distribution" distribution, AllCommandOptions command_options, ignore_option_errors = False)
Performs additional parsing of configuration options
for a distribution.
Returns a list of used option handlers.
:param Distribution distribution:
:param dict command_options:
:param bool ignore_option_errors: Whether to silently ignore
    options, values of which could not be resolved (e.g. due to exceptions
    in directives such as file:, attr:, etc.).
    If False exceptions are propagated as expected.
:rtype: list
read_configuration()
dict setuptools.config.setupcfg.read_configuration (_Path filepath, find_others = False, ignore_option_errors = False)
Read given configuration file and returns options from it as a dict.
:param str|unicode filepath: Path to configuration file
    to get options from.
:param bool find_others: Whether to search for other configuration files
    which could be on in various places.
:param bool ignore_option_errors: Whether to silently ignore
    options, values of which could not be resolved (e.g. due to exceptions
    in directives such as file:, attr:, etc.).
    If False exceptions are propagated as expected.
:rtype: dict
References setuptools.config.setupcfg._apply(), and setuptools.config.setupcfg.configuration_to_dict().
Variable Documentation
_Path
setuptools.config.setupcfg._Path = Union[str, os.PathLike] protected
AllCommandOptions
setuptools.config.setupcfg.AllCommandOptions = Dict["str", SingleCommandOptions]
SingleCommandOptions
setuptools.config.setupcfg.SingleCommandOptions = Dict["str", Tuple["str", Any]]
Target
setuptools.config.setupcfg.Target = TypeVar("Target", bound=Union["Distribution", "DistributionMetadata"])