Django Project: cryptography.hazmat.primitives.serialization.ssh Namespace Reference
cryptography.hazmat.primitives.serialization.ssh Namespace Reference
Classes
class _FragList
class _SSHCipher
class _SSHFormatDSA
class _SSHFormatECDSA
class _SSHFormatEd25519
class _SSHFormatRSA
class SSHCertificate
class SSHCertificateBuilder
class SSHCertificateType
Functions
bytes _bcrypt_kdf (bytes password, bytes salt, int desired_key_bytes, int rounds, bool ignore_few_rounds=False)
bytes _get_ssh_key_type (SSHPrivateKeyTypes|SSHPublicKeyTypes key)
bytes _ecdsa_key_type (ec.EllipticCurvePublicKey public_key)
bytes _ssh_pem_encode (bytes data, bytes prefix=_SK_START+b"\n", bytes suffix=_SK_END+b"\n")
None _check_block_size (bytes data, int block_len)
None _check_empty (bytes data)
Cipher[modes.CBC|modes.CTR|modes.GCM] _init_cipher (bytes ciphername, bytes|None password, bytes salt, int rounds)
tuple[int, memoryview] _get_u32 (memoryview data)
tuple[int, memoryview] _get_u64 (memoryview data)
tuple[memoryview, memoryview] _get_sshstr (memoryview data)
tuple[int, memoryview] _get_mpint (memoryview data)
bytes _to_mpint (int val)
_lookup_kformat (bytes key_type)
SSHPrivateKeyTypes load_ssh_private_key (bytes data, bytes|None password, typing.Any backend=None)
bytes _serialize_ssh_private_key (SSHPrivateKeyTypes private_key, bytes password, KeySerializationEncryption encryption_algorithm)
hashes.HashAlgorithm _get_ec_hash_alg (ec.EllipticCurve curve)
SSHCertificate|SSHPublicKeyTypes _load_ssh_public_identity (bytes data, _legacy_dsa_allowed=False)
SSHCertificate|SSHPublicKeyTypes load_ssh_public_identity (bytes data)
dict[bytes, bytes] _parse_exts_opts (memoryview exts_opts)
SSHPublicKeyTypes load_ssh_public_key (bytes data, typing.Any backend=None)
bytes serialize_ssh_public_key (SSHPublicKeyTypes public_key)
Variables
bool _bcrypt_supported = True
str _SSH_ED25519 = b"ssh-ed25519"
str _SSH_RSA = b"ssh-rsa"
str _SSH_DSA = b"ssh-dss"
str _ECDSA_NISTP256 = b"ecdsa-sha2-nistp256"
str _ECDSA_NISTP384 = b"ecdsa-sha2-nistp384"
str _ECDSA_NISTP521 = b"ecdsa-sha2-nistp521"
str _CERT_SUFFIX = b"-cert-v01@openssh.com"
str _SSH_RSA_SHA256 = b"rsa-sha2-256"
str _SSH_RSA_SHA512 = b"rsa-sha2-512"
_SSH_PUBKEY_RC = re.compile(rb"\A(\S+)[ \t]+(\S+)")
str _SK_MAGIC = b"openssh-key-v1\0"
str _SK_START = b"-----BEGIN OPENSSH PRIVATE KEY-----"
str _SK_END = b"-----END OPENSSH PRIVATE KEY-----"
str _BCRYPT = b"bcrypt"
str _NONE = b"none"
str _DEFAULT_CIPHER = b"aes256-ctr"
int _DEFAULT_ROUNDS = 16
_PEM_RC = re.compile(_SK_START + b"(.*?)" + _SK_END, re.DOTALL)
_PADDING = memoryview(bytearray(range(1, 1 + 16)))
dict _ECDSA_KEY_TYPE
dict _KEY_FORMATS
SSHPrivateKeyTypes
SSHPublicKeyTypes
SSHCertPublicKeyTypes
SSHCertPrivateKeyTypes
int _SSHKEY_CERT_MAX_PRINCIPALS = 256
Function Documentation
_bcrypt_kdf()
bytes cryptography.hazmat.primitives.serialization.ssh._bcrypt_kdf (bytes password, bytes salt, int desired_key_bytes, int rounds, bool ignore_few_rounds = False) protected
Referenced by cryptography.hazmat.primitives.serialization.ssh._init_cipher().
_check_block_size()
None cryptography.hazmat.primitives.serialization.ssh._check_block_size (bytes data, int block_len) protected
Require data to be full blocks
_check_empty()
None cryptography.hazmat.primitives.serialization.ssh._check_empty (bytes data) protected
All data should have been parsed.
_ecdsa_key_type()
bytes cryptography.hazmat.primitives.serialization.ssh._ecdsa_key_type (ec.EllipticCurvePublicKey public_key) protected
Return SSH key_type and curve_name for private key.
Referenced by cryptography.hazmat.primitives.serialization.ssh._get_ssh_key_type().
_get_ec_hash_alg()
hashes.HashAlgorithm cryptography.hazmat.primitives.serialization.ssh._get_ec_hash_alg (ec.EllipticCurve curve) protected
_get_mpint()
tuple[int, memoryview] cryptography.hazmat.primitives.serialization.ssh._get_mpint (memoryview data) protected
Big integer.
References cryptography.hazmat.primitives.serialization.ssh._get_sshstr().
Referenced by cryptography.hazmat.primitives.serialization.ssh._SSHFormatDSA.get_public(), cryptography.hazmat.primitives.serialization.ssh._SSHFormatRSA.get_public(), cryptography.hazmat.primitives.serialization.ssh._SSHFormatDSA.load_private(), cryptography.hazmat.primitives.serialization.ssh._SSHFormatECDSA.load_private(), and cryptography.hazmat.primitives.serialization.ssh._SSHFormatRSA.load_private().
_get_ssh_key_type()
bytes cryptography.hazmat.primitives.serialization.ssh._get_ssh_key_type (SSHPrivateKeyTypes | SSHPublicKeyTypes key) protected
References cryptography.hazmat.primitives.serialization.ssh._ecdsa_key_type().
_get_sshstr()
tuple[memoryview, memoryview] cryptography.hazmat.primitives.serialization.ssh._get_sshstr (memoryview data) protected
Bytes with u32 length prefix
References cryptography.hazmat.primitives.serialization.ssh._get_u32().
Referenced by cryptography.hazmat.primitives.serialization.ssh._get_mpint(), cryptography.hazmat.primitives.serialization.ssh._SSHFormatECDSA.get_public(), cryptography.hazmat.primitives.serialization.ssh._SSHFormatEd25519.get_public(), and cryptography.hazmat.primitives.serialization.ssh._SSHFormatEd25519.load_private().
_get_u32()
tuple[int, memoryview] cryptography.hazmat.primitives.serialization.ssh._get_u32 (memoryview data) protected
Uint32
Referenced by cryptography.hazmat.primitives.serialization.ssh._get_sshstr().
_get_u64()
tuple[int, memoryview] cryptography.hazmat.primitives.serialization.ssh._get_u64 (memoryview data) protected
Uint64
_init_cipher()
Cipher[modes.CBC | modes.CTR | modes.GCM] cryptography.hazmat.primitives.serialization.ssh._init_cipher (bytes ciphername, bytes | None password, bytes salt, int rounds) protected
Generate key + iv and return cipher.
References cryptography.hazmat.primitives.serialization.ssh._bcrypt_kdf().
_load_ssh_public_identity()
SSHCertificate | SSHPublicKeyTypes cryptography.hazmat.primitives.serialization.ssh._load_ssh_public_identity (bytes data, _legacy_dsa_allowed = False) protected
_lookup_kformat()
cryptography.hazmat.primitives.serialization.ssh._lookup_kformat (bytes key_type) protected
Return valid format or throw error
_parse_exts_opts()
dict[bytes, bytes] cryptography.hazmat.primitives.serialization.ssh._parse_exts_opts (memoryview exts_opts) protected
_serialize_ssh_private_key()
bytes cryptography.hazmat.primitives.serialization.ssh._serialize_ssh_private_key (SSHPrivateKeyTypes private_key, bytes password, KeySerializationEncryption encryption_algorithm) protected
Serialize private key with OpenSSH custom encoding.
_ssh_pem_encode()
bytes cryptography.hazmat.primitives.serialization.ssh._ssh_pem_encode (bytes data, bytes prefix = _SK_START + b"\n", bytes suffix = _SK_END + b"\n") protected
_to_mpint()
bytes cryptography.hazmat.primitives.serialization.ssh._to_mpint (int val) protected
Storage format for signed bigint.
Referenced by cryptography.hazmat.primitives.serialization.ssh._FragList.put_mpint().
load_ssh_private_key()
SSHPrivateKeyTypes cryptography.hazmat.primitives.serialization.ssh.load_ssh_private_key (bytes data, bytes | None password, typing.Any backend = None)
Load private key from OpenSSH custom encoding.
load_ssh_public_identity()
SSHCertificate | SSHPublicKeyTypes cryptography.hazmat.primitives.serialization.ssh.load_ssh_public_identity (bytes data)
load_ssh_public_key()
SSHPublicKeyTypes cryptography.hazmat.primitives.serialization.ssh.load_ssh_public_key (bytes data, typing.Any backend = None)
serialize_ssh_public_key()
bytes cryptography.hazmat.primitives.serialization.ssh.serialize_ssh_public_key (SSHPublicKeyTypes public_key)
One-line public key format for OpenSSH
Variable Documentation
_BCRYPT
str cryptography.hazmat.primitives.serialization.ssh._BCRYPT = b"bcrypt" protected
_bcrypt_supported
bool cryptography.hazmat.primitives.serialization.ssh._bcrypt_supported = True protected
_CERT_SUFFIX
str cryptography.hazmat.primitives.serialization.ssh._CERT_SUFFIX = b"-cert-v01@openssh.com" protected
_DEFAULT_CIPHER
str cryptography.hazmat.primitives.serialization.ssh._DEFAULT_CIPHER = b"aes256-ctr" protected
_DEFAULT_ROUNDS
int cryptography.hazmat.primitives.serialization.ssh._DEFAULT_ROUNDS = 16 protected
_ECDSA_KEY_TYPE
dict cryptography.hazmat.primitives.serialization.ssh._ECDSA_KEY_TYPE protected
Initial value:
=  {
    "secp256r1": _ECDSA_NISTP256,
    "secp384r1": _ECDSA_NISTP384,
    "secp521r1": _ECDSA_NISTP521,
}
_ECDSA_NISTP256
str cryptography.hazmat.primitives.serialization.ssh._ECDSA_NISTP256 = b"ecdsa-sha2-nistp256" protected
_ECDSA_NISTP384
str cryptography.hazmat.primitives.serialization.ssh._ECDSA_NISTP384 = b"ecdsa-sha2-nistp384" protected
_ECDSA_NISTP521
str cryptography.hazmat.primitives.serialization.ssh._ECDSA_NISTP521 = b"ecdsa-sha2-nistp521" protected
_KEY_FORMATS
dict cryptography.hazmat.primitives.serialization.ssh._KEY_FORMATS protected
Initial value:
=  {
    _SSH_RSA: _SSHFormatRSA(),
    _SSH_DSA: _SSHFormatDSA(),
    _SSH_ED25519: _SSHFormatEd25519(),
    _ECDSA_NISTP256: _SSHFormatECDSA(b"nistp256", ec.SECP256R1()),
    _ECDSA_NISTP384: _SSHFormatECDSA(b"nistp384", ec.SECP384R1()),
    _ECDSA_NISTP521: _SSHFormatECDSA(b"nistp521", ec.SECP521R1()),
}
_NONE
str cryptography.hazmat.primitives.serialization.ssh._NONE = b"none" protected
_PADDING
cryptography.hazmat.primitives.serialization.ssh._PADDING = memoryview(bytearray(range(1, 1 + 16))) protected
_PEM_RC
cryptography.hazmat.primitives.serialization.ssh._PEM_RC = re.compile(_SK_START + b"(.*?)" + _SK_END, re.DOTALL) protected
_SK_END
str cryptography.hazmat.primitives.serialization.ssh._SK_END = b"-----END OPENSSH PRIVATE KEY-----" protected
_SK_MAGIC
str cryptography.hazmat.primitives.serialization.ssh._SK_MAGIC = b"openssh-key-v1\0" protected
_SK_START
str cryptography.hazmat.primitives.serialization.ssh._SK_START = b"-----BEGIN OPENSSH PRIVATE KEY-----" protected
_SSH_DSA
str cryptography.hazmat.primitives.serialization.ssh._SSH_DSA = b"ssh-dss" protected
_SSH_ED25519
str cryptography.hazmat.primitives.serialization.ssh._SSH_ED25519 = b"ssh-ed25519" protected
_SSH_PUBKEY_RC
cryptography.hazmat.primitives.serialization.ssh._SSH_PUBKEY_RC = re.compile(rb"\A(\S+)[ \t]+(\S+)") protected
_SSH_RSA
str cryptography.hazmat.primitives.serialization.ssh._SSH_RSA = b"ssh-rsa" protected
_SSH_RSA_SHA256
str cryptography.hazmat.primitives.serialization.ssh._SSH_RSA_SHA256 = b"rsa-sha2-256" protected
_SSH_RSA_SHA512
str cryptography.hazmat.primitives.serialization.ssh._SSH_RSA_SHA512 = b"rsa-sha2-512" protected
_SSHKEY_CERT_MAX_PRINCIPALS
int cryptography.hazmat.primitives.serialization.ssh._SSHKEY_CERT_MAX_PRINCIPALS = 256 protected
SSHCertPrivateKeyTypes
cryptography.hazmat.primitives.serialization.ssh.SSHCertPrivateKeyTypes
Initial value:
=  typing.Union[
    ec.EllipticCurvePrivateKey,
    rsa.RSAPrivateKey,
    ed25519.Ed25519PrivateKey,
]
SSHCertPublicKeyTypes
cryptography.hazmat.primitives.serialization.ssh.SSHCertPublicKeyTypes
Initial value:
=  typing.Union[
    ec.EllipticCurvePublicKey,
    rsa.RSAPublicKey,
    ed25519.Ed25519PublicKey,
]
SSHPrivateKeyTypes
cryptography.hazmat.primitives.serialization.ssh.SSHPrivateKeyTypes
Initial value:
=  typing.Union[
    ec.EllipticCurvePrivateKey,
    rsa.RSAPrivateKey,
    dsa.DSAPrivateKey,
    ed25519.Ed25519PrivateKey,
]
SSHPublicKeyTypes
cryptography.hazmat.primitives.serialization.ssh.SSHPublicKeyTypes
Initial value:
=  typing.Union[
    ec.EllipticCurvePublicKey,
    rsa.RSAPublicKey,
    dsa.DSAPublicKey,
    ed25519.Ed25519PublicKey,
]