Django Project: setuptools.command.bdist_egg Namespace Reference
setuptools.command.bdist_egg Namespace Reference
Classes
class bdist_egg
Functions
_get_purelib ()
strip_module (filename)
sorted_walk (dir)
write_stub (resource, pyfile)
walk_egg (egg_dir)
analyze_egg (egg_dir, stubs)
write_safety_flag (egg_dir, safe)
scan_module (egg_dir, base, name, stubs)
iter_symbols (code)
can_scan ()
make_zipfile (zip_filename, base_dir, verbose=0, dry_run=0, compress=True, mode='w')
Variables
NATIVE_EXTENSIONS = dict.fromkeys('.dll .so .dylib .pyd'.split())
dict safety_flags
list INSTALL_DIRECTORY_ATTRS
Detailed Description
setuptools.command.bdist_egg
Build .egg distributions
Function Documentation
_get_purelib()
setuptools.command.bdist_egg._get_purelib () protected
Referenced by setuptools.command.bdist_egg.bdist_egg.do_install_data().
analyze_egg()
setuptools.command.bdist_egg.analyze_egg (egg_dir, stubs)
References setuptools.command.bdist_egg.can_scan(), setuptools.command.bdist_egg.scan_module(), and setuptools.command.bdist_egg.walk_egg().
Referenced by setuptools.command.bdist_egg.bdist_egg.zip_safe().
can_scan()
setuptools.command.bdist_egg.can_scan ()
Referenced by setuptools.command.bdist_egg.analyze_egg().
iter_symbols()
setuptools.command.bdist_egg.iter_symbols (code)
Yield names and strings used by `code` and its nested code objects
References setuptools.command.bdist_egg.iter_symbols().
Referenced by setuptools.command.bdist_egg.iter_symbols(), and setuptools.command.bdist_egg.scan_module().
make_zipfile()
setuptools.command.bdist_egg.make_zipfile (zip_filename, base_dir, verbose = 0, dry_run = 0, compress = True, mode = 'w')
Create a zip file from all the files under 'base_dir'.  The output
zip file will be named 'base_dir' + ".zip".  Uses either the "zipfile"
Python module (if available) or the InfoZIP "zip" utility (if installed
and found on the default search path).  If neither tool is available,
raises DistutilsExecError.  Returns the name of the output zip file.
References setuptools.command.bdist_egg.sorted_walk().
scan_module()
setuptools.command.bdist_egg.scan_module (egg_dir, base, name, stubs)
Check whether module possibly uses unsafe-for-zipfile stuff
References setuptools.command.bdist_egg.iter_symbols().
Referenced by setuptools.command.bdist_egg.analyze_egg().
sorted_walk()
setuptools.command.bdist_egg.sorted_walk (dir)
Do os.walk in a reproducible way,
independent of indeterministic filesystem readdir order
Referenced by setuptools.command.bdist_egg.bdist_egg.get_ext_outputs(), setuptools.command.bdist_egg.make_zipfile(), and setuptools.command.bdist_egg.walk_egg().
strip_module()
setuptools.command.bdist_egg.strip_module (filename)
walk_egg()
setuptools.command.bdist_egg.walk_egg (egg_dir)
Walk an unpacked egg's contents, skipping the metadata directory
References setuptools.command.bdist_egg.sorted_walk().
Referenced by setuptools.command.bdist_egg.analyze_egg(), and setuptools.command.bdist_egg.bdist_egg.zap_pyfiles().
write_safety_flag()
setuptools.command.bdist_egg.write_safety_flag (egg_dir, safe)
write_stub()
setuptools.command.bdist_egg.write_stub (resource, pyfile)
Variable Documentation
INSTALL_DIRECTORY_ATTRS
list setuptools.command.bdist_egg.INSTALL_DIRECTORY_ATTRS
Initial value:
=  [
    'install_lib', 'install_dir', 'install_data', 'install_base'
]
NATIVE_EXTENSIONS
setuptools.command.bdist_egg.NATIVE_EXTENSIONS = dict.fromkeys('.dll .so .dylib .pyd'.split())
safety_flags
dict setuptools.command.bdist_egg.safety_flags
Initial value:
=  {
    True: 'zip-safe',
    False: 'not-zip-safe',
}