Django Project: gunicorn.config Namespace Reference
gunicorn.config Namespace Reference
Classes
class AccessLog
class AccessLogFormat
class Backlog
class Bind
class CACerts
class CaptureOutput
class CasefoldHTTPMethod
class CertFile
class CertReqs
class Chdir
class ChildExit
class Ciphers
class Config
class ConfigCheck
class ConfigFile
class Daemon
class DefaultProcName
class DisableRedirectAccessToSyslog
class DogstatsdTags
class DoHandshakeOnConnect
class EnableStdioInheritance
class Env
class ErrorLog
class ForwardedAllowIPS
class GracefulTimeout
class Group
class HeaderMap
class Initgroups
class Keepalive
class KeyFile
class LimitRequestFields
class LimitRequestFieldSize
class LimitRequestLine
class LogConfig
class LogConfigDict
class LogConfigJson
class LoggerClass
class Loglevel
class MaxRequests
class MaxRequestsJitter
class NewSSLContext
class NumWorkersChanged
class OnExit
class OnReload
class OnStarting
class Paste
class PasteGlobalConf
class PermitUnconventionalHTTPMethod
class PermitUnconventionalHTTPVersion
class Pidfile
class Postfork
class PostRequest
class PostWorkerInit
class PreExec
class Prefork
class PreloadApp
class PreRequest
class PrintConfig
class Procname
class ProxyAllowFrom
class ProxyProtocol
class PythonPath
class Reload
class ReloadEngine
class ReloadExtraFiles
class ReusePort
class SecureSchemeHeader
class Sendfile
class Setting
class SettingMeta
class Spew
class SSLVersion
class StatsdHost
class StatsdPrefix
class StripHeaderSpaces
class SuppressRaggedEOFs
class Syslog
class SyslogFacility
class SyslogPrefix
class SyslogTo
class Timeout
class TmpUploadDir
class TolerateDangerousFraming
class Umask
class User
class WhenReady
class WorkerAbort
class WorkerClass
class WorkerConnections
class WorkerExit
class WorkerInt
class Workers
class WorkerThreads
class WorkerTmpDir
class WSGIApp
Functions
make_settings (ignore=None)
auto_int (_, x)
validate_bool (val)
validate_dict (val)
validate_pos_int (val)
validate_ssl_version (val)
validate_string (val)
validate_file_exists (val)
validate_list_string (val)
validate_list_of_existing_files (val)
validate_string_to_list (val)
validate_class (val)
validate_callable (arity)
validate_user (val)
validate_group (val)
validate_post_request (val)
validate_chdir (val)
validate_statsd_address (val)
validate_reload_engine (val)
get_default_config_file ()
validate_header_map_behaviour (val)
Variables
list KNOWN_SETTINGS = []
PLATFORM = sys.platform
Setting = SettingMeta('Setting', (Setting,), {})
Function Documentation
auto_int()
gunicorn.config.auto_int (_, x)
get_default_config_file()
gunicorn.config.get_default_config_file ()
make_settings()
gunicorn.config.make_settings (ignore = None)
validate_bool()
gunicorn.config.validate_bool (val)
validate_callable()
gunicorn.config.validate_callable (arity)
Referenced by gunicorn.config.validate_post_request().
validate_chdir()
gunicorn.config.validate_chdir (val)
References gunicorn.config.validate_string().
validate_class()
gunicorn.config.validate_class (val)
References gunicorn.config.validate_string().
validate_dict()
gunicorn.config.validate_dict (val)
validate_file_exists()
gunicorn.config.validate_file_exists (val)
Referenced by gunicorn.config.validate_list_of_existing_files().
validate_group()
gunicorn.config.validate_group (val)
validate_header_map_behaviour()
gunicorn.config.validate_header_map_behaviour (val)
validate_list_of_existing_files()
gunicorn.config.validate_list_of_existing_files (val)
References gunicorn.config.validate_file_exists(), and gunicorn.config.validate_list_string().
validate_list_string()
gunicorn.config.validate_list_string (val)
References gunicorn.config.validate_string().
Referenced by gunicorn.config.validate_list_of_existing_files().
validate_pos_int()
gunicorn.config.validate_pos_int (val)
validate_post_request()
gunicorn.config.validate_post_request (val)
References gunicorn.config.validate_callable().
validate_reload_engine()
gunicorn.config.validate_reload_engine (val)
validate_ssl_version()
gunicorn.config.validate_ssl_version (val)
validate_statsd_address()
gunicorn.config.validate_statsd_address (val)
References gunicorn.config.validate_string().
validate_string()
gunicorn.config.validate_string (val)
Referenced by gunicorn.config.validate_chdir(), gunicorn.config.validate_class(), gunicorn.config.validate_list_string(), gunicorn.config.validate_statsd_address(), and gunicorn.config.validate_string_to_list().
validate_string_to_list()
gunicorn.config.validate_string_to_list (val)
References gunicorn.config.validate_string().
validate_user()
gunicorn.config.validate_user (val)
Variable Documentation
KNOWN_SETTINGS
list gunicorn.config.KNOWN_SETTINGS = []
PLATFORM
gunicorn.config.PLATFORM = sys.platform
Setting
gunicorn.config.Setting = SettingMeta('Setting', (Setting,), {})