Django Project: packaging.metadata Namespace Reference
packaging.metadata Namespace Reference
Classes
class _Validator
class ExceptionGroup
class InvalidMetadata
class Metadata
class RawMetadata
Functions
list[str] _parse_keywords (str data)
dict[str, str] _parse_project_urls (list[str] data)
str _get_payload (email.message.Message msg, bytes|str source)
tuple[RawMetadata, dict[str, list[str]]] parse_email (bytes|str data)
Variables
T = typing.TypeVar("T")
ExceptionGroup
dict _STRING_FIELDS
dict _LIST_FIELDS
dict _DICT_FIELDS
dict _EMAIL_TO_RAW_MAPPING
dict _RAW_TO_EMAIL_MAPPING = {raw: email for email, raw in _EMAIL_TO_RAW_MAPPING.items()}
_NOT_FOUND = object()
list _VALID_METADATA_VERSIONS = ["1.0", "1.1", "1.2", "2.1", "2.2", "2.3"]
_MetadataVersion = Literal["1.0", "1.1", "1.2", "2.1", "2.2", "2.3"]
_REQUIRED_ATTRS = frozenset(["metadata_version", "name", "version"])
Function Documentation
_get_payload()
str packaging.metadata._get_payload (email.message.Message msg, bytes | str source) protected
Get the body of the message.
Referenced by packaging.metadata.parse_email().
_parse_keywords()
list[str] packaging.metadata._parse_keywords (str data) protected
Split a string of comma-separate keyboards into a list of keywords.
Referenced by packaging.metadata.parse_email().
_parse_project_urls()
dict[str, str] packaging.metadata._parse_project_urls (list[str] data) protected
Parse a list of label/URL string pairings separated by a comma.
Referenced by packaging.metadata.parse_email().
parse_email()
tuple[RawMetadata, dict[str, list[str]]] packaging.metadata.parse_email (bytes | str data)
Parse a distribution's metadata stored as email headers (e.g. from ``METADATA``).
This function returns a two-item tuple of dicts. The first dict is of
recognized fields from the core metadata specification. Fields that can be
parsed and translated into Python's built-in types are converted
appropriately. All other fields are left as-is. Fields that are allowed to
appear multiple times are stored as lists.
The second dict contains all other fields from the metadata. This includes
any unrecognized fields. It also includes any fields which are expected to
be parsed into a built-in type but were not formatted appropriately. Finally,
any fields that are expected to appear only once but are repeated are
included in this dict.
References packaging.metadata._get_payload(), packaging.metadata._parse_keywords(), and packaging.metadata._parse_project_urls().
Referenced by packaging.metadata.Metadata.from_email().
Variable Documentation
_DICT_FIELDS
dict packaging.metadata._DICT_FIELDS protected
Initial value:
=  {
    "project_urls",
}
_EMAIL_TO_RAW_MAPPING
dict packaging.metadata._EMAIL_TO_RAW_MAPPING protected
Initial value:
=  {
    "author": "author",
    "author-email": "author_email",
    "classifier": "classifiers",
    "description": "description",
    "description-content-type": "description_content_type",
    "download-url": "download_url",
    "dynamic": "dynamic",
    "home-page": "home_page",
    "keywords": "keywords",
    "license": "license",
    "maintainer": "maintainer",
    "maintainer-email": "maintainer_email",
    "metadata-version": "metadata_version",
    "name": "name",
    "obsoletes": "obsoletes",
    "obsoletes-dist": "obsoletes_dist",
    "platform": "platforms",
    "project-url": "project_urls",
    "provides": "provides",
    "provides-dist": "provides_dist",
    "provides-extra": "provides_extra",
    "requires": "requires",
    "requires-dist": "requires_dist",
    "requires-external": "requires_external",
    "requires-python": "requires_python",
    "summary": "summary",
    "supported-platform": "supported_platforms",
    "version": "version",
}
_LIST_FIELDS
dict packaging.metadata._LIST_FIELDS protected
Initial value:
=  {
    "classifiers",
    "dynamic",
    "obsoletes",
    "obsoletes_dist",
    "platforms",
    "provides",
    "provides_dist",
    "provides_extra",
    "requires",
    "requires_dist",
    "requires_external",
    "supported_platforms",
}
_MetadataVersion
packaging.metadata._MetadataVersion = Literal["1.0", "1.1", "1.2", "2.1", "2.2", "2.3"] protected
_NOT_FOUND
packaging.metadata._NOT_FOUND = object() protected
_RAW_TO_EMAIL_MAPPING
dict packaging.metadata._RAW_TO_EMAIL_MAPPING = {raw: email for email, raw in _EMAIL_TO_RAW_MAPPING.items()} protected
_REQUIRED_ATTRS
packaging.metadata._REQUIRED_ATTRS = frozenset(["metadata_version", "name", "version"]) protected
_STRING_FIELDS
dict packaging.metadata._STRING_FIELDS protected
Initial value:
=  {
    "author",
    "author_email",
    "description",
    "description_content_type",
    "download_url",
    "home_page",
    "license",
    "maintainer",
    "maintainer_email",
    "metadata_version",
    "name",
    "requires_python",
    "summary",
    "version",
}
_VALID_METADATA_VERSIONS
list packaging.metadata._VALID_METADATA_VERSIONS = ["1.0", "1.1", "1.2", "2.1", "2.2", "2.3"] protected
ExceptionGroup
packaging.metadata.ExceptionGroup
T
packaging.metadata.T = typing.TypeVar("T")