Django Project: setuptools.discovery Namespace Reference
setuptools.discovery Namespace Reference
Classes
class _Finder
class ConfigDiscovery
class FlatLayoutModuleFinder
class FlatLayoutPackageFinder
class ModuleFinder
class PackageFinder
class PEP420PackageFinder
Functions
bool _valid_name (_Path path)
List[str] _find_packages_within (str root_pkg, _Path pkg_dir)
List[str] remove_nested_packages (List[str] packages)
List[str] remove_stubs (List[str] packages)
Optional[str] find_parent_package (List[str] packages, Mapping[str, str] package_dir, _Path root_dir)
str find_package_path (str name, Mapping[str, str] package_dir, _Path root_dir)
Dict[str, str] construct_package_dir (List[str] packages, _Path package_path)
Variables
_Path = Union[str, os.PathLike]
_Filter = Callable[[str], bool]
StrIter = Iterator[str]
chain_iter = itertools.chain.from_iterable
Detailed Description
Automatic discovery of Python modules and packages (for inclusion in the
distribution) and other config values.
For the purposes of this module, the following nomenclature is used:
- "src-layout": a directory representing a Python project that contains a "src"
  folder. Everything under the "src" folder is meant to be included in the
  distribution when packaging the project. Example::
    .
    ├── tox.ini
    ├── pyproject.toml
    └── src/
        └── mypkg/
            ├── __init__.py
            ├── mymodule.py
            └── my_data_file.txt
- "flat-layout": a Python project that does not use "src-layout" but instead
  have a directory under the project root for each package::
    .
    ├── tox.ini
    ├── pyproject.toml
    └── mypkg/
        ├── __init__.py
        ├── mymodule.py
        └── my_data_file.txt
- "single-module": a project that contains a single Python script direct under
  the project root (no directory used)::
    .
    ├── tox.ini
    ├── pyproject.toml
    └── mymodule.py
Function Documentation
_find_packages_within()
List[str] setuptools.discovery._find_packages_within (str root_pkg, _Path pkg_dir) protected
Referenced by setuptools.discovery.ConfigDiscovery._analyse_explicit_layout().
_valid_name()
bool setuptools.discovery._valid_name (_Path path) protected
construct_package_dir()
Dict[str, str] setuptools.discovery.construct_package_dir (List[str] packages, _Path package_path)
References setuptools.discovery.remove_nested_packages().
find_package_path()
str setuptools.discovery.find_package_path (str name, Mapping[str, str] package_dir, _Path root_dir)
Given a package name, return the path where it should be found on
disk, considering the ``package_dir`` option.
>>> path = find_package_path("my.pkg", {"": "root/is/nested"}, ".")
>>> path.replace(os.sep, "/")
'./root/is/nested/my/pkg'
>>> path = find_package_path("my.pkg", {"my": "root/is/nested"}, ".")
>>> path.replace(os.sep, "/")
'./root/is/nested/pkg'
>>> path = find_package_path("my.pkg", {"my.pkg": "root/is/nested"}, ".")
>>> path.replace(os.sep, "/")
'./root/is/nested'
>>> path = find_package_path("other.pkg", {"my.pkg": "root/is/nested"}, ".")
>>> path.replace(os.sep, "/")
'./other/pkg'
find_parent_package()
Optional[str] setuptools.discovery.find_parent_package (List[str] packages, Mapping[str, str] package_dir, _Path root_dir)
Find the parent package that is not a namespace.
Referenced by setuptools.discovery.ConfigDiscovery._find_name_from_packages().
remove_nested_packages()
List[str] setuptools.discovery.remove_nested_packages (List[str] packages)
Remove nested packages from a list of packages.
>>> remove_nested_packages(["a", "a.b1", "a.b2", "a.b1.c1"])
['a']
>>> remove_nested_packages(["a", "b", "c.d", "c.d.e.f", "g.h", "a.a1"])
['a', 'b', 'c.d', 'g.h']
Referenced by setuptools.discovery.ConfigDiscovery._analyse_flat_packages(), and setuptools.discovery.construct_package_dir().
remove_stubs()
List[str] setuptools.discovery.remove_stubs (List[str] packages)
Remove type stubs (:pep:`561`) from a list of packages.
>>> remove_stubs(["a", "a.b", "a-stubs", "a-stubs.b.c", "b", "c-stubs"])
['a', 'a.b', 'b']
Referenced by setuptools.discovery.ConfigDiscovery._analyse_flat_packages(), and setuptools.discovery.ConfigDiscovery._find_name_from_packages().
Variable Documentation
_Filter
setuptools.discovery._Filter = Callable[[str], bool] protected
_Path
setuptools.discovery._Path = Union[str, os.PathLike] protected
chain_iter
setuptools.discovery.chain_iter = itertools.chain.from_iterable
Referenced by setuptools.discovery.ConfigDiscovery._analyse_explicit_layout().
StrIter
setuptools.discovery.StrIter = Iterator[str]