Django Project: django Namespace Reference
django Namespace Reference
Namespaces
namespace __main__
namespace apps
namespace conf
namespace contrib
namespace core
namespace db
namespace dispatch
namespace forms
namespace http
namespace middleware
namespace shortcuts
namespace template
namespace templatetags
namespace test
namespace urls
namespace utils
namespace views
Functions
setup (set_prefix=True)
Variables
tuple VERSION = (5, 0, 6, "final", 0)
Function Documentation
setup()
django.setup (set_prefix = True)
Configure the settings (this happens as a side effect of accessing the
first setting), configure logging and populate the app registry.
Set the thread-local urlresolvers script prefix if `set_prefix` is True.
Referenced by django.test.runner._init_worker(), pytest_django.plugin._setup_django(), django.core.management.ManagementUtility.execute(), django.core.asgi.get_asgi_application(), and django.core.wsgi.get_wsgi_application().
Variable Documentation
VERSION
tuple django.VERSION = (5, 0, 6, "final", 0)