Django Project: packaging.specifiers Namespace Reference
packaging.specifiers Namespace Reference
Classes
class BaseSpecifier
class InvalidSpecifier
class Specifier
class SpecifierSet
Functions
Version _coerce_version (UnparsedVersion version)
list[str] _version_split (str version)
str _version_join (list[str] components)
bool _is_not_suffix (str segment)
tuple[list[str], list[str]] _pad_version (list[str] left, list[str] right)
Variables
UnparsedVersion = Union[Version, str]
UnparsedVersionVar = TypeVar("UnparsedVersionVar", bound=UnparsedVersion)
CallableOperator = Callable[[Version, str], bool]
_prefix_regex = re.compile(r"^([0-9]+)((?:a|b|c|rc)[0-9]+)$")
Detailed Description
.. testsetup::
    from packaging.specifiers import Specifier, SpecifierSet, InvalidSpecifier
    from packaging.version import Version
Function Documentation
_coerce_version()
Version packaging.specifiers._coerce_version (UnparsedVersion version) protected
Referenced by packaging.specifiers.Specifier.contains(), packaging.specifiers.Specifier.filter(), and packaging.specifiers.SpecifierSet.filter().
_is_not_suffix()
bool packaging.specifiers._is_not_suffix (str segment) protected
_pad_version()
tuple[list[str], list[str]] packaging.specifiers._pad_version (list[str] left, list[str] right) protected
Referenced by packaging.specifiers.Specifier._compare_equal().
_version_join()
str packaging.specifiers._version_join (list[str] components) protected
Join split version components into a version string.
This function assumes the input came from :func:`_version_split`, where the
first component must be the epoch (either empty or numeric), and all other
components numeric.
Referenced by packaging.specifiers.Specifier._compare_compatible().
_version_split()
list[str] packaging.specifiers._version_split (str version) protected
Split version into components.
The split components are intended for version comparison. The logic does
not attempt to retain the original version string, so joining the
components back with :func:`_version_join` may not produce the original
version string.
Referenced by packaging.specifiers.Specifier._compare_compatible(), and packaging.specifiers.Specifier._compare_equal().
Variable Documentation
_prefix_regex
packaging.specifiers._prefix_regex = re.compile(r"^([0-9]+)((?:a|b|c|rc)[0-9]+)$") protected
CallableOperator
packaging.specifiers.CallableOperator = Callable[[Version, str], bool]
UnparsedVersion
packaging.specifiers.UnparsedVersion = Union[Version, str]
UnparsedVersionVar
packaging.specifiers.UnparsedVersionVar = TypeVar("UnparsedVersionVar", bound=UnparsedVersion)