Django Project: pip._vendor.typing_extensions Namespace Reference
pip._vendor.typing_extensions Namespace Reference
Classes
class _AnnotatedAlias
class _AnyMeta
class _ConcatenateForm
class _ConcatenateGenericAlias
class _DefaultMixin
class _ExtensionsSpecialForm
class _FinalForm
class _Immutable
class _LiteralForm
class _LiteralGenericAlias
class _NamedTupleMeta
class _ProtocolMeta
class _RequiredForm
class _Sentinel
class _SpecialForm
class _TypedDictMeta
class _TypeGuardForm
class _TypeVarLikeMeta
class _UnpackAlias
class _UnpackForm
class _UnpackSpecialForm
class Annotated
class Any
class Buffer
class NewType
class ParamSpec
class ParamSpecArgs
class ParamSpecKwargs
class Protocol
class SupportsAbs
class SupportsBytes
class SupportsComplex
class SupportsFloat
class SupportsIndex
class SupportsInt
class SupportsRound
class TypeAliasType
class TypeVar
class TypeVarTuple
Functions
_check_generic (cls, parameters, elen=_marker)
_should_collect_from_parameters (t)
_collect_type_vars (types, typevar_types=None)
final (f)
IntVar (name)
_flatten_literal_params (parameters)
_value_and_type_iter (params)
overload (func)
get_overloads (func)
_get_protocol_attrs (cls)
_maybe_adjust_parameters (cls)
_caller (depth=2)
_allow_reckless_class_checks (depth=3)
_no_init (self, *args, **kwargs)
_proto_hook (cls, other)
runtime_checkable (cls)
_ensure_subclassable (mro_entries)
TypedDict (__typename, __fields=_marker, *, total=True, **kwargs)
is_typeddict (tp)
assert_type (__val, __typ)
_strip_extras (t)
get_type_hints (obj, globalns=None, localns=None, include_extras=False)
get_origin (tp)
get_args (tp)
TypeAlias (self, parameters)
_set_default (type_param, default)
_set_module (typevarlike)
_concatenate_getitem (self, parameters)
Concatenate (self, parameters)
TypeGuard (self, parameters)
LiteralString (self, params)
Self (self, params)
Never (self, params)
Required (self, parameters)
NotRequired (self, parameters)
_is_unpack (obj)
Unpack (self, parameters)
T reveal_type (T __obj)
Never assert_never (Never __arg)
typing.Callable[[T], T] dataclass_transform (*, bool eq_default=True, bool order_default=False, bool kw_only_default=False, bool frozen_default=False, typing.Tuple[typing.Union[typing.Type[typing.Any], typing.Callable[..., typing.Any]],...] field_specifiers=(), **typing.Any kwargs)
_F override (_F __arg)
typing.Callable[[_T], _T] deprecated (str __msg, *, typing.Optional[typing.Type[Warning]] category=DeprecationWarning, int stacklevel=1)
_make_nmtuple (name, types, module, defaults=())
_namedtuple_mro_entries (bases)
NamedTuple (__typename, __fields=_marker, **kwargs)
get_original_bases (__cls)
_is_unionable (obj)
bool is_protocol (type __tp)
typing.FrozenSet[str] get_protocol_members (type __tp)
Variables
bool PEP_560 = True
GenericMeta = type
_marker = _Sentinel()
NoReturn = typing.NoReturn
T = typing.TypeVar('T')
KT = typing.TypeVar('KT')
VT = typing.TypeVar('VT')
T_co = typing.TypeVar('T_co', covariant=True)
T_contra = typing.TypeVar('T_contra', contravariant=True)
ClassVar = typing.ClassVar
Final = typing.Final
doc
final = typing.final
Literal = typing.Literal
_overload_dummy = typing._overload_dummy
overload = typing.overload
get_overloads = typing.get_overloads
clear_overloads = typing.clear_overloads
_overload_registry
Type = typing.Type
Awaitable = typing.Awaitable
Coroutine = typing.Coroutine
AsyncIterable = typing.AsyncIterable
AsyncIterator = typing.AsyncIterator
Deque = typing.Deque
ContextManager = typing.ContextManager
AsyncContextManager = typing.AsyncContextManager
DefaultDict = typing.DefaultDict
OrderedDict = typing.OrderedDict
Counter = typing.Counter
ChainMap = typing.ChainMap
AsyncGenerator = typing.AsyncGenerator
Text = typing.Text
TYPE_CHECKING = typing.TYPE_CHECKING
dict _PROTO_ALLOWLIST
dict _EXCLUDED_ATTRS
Protocol = typing.Protocol
_typing_Protocol = typing.Protocol
_ProtocolMetaBase = type(_typing_Protocol)
runtime_checkable = typing.runtime_checkable
runtime = runtime_checkable
SupportsInt = typing.SupportsInt
SupportsFloat = typing.SupportsFloat
SupportsComplex = typing.SupportsComplex
SupportsBytes = typing.SupportsBytes
SupportsIndex = typing.SupportsIndex
SupportsAbs = typing.SupportsAbs
SupportsRound = typing.SupportsRound
TypedDict = typing.TypedDict
_TypedDictMeta = typing._TypedDictMeta
is_typeddict = typing.is_typeddict
str _TAKES_MODULE = "module" in inspect.signature(typing._type_check).parameters
str _fake_name = "Protocol"
_TypedDict
tuple _TYPEDDICT_TYPES = (typing._TypedDictMeta, _TypedDictMeta)
assert_type = typing.assert_type
get_type_hints = typing.get_type_hints
Annotated = typing.Annotated
_AnnotatedAlias = typing._AnnotatedAlias
get_origin = typing.get_origin
get_args = typing.get_args
_BaseGenericAlias = typing._GenericAlias
_typing_GenericAlias = typing._GenericAlias
TypeAlias = typing.TypeAlias
ParamSpecArgs = typing.ParamSpecArgs
ParamSpecKwargs = typing.ParamSpecKwargs
Concatenate = typing.Concatenate
_ConcatenateGenericAlias = typing._ConcatenateGenericAlias
TypeGuard = typing.TypeGuard
LiteralString = typing.LiteralString
Self = typing.Self
Never = typing.Never
Required = typing.Required
NotRequired = typing.NotRequired
str _UNPACK_DOC
Unpack = typing.Unpack
reveal_type = typing.reveal_type
assert_never = typing.assert_never
dataclass_transform = typing.dataclass_transform
override = typing.override
_F = typing.TypeVar("_F", bound=typing.Callable[..., typing.Any])
deprecated = typing.deprecated
_T = typing.TypeVar("_T")
_collect_type_vars
_check_generic
NamedTuple = typing.NamedTuple
_prohibited_namedtuple_fields = typing._prohibited
_special_namedtuple_fields = frozenset({'__module__', '__name__', '__annotations__'})
_NamedTuple
str _new_signature = '(typename, fields=None, /, **kwargs)'
Buffer = collections.abc.Buffer
get_original_bases = _types.get_original_bases
NewType = typing.NewType
TypeAliasType = typing.TypeAliasType
is_protocol = typing.is_protocol
get_protocol_members = typing.get_protocol_members
AbstractSet = typing.AbstractSet
AnyStr = typing.AnyStr
BinaryIO = typing.BinaryIO
Callable = typing.Callable
Collection = typing.Collection
Container = typing.Container
Dict = typing.Dict
ForwardRef = typing.ForwardRef
FrozenSet = typing.FrozenSet
Generator = typing.Generator
Generic = typing.Generic
Hashable = typing.Hashable
IO = typing.IO
ItemsView = typing.ItemsView
Iterable = typing.Iterable
Iterator = typing.Iterator
KeysView = typing.KeysView
List = typing.List
Mapping = typing.Mapping
MappingView = typing.MappingView
Match = typing.Match
MutableMapping = typing.MutableMapping
MutableSequence = typing.MutableSequence
MutableSet = typing.MutableSet
Optional = typing.Optional
Pattern = typing.Pattern
Reversible = typing.Reversible
Sequence = typing.Sequence
Set = typing.Set
Sized = typing.Sized
TextIO = typing.TextIO
Tuple = typing.Tuple
Union = typing.Union
ValuesView = typing.ValuesView
cast = typing.cast
no_type_check = typing.no_type_check
no_type_check_decorator = typing.no_type_check_decorator
_is_runtime_protocol
Function Documentation
_allow_reckless_class_checks()
pip._vendor.typing_extensions._allow_reckless_class_checks (depth = 3) protected
Allow instance and class checks for special stdlib modules.
The abc and functools modules indiscriminately call isinstance() and
issubclass() on the whole MRO of a user class, which may contain protocols.
References pip._vendor.typing_extensions._caller().
Referenced by pip._vendor.typing_extensions._ProtocolMeta.__instancecheck__(), and pip._vendor.typing_extensions._ProtocolMeta.__subclasscheck__().
_caller()
pip._vendor.typing_extensions._caller (depth = 2) protected
Referenced by pip._vendor.typing_extensions.NewType.__init__(), pip._vendor.typing_extensions.ParamSpec.__init__(), pip._vendor.typing_extensions.TypeAliasType.__init__(), pip._vendor.typing_extensions.TypeVarTuple.__init__(), pip._vendor.typing_extensions._allow_reckless_class_checks(), pip._vendor.typing_extensions._set_module(), pip._vendor.typing_extensions.NamedTuple(), and pip._vendor.typing_extensions.TypedDict().
_check_generic()
pip._vendor.typing_extensions._check_generic (cls, parameters, elen = _marker) protected
Check correct count for parameters of a generic cls (internal helper).
This gives a nice error message in case of count mismatch.
References pip._vendor.typing_extensions._is_unpack().
_collect_type_vars()
pip._vendor.typing_extensions._collect_type_vars (types, typevar_types = None) protected
Collect all type variable contained in types in order of
first appearance (lexicographic order). For example::
    _collect_type_vars((T, List[S, T])) == (T, S)
References pip._vendor.typing_extensions._is_unpack(), and pip._vendor.typing_extensions._should_collect_from_parameters().
_concatenate_getitem()
pip._vendor.typing_extensions._concatenate_getitem (self, parameters) protected
Referenced by pip._vendor.typing_extensions._ConcatenateForm.__getitem__(), and pip._vendor.typing_extensions.Concatenate().
_ensure_subclassable()
pip._vendor.typing_extensions._ensure_subclassable (mro_entries) protected
_flatten_literal_params()
pip._vendor.typing_extensions._flatten_literal_params (parameters) protected
An internal helper for Literal creation: flatten Literals among parameters
Referenced by pip._vendor.typing_extensions._LiteralForm.__getitem__().
_get_protocol_attrs()
pip._vendor.typing_extensions._get_protocol_attrs (cls) protected
Referenced by pip._vendor.typing_extensions._ProtocolMeta.__init__(), and pip._vendor.typing_extensions.get_protocol_members().
_is_unionable()
pip._vendor.typing_extensions._is_unionable (obj) protected
Corresponds to is_unionable() in unionobject.c in CPython.
Referenced by pip._vendor.typing_extensions.TypeAliasType.__or__(), and pip._vendor.typing_extensions.TypeAliasType.__ror__().
_is_unpack()
pip._vendor.typing_extensions._is_unpack (obj) protected
References pip._vendor.typing_extensions.get_origin.
Referenced by pip._vendor.typing_extensions._check_generic(), and pip._vendor.typing_extensions._collect_type_vars().
_make_nmtuple()
pip._vendor.typing_extensions._make_nmtuple (name, types, module, defaults = ()) protected
Referenced by pip._vendor.typing_extensions._NamedTupleMeta.__new__(), and pip._vendor.typing_extensions.NamedTuple().
_maybe_adjust_parameters()
pip._vendor.typing_extensions._maybe_adjust_parameters (cls) protected
Helper function used in Protocol.__init_subclass__ and _TypedDictMeta.__new__.
The contents of this function are very similar
to logic found in typing.Generic.__init_subclass__
on the CPython main branch.
Referenced by pip._vendor.typing_extensions.Protocol.__init_subclass__().
_namedtuple_mro_entries()
pip._vendor.typing_extensions._namedtuple_mro_entries (bases) protected
_no_init()
pip._vendor.typing_extensions._no_init (self, * args, ** kwargs) protected
_proto_hook()
pip._vendor.typing_extensions._proto_hook (cls, other) protected
References pip._vendor.typing_extensions.is_protocol.
_set_default()
pip._vendor.typing_extensions._set_default (type_param, default) protected
Referenced by pip._vendor.typing_extensions.ParamSpec.__new__(), pip._vendor.typing_extensions.TypeVar.__new__(), and pip._vendor.typing_extensions.TypeVarTuple.__new__().
_set_module()
pip._vendor.typing_extensions._set_module (typevarlike) protected
References pip._vendor.typing_extensions._caller().
Referenced by pip._vendor.typing_extensions.ParamSpec.__new__(), pip._vendor.typing_extensions.TypeVar.__new__(), and pip._vendor.typing_extensions.TypeVarTuple.__new__().
_should_collect_from_parameters()
pip._vendor.typing_extensions._should_collect_from_parameters (t) protected
Referenced by pip._vendor.typing_extensions._collect_type_vars().
_strip_extras()
pip._vendor.typing_extensions._strip_extras (t) protected
Strips Annotated, Required and NotRequired from a given type.
References pip._vendor.typing_extensions._strip_extras().
Referenced by pip._vendor.typing_extensions._strip_extras(), and pip._vendor.typing_extensions.get_type_hints().
_value_and_type_iter()
pip._vendor.typing_extensions._value_and_type_iter (params) protected
Referenced by pip._vendor.typing_extensions._LiteralGenericAlias.__eq__(), pip._vendor.typing_extensions._LiteralForm.__getitem__(), and pip._vendor.typing_extensions._LiteralGenericAlias.__hash__().
assert_never()
Never pip._vendor.typing_extensions.assert_never (Never __arg)
Assert to the type checker that a line of code is unreachable.
Example::
    def int_or_str(arg: int | str) -> None:
        match arg:
            case int():
                print("It's an int")
            case str():
                print("It's a str")
            case _:
                assert_never(arg)
If a type checker finds that a call to assert_never() is
reachable, it will emit an error.
At runtime, this throws an exception when called.
assert_type()
pip._vendor.typing_extensions.assert_type (__val, __typ)
Assert (to the type checker) that the value is of the given type.
When the type checker encounters a call to assert_type(), it
emits an error if the value is not of the specified type::
    def greet(name: str) -> None:
        assert_type(name, str)  # ok
        assert_type(name, int)  # type checker error
At runtime this returns the first argument unchanged and otherwise
does nothing.
Concatenate()
pip._vendor.typing_extensions.Concatenate (self, parameters)
Used in conjunction with ``ParamSpec`` and ``Callable`` to represent a
higher order function which adds, removes or transforms parameters of a
callable.
For example::
   Callable[Concatenate[int, P], int]
See PEP 612 for detailed information.
References pip._vendor.typing_extensions._concatenate_getitem().
dataclass_transform()
typing.Callable[[T], T] pip._vendor.typing_extensions.dataclass_transform (* , bool eq_default = True, bool order_default = False, bool kw_only_default = False, bool frozen_default = False, typing.Tuple[ typing.Union[typing.Type[typing.Any], typing.Callable[..., typing.Any]], ... ] field_specifiers = (), **typing.Any kwargs)
Decorator that marks a function, class, or metaclass as providing
dataclass-like behavior.
Example:
    from pip._vendor.typing_extensions import dataclass_transform
    _T = TypeVar("_T")
    # Used on a decorator function
    @dataclass_transform()
    def create_model(cls: type[_T]) -> type[_T]:
        ...
        return cls
    @create_model
    class CustomerModel:
        id: int
        name: str
    # Used on a base class
    @dataclass_transform()
    class ModelBase: ...
    class CustomerModel(ModelBase):
        id: int
        name: str
    # Used on a metaclass
    @dataclass_transform()
    class ModelMeta(type): ...
    class ModelBase(metaclass=ModelMeta): ...
    class CustomerModel(ModelBase):
        id: int
        name: str
Each of the ``CustomerModel`` classes defined in this example will now
behave similarly to a dataclass created with the ``@dataclasses.dataclass``
decorator. For example, the type checker will synthesize an ``__init__``
method.
The arguments to this decorator can be used to customize this behavior:
- ``eq_default`` indicates whether the ``eq`` parameter is assumed to be
  True or False if it is omitted by the caller.
- ``order_default`` indicates whether the ``order`` parameter is
  assumed to be True or False if it is omitted by the caller.
- ``kw_only_default`` indicates whether the ``kw_only`` parameter is
  assumed to be True or False if it is omitted by the caller.
- ``frozen_default`` indicates whether the ``frozen`` parameter is
  assumed to be True or False if it is omitted by the caller.
- ``field_specifiers`` specifies a static list of supported classes
  or functions that describe fields, similar to ``dataclasses.field()``.
At runtime, this decorator records its arguments in the
``__dataclass_transform__`` attribute on the decorated object.
See PEP 681 for details.
deprecated()
typing.Callable[[_T], _T] pip._vendor.typing_extensions.deprecated (str __msg, * , typing.Optional[typing.Type[Warning]] category = DeprecationWarning, int stacklevel = 1)
Indicate that a class, function or overload is deprecated.
Usage:
    @deprecated("Use B instead")
    class A:
        pass
    @deprecated("Use g instead")
    def f():
        pass
    @overload
    @deprecated("int support is deprecated")
    def g(x: int) -> int: ...
    @overload
    def g(x: str) -> int: ...
When this decorator is applied to an object, the type checker
will generate a diagnostic on usage of the deprecated object.
The warning specified by ``category`` will be emitted on use
of deprecated objects. For functions, that happens on calls;
for classes, on instantiation. If the ``category`` is ``None``,
no warning is emitted. The ``stacklevel`` determines where the
warning is emitted. If it is ``1`` (the default), the warning
is emitted at the direct caller of the deprecated object; if it
is higher, it is emitted further up the stack.
The decorator sets the ``__deprecated__``
attribute on the decorated object to the deprecation message
passed to the decorator. If applied to an overload, the decorator
must be after the ``@overload`` decorator for the attribute to
exist on the overload as returned by ``get_overloads()``.
See PEP 702 for details.
final()
pip._vendor.typing_extensions.final (f)
This decorator can be used to indicate to type checkers that
the decorated method cannot be overridden, and decorated class
cannot be subclassed. For example:
    class Base:
        @final
        def done(self) -> None:
            ...
    class Sub(Base):
        def done(self) -> None:  # Error reported by type checker
            ...
    @final
    class Leaf:
        ...
    class Other(Leaf):  # Error reported by type checker
        ...
There is no runtime checking of these properties. The decorator
sets the ``__final__`` attribute to ``True`` on the decorated object
to allow runtime introspection.
get_args()
pip._vendor.typing_extensions.get_args (tp)
Get type arguments with all substitutions performed.
For unions, basic simplifications used by Union constructor are performed.
Examples::
    get_args(Dict[str, int]) == (str, int)
    get_args(int) == ()
    get_args(Union[int, Union[T, int], str][int]) == (int, str)
    get_args(Union[int, Tuple[T, int]][str]) == (int, Tuple[str, int])
    get_args(Callable[[], T][int]) == ([], int)
References pip._vendor.typing_extensions.get_origin.
get_origin()
pip._vendor.typing_extensions.get_origin (tp)
Get the unsubscripted version of a type.
This supports generic types, Callable, Tuple, Union, Literal, Final, ClassVar
and Annotated. Return None for unsupported types. Examples::
    get_origin(Literal[42]) is Literal
    get_origin(int) is None
    get_origin(ClassVar[int]) is ClassVar
    get_origin(Generic) is Generic
    get_origin(Generic[T]) is Generic
    get_origin(Union[T, int]) is Union
    get_origin(List[Tuple[T, T]][int]) == list
    get_origin(P.args) is P
get_original_bases()
pip._vendor.typing_extensions.get_original_bases (__cls)
Return the class's "original" bases prior to modification by `__mro_entries__`.
Examples::
    from typing import TypeVar, Generic
    from pip._vendor.typing_extensions import NamedTuple, TypedDict
    T = TypeVar("T")
    class Foo(Generic[T]): ...
    class Bar(Foo[int], float): ...
    class Baz(list[str]): ...
    Eggs = NamedTuple("Eggs", [("a", int), ("b", str)])
    Spam = TypedDict("Spam", {"a": int, "b": str})
    assert get_original_bases(Bar) == (Foo[int], float)
    assert get_original_bases(Baz) == (list[str],)
    assert get_original_bases(Eggs) == (NamedTuple,)
    assert get_original_bases(Spam) == (TypedDict,)
    assert get_original_bases(int) == (object,)
get_overloads()
pip._vendor.typing_extensions.get_overloads (func)
Return all defined overloads for *func* as a sequence.
get_protocol_members()
typing.FrozenSet[str] pip._vendor.typing_extensions.get_protocol_members (type __tp)
Return the set of members defined in a Protocol.
Example::
    >>> from typing_extensions import Protocol, get_protocol_members
    >>> class P(Protocol):
    ...     def a(self) -> str: ...
    ...     b: int
    >>> get_protocol_members(P)
    frozenset({'a', 'b'})
Raise a TypeError for arguments that are not Protocols.
References pip._vendor.typing_extensions._get_protocol_attrs(), and pip._vendor.typing_extensions.is_protocol.
get_type_hints()
pip._vendor.typing_extensions.get_type_hints (obj, globalns = None, localns = None, include_extras = False)
Return type hints for an object.
This is often the same as obj.__annotations__, but it handles
forward references encoded as string literals, adds Optional[t] if a
default value equal to None is set and recursively replaces all
'Annotated[T, ...]', 'Required[T]' or 'NotRequired[T]' with 'T'
(unless 'include_extras=True').
The argument may be a module, class, method, or function. The annotations
are returned as a dictionary. For classes, annotations include also
inherited members.
TypeError is raised if the argument is not of a type that can contain
annotations, and an empty dictionary is returned if no annotations are
present.
BEWARE -- the behavior of globalns and localns is counterintuitive
(unless you are familiar with how eval() and exec() work).  The
search order is locals first, then globals.
- If no dict arguments are passed, an attempt is made to use the
  globals from obj (or the respective module's globals for classes),
  and these are also used as the locals.  If the object does not appear
  to have globals, an empty dictionary is used.
- If one dict argument is passed, it is used for both globals and
  locals.
- If two dict arguments are passed, they specify globals and
  locals, respectively.
References pip._vendor.typing_extensions._strip_extras().
IntVar()
pip._vendor.typing_extensions.IntVar (name)
is_protocol()
bool pip._vendor.typing_extensions.is_protocol (type __tp)
Return True if the given type is a Protocol.
Example::
    >>> from typing_extensions import Protocol, is_protocol
    >>> class P(Protocol):
    ...     def a(self) -> str: ...
    ...     b: int
    >>> is_protocol(P)
    True
    >>> is_protocol(int)
    False
is_typeddict()
pip._vendor.typing_extensions.is_typeddict (tp)
Check if an annotation is a TypedDict class
For example::
    class Film(TypedDict):
        title: str
        year: int
    is_typeddict(Film)  # => True
    is_typeddict(Union[list, str])  # => False
LiteralString()
pip._vendor.typing_extensions.LiteralString (self, params)
Represents an arbitrary literal string.
Example::
  from pip._vendor.typing_extensions import LiteralString
  def query(sql: LiteralString) -> ...:
      ...
  query("SELECT * FROM table")  # ok
  query(f"SELECT * FROM {input()}")  # not ok
See PEP 675 for details.
NamedTuple()
pip._vendor.typing_extensions.NamedTuple (__typename, __fields = _marker, ** kwargs)
Typed version of namedtuple.
Usage::
    class Employee(NamedTuple):
        name: str
        id: int
This is equivalent to::
    Employee = collections.namedtuple('Employee', ['name', 'id'])
The resulting class has an extra __annotations__ attribute, giving a
dict that maps field names to types.  (The field names are also in
the _fields attribute, which is part of the namedtuple API.)
An alternative equivalent functional syntax is also accepted::
    Employee = NamedTuple('Employee', [('name', str), ('id', int)])
References pip._vendor.typing_extensions._caller(), and pip._vendor.typing_extensions._make_nmtuple().
Never()
pip._vendor.typing_extensions.Never (self, params)
The bottom type, a type that has no members.
This can be used to define a function that should never be
called, or a function that never returns::
    from pip._vendor.typing_extensions import Never
    def never_call_me(arg: Never) -> None:
        pass
    def int_or_str(arg: int | str) -> None:
        never_call_me(arg)  # type checker error
        match arg:
            case int():
                print("It's an int")
            case str():
                print("It's a str")
            case _:
                never_call_me(arg)  # ok, arg is of type Never
NotRequired()
pip._vendor.typing_extensions.NotRequired (self, parameters)
A special typing construct to mark a key of a TypedDict as
potentially missing. For example:
    class Movie(TypedDict):
        title: str
        year: NotRequired[int]
    m = Movie(
        title='The Matrix',  # typechecker error if key is omitted
        year=1999,
    )
overload()
pip._vendor.typing_extensions.overload (func)
Decorator for overloaded functions/methods.
In a stub file, place two or more stub definitions for the same
function in a row, each decorated with @overload.  For example:
@overload
def utf8(value: None) -> None: ...
@overload
def utf8(value: bytes) -> bytes: ...
@overload
def utf8(value: str) -> bytes: ...
In a non-stub file (i.e. a regular .py file), do the same but
follow it with an implementation.  The implementation should *not*
be decorated with @overload.  For example:
@overload
def utf8(value: None) -> None: ...
@overload
def utf8(value: bytes) -> bytes: ...
@overload
def utf8(value: str) -> bytes: ...
def utf8(value):
    # implementation goes here
The overloads for a function can be retrieved at runtime using the
get_overloads() function.
override()
_F pip._vendor.typing_extensions.override (_F __arg)
Indicate that a method is intended to override a method in a base class.
Usage:
    class Base:
        def method(self) -> None: ...
            pass
    class Child(Base):
        @override
        def method(self) -> None:
            super().method()
When this decorator is applied to a method, the type checker will
validate that it overrides a method with the same name on a base class.
This helps prevent bugs that may occur when a base class is changed
without an equivalent change to a child class.
There is no runtime checking of these properties. The decorator
sets the ``__override__`` attribute to ``True`` on the decorated object
to allow runtime introspection.
See PEP 698 for details.
Required()
pip._vendor.typing_extensions.Required (self, parameters)
A special typing construct to mark a key of a total=False TypedDict
as required. For example:
    class Movie(TypedDict, total=False):
        title: Required[str]
        year: int
    m = Movie(
        title='The Matrix',  # typechecker error if key is omitted
        year=1999,
    )
There is no runtime checking that a required key is actually provided
when instantiating a related TypedDict.
reveal_type()
T pip._vendor.typing_extensions.reveal_type (T __obj)
Reveal the inferred type of a variable.
When a static type checker encounters a call to ``reveal_type()``,
it will emit the inferred type of the argument::
    x: int = 1
    reveal_type(x)
Running a static type checker (e.g., ``mypy``) on this example
will produce output similar to 'Revealed type is "builtins.int"'.
At runtime, the function prints the runtime type of the
argument and returns it unchanged.
runtime_checkable()
pip._vendor.typing_extensions.runtime_checkable (cls)
Mark a protocol class as a runtime protocol, so that it
can be used with isinstance() and issubclass(). Raise TypeError
if applied to a non-protocol class.
This allows a simple-minded structural check very similar to the
one-offs in collections.abc such as Hashable.
Self()
pip._vendor.typing_extensions.Self (self, params)
Used to spell the type of "self" in classes.
Example::
  from typing import Self
  class ReturnsSelf:
      def parse(self, data: bytes) -> Self:
          ...
          return self
TypeAlias()
pip._vendor.typing_extensions.TypeAlias (self, parameters)
Special marker indicating that an assignment should
be recognized as a proper type alias definition by type
checkers.
For example::
    Predicate: TypeAlias = Callable[..., bool]
It's invalid when used anywhere except as in the example above.
TypedDict()
pip._vendor.typing_extensions.TypedDict (__typename, __fields = _marker, * , total = True, ** kwargs)
A simple typed namespace. At runtime it is equivalent to a plain dict.
TypedDict creates a dictionary type such that a type checker will expect all
instances to have a certain set of keys, where each key is
associated with a value of a consistent type. This expectation
is not checked at runtime.
Usage::
    class Point2D(TypedDict):
        x: int
        y: int
        label: str
    a: Point2D = {'x': 1, 'y': 2, 'label': 'good'}  # OK
    b: Point2D = {'z': 3, 'label': 'bad'}           # Fails type check
    assert Point2D(x=1, y=2, label='first') == dict(x=1, y=2, label='first')
The type info can be accessed via the Point2D.__annotations__ dict, and
the Point2D.__required_keys__ and Point2D.__optional_keys__ frozensets.
TypedDict supports an additional equivalent form::
    Point2D = TypedDict('Point2D', {'x': int, 'y': int, 'label': str})
By default, all keys must be present in a TypedDict. It is possible
to override this by specifying totality::
    class Point2D(TypedDict, total=False):
        x: int
        y: int
This means that a Point2D TypedDict can have any of the keys omitted. A type
checker is only expected to support a literal False or True as the value of
the total argument. True is the default, and makes all items defined in the
class body be required.
The Required and NotRequired special forms can also be used to mark
individual keys as being required or not required::
    class Point2D(TypedDict):
        x: int  # the "x" key must always be present (Required is the default)
        y: NotRequired[int]  # the "y" key can be omitted
See PEP 655 for more details on Required and NotRequired.
References pip._vendor.typing_extensions._caller().
TypeGuard()
pip._vendor.typing_extensions.TypeGuard (self, parameters)
Special typing form used to annotate the return type of a user-defined
type guard function.  ``TypeGuard`` only accepts a single type argument.
At runtime, functions marked this way should return a boolean.
``TypeGuard`` aims to benefit *type narrowing* -- a technique used by static
type checkers to determine a more precise type of an expression within a
program's code flow.  Usually type narrowing is done by analyzing
conditional code flow and applying the narrowing to a block of code.  The
conditional expression here is sometimes referred to as a "type guard".
Sometimes it would be convenient to use a user-defined boolean function
as a type guard.  Such a function should use ``TypeGuard[...]`` as its
return type to alert static type checkers to this intention.
Using  ``-> TypeGuard`` tells the static type checker that for a given
function:
1. The return value is a boolean.
2. If the return value is ``True``, the type of its argument
is the type inside ``TypeGuard``.
For example::
    def is_str(val: Union[str, float]):
        # "isinstance" type guard
        if isinstance(val, str):
            # Type of ``val`` is narrowed to ``str``
            ...
        else:
            # Else, type of ``val`` is narrowed to ``float``.
            ...
Strict type narrowing is not enforced -- ``TypeB`` need not be a narrower
form of ``TypeA`` (it can even be a wider form) and this may lead to
type-unsafe results.  The main reason is to allow for things like
narrowing ``List[object]`` to ``List[str]`` even though the latter is not
a subtype of the former, since ``List`` is invariant.  The responsibility of
writing type-safe type guards is left to the user.
``TypeGuard`` also works with type variables.  For more information, see
PEP 647 (User-Defined Type Guards).
Unpack()
pip._vendor.typing_extensions.Unpack (self, parameters)
Variable Documentation
_AnnotatedAlias
pip._vendor.typing_extensions._AnnotatedAlias = typing._AnnotatedAlias protected
_BaseGenericAlias
pip._vendor.typing_extensions._BaseGenericAlias = typing._GenericAlias protected
_check_generic
pip._vendor.typing_extensions._check_generic protected
Referenced by pip._vendor.typing_extensions.Protocol.__class_getitem__().
_collect_type_vars
pip._vendor.typing_extensions._collect_type_vars protected
_ConcatenateGenericAlias
pip._vendor.typing_extensions._ConcatenateGenericAlias = typing._ConcatenateGenericAlias protected
_EXCLUDED_ATTRS
pip._vendor.typing_extensions._EXCLUDED_ATTRS protected
Initial value:
=  {
    "__abstractmethods__", "__annotations__", "__weakref__", "_is_protocol",
    "_is_runtime_protocol", "__dict__", "__slots__", "__parameters__",
    "__orig_bases__", "__module__", "_MutableMapping__marker", "__doc__",
    "__subclasshook__", "__orig_class__", "__init__", "__new__",
    "__protocol_attrs__", "__callable_proto_members_only__",
}
_F
pip._vendor.typing_extensions._F = typing.TypeVar("_F", bound=typing.Callable[..., typing.Any]) protected
_fake_name
str pip._vendor.typing_extensions._fake_name = "Protocol" protected
_is_runtime_protocol
pip._vendor.typing_extensions._is_runtime_protocol protected
_marker
pip._vendor.typing_extensions._marker = _Sentinel() protected
_NamedTuple
pip._vendor.typing_extensions._NamedTuple protected
_new_signature
str pip._vendor.typing_extensions._new_signature = '(typename, fields=None, /, **kwargs)' protected
_overload_dummy
pip._vendor.typing_extensions._overload_dummy = typing._overload_dummy protected
_overload_registry
pip._vendor.typing_extensions._overload_registry protected
Initial value:
=  collections.defaultdict(
        functools.partial(collections.defaultdict, dict)
    )
_prohibited_namedtuple_fields
pip._vendor.typing_extensions._prohibited_namedtuple_fields = typing._prohibited protected
_PROTO_ALLOWLIST
dict pip._vendor.typing_extensions._PROTO_ALLOWLIST protected
Initial value:
=  {
    'collections.abc': [
        'Callable', 'Awaitable', 'Iterable', 'Iterator', 'AsyncIterable',
        'Hashable', 'Sized', 'Container', 'Collection', 'Reversible', 'Buffer',
    ],
    'contextlib': ['AbstractContextManager', 'AbstractAsyncContextManager'],
    'typing_extensions': ['Buffer'],
}
_ProtocolMetaBase
pip._vendor.typing_extensions._ProtocolMetaBase = type(_typing_Protocol) protected
_special_namedtuple_fields
pip._vendor.typing_extensions._special_namedtuple_fields = frozenset({'__module__', '__name__', '__annotations__'}) protected
_T
pip._vendor.typing_extensions._T = typing.TypeVar("_T") protected
_TAKES_MODULE
str pip._vendor.typing_extensions._TAKES_MODULE = "module" in inspect.signature(typing._type_check).parameters protected
_TypedDict
pip._vendor.typing_extensions._TypedDict protected
_TYPEDDICT_TYPES
tuple pip._vendor.typing_extensions._TYPEDDICT_TYPES = (typing._TypedDictMeta, _TypedDictMeta) protected
_TypedDictMeta
pip._vendor.typing_extensions._TypedDictMeta = typing._TypedDictMeta protected
_typing_GenericAlias
pip._vendor.typing_extensions._typing_GenericAlias = typing._GenericAlias protected
_typing_Protocol
pip._vendor.typing_extensions._typing_Protocol = typing.Protocol protected
_UNPACK_DOC
str pip._vendor.typing_extensions._UNPACK_DOC protected
AbstractSet
pip._vendor.typing_extensions.AbstractSet = typing.AbstractSet
Annotated
pip._vendor.typing_extensions.Annotated = typing.Annotated
AnyStr
pip._vendor.typing_extensions.AnyStr = typing.AnyStr
assert_never
pip._vendor.typing_extensions.assert_never = typing.assert_never
assert_type
pip._vendor.typing_extensions.assert_type = typing.assert_type
AsyncContextManager
pip._vendor.typing_extensions.AsyncContextManager = typing.AsyncContextManager
AsyncGenerator
pip._vendor.typing_extensions.AsyncGenerator = typing.AsyncGenerator
AsyncIterable
pip._vendor.typing_extensions.AsyncIterable = typing.AsyncIterable
AsyncIterator
pip._vendor.typing_extensions.AsyncIterator = typing.AsyncIterator
Awaitable
pip._vendor.typing_extensions.Awaitable = typing.Awaitable
BinaryIO
pip._vendor.typing_extensions.BinaryIO = typing.BinaryIO
Buffer
pip._vendor.typing_extensions.Buffer = collections.abc.Buffer
Callable
pip._vendor.typing_extensions.Callable = typing.Callable
cast
pip._vendor.typing_extensions.cast = typing.cast
ChainMap
pip._vendor.typing_extensions.ChainMap = typing.ChainMap
ClassVar
pip._vendor.typing_extensions.ClassVar = typing.ClassVar
clear_overloads
pip._vendor.typing_extensions.clear_overloads () = typing.clear_overloads
Clear all overloads in the registry.
Collection
pip._vendor.typing_extensions.Collection = typing.Collection
Concatenate
pip._vendor.typing_extensions.Concatenate = typing.Concatenate
Container
pip._vendor.typing_extensions.Container = typing.Container
ContextManager
pip._vendor.typing_extensions.ContextManager = typing.ContextManager
Coroutine
pip._vendor.typing_extensions.Coroutine = typing.Coroutine
Counter
pip._vendor.typing_extensions.Counter = typing.Counter
dataclass_transform
pip._vendor.typing_extensions.dataclass_transform = typing.dataclass_transform
DefaultDict
pip._vendor.typing_extensions.DefaultDict = typing.DefaultDict
deprecated
pip._vendor.typing_extensions.deprecated = typing.deprecated
Deque
pip._vendor.typing_extensions.Deque = typing.Deque
Dict
pip._vendor.typing_extensions.Dict = typing.Dict
doc
pip._vendor.typing_extensions.doc
Final
pip._vendor.typing_extensions.Final = typing.Final
final
pip._vendor.typing_extensions.final = typing.final
ForwardRef
pip._vendor.typing_extensions.ForwardRef = typing.ForwardRef
FrozenSet
pip._vendor.typing_extensions.FrozenSet = typing.FrozenSet
Generator
pip._vendor.typing_extensions.Generator = typing.Generator
Generic
pip._vendor.typing_extensions.Generic = typing.Generic
GenericMeta
pip._vendor.typing_extensions.GenericMeta = type
get_args
pip._vendor.typing_extensions.get_args = typing.get_args
Referenced by pip._vendor.typing_extensions._TypedDictMeta.__new__().
get_origin
pip._vendor.typing_extensions.get_origin = typing.get_origin
Referenced by pip._vendor.typing_extensions.Annotated.__class_getitem__(), pip._vendor.typing_extensions._TypedDictMeta.__new__(), pip._vendor.typing_extensions._is_unpack(), and pip._vendor.typing_extensions.get_args().
get_original_bases
pip._vendor.typing_extensions.get_original_bases = _types.get_original_bases
get_overloads
pip._vendor.typing_extensions.get_overloads = typing.get_overloads
get_protocol_members
pip._vendor.typing_extensions.get_protocol_members = typing.get_protocol_members
get_type_hints
pip._vendor.typing_extensions.get_type_hints = typing.get_type_hints
Hashable
pip._vendor.typing_extensions.Hashable = typing.Hashable
IO
pip._vendor.typing_extensions.IO = typing.IO
is_protocol
pip._vendor.typing_extensions.is_protocol = typing.is_protocol
Referenced by pip._vendor.typing_extensions._ProtocolMeta.__new__(), pip._vendor.typing_extensions._proto_hook(), and pip._vendor.typing_extensions.get_protocol_members().
is_typeddict
pip._vendor.typing_extensions.is_typeddict = typing.is_typeddict
ItemsView
pip._vendor.typing_extensions.ItemsView = typing.ItemsView
Iterable
pip._vendor.typing_extensions.Iterable = typing.Iterable
Iterator
pip._vendor.typing_extensions.Iterator = typing.Iterator
KeysView
pip._vendor.typing_extensions.KeysView = typing.KeysView
KT
pip._vendor.typing_extensions.KT = typing.TypeVar('KT')
List
pip._vendor.typing_extensions.List = typing.List
Literal
pip._vendor.typing_extensions.Literal = typing.Literal
LiteralString
pip._vendor.typing_extensions.LiteralString = typing.LiteralString
Mapping
pip._vendor.typing_extensions.Mapping = typing.Mapping
MappingView
pip._vendor.typing_extensions.MappingView = typing.MappingView
Match
pip._vendor.typing_extensions.Match = typing.Match
MutableMapping
pip._vendor.typing_extensions.MutableMapping = typing.MutableMapping
MutableSequence
pip._vendor.typing_extensions.MutableSequence = typing.MutableSequence
MutableSet
pip._vendor.typing_extensions.MutableSet = typing.MutableSet
NamedTuple
pip._vendor.typing_extensions.NamedTuple = typing.NamedTuple
Never
pip._vendor.typing_extensions.Never = typing.Never
NewType
pip._vendor.typing_extensions.NewType = typing.NewType
no_type_check
pip._vendor.typing_extensions.no_type_check = typing.no_type_check
no_type_check_decorator
pip._vendor.typing_extensions.no_type_check_decorator = typing.no_type_check_decorator
NoReturn
pip._vendor.typing_extensions.NoReturn = typing.NoReturn
NotRequired
pip._vendor.typing_extensions.NotRequired = typing.NotRequired
Optional
pip._vendor.typing_extensions.Optional = typing.Optional
OrderedDict
pip._vendor.typing_extensions.OrderedDict = typing.OrderedDict
overload
pip._vendor.typing_extensions.overload = typing.overload
override
pip._vendor.typing_extensions.override = typing.override
ParamSpecArgs
pip._vendor.typing_extensions.ParamSpecArgs = typing.ParamSpecArgs
ParamSpecKwargs
pip._vendor.typing_extensions.ParamSpecKwargs = typing.ParamSpecKwargs
Pattern
pip._vendor.typing_extensions.Pattern = typing.Pattern
PEP_560
bool pip._vendor.typing_extensions.PEP_560 = True
Protocol
pip._vendor.typing_extensions.Protocol = typing.Protocol
Required
pip._vendor.typing_extensions.Required = typing.Required
reveal_type
pip._vendor.typing_extensions.reveal_type = typing.reveal_type
Reversible
pip._vendor.typing_extensions.Reversible = typing.Reversible
runtime
pip._vendor.typing_extensions.runtime = runtime_checkable
runtime_checkable
pip._vendor.typing_extensions.runtime_checkable = typing.runtime_checkable
Self
pip._vendor.typing_extensions.Self = typing.Self
Sequence
pip._vendor.typing_extensions.Sequence = typing.Sequence
Set
pip._vendor.typing_extensions.Set = typing.Set
Sized
pip._vendor.typing_extensions.Sized = typing.Sized
SupportsAbs
pip._vendor.typing_extensions.SupportsAbs = typing.SupportsAbs
SupportsBytes
pip._vendor.typing_extensions.SupportsBytes = typing.SupportsBytes
SupportsComplex
pip._vendor.typing_extensions.SupportsComplex = typing.SupportsComplex
SupportsFloat
pip._vendor.typing_extensions.SupportsFloat = typing.SupportsFloat
SupportsIndex
pip._vendor.typing_extensions.SupportsIndex = typing.SupportsIndex
SupportsInt
pip._vendor.typing_extensions.SupportsInt = typing.SupportsInt
SupportsRound
pip._vendor.typing_extensions.SupportsRound = typing.SupportsRound
T
pip._vendor.typing_extensions.T = typing.TypeVar('T')
T_co
pip._vendor.typing_extensions.T_co = typing.TypeVar('T_co', covariant=True)
T_contra
pip._vendor.typing_extensions.T_contra = typing.TypeVar('T_contra', contravariant=True)
Text
pip._vendor.typing_extensions.Text = typing.Text
TextIO
pip._vendor.typing_extensions.TextIO = typing.TextIO
Tuple
pip._vendor.typing_extensions.Tuple = typing.Tuple
Type
pip._vendor.typing_extensions.Type = typing.Type
TYPE_CHECKING
pip._vendor.typing_extensions.TYPE_CHECKING = typing.TYPE_CHECKING
TypeAlias
pip._vendor.typing_extensions.TypeAlias = typing.TypeAlias
TypeAliasType
pip._vendor.typing_extensions.TypeAliasType = typing.TypeAliasType
TypedDict
pip._vendor.typing_extensions.TypedDict = typing.TypedDict
TypeGuard
pip._vendor.typing_extensions.TypeGuard = typing.TypeGuard
Union
pip._vendor.typing_extensions.Union = typing.Union
Unpack
pip._vendor.typing_extensions.Unpack = typing.Unpack
ValuesView
pip._vendor.typing_extensions.ValuesView = typing.ValuesView
VT
pip._vendor.typing_extensions.VT = typing.TypeVar('VT')