Django Project: cryptography.hazmat.primitives.keywrap Namespace Reference
cryptography.hazmat.primitives.keywrap Namespace Reference
Classes
class InvalidUnwrap
Functions
bytes _wrap_core (bytes wrapping_key, bytes a, list[bytes] r)
bytes aes_key_wrap (bytes wrapping_key, bytes key_to_wrap, typing.Any backend=None)
tuple[bytes, list[bytes]] _unwrap_core (bytes wrapping_key, bytes a, list[bytes] r)
bytes aes_key_wrap_with_padding (bytes wrapping_key, bytes key_to_wrap, typing.Any backend=None)
bytes aes_key_unwrap_with_padding (bytes wrapping_key, bytes wrapped_key, typing.Any backend=None)
bytes aes_key_unwrap (bytes wrapping_key, bytes wrapped_key, typing.Any backend=None)
Function Documentation
_unwrap_core()
tuple[bytes, list[bytes]] cryptography.hazmat.primitives.keywrap._unwrap_core (bytes wrapping_key, bytes a, list[bytes] r) protected
Referenced by cryptography.hazmat.primitives.keywrap.aes_key_unwrap(), and cryptography.hazmat.primitives.keywrap.aes_key_unwrap_with_padding().
_wrap_core()
bytes cryptography.hazmat.primitives.keywrap._wrap_core (bytes wrapping_key, bytes a, list[bytes] r) protected
Referenced by cryptography.hazmat.primitives.keywrap.aes_key_wrap(), and cryptography.hazmat.primitives.keywrap.aes_key_wrap_with_padding().
aes_key_unwrap()
bytes cryptography.hazmat.primitives.keywrap.aes_key_unwrap (bytes wrapping_key, bytes wrapped_key, typing.Any backend = None)
References cryptography.hazmat.primitives.keywrap._unwrap_core().
aes_key_unwrap_with_padding()
bytes cryptography.hazmat.primitives.keywrap.aes_key_unwrap_with_padding (bytes wrapping_key, bytes wrapped_key, typing.Any backend = None)
References cryptography.hazmat.primitives.keywrap._unwrap_core().
aes_key_wrap()
bytes cryptography.hazmat.primitives.keywrap.aes_key_wrap (bytes wrapping_key, bytes key_to_wrap, typing.Any backend = None)
References cryptography.hazmat.primitives.keywrap._wrap_core().
aes_key_wrap_with_padding()
bytes cryptography.hazmat.primitives.keywrap.aes_key_wrap_with_padding (bytes wrapping_key, bytes key_to_wrap, typing.Any backend = None)
References cryptography.hazmat.primitives.keywrap._wrap_core().