Django Project: _pytest.helpconfig Namespace Reference
_pytest.helpconfig Namespace Reference
Classes
class HelpAction
Functions
None pytest_addoption (Parser parser)
Generator[None, Config, Config] pytest_cmdline_parse ()
None showversion (Config config)
int|ExitCode|None pytest_cmdline_main (Config config)
None showhelp (Config config)
list[str] getpluginversioninfo (Config config)
list[str] pytest_report_header (Config config)
Variables
list conftest_options = [("pytest_plugins", "list of plugin names to load")]
Detailed Description
Version info, help messages, tracing configuration.
Function Documentation
getpluginversioninfo()
list[str] _pytest.helpconfig.getpluginversioninfo (Config config)
Referenced by _pytest.helpconfig.pytest_report_header(), and _pytest.helpconfig.showversion().
pytest_addoption()
None _pytest.helpconfig.pytest_addoption (Parser parser)
pytest_cmdline_main()
int | ExitCode | None _pytest.helpconfig.pytest_cmdline_main (Config config)
References _pytest.helpconfig.showhelp(), and _pytest.helpconfig.showversion().
pytest_cmdline_parse()
Generator[None, Config, Config] _pytest.helpconfig.pytest_cmdline_parse ()
pytest_report_header()
list[str] _pytest.helpconfig.pytest_report_header (Config config)
References _pytest.helpconfig.getpluginversioninfo().
showhelp()
None _pytest.helpconfig.showhelp (Config config)
Referenced by _pytest.helpconfig.pytest_cmdline_main().
showversion()
None _pytest.helpconfig.showversion (Config config)
References _pytest.helpconfig.getpluginversioninfo().
Referenced by _pytest.helpconfig.pytest_cmdline_main().
Variable Documentation
conftest_options
list _pytest.helpconfig.conftest_options = [("pytest_plugins", "list of plugin names to load")]