Django Project: packaging.markers Namespace Reference
packaging.markers Namespace Reference
Classes
class Environment
class InvalidMarker
class Marker
class UndefinedComparison
class UndefinedEnvironmentName
Functions
Any _normalize_extra_values (Any results)
str _format_marker (list[str]|MarkerAtom|str marker, bool|None first=True)
bool _eval_op (str lhs, Op op, str rhs)
tuple[str,...] _normalize (*str values, str key)
bool _evaluate_markers (MarkerList markers, dict[str, str] environment)
str format_full_version (sys._version_info info)
Environment default_environment ()
Variables
Operator = Callable[[str, str], bool]
dict _operators
Function Documentation
_eval_op()
bool packaging.markers._eval_op (str lhs, Op op, str rhs) protected
Referenced by packaging.markers._evaluate_markers().
_evaluate_markers()
bool packaging.markers._evaluate_markers (MarkerList markers, dict[str, str] environment) protected
References packaging.markers._eval_op(), packaging.markers._evaluate_markers(), and packaging.markers._normalize().
Referenced by packaging.markers._evaluate_markers(), and packaging.markers.Marker.evaluate().
_format_marker()
str packaging.markers._format_marker (list[str] | MarkerAtom | str marker, bool | None first = True) protected
References packaging.markers._format_marker().
Referenced by packaging.markers.Marker.__str__(), and packaging.markers._format_marker().
_normalize()
tuple[str, ...] packaging.markers._normalize (*str values, str key) protected
Referenced by packaging.markers._evaluate_markers().
_normalize_extra_values()
Any packaging.markers._normalize_extra_values (Any results) protected
Normalize extra values.
default_environment()
Environment packaging.markers.default_environment ()
References packaging.markers.format_full_version().
format_full_version()
str packaging.markers.format_full_version (sys._version_info info)
Referenced by packaging.markers.default_environment().
Variable Documentation
_operators
dict packaging.markers._operators protected
Initial value:
=  {
    "in": lambda lhs, rhs: lhs in rhs,
    "not in": lambda lhs, rhs: lhs not in rhs,
    "<": operator.lt,
    "<=": operator.le,
    "==": operator.eq,
    "!=": operator.ne,
    ">=": operator.ge,
    ">": operator.gt,
}
Operator
packaging.markers.Operator = Callable[[str, str], bool]