Django Project: setuptools.config.pyprojecttoml Namespace Reference
setuptools.config.pyprojecttoml Namespace Reference
Classes
class _BetaConfiguration
class _ConfigExpander
class _EnsurePackagesDiscovered
class _InvalidFile
Functions
dict load_file (_Path filepath)
bool validate (dict config, _Path filepath)
"Distribution" apply_configuration ("Distribution" dist, _Path filepath, ignore_option_errors=False)
read_configuration (_Path filepath, expand=True, ignore_option_errors=False, Optional["Distribution"] dist=None)
bool _skip_bad_config (dict project_cfg, dict setuptools_cfg, Optional["Distribution"] dist)
dict expand_configuration (dict config, Optional[_Path] root_dir=None, bool ignore_option_errors=False, Optional["Distribution"] dist=None)
_parse_requirements_list (value)
_ignore_errors (bool ignore_option_errors)
Variables
_Path = Union[str, os.PathLike]
_logger = logging.getLogger(__name__)
Detailed Description
Load setuptools configuration from ``pyproject.toml`` files.
**PRIVATE MODULE**: API reserved for setuptools internal usage only.
Function Documentation
_ignore_errors()
setuptools.config.pyprojecttoml._ignore_errors (bool ignore_option_errors) protected
Referenced by setuptools.config.pyprojecttoml._ConfigExpander._expand_directive(), setuptools.config.pyprojecttoml._ConfigExpander._expand_packages(), and setuptools.config.pyprojecttoml._ConfigExpander._process_field().
_parse_requirements_list()
setuptools.config.pyprojecttoml._parse_requirements_list (value) protected
Referenced by setuptools.config.pyprojecttoml._ConfigExpander._obtain_dependencies(), and setuptools.config.pyprojecttoml._ConfigExpander._obtain_optional_dependencies().
_skip_bad_config()
bool setuptools.config.pyprojecttoml._skip_bad_config (dict project_cfg, dict setuptools_cfg, Optional["Distribution"] dist) protected
Be temporarily forgiving with invalid ``pyproject.toml``
Referenced by setuptools.config.pyprojecttoml.read_configuration().
apply_configuration()
"Distribution" setuptools.config.pyprojecttoml.apply_configuration ("Distribution" dist, _Path filepath, ignore_option_errors = False)
Apply the configuration from a ``pyproject.toml`` file into an existing
distribution object.
References setuptools.config.read_configuration.
expand_configuration()
dict setuptools.config.pyprojecttoml.expand_configuration (dict config, Optional[_Path] root_dir = None, bool ignore_option_errors = False, Optional["Distribution"] dist = None)
Given a configuration with unresolved fields (e.g. dynamic, cmdclass, ...)
find their final values.
:param dict config: Dict containing the configuration for the distribution
:param str root_dir: Top-level directory for the distribution/project
    (the same directory where ``pyproject.toml`` is place)
:param bool ignore_option_errors: see :func:`read_configuration`
:param Distribution|None: Distribution object to which the configuration refers.
    If not given a dummy object will be created and discarded after the
    configuration is read. Used in the case a dynamic configuration
    (e.g. ``attr`` or ``cmdclass``).
:rtype: dict
Referenced by setuptools.config.pyprojecttoml.read_configuration().
load_file()
dict setuptools.config.pyprojecttoml.load_file (_Path filepath)
Referenced by setuptools.config.pyprojecttoml.read_configuration().
read_configuration()
setuptools.config.pyprojecttoml.read_configuration (_Path filepath, expand = True, ignore_option_errors = False, Optional["Distribution"] dist = None)
Read given configuration file and returns options from it as a dict.
:param str|unicode filepath: Path to configuration file in the ``pyproject.toml``
    format.
:param bool expand: Whether to expand directives and other computed values
    (i.e. post-process the given configuration)
:param bool ignore_option_errors: Whether to silently ignore
    options, values of which could not be resolved (e.g. due to exceptions
    in directives such as file:, attr:, etc.).
    If False exceptions are propagated as expected.
:param Distribution|None: Distribution object to which the configuration refers.
    If not given a dummy object will be created and discarded after the
    configuration is read. This is used for auto-discovery of packages in the case
    a dynamic configuration (e.g. ``attr`` or ``cmdclass``) is expanded.
    When ``expand=False`` this object is simply ignored.
:rtype: dict
References setuptools.config.pyprojecttoml._skip_bad_config(), setuptools.config.pyprojecttoml.expand_configuration(), and setuptools.config.pyprojecttoml.load_file().
validate()
bool setuptools.config.pyprojecttoml.validate (dict config, _Path filepath)
Variable Documentation
_logger
setuptools.config.pyprojecttoml._logger = logging.getLogger(__name__) protected
_Path
setuptools.config.pyprojecttoml._Path = Union[str, os.PathLike] protected