Django Project: waitress.runner Namespace Reference
waitress.runner Namespace Reference
Functions
match (obj_name)
resolve (module_name, object_name)
show_help (stream, name, error=None)
show_exception (stream)
run (argv=sys.argv, _serve=serve)
Variables
str HELP
RUNNER_PATTERN
Function Documentation
match()
waitress.runner.match (obj_name)
Referenced by waitress.runner.run().
resolve()
waitress.runner.resolve (module_name, object_name)
Resolve a named object in a module.
run()
waitress.runner.run (argv = sys.argv, _serve = serve)
Command line runner.
References waitress.runner.match(), waitress.runner.show_exception(), and waitress.runner.show_help().
show_exception()
waitress.runner.show_exception (stream)
Referenced by waitress.runner.run().
show_help()
waitress.runner.show_help (stream, name, error = None)
Referenced by waitress.runner.run().
Variable Documentation
HELP
str waitress.runner.HELP
RUNNER_PATTERN
waitress.runner.RUNNER_PATTERN
Initial value:
=  re.compile(
    ,
    re.I | re.X,
)