Django Project: setuptools.glob Namespace Reference
setuptools.glob Namespace Reference
Functions
glob (pathname, recursive=False)
iglob (pathname, recursive=False)
_iglob (pathname, recursive)
glob1 (dirname, pattern)
glob0 (dirname, basename)
glob2 (dirname, pattern)
_rlistdir (dirname)
has_magic (s)
_isrecursive (pattern)
escape (pathname)
Variables
magic_check = re.compile('([*?[])')
magic_check_bytes = re.compile(b'([*?[])')
Detailed Description
Filename globbing utility. Mostly a copy of `glob` from Python 3.5.
Changes include:
 * `yield from` and PEP3102 `*` removed.
 * Hidden files are not ignored.
Function Documentation
_iglob()
setuptools.glob._iglob (pathname, recursive) protected
References setuptools.glob._iglob(), setuptools.glob._isrecursive(), and setuptools.glob.has_magic().
Referenced by setuptools.glob._iglob(), and setuptools.glob.iglob().
_isrecursive()
setuptools.glob._isrecursive (pattern) protected
Referenced by setuptools.glob._iglob(), setuptools.glob.glob2(), and setuptools.glob.iglob().
_rlistdir()
setuptools.glob._rlistdir (dirname) protected
References setuptools.glob._rlistdir().
Referenced by setuptools.glob._rlistdir(), and setuptools.glob.glob2().
escape()
setuptools.glob.escape (pathname)
Escape all special characters.
glob()
setuptools.glob.glob (pathname, recursive = False)
Return a list of paths matching a pathname pattern.
The pattern may contain simple shell-style wildcards a la
fnmatch. However, unlike fnmatch, filenames starting with a
dot are special cases that are not matched by '*' and '?'
patterns.
If recursive is true, the pattern '**' will match any files and
zero or more directories and subdirectories.
glob0()
setuptools.glob.glob0 (dirname, basename)
glob1()
setuptools.glob.glob1 (dirname, pattern)
glob2()
setuptools.glob.glob2 (dirname, pattern)
References setuptools.glob._isrecursive(), and setuptools.glob._rlistdir().
has_magic()
setuptools.glob.has_magic (s)
Referenced by setuptools.glob._iglob().
iglob()
setuptools.glob.iglob (pathname, recursive = False)
Return an iterator which yields the paths matching a pathname pattern.
The pattern may contain simple shell-style wildcards a la
fnmatch. However, unlike fnmatch, filenames starting with a
dot are special cases that are not matched by '*' and '?'
patterns.
If recursive is true, the pattern '**' will match any files and
zero or more directories and subdirectories.
References setuptools.glob._iglob(), and setuptools.glob._isrecursive().
Variable Documentation
magic_check
setuptools.glob.magic_check = re.compile('([*?[])')
magic_check_bytes
setuptools.glob.magic_check_bytes = re.compile(b'([*?[])')