Django Project: waitress.wasyncore Namespace Reference
waitress.wasyncore Namespace Reference
Classes
class dispatcher
class dispatcher_with_send
class ExitNow
class file_dispatcher
class file_wrapper
Functions
_strerror (err)
read (obj)
write (obj)
_exception (obj)
readwrite (obj, flags)
poll (timeout=0.0, map=None)
poll2 (timeout=0.0, map=None)
loop (timeout=30.0, use_poll=False, map=None, count=None)
compact_traceback ()
close_all (map=None, ignore_all=False)
Variables
_DISCONNECTED = frozenset({ECONNRESET, ENOTCONN, ESHUTDOWN, ECONNABORTED, EPIPE, EBADF})
dict socket_map = {}
tuple _reraised_exceptions = (ExitNow, KeyboardInterrupt, SystemExit)
poll3 = poll2
Detailed Description
Basic infrastructure for asynchronous socket service clients and servers.
There are only two ways to have a program on a single processor do "more
than one thing at a time".  Multi-threaded programming is the simplest and
most popular way to do it, but there is another very different technique,
that lets you have nearly all the advantages of multi-threading, without
actually using multiple threads. it's really only practical if your program
is largely I/O bound. If your program is CPU bound, then pre-emptive
scheduled threads are probably what you really need. Network servers are
rarely CPU-bound, however.
If your operating system supports the select() system call in its I/O
library (and nearly all do), then you can use it to juggle multiple
communication channels at once; doing other work while your I/O is taking
place in the "background."  Although this strategy can seem strange and
complex, especially at first, it is in many ways easier to understand and
control than multi-threaded programming. The module documented here solves
many of the difficult problems for you, making the task of building
sophisticated high-performance network servers and clients a snap.
NB: this is a fork of asyncore from the stdlib that we've (the waitress
developers) named 'wasyncore' to ensure forward compatibility, as asyncore
in the stdlib will be dropped soon.  It is neither a copy of the 2.7 asyncore
nor the 3.X asyncore; it is a version compatible with either 2.7 or 3.X.
Function Documentation
_exception()
waitress.wasyncore._exception (obj) protected
Referenced by waitress.wasyncore.poll().
_strerror()
waitress.wasyncore._strerror (err) protected
Referenced by waitress.wasyncore.dispatcher.handle_connect_event().
close_all()
waitress.wasyncore.close_all (map = None, ignore_all = False)
compact_traceback()
waitress.wasyncore.compact_traceback ()
loop()
waitress.wasyncore.loop (timeout = 30.0, use_poll = False, map = None, count = None)
poll()
waitress.wasyncore.poll (timeout = 0.0, map = None)
References waitress.wasyncore._exception(), waitress.wasyncore.read(), and waitress.wasyncore.write().
poll2()
waitress.wasyncore.poll2 (timeout = 0.0, map = None)
References waitress.wasyncore.readwrite().
read()
waitress.wasyncore.read (obj)
Referenced by waitress.wasyncore.poll().
readwrite()
waitress.wasyncore.readwrite (obj, flags)
Referenced by waitress.wasyncore.poll2().
write()
waitress.wasyncore.write (obj)
Referenced by waitress.wasyncore.poll().
Variable Documentation
_DISCONNECTED
waitress.wasyncore._DISCONNECTED = frozenset({ECONNRESET, ENOTCONN, ESHUTDOWN, ECONNABORTED, EPIPE, EBADF}) protected
_reraised_exceptions
tuple waitress.wasyncore._reraised_exceptions = (ExitNow, KeyboardInterrupt, SystemExit) protected
poll3
waitress.wasyncore.poll3 = poll2
socket_map
dict waitress.wasyncore.socket_map = {}