Django Project: cryptography.hazmat.primitives.padding Namespace Reference
cryptography.hazmat.primitives.padding Namespace Reference
Classes
class _ANSIX923PaddingContext
class _ANSIX923UnpaddingContext
class _PKCS7PaddingContext
class _PKCS7UnpaddingContext
class ANSIX923
class PaddingContext
class PKCS7
Functions
None _byte_padding_check (int block_size)
tuple[bytes, bytes] _byte_padding_update (bytes|None buffer_, bytes data, int block_size)
bytes _byte_padding_pad (bytes|None buffer_, int block_size, typing.Callable[[int], bytes] paddingfn)
tuple[bytes, bytes] _byte_unpadding_update (bytes|None buffer_, bytes data, int block_size)
bytes _byte_unpadding_check (bytes|None buffer_, int block_size, typing.Callable[[bytes], int] checkfn)
Function Documentation
_byte_padding_check()
None cryptography.hazmat.primitives.padding._byte_padding_check (int block_size) protected
Referenced by cryptography.hazmat.primitives.padding.ANSIX923.__init__(), and cryptography.hazmat.primitives.padding.PKCS7.__init__().
_byte_padding_pad()
bytes cryptography.hazmat.primitives.padding._byte_padding_pad (bytes | None buffer_, int block_size, typing.Callable[[int], bytes] paddingfn) protected
Referenced by cryptography.hazmat.primitives.padding._ANSIX923PaddingContext.finalize(), and cryptography.hazmat.primitives.padding._PKCS7PaddingContext.finalize().
_byte_padding_update()
tuple[bytes, bytes] cryptography.hazmat.primitives.padding._byte_padding_update (bytes | None buffer_, bytes data, int block_size) protected
_byte_unpadding_check()
bytes cryptography.hazmat.primitives.padding._byte_unpadding_check (bytes | None buffer_, int block_size, typing.Callable[[bytes], int] checkfn) protected
Referenced by cryptography.hazmat.primitives.padding._ANSIX923UnpaddingContext.finalize(), and cryptography.hazmat.primitives.padding._PKCS7UnpaddingContext.finalize().
_byte_unpadding_update()
tuple[bytes, bytes] cryptography.hazmat.primitives.padding._byte_unpadding_update (bytes | None buffer_, bytes data, int block_size) protected