Django Project: waitress.proxy_headers Namespace Reference
waitress.proxy_headers Namespace Reference
Classes
class MalformedProxyHeader
Functions
proxy_headers_middleware (app, trusted_proxy=None, trusted_proxy_count=1, trusted_proxy_headers=None, clear_untrusted=True, log_untrusted=False, logger=logger)
parse_proxy_headers (environ, trusted_proxy_count, trusted_proxy_headers, logger=logger)
strip_brackets (addr)
clear_untrusted_headers (environ, untrusted_headers, log_warning=False, logger=logger)
Variables
PROXY_HEADERS
Forwarded = namedtuple("Forwarded", ["by", "for_", "host", "proto"])
Function Documentation
clear_untrusted_headers()
waitress.proxy_headers.clear_untrusted_headers (environ, untrusted_headers, log_warning = False, logger = logger)
Referenced by waitress.proxy_headers.proxy_headers_middleware().
parse_proxy_headers()
waitress.proxy_headers.parse_proxy_headers (environ, trusted_proxy_count, trusted_proxy_headers, logger = logger)
References waitress.proxy_headers.Forwarded, and waitress.proxy_headers.strip_brackets().
Referenced by waitress.proxy_headers.proxy_headers_middleware().
proxy_headers_middleware()
waitress.proxy_headers.proxy_headers_middleware (app, trusted_proxy = None, trusted_proxy_count = 1, trusted_proxy_headers = None, clear_untrusted = True, log_untrusted = False, logger = logger)
References waitress.proxy_headers.clear_untrusted_headers(), and waitress.proxy_headers.parse_proxy_headers().
strip_brackets()
waitress.proxy_headers.strip_brackets (addr)
Referenced by waitress.proxy_headers.parse_proxy_headers().
Variable Documentation
Forwarded
waitress.proxy_headers.Forwarded = namedtuple("Forwarded", ["by", "for_", "host", "proto"])
Referenced by waitress.proxy_headers.parse_proxy_headers().
PROXY_HEADERS
waitress.proxy_headers.PROXY_HEADERS
Initial value:
=  frozenset(
    {
        "X_FORWARDED_FOR",
        "X_FORWARDED_HOST",
        "X_FORWARDED_PROTO",
        "X_FORWARDED_PORT",
        "X_FORWARDED_BY",
        "FORWARDED",
    }
)