Django Project: pkg_resources._vendor.appdirs Namespace Reference
pkg_resources._vendor.appdirs Namespace Reference
Classes
class AppDirs
Functions
user_data_dir (appname=None, appauthor=None, version=None, roaming=False)
site_data_dir (appname=None, appauthor=None, version=None, multipath=False)
user_config_dir (appname=None, appauthor=None, version=None, roaming=False)
site_config_dir (appname=None, appauthor=None, version=None, multipath=False)
user_cache_dir (appname=None, appauthor=None, version=None, opinion=True)
user_state_dir (appname=None, appauthor=None, version=None, roaming=False)
user_log_dir (appname=None, appauthor=None, version=None, opinion=True)
_get_win_folder_from_registry (csidl_name)
_get_win_folder_with_pywin32 (csidl_name)
_get_win_folder_with_ctypes (csidl_name)
_get_win_folder_with_jna (csidl_name)
Variables
int PY3 = 3
unicode = str
os_name = platform.java_ver()[3][0]
str system = 'win32'
_get_win_folder = _get_win_folder_with_pywin32
str appname = "MyApp"
str appauthor = "MyCompany"
tuple props
dirs = AppDirs(appname, appauthor, version="1.0")
Detailed Description
Utilities for determining application-specific dirs.
See <http://github.com/ActiveState/appdirs> for details and usage.
Function Documentation
_get_win_folder_from_registry()
pkg_resources._vendor.appdirs._get_win_folder_from_registry (csidl_name) protected
This is a fallback technique at best. I'm not sure if using the
registry for this guarantees us the correct answer for all CSIDL_*
names.
_get_win_folder_with_ctypes()
pkg_resources._vendor.appdirs._get_win_folder_with_ctypes (csidl_name) protected
_get_win_folder_with_jna()
pkg_resources._vendor.appdirs._get_win_folder_with_jna (csidl_name) protected
_get_win_folder_with_pywin32()
pkg_resources._vendor.appdirs._get_win_folder_with_pywin32 (csidl_name) protected
References pkg_resources._vendor.appdirs.unicode.
site_config_dir()
pkg_resources._vendor.appdirs.site_config_dir (appname = None, appauthor = None, version = None, multipath = False)
Return full path to the user-shared data dir for this application.
"appname" is the name of application.
    If None, just the system directory is returned.
"appauthor" (only used on Windows) is the name of the
    appauthor or distributing body for this application. Typically
    it is the owning company name. This falls back to appname. You may
    pass False to disable it.
"version" is an optional version path element to append to the
    path. You might want to use this if you want multiple versions
    of your app to be able to run independently. If used, this
    would typically be "<major>.<minor>".
    Only applied when appname is present.
"multipath" is an optional parameter only applicable to *nix
    which indicates that the entire list of config dirs should be
    returned. By default, the first item from XDG_CONFIG_DIRS is
    returned, or '/etc/xdg/<AppName>', if XDG_CONFIG_DIRS is not set
Typical site config directories are:
Mac OS X:   same as site_data_dir
Unix:       /etc/xdg/<AppName> or $XDG_CONFIG_DIRS[i]/<AppName> for each value in
            $XDG_CONFIG_DIRS
Win *:      same as site_data_dir
Vista:      (Fail! "C:\ProgramData" is a hidden *system* directory on Vista.)
For Unix, this is using the $XDG_CONFIG_DIRS[0] default, if multipath=False
WARNING: Do not use this on Windows. See the Vista-Fail note above for why.
References pkg_resources._vendor.appdirs.site_data_dir().
site_data_dir()
pkg_resources._vendor.appdirs.site_data_dir (appname = None, appauthor = None, version = None, multipath = False)
Return full path to the user-shared data dir for this application.
"appname" is the name of application.
    If None, just the system directory is returned.
"appauthor" (only used on Windows) is the name of the
    appauthor or distributing body for this application. Typically
    it is the owning company name. This falls back to appname. You may
    pass False to disable it.
"version" is an optional version path element to append to the
    path. You might want to use this if you want multiple versions
    of your app to be able to run independently. If used, this
    would typically be "<major>.<minor>".
    Only applied when appname is present.
"multipath" is an optional parameter only applicable to *nix
    which indicates that the entire list of data dirs should be
    returned. By default, the first item from XDG_DATA_DIRS is
    returned, or '/usr/local/share/<AppName>',
    if XDG_DATA_DIRS is not set
Typical site data directories are:
Mac OS X:   /Library/Application Support/<AppName>
Unix:       /usr/local/share/<AppName> or /usr/share/<AppName>
Win XP:     C:\Documents and Settings\All Users\Application Data\<AppAuthor>\<AppName>
Vista:      (Fail! "C:\ProgramData" is a hidden *system* directory on Vista.)
Win 7:      C:\ProgramData\<AppAuthor>\<AppName>   # Hidden, but writeable on Win 7.
For Unix, this is using the $XDG_DATA_DIRS[0] default.
WARNING: Do not use this on Windows. See the Vista-Fail note above for why.
References pkg_resources._vendor.appdirs._get_win_folder.
Referenced by pkg_resources._vendor.appdirs.site_config_dir().
user_cache_dir()
pkg_resources._vendor.appdirs.user_cache_dir (appname = None, appauthor = None, version = None, opinion = True)
Return full path to the user-specific cache dir for this application.
"appname" is the name of application.
    If None, just the system directory is returned.
"appauthor" (only used on Windows) is the name of the
    appauthor or distributing body for this application. Typically
    it is the owning company name. This falls back to appname. You may
    pass False to disable it.
"version" is an optional version path element to append to the
    path. You might want to use this if you want multiple versions
    of your app to be able to run independently. If used, this
    would typically be "<major>.<minor>".
    Only applied when appname is present.
"opinion" (boolean) can be False to disable the appending of
    "Cache" to the base app data dir for Windows. See
    discussion below.
Typical user cache directories are:
Mac OS X:   ~/Library/Caches/<AppName>
Unix:       ~/.cache/<AppName> (XDG default)
Win XP:     C:\Documents and Settings\<username>\Local Settings\Application Data\<AppAuthor>\<AppName>\Cache
Vista:      C:\Users\<username>\AppData\Local\<AppAuthor>\<AppName>\Cache
On Windows the only suggestion in the MSDN docs is that local settings go in
the `CSIDL_LOCAL_APPDATA` directory. This is identical to the non-roaming
app data dir (the default returned by `user_data_dir` above). Apps typically
put cache data somewhere *under* the given dir here. Some examples:
...\Mozilla\Firefox\Profiles\<ProfileName>\Cache
...\Acme\SuperApp\Cache\1.0
OPINION: This function appends "Cache" to the `CSIDL_LOCAL_APPDATA` value.
This can be disabled with the `opinion=False` option.
References pkg_resources._vendor.appdirs._get_win_folder.
Referenced by pkg_resources._vendor.appdirs.user_log_dir().
user_config_dir()
pkg_resources._vendor.appdirs.user_config_dir (appname = None, appauthor = None, version = None, roaming = False)
Return full path to the user-specific config dir for this application.
"appname" is the name of application.
    If None, just the system directory is returned.
"appauthor" (only used on Windows) is the name of the
    appauthor or distributing body for this application. Typically
    it is the owning company name. This falls back to appname. You may
    pass False to disable it.
"version" is an optional version path element to append to the
    path. You might want to use this if you want multiple versions
    of your app to be able to run independently. If used, this
    would typically be "<major>.<minor>".
    Only applied when appname is present.
"roaming" (boolean, default False) can be set True to use the Windows
    roaming appdata directory. That means that for users on a Windows
    network setup for roaming profiles, this user data will be
    sync'd on login. See
    <http://technet.microsoft.com/en-us/library/cc766489(WS.10).aspx>
    for a discussion of issues.
Typical user config directories are:
Mac OS X:               same as user_data_dir
Unix:                   ~/.config/<AppName>     # or in $XDG_CONFIG_HOME, if defined
Win *:                  same as user_data_dir
For Unix, we follow the XDG spec and support $XDG_CONFIG_HOME.
That means, by default "~/.config/<AppName>".
References pkg_resources._vendor.appdirs.user_data_dir().
user_data_dir()
pkg_resources._vendor.appdirs.user_data_dir (appname = None, appauthor = None, version = None, roaming = False)
Return full path to the user-specific data dir for this application.
"appname" is the name of application.
    If None, just the system directory is returned.
"appauthor" (only used on Windows) is the name of the
    appauthor or distributing body for this application. Typically
    it is the owning company name. This falls back to appname. You may
    pass False to disable it.
"version" is an optional version path element to append to the
    path. You might want to use this if you want multiple versions
    of your app to be able to run independently. If used, this
    would typically be "<major>.<minor>".
    Only applied when appname is present.
"roaming" (boolean, default False) can be set True to use the Windows
    roaming appdata directory. That means that for users on a Windows
    network setup for roaming profiles, this user data will be
    sync'd on login. See
    <http://technet.microsoft.com/en-us/library/cc766489(WS.10).aspx>
    for a discussion of issues.
Typical user data directories are:
Mac OS X:               ~/Library/Application Support/<AppName>
Unix:                   ~/.local/share/<AppName>    # or in $XDG_DATA_HOME, if defined
Win XP (not roaming):   C:\Documents and Settings\<username>\Application Data\<AppAuthor>\<AppName>
Win XP (roaming):       C:\Documents and Settings\<username>\Local Settings\Application Data\<AppAuthor>\<AppName>
Win 7  (not roaming):   C:\Users\<username>\AppData\Local\<AppAuthor>\<AppName>
Win 7  (roaming):       C:\Users\<username>\AppData\Roaming\<AppAuthor>\<AppName>
For Unix, we follow the XDG spec and support $XDG_DATA_HOME.
That means, by default "~/.local/share/<AppName>".
References pkg_resources._vendor.appdirs._get_win_folder.
Referenced by pkg_resources._vendor.appdirs.user_config_dir(), pkg_resources._vendor.appdirs.user_log_dir(), and pkg_resources._vendor.appdirs.user_state_dir().
user_log_dir()
pkg_resources._vendor.appdirs.user_log_dir (appname = None, appauthor = None, version = None, opinion = True)
Return full path to the user-specific log dir for this application.
"appname" is the name of application.
    If None, just the system directory is returned.
"appauthor" (only used on Windows) is the name of the
    appauthor or distributing body for this application. Typically
    it is the owning company name. This falls back to appname. You may
    pass False to disable it.
"version" is an optional version path element to append to the
    path. You might want to use this if you want multiple versions
    of your app to be able to run independently. If used, this
    would typically be "<major>.<minor>".
    Only applied when appname is present.
"opinion" (boolean) can be False to disable the appending of
    "Logs" to the base app data dir for Windows, and "log" to the
    base cache dir for Unix. See discussion below.
Typical user log directories are:
Mac OS X:   ~/Library/Logs/<AppName>
Unix:       ~/.cache/<AppName>/log  # or under $XDG_CACHE_HOME if defined
Win XP:     C:\Documents and Settings\<username>\Local Settings\Application Data\<AppAuthor>\<AppName>\Logs
Vista:      C:\Users\<username>\AppData\Local\<AppAuthor>\<AppName>\Logs
On Windows the only suggestion in the MSDN docs is that local settings
go in the `CSIDL_LOCAL_APPDATA` directory. (Note: I'm interested in
examples of what some windows apps use for a logs dir.)
OPINION: This function appends "Logs" to the `CSIDL_LOCAL_APPDATA`
value for Windows and appends "log" to the user cache dir for Unix.
This can be disabled with the `opinion=False` option.
References pkg_resources._vendor.appdirs.user_cache_dir(), and pkg_resources._vendor.appdirs.user_data_dir().
user_state_dir()
pkg_resources._vendor.appdirs.user_state_dir (appname = None, appauthor = None, version = None, roaming = False)
Return full path to the user-specific state dir for this application.
"appname" is the name of application.
    If None, just the system directory is returned.
"appauthor" (only used on Windows) is the name of the
    appauthor or distributing body for this application. Typically
    it is the owning company name. This falls back to appname. You may
    pass False to disable it.
"version" is an optional version path element to append to the
    path. You might want to use this if you want multiple versions
    of your app to be able to run independently. If used, this
    would typically be "<major>.<minor>".
    Only applied when appname is present.
"roaming" (boolean, default False) can be set True to use the Windows
    roaming appdata directory. That means that for users on a Windows
    network setup for roaming profiles, this user data will be
    sync'd on login. See
    <http://technet.microsoft.com/en-us/library/cc766489(WS.10).aspx>
    for a discussion of issues.
Typical user state directories are:
Mac OS X:  same as user_data_dir
Unix:      ~/.local/state/<AppName>   # or in $XDG_STATE_HOME, if defined
Win *:     same as user_data_dir
For Unix, we follow this Debian proposal <https://wiki.debian.org/XDGBaseDirectorySpecification#state>
to extend the XDG spec and support $XDG_STATE_HOME.
That means, by default "~/.local/state/<AppName>".
References pkg_resources._vendor.appdirs.user_data_dir().
Variable Documentation
_get_win_folder
pkg_resources._vendor.appdirs._get_win_folder = _get_win_folder_with_pywin32 protected
Referenced by pkg_resources._vendor.appdirs.site_data_dir(), pkg_resources._vendor.appdirs.user_cache_dir(), and pkg_resources._vendor.appdirs.user_data_dir().
appauthor
str pkg_resources._vendor.appdirs.appauthor = "MyCompany"
appname
str pkg_resources._vendor.appdirs.appname = "MyApp"
dirs
pkg_resources._vendor.appdirs.dirs = AppDirs(appname, appauthor, version="1.0")
os_name
pkg_resources._vendor.appdirs.os_name = platform.java_ver()[3][0]
props
tuple pkg_resources._vendor.appdirs.props
Initial value:
=  ("user_data_dir",
             "user_config_dir",
             "user_cache_dir",
             "user_state_dir",
             "user_log_dir",
             "site_data_dir",
             "site_config_dir")
PY3
int pkg_resources._vendor.appdirs.PY3 = 3
system
str pkg_resources._vendor.appdirs.system = 'win32'
unicode
pkg_resources._vendor.appdirs.unicode = str
Referenced by pkg_resources._vendor.appdirs._get_win_folder_with_pywin32().