Django Project: pkg_resources Namespace Reference
pkg_resources Namespace Reference
Namespaces
namespace _vendor
namespace extern
Classes
class _ReqExtras
class ContextualVersionConflict
class DefaultProvider
class DistInfoDistribution
class Distribution
class DistributionNotFound
class EggInfoDistribution
class EggMetadata
class EggProvider
class EmptyProvider
class EntryPoint
class Environment
class ExtractionError
class FileMetadata
class IMetadataProvider
class IResourceProvider
class MemoizedZipManifests
class NoDists
class NullProvider
class PathMetadata
class PEP440Warning
class PkgResourcesDeprecationWarning
class Requirement
class RequirementParseError
class ResolutionError
class ResourceManager
class UnknownExtra
class VersionConflict
class WorkingSet
class ZipManifests
class ZipProvider
Functions
parse_version (v)
_declare_state (vartype, **kw)
__getstate__ ()
__setstate__ (state)
_sget_dict (val)
_sset_dict (key, ob, state)
_sget_object (val)
_sset_object (key, ob, state)
get_supported_platform ()
register_loader_type (loader_type, provider_factory)
get_provider (moduleOrReq)
_macos_vers (_cache=[])
_macos_arch (machine)
get_build_platform ()
compatible_platforms (provided, required)
run_script (dist_spec, script_name)
get_distribution (dist)
load_entry_point (dist, group, name)
get_entry_map (dist, group=None)
get_entry_info (dist, group, name)
get_default_cache ()
safe_name (name)
safe_version (version)
safe_extra (extra)
to_filename (name)
invalid_marker (text)
evaluate_marker (text, extra=None)
_parents (path)
register_finder (importer_type, distribution_finder)
find_distributions (path_item, only=False)
find_eggs_in_zip (importer, path_item, only=False)
find_nothing (importer, path_item, only=False)
_by_version_descending (names)
find_on_path (importer, path_item, only=False)
dist_factory (path_item, entry, only)
safe_listdir (path)
distributions_from_metadata (path)
non_empty_lines (path)
resolve_egg_link (path)
register_namespace_handler (importer_type, namespace_handler)
_handle_ns (packageName, path_item)
_rebuild_mod_path (orig_path, package_name, module)
declare_namespace (packageName)
fixup_namespace_packages (path_item, parent=None)
file_ns_handler (importer, path_item, packageName, module)
null_ns_handler (importer, path_item, packageName, module)
normalize_path (filename)
_cygwin_patch (filename)
_normalize_cached (filename, _cache={})
_is_egg_path (path)
_is_zip_egg (path)
_is_unpacked_egg (path)
_set_parent_ns (packageName)
_version_from_file (lines)
issue_warning (*args, **kw)
parse_requirements (strs)
_always_object (classes)
_find_adapter (registry, ob)
ensure_directory (path)
_bypass_ensure_directory (path)
split_sections (s)
_mkstemp (*args, **kw)
_call_aside (f, *args, **kwargs)
_initialize (g=globals())
_initialize_master_working_set ()
Variables
FileExistsError = OSError
bool WRITE_SUPPORT = True
importlib_machinery = None
require = None
working_set = None
add_activation_listener = None
resources_stream = None
cleanup_resources = None
resource_dir = None
resource_stream = None
set_extraction_path = None
resource_isdir = None
resource_string = None
iter_entry_points = None
resource_listdir = None
resource_filename = None
resource_exists = None
_distribution_finders = None
_namespace_handlers = None
_namespace_packages = None
dict _state_vars = {}
None _sget_none = lambda *args
dict _provider_factories = {}
str PY_MAJOR = '{}.{}'.format(*sys.version_info)
int EGG_DIST = 3
int BINARY_DIST = 2
int SOURCE_DIST = 1
int CHECKOUT_DIST = 0
int DEVELOP_DIST = -1
macosVersionString = re.compile(r"macosx-(\d+)\.(\d+)-(.*)")
darwinVersionString = re.compile(r"darwin-(\d+)\.(\d+)\.(\d+)-(.*)")
get_platform = get_build_platform
run_main = run_script
AvailableDistributions = Environment
empty_provider = EmptyProvider()
MODULE = re.compile(r"\w+(\.\w+)*$").match
EGG_NAME
dict _distributionImpl
category
PEP440Warning
append
Detailed Description
Package resource API
--------------------
A resource is a logical file contained within a package, or a logical
subdirectory thereof.  The package resource API expects resource names
to have their path parts separated with ``/``, *not* whatever the local
path separator is.  Do not use os.path operations to manipulate resource
names being passed into the API.
The package resource API is designed to work with normal filesystem packages,
.egg files, and unpacked .egg files.  It can also work in a limited way with
.zip files and with custom PEP 302 loaders that support the ``get_data()``
method.
Function Documentation
__getstate__()
pkg_resources.__getstate__ ()
Referenced by setuptools.sandbox.save_pkg_resources_state().
__setstate__()
pkg_resources.__setstate__ (state)
Referenced by setuptools.sandbox.save_pkg_resources_state().
_always_object()
pkg_resources._always_object (classes) protected
Ensure object appears in the mro even
for old-style classes.
_by_version_descending()
pkg_resources._by_version_descending (names) protected
Given a list of filenames, return them in descending order
by version number.
>>> names = 'bar', 'foo', 'Python-2.7.10.egg', 'Python-2.7.2.egg'
>>> _by_version_descending(names)
['Python-2.7.10.egg', 'Python-2.7.2.egg', 'bar', 'foo']
>>> names = 'Setuptools-1.2.3b1.egg', 'Setuptools-1.2.3.egg'
>>> _by_version_descending(names)
['Setuptools-1.2.3.egg', 'Setuptools-1.2.3b1.egg']
>>> names = 'Setuptools-1.2.3b1.egg', 'Setuptools-1.2.3.post1.egg'
>>> _by_version_descending(names)
['Setuptools-1.2.3.post1.egg', 'Setuptools-1.2.3b1.egg']
_bypass_ensure_directory()
pkg_resources._bypass_ensure_directory (path) protected
Sandbox-bypassing version of ensure_directory()
_call_aside()
pkg_resources._call_aside (f, * args, ** kwargs) protected
_cygwin_patch()
pkg_resources._cygwin_patch (filename) protected
Contrary to POSIX 2008, on Cygwin, getcwd (3) contains
symlink components. Using
os.path.abspath() works around this limitation. A fix in os.getcwd()
would probably better, in Cygwin even more so, except
that this seems to be by design...
_declare_state()
pkg_resources._declare_state (vartype, ** kw) protected
_find_adapter()
pkg_resources._find_adapter (registry, ob) protected
Return an adapter factory for `ob` from `registry`
Referenced by get_provider().
_handle_ns()
pkg_resources._handle_ns (packageName, path_item) protected
Ensure that named package includes a subpath of path_item (if needed)
_initialize()
pkg_resources._initialize (g = globals()) protected
_initialize_master_working_set()
pkg_resources._initialize_master_working_set () protected
Prepare the master working set and make the ``require()``
API available.
This function has explicit effects on the global state
of pkg_resources. It is intended to be invoked once at
the initialization of this module.
Invocation by other packages is unsupported and done
at their own risk.
_is_egg_path()
pkg_resources._is_egg_path (path) protected
Determine if given path appears to be an egg.
_is_unpacked_egg()
pkg_resources._is_unpacked_egg (path) protected
Determine if given path appears to be an unpacked egg.
_is_zip_egg()
pkg_resources._is_zip_egg (path) protected
_macos_arch()
pkg_resources._macos_arch (machine) protected
Referenced by get_build_platform().
_macos_vers()
pkg_resources._macos_vers (_cache = []) protected
Referenced by get_build_platform(), and get_supported_platform().
_mkstemp()
pkg_resources._mkstemp (* args, ** kw) protected
_normalize_cached()
pkg_resources._normalize_cached (filename, _cache = {}) protected
_parents()
pkg_resources._parents (path) protected
yield all parents of path including path
_rebuild_mod_path()
pkg_resources._rebuild_mod_path (orig_path, package_name, module) protected
Rebuild module.__path__ ensuring that all entries are ordered
corresponding to their sys.path order
_set_parent_ns()
pkg_resources._set_parent_ns (packageName) protected
_sget_dict()
pkg_resources._sget_dict (val) protected
_sget_object()
pkg_resources._sget_object (val) protected
_sset_dict()
pkg_resources._sset_dict (key, ob, state) protected
_sset_object()
pkg_resources._sset_object (key, ob, state) protected
_version_from_file()
pkg_resources._version_from_file (lines) protected
Given an iterable of lines from a Metadata file, return
the value of the Version field, if present, or None otherwise.
compatible_platforms()
pkg_resources.compatible_platforms (provided, required)
Can code for the `provided` platform run on the `required` platform?
Returns true if either platform is ``None``, or the platforms are equal.
XXX Needs compatibility checks for Linux and other unixy OSes.
declare_namespace()
pkg_resources.declare_namespace (packageName)
Declare that package 'packageName' is a namespace package
dist_factory()
pkg_resources.dist_factory (path_item, entry, only)
Return a dist_factory for the given entry.
distributions_from_metadata()
pkg_resources.distributions_from_metadata (path)
ensure_directory()
pkg_resources.ensure_directory (path)
Ensure that the parent directory of `path` exists
evaluate_marker()
pkg_resources.evaluate_marker (text, extra = None)
Evaluate a PEP 508 environment marker.
Return a boolean indicating the marker result in this environment.
Raise SyntaxError if marker is invalid.
This implementation uses the 'pyparsing' module.
file_ns_handler()
pkg_resources.file_ns_handler (importer, path_item, packageName, module)
Compute an ns-package subpath for a filesystem or zipfile importer
find_distributions()
pkg_resources.find_distributions (path_item, only = False)
Yield distributions accessible via `path_item`
Referenced by setuptools.installer.fetch_build_egg().
find_eggs_in_zip()
pkg_resources.find_eggs_in_zip (importer, path_item, only = False)
Find eggs in zip files; possibly multiple nested eggs.
find_nothing()
pkg_resources.find_nothing (importer, path_item, only = False)
find_on_path()
pkg_resources.find_on_path (importer, path_item, only = False)
Yield distributions accessible on a sys.path directory
fixup_namespace_packages()
pkg_resources.fixup_namespace_packages (path_item, parent = None)
Ensure that previously-declared namespace packages include path_item
get_build_platform()
pkg_resources.get_build_platform ()
Return this platform's string for platform-specific distributions
XXX Currently this is the same as ``distutils.util.get_platform()``, but it
needs some hacks for Linux and macOS.
References _macos_arch(), and _macos_vers().
get_default_cache()
pkg_resources.get_default_cache ()
Return the ``PYTHON_EGG_CACHE`` environment variable
or a platform-relevant user cache dir for an app
named "Python-Eggs".
get_distribution()
pkg_resources.get_distribution (dist)
Return a current distribution object for a Requirement or string
References get_provider().
Referenced by setuptools.installer.fetch_build_egg().
get_entry_info()
pkg_resources.get_entry_info (dist, group, name)
Return the EntryPoint object for `group`+`name`, or ``None``
get_entry_map()
pkg_resources.get_entry_map (dist, group = None)
Return the entry point map for `group`, or the full entry map
get_provider()
pkg_resources.get_provider (moduleOrReq)
Return an IResourceProvider for the named module or requirement
References _find_adapter().
Referenced by get_distribution().
get_supported_platform()
pkg_resources.get_supported_platform ()
Return this platform's maximum compatible version.
distutils.util.get_platform() normally reports the minimum version
of macOS that would be required to *use* extensions produced by
distutils.  But what we want when checking compatibility is to know the
version of macOS that we are *running*.  To allow usage of packages that
explicitly require a newer version of macOS, we must also know the
current version of the OS.
If this condition occurs for any other platform with a version in its
platform strings, this function should be extended accordingly.
References _macos_vers().
invalid_marker()
pkg_resources.invalid_marker (text)
Validate text as a PEP 508 environment marker; return an exception
if invalid or False otherwise.
Referenced by setuptools.dist._check_extra().
issue_warning()
pkg_resources.issue_warning (* args, ** kw)
load_entry_point()
pkg_resources.load_entry_point (dist, group, name)
Return `name` entry point of `group` for `dist` or raise ImportError
non_empty_lines()
pkg_resources.non_empty_lines (path)
Yield non-empty lines from file at path
normalize_path()
pkg_resources.normalize_path (filename)
Normalize a file/dir name for comparison purposes
Referenced by setuptools.command.develop.develop._resolve_setup_path().
null_ns_handler()
pkg_resources.null_ns_handler (importer, path_item, packageName, module)
parse_requirements()
pkg_resources.parse_requirements (strs)
Yield ``Requirement`` objects for each specification in `strs`.
`strs` must be a string, or a (possibly-nested) iterable thereof.
parse_version()
pkg_resources.parse_version (v)
register_finder()
pkg_resources.register_finder (importer_type, distribution_finder)
Register `distribution_finder` to find distributions in sys.path items
`importer_type` is the type or class of a PEP 302 "Importer" (sys.path item
handler), and `distribution_finder` is a callable that, passed a path
item and the importer instance, yields ``Distribution`` instances found on
that path item.  See ``pkg_resources.find_on_path`` for an example.
register_loader_type()
pkg_resources.register_loader_type (loader_type, provider_factory)
Register `provider_factory` to make providers for `loader_type`
`loader_type` is the type or class of a PEP 302 ``module.__loader__``,
and `provider_factory` is a function that, passed a *module* object,
returns an ``IResourceProvider`` for that module.
register_namespace_handler()
pkg_resources.register_namespace_handler (importer_type, namespace_handler)
Register `namespace_handler` to declare namespace packages
`importer_type` is the type or class of a PEP 302 "Importer" (sys.path item
handler), and `namespace_handler` is a callable like this::
    def namespace_handler(importer, path_entry, moduleName, module):
        # return a path_entry to use for child packages
Namespace handlers are only called if the importer object has already
agreed that it can handle the relevant path item, and they should only
return a subpath if the module __path__ does not already contain an
equivalent subpath.  For an example namespace handler, see
``pkg_resources.file_ns_handler``.
resolve_egg_link()
pkg_resources.resolve_egg_link (path)
Given a path to an .egg-link, resolve distributions
present in the referenced path.
run_script()
pkg_resources.run_script (dist_spec, script_name)
Locate distribution `dist_spec` and run its `script_name` script
References run_script().
Referenced by run_script().
safe_extra()
pkg_resources.safe_extra (extra)
Convert an arbitrary string to a standard 'extra' name
Any runs of non-alphanumeric characters are replaced with a single '_',
and the result is always lowercased.
Referenced by pip._internal.metadata.pkg_resources.Distribution.is_extra_provided(), and pip._internal.metadata.pkg_resources.Distribution.iter_dependencies().
safe_listdir()
pkg_resources.safe_listdir (path)
Attempt to list contents of path, but suppress some exceptions.
safe_name()
pkg_resources.safe_name (name)
Convert an arbitrary string to a standard distribution name
Any runs of non-alphanumeric/. characters are replaced with a single '-'.
safe_version()
pkg_resources.safe_version (version)
Convert an arbitrary string to a standard version string
split_sections()
pkg_resources.split_sections (s)
Split a string or iterable thereof into (section, content) pairs
Each ``section`` is a stripped version of the section header ("[section]")
and each ``content`` is a list of stripped lines excluding blank lines and
comment-only lines.  If there are any such lines before the first section
header, they're returned in a first ``section`` of ``None``.
to_filename()
pkg_resources.to_filename (name)
Convert a project or version name to its filename-escaped form
Any '-' characters are currently replaced with '_'.
Variable Documentation
_distribution_finders
pkg_resources._distribution_finders = None protected
_distributionImpl
dict pkg_resources._distributionImpl protected
Initial value:
=  {
    '.egg': Distribution,
    '.egg-info': EggInfoDistribution,
    '.dist-info': DistInfoDistribution,
}
_namespace_handlers
pkg_resources._namespace_handlers = None protected
_namespace_packages
pkg_resources._namespace_packages = None protected
_provider_factories
dict pkg_resources._provider_factories = {} protected
_sget_none
None pkg_resources._sget_none = lambda *args protected
_state_vars
dict pkg_resources._state_vars = {} protected
add_activation_listener
pkg_resources.add_activation_listener = None
append
pkg_resources.append
Referenced by pkg_resources._vendor.more_itertools.more.bucket.__iter__(), pkg_resources._vendor.more_itertools.more.seekable.__next__(), pkg_resources._vendor.packaging.markers._evaluate_markers(), pkg_resources._vendor.more_itertools.more.bucket._get_values(), pkg_resources._vendor.pyparsing.core.ParserElement.add_condition(), pkg_resources._vendor.pyparsing.core.ParseExpression.append(), pkg_resources._vendor.pyparsing.results.ParseResults.append(), pkg_resources._vendor.pyparsing.core.ParserElement.ignore(), pkg_resources._vendor.more_itertools.more.map_reduce(), pkg_resources._vendor.more_itertools.more.peekable.peek(), and pkg_resources._vendor.pyparsing.core.ParserElement.suppress_warning().
AvailableDistributions
pkg_resources.AvailableDistributions = Environment
BINARY_DIST
int pkg_resources.BINARY_DIST = 2
category
pkg_resources.category
CHECKOUT_DIST
int pkg_resources.CHECKOUT_DIST = 0
cleanup_resources
pkg_resources.cleanup_resources = None
darwinVersionString
pkg_resources.darwinVersionString = re.compile(r"darwin-(\d+)\.(\d+)\.(\d+)-(.*)")
DEVELOP_DIST
int pkg_resources.DEVELOP_DIST = -1
EGG_DIST
int pkg_resources.EGG_DIST = 3
EGG_NAME
pkg_resources.EGG_NAME
Initial value:
=  re.compile(
    ,
    re.VERBOSE | re.IGNORECASE,
).match
empty_provider
pkg_resources.empty_provider = EmptyProvider()
FileExistsError
pkg_resources.FileExistsError = OSError
get_platform
pkg_resources.get_platform = get_build_platform
importlib_machinery
pkg_resources.importlib_machinery = None
iter_entry_points
pkg_resources.iter_entry_points = None
macosVersionString
pkg_resources.macosVersionString = re.compile(r"macosx-(\d+)\.(\d+)-(.*)")
MODULE
pkg_resources.MODULE = re.compile(r"\w+(\.\w+)*$").match
PEP440Warning
pkg_resources.PEP440Warning
PY_MAJOR
str pkg_resources.PY_MAJOR = '{}.{}'.format(*sys.version_info)
require
pkg_resources.require = None
resource_dir
pkg_resources.resource_dir = None
resource_exists
pkg_resources.resource_exists = None
resource_filename
pkg_resources.resource_filename = None
resource_isdir
pkg_resources.resource_isdir = None
resource_listdir
pkg_resources.resource_listdir = None
resource_stream
pkg_resources.resource_stream = None
resource_string
pkg_resources.resource_string = None
resources_stream
pkg_resources.resources_stream = None
run_main
pkg_resources.run_main = run_script
set_extraction_path
pkg_resources.set_extraction_path = None
SOURCE_DIST
int pkg_resources.SOURCE_DIST = 1
working_set
pkg_resources.working_set = None
WRITE_SUPPORT
bool pkg_resources.WRITE_SUPPORT = True