Django Project: pip._vendor.platformdirs.windows Namespace Reference
pip._vendor.platformdirs.windows Namespace Reference
Classes
class Windows
Functions
str get_win_folder_from_env_vars (str csidl_name)
str|None get_win_folder_if_csidl_name_not_env_var (str csidl_name)
str get_win_folder_from_registry (str csidl_name)
str get_win_folder_via_ctypes (str csidl_name)
Callable[[str], str] _pick_get_win_folder ()
Variables
get_win_folder = lru_cache(maxsize=None)(_pick_get_win_folder())
Detailed Description
Windows.
Function Documentation
_pick_get_win_folder()
Callable[[str], str] pip._vendor.platformdirs.windows._pick_get_win_folder () protected
get_win_folder_from_env_vars()
str pip._vendor.platformdirs.windows.get_win_folder_from_env_vars (str csidl_name)
Get folder from environment variables.
References pip._vendor.platformdirs.windows.get_win_folder_if_csidl_name_not_env_var().
get_win_folder_from_registry()
str pip._vendor.platformdirs.windows.get_win_folder_from_registry (str csidl_name)
Get folder from the registry.
This is a fallback technique at best. I'm not sure if using the registry for these guarantees us the correct answer
for all CSIDL_* names.
get_win_folder_if_csidl_name_not_env_var()
str | None pip._vendor.platformdirs.windows.get_win_folder_if_csidl_name_not_env_var (str csidl_name)
Get folder for a CSIDL name that does not exist as an environment variable.
Referenced by pip._vendor.platformdirs.windows.get_win_folder_from_env_vars().
get_win_folder_via_ctypes()
str pip._vendor.platformdirs.windows.get_win_folder_via_ctypes (str csidl_name)
Get folder with ctypes.
Variable Documentation
get_win_folder
pip._vendor.platformdirs.windows.get_win_folder = lru_cache(maxsize=None)(_pick_get_win_folder())
Referenced by pip._vendor.platformdirs.windows.Windows.site_cache_dir(), pip._vendor.platformdirs.windows.Windows.site_data_dir(), pip._vendor.platformdirs.windows.Windows.user_cache_dir(), pip._vendor.platformdirs.windows.Windows.user_data_dir(), pip._vendor.platformdirs.windows.Windows.user_documents_dir(), pip._vendor.platformdirs.windows.Windows.user_downloads_dir(), pip._vendor.platformdirs.windows.Windows.user_music_dir(), pip._vendor.platformdirs.windows.Windows.user_pictures_dir(), pip._vendor.platformdirs.windows.Windows.user_runtime_dir(), and pip._vendor.platformdirs.windows.Windows.user_videos_dir().