Django Project: setuptools Namespace Reference
setuptools Namespace Reference
Namespaces
namespace _deprecation_warning
namespace _distutils
namespace _entry_points
namespace _imp
namespace _importlib
namespace _itertools
namespace _path
namespace _reqs
namespace _vendor
namespace archive_util
namespace build_meta
namespace command
namespace config
namespace dep_util
namespace depends
namespace discovery
namespace dist
namespace errors
namespace extension
namespace extern
namespace glob
namespace installer
namespace launch
namespace logging
namespace monkey
namespace msvc
namespace namespaces
namespace package_index
namespace py34compat
namespace sandbox
namespace unicode_utils
namespace version
namespace wheel
namespace windows_support
Classes
class Command
class sic
Functions
_install_setup_requires (attrs)
setup (**attrs)
_find_all_simple (path)
findall (dir=os.curdir)
convert_path (pathname)
Variables
bootstrap_install_from = None
find_packages = PackageFinder.find
find_namespace_packages = PEP420PackageFinder.find
_Command = monkey.get_unpatched(distutils.core.Command)
Detailed Description
Extensions to the 'distutils' for large or complex distributions
Function Documentation
_find_all_simple()
setuptools._find_all_simple (path) protected
Find all files under 'path'
Referenced by findall().
_install_setup_requires()
setuptools._install_setup_requires (attrs) protected
Referenced by setup().
convert_path()
setuptools.convert_path (pathname)
findall()
setuptools.findall (dir = os.curdir)
Find all files under 'dir' and return the list of full filenames.
Unless dir is '.', return full filenames with dir prepended.
References _find_all_simple().
Referenced by setuptools._distutils.command.sdist.sdist.get_file_list().
setup()
setuptools.setup (** attrs)
References _install_setup_requires().
Variable Documentation
_Command
setuptools._Command = monkey.get_unpatched(distutils.core.Command) protected
bootstrap_install_from
setuptools.bootstrap_install_from = None
find_namespace_packages
setuptools.find_namespace_packages = PEP420PackageFinder.find
find_packages
setuptools.find_packages = PackageFinder.find