Django Project: _pytest.monkeypatch Namespace Reference
_pytest.monkeypatch Namespace Reference
Classes
class MonkeyPatch
class Notset
Functions
Generator[MonkeyPatch, None, None] monkeypatch ()
object resolve (str name)
object annotated_getattr (object obj, str name, str ann)
tuple[str, object] derive_importpath (str import_path, bool raising)
Variables
RE_IMPORT_ERROR_NAME = re.compile(r"^No module named (.*)$")
K = TypeVar("K")
V = TypeVar("V")
notset = Notset()
Detailed Description
Monkeypatching and mocking functionality.
Function Documentation
annotated_getattr()
object _pytest.monkeypatch.annotated_getattr (object obj, str name, str ann)
Referenced by _pytest.monkeypatch.derive_importpath(), and _pytest.monkeypatch.resolve().
derive_importpath()
tuple[str, object] _pytest.monkeypatch.derive_importpath (str import_path, bool raising)
References _pytest.monkeypatch.annotated_getattr().
Referenced by _pytest.monkeypatch.MonkeyPatch.delattr(), and _pytest.monkeypatch.MonkeyPatch.setattr().
monkeypatch()
Generator[MonkeyPatch, None, None] _pytest.monkeypatch.monkeypatch ()
A convenient fixture for monkey-patching.
The fixture provides these methods to modify objects, dictionaries, or
:data:`os.environ`:
* :meth:`monkeypatch.setattr(obj, name, value, raising=True) <pytest.MonkeyPatch.setattr>`
* :meth:`monkeypatch.delattr(obj, name, raising=True) <pytest.MonkeyPatch.delattr>`
* :meth:`monkeypatch.setitem(mapping, name, value) <pytest.MonkeyPatch.setitem>`
* :meth:`monkeypatch.delitem(obj, name, raising=True) <pytest.MonkeyPatch.delitem>`
* :meth:`monkeypatch.setenv(name, value, prepend=None) <pytest.MonkeyPatch.setenv>`
* :meth:`monkeypatch.delenv(name, raising=True) <pytest.MonkeyPatch.delenv>`
* :meth:`monkeypatch.syspath_prepend(path) <pytest.MonkeyPatch.syspath_prepend>`
* :meth:`monkeypatch.chdir(path) <pytest.MonkeyPatch.chdir>`
* :meth:`monkeypatch.context() <pytest.MonkeyPatch.context>`
All modifications will be undone after the requesting test function or
fixture has finished. The ``raising`` parameter determines if a :class:`KeyError`
or :class:`AttributeError` will be raised if the set/deletion operation does not have the
specified target.
To undo modifications done by the fixture in a contained scope,
use :meth:`context() <pytest.MonkeyPatch.context>`.
resolve()
object _pytest.monkeypatch.resolve (str name)
References _pytest.monkeypatch.annotated_getattr().
Variable Documentation
K
_pytest.monkeypatch.K = TypeVar("K")
notset
_pytest.monkeypatch.notset = Notset()
RE_IMPORT_ERROR_NAME
_pytest.monkeypatch.RE_IMPORT_ERROR_NAME = re.compile(r"^No module named (.*)$")
V
_pytest.monkeypatch.V = TypeVar("V")