Django Project: pkg_resources._vendor.packaging.markers Namespace Reference
pkg_resources._vendor.packaging.markers Namespace Reference
Classes
class InvalidMarker
class Marker
class Node
class Op
class Undefined
class UndefinedComparison
class UndefinedEnvironmentName
class Value
class Variable
Functions
List[Any] _coerce_parse_result (Union[ParseResults, List[Any]] results)
str _format_marker (Union[List[str], Tuple[Node,...], str] marker, Optional[bool] first=True)
bool _eval_op (str lhs, Op op, str rhs)
str _get_env (Dict[str, str] environment, str name)
bool _evaluate_markers (List[Any] markers, Dict[str, str] environment)
str format_full_version ("sys._version_info" info)
Dict[str, str] default_environment ()
Variables
Operator = Callable[[str, str], bool]
tuple VARIABLE
dict ALIASES
tuple VERSION_CMP
tuple MARKER_OP = VERSION_CMP | L("not in") | L("in")
MARKER_VALUE = QuotedString("'") | QuotedString('"')
BOOLOP = L("and") | L("or")
tuple MARKER_VAR = VARIABLE | MARKER_VALUE
MARKER_ITEM = Group(MARKER_VAR + MARKER_OP + MARKER_VAR)
LPAREN = L("(").suppress()
RPAREN = L(")").suppress()
MARKER_EXPR = Forward()
MARKER_ATOM = MARKER_ITEM | Group(LPAREN + MARKER_EXPR + RPAREN)
MARKER = stringStart + MARKER_EXPR + stringEnd
dict _operators
_undefined = Undefined()
Function Documentation
_coerce_parse_result()
List[Any] pkg_resources._vendor.packaging.markers._coerce_parse_result (Union[ParseResults, List[Any]] results) protected
References pkg_resources._vendor.packaging.markers._coerce_parse_result().
Referenced by pkg_resources._vendor.packaging.markers._coerce_parse_result().
_eval_op()
bool pkg_resources._vendor.packaging.markers._eval_op (str lhs, Op op, str rhs) protected
Referenced by pkg_resources._vendor.packaging.markers._evaluate_markers().
_evaluate_markers()
bool pkg_resources._vendor.packaging.markers._evaluate_markers (List[Any] markers, Dict[str, str] environment) protected
References pkg_resources._vendor.packaging.markers._eval_op(), pkg_resources._vendor.packaging.markers._evaluate_markers(), pkg_resources._vendor.packaging.markers._get_env(), and pkg_resources.append.
Referenced by pkg_resources._vendor.packaging.markers._evaluate_markers(), and pkg_resources._vendor.packaging.markers.Marker.evaluate().
_format_marker()
str pkg_resources._vendor.packaging.markers._format_marker (Union[List[str], Tuple[Node, ...], str] marker, Optional[bool] first = True) protected
References pkg_resources._vendor.packaging.markers._format_marker().
Referenced by pkg_resources._vendor.packaging.markers.Marker.__str__(), and pkg_resources._vendor.packaging.markers._format_marker().
_get_env()
str pkg_resources._vendor.packaging.markers._get_env (Dict[str, str] environment, str name) protected
Referenced by pkg_resources._vendor.packaging.markers._evaluate_markers().
default_environment()
Dict[str, str] pkg_resources._vendor.packaging.markers.default_environment ()
References pkg_resources._vendor.packaging.markers.format_full_version().
format_full_version()
str pkg_resources._vendor.packaging.markers.format_full_version ("sys._version_info" info)
Referenced by pkg_resources._vendor.packaging.markers.default_environment().
Variable Documentation
_operators
dict pkg_resources._vendor.packaging.markers._operators protected
Initial value:
=  {
    "in": lambda lhs, rhs: lhs in rhs,
    "not in": lambda lhs, rhs: lhs not in rhs,
    "<": operator.lt,
    "<=": operator.le,
    "==": operator.eq,
    "!=": operator.ne,
    ">=": operator.ge,
    ">": operator.gt,
}
_undefined
pkg_resources._vendor.packaging.markers._undefined = Undefined() protected
ALIASES
dict pkg_resources._vendor.packaging.markers.ALIASES
Initial value:
=  {
    "os.name": "os_name",
    "sys.platform": "sys_platform",
    "platform.version": "platform_version",
    "platform.machine": "platform_machine",
    "platform.python_implementation": "platform_python_implementation",
    "python_implementation": "platform_python_implementation",
}
BOOLOP
pkg_resources._vendor.packaging.markers.BOOLOP = L("and") | L("or")
LPAREN
pkg_resources._vendor.packaging.markers.LPAREN = L("(").suppress()
MARKER
pkg_resources._vendor.packaging.markers.MARKER = stringStart + MARKER_EXPR + stringEnd
MARKER_ATOM
pkg_resources._vendor.packaging.markers.MARKER_ATOM = MARKER_ITEM | Group(LPAREN + MARKER_EXPR + RPAREN)
MARKER_EXPR
pkg_resources._vendor.packaging.markers.MARKER_EXPR = Forward()
MARKER_ITEM
pkg_resources._vendor.packaging.markers.MARKER_ITEM = Group(MARKER_VAR + MARKER_OP + MARKER_VAR)
MARKER_OP
tuple pkg_resources._vendor.packaging.markers.MARKER_OP = VERSION_CMP | L("not in") | L("in")
MARKER_VALUE
pkg_resources._vendor.packaging.markers.MARKER_VALUE = QuotedString("'") | QuotedString('"')
MARKER_VAR
tuple pkg_resources._vendor.packaging.markers.MARKER_VAR = VARIABLE | MARKER_VALUE
Operator
pkg_resources._vendor.packaging.markers.Operator = Callable[[str, str], bool]
RPAREN
pkg_resources._vendor.packaging.markers.RPAREN = L(")").suppress()
VARIABLE
tuple pkg_resources._vendor.packaging.markers.VARIABLE
Initial value:
=  (
    L("implementation_version")
    | L("platform_python_implementation")
    | L("implementation_name")
    | L("python_full_version")
    | L("platform_release")
    | L("platform_version")
    | L("platform_machine")
    | L("platform_system")
    | L("python_version")
    | L("sys_platform")
    | L("os_name")
    | L("os.name")  # PEP-345
    | L("sys.platform")  # PEP-345
    | L("platform.version")  # PEP-345
    | L("platform.machine")  # PEP-345
    | L("platform.python_implementation")  # PEP-345
    | L("python_implementation")  # undocumented setuptools legacy
    | L("extra")  # PEP-508
)
VERSION_CMP
tuple pkg_resources._vendor.packaging.markers.VERSION_CMP
Initial value:
=  (
    L("===") | L("==") | L(">=") | L("<=") | L("!=") | L("~=") | L(">") | L("<")
)