Django Project: setuptools.command.editable_wheel Namespace Reference
setuptools.command.editable_wheel Namespace Reference
Classes
class _EditableMode
class _LinkTree
class _NamespaceInstaller
class _StaticPth
class _TopLevelFinder
class editable_wheel
class EditableStrategy
class InformationOnly
class LinksNotSupported
Functions
bool _can_symlink_files (Path base_dir)
bool _simple_layout (Iterable[str] packages, Dict[str, str] package_dir, Path project_dir)
_parent_path (pkg, pkg_path)
Iterator[str] _find_packages (Distribution dist)
Iterator[str] _find_top_level_modules (Distribution dist)
Dict[str, str] _find_package_roots (Iterable[str] packages, Mapping[str, str] package_dir, _Path src_root)
str _absolute_root (_Path path)
Iterator[str] _find_virtual_namespaces (Dict[str, str] pkg_roots)
Iterator[Tuple[str, List[str]]] _find_namespaces (List[str] packages, Dict[str, str] pkg_roots)
Dict[str, str] _remove_nested (Dict[str, str] pkg_roots)
bool _is_nested (str pkg, str pkg_path, str parent, str parent_path)
str _normalize_path (_Path filename)
_P _empty_dir (_P dir_)
str _make_identifier (str name)
str _finder_template (str name, Mapping[str, str] mapping, Dict[str, List[str]] namespaces)
Variables
_Path = Union[str, Path]
_P = TypeVar("_P", bound=_Path)
_logger = logging.getLogger(__name__)
str _STRICT_WARNING
str _LENIENT_WARNING
str _FINDER_TEMPLATE
Detailed Description
Create a wheel that, when installed, will make the source package 'editable'
(add it to the interpreter's path, including metadata) per PEP 660. Replaces
'setup.py develop'.
.. note::
   One of the mechanisms briefly mentioned in PEP 660 to implement editable installs is
   to create a separated directory inside ``build`` and use a .pth file to point to that
   directory. In the context of this file such directory is referred as
   *auxiliary build directory* or ``auxiliary_dir``.
Function Documentation
_absolute_root()
str setuptools.command.editable_wheel._absolute_root (_Path path) protected
Works for packages and top-level modules
Referenced by setuptools.command.editable_wheel._find_package_roots().
_can_symlink_files()
bool setuptools.command.editable_wheel._can_symlink_files (Path base_dir) protected
Referenced by setuptools.command.editable_wheel._LinkTree._create_links().
_empty_dir()
_P setuptools.command.editable_wheel._empty_dir (_P dir_) protected
Create a directory ensured to be empty. Existing files may be removed.
Referenced by setuptools.command.editable_wheel.editable_wheel._select_strategy().
_find_namespaces()
Iterator[Tuple[str, List[str]]] setuptools.command.editable_wheel._find_namespaces (List[str] packages, Dict[str, str] pkg_roots) protected
Referenced by setuptools.command.editable_wheel._TopLevelFinder.__call__().
_find_package_roots()
Dict[str, str] setuptools.command.editable_wheel._find_package_roots (Iterable[str] packages, Mapping[str, str] package_dir, _Path src_root) protected
References setuptools.command.editable_wheel._absolute_root(), and setuptools.command.editable_wheel._remove_nested().
Referenced by setuptools.command.editable_wheel._TopLevelFinder.__call__().
_find_packages()
Iterator[str] setuptools.command.editable_wheel._find_packages (Distribution dist) protected
Referenced by setuptools.command.editable_wheel._TopLevelFinder.__call__().
_find_top_level_modules()
Iterator[str] setuptools.command.editable_wheel._find_top_level_modules (Distribution dist) protected
Referenced by setuptools.command.editable_wheel._TopLevelFinder.__call__().
_find_virtual_namespaces()
Iterator[str] setuptools.command.editable_wheel._find_virtual_namespaces (Dict[str, str] pkg_roots) protected
By carefully designing ``package_dir``, it is possible to implement the logical
structure of PEP 420 in a package without the corresponding directories.
Moreover a parent package can be purposefully/accidentally skipped in the discovery
phase (e.g. ``find_packages(include=["mypkg.*"])``, when ``mypkg.foo`` is included
by ``mypkg`` itself is not).
We consider this case to also be a virtual namespace (ignoring the original
directory) to emulate a non-editable installation.
This function will try to find these kinds of namespaces.
Referenced by setuptools.command.editable_wheel._TopLevelFinder.__call__().
_finder_template()
str setuptools.command.editable_wheel._finder_template (str name, Mapping[str, str] mapping, Dict[str, List[str]] namespaces) protected
Create a string containing the code for the``MetaPathFinder`` and
``PathEntryFinder``.
Referenced by setuptools.command.editable_wheel._TopLevelFinder.__call__().
_is_nested()
bool setuptools.command.editable_wheel._is_nested (str pkg, str pkg_path, str parent, str parent_path) protected
Return ``True`` if ``pkg`` is nested inside ``parent`` both logically and in the
file system.
>>> _is_nested("a.b", "path/a/b", "a", "path/a")
True
>>> _is_nested("a.b", "path/a/b", "a", "otherpath/a")
False
>>> _is_nested("a.b", "path/a/b", "c", "path/c")
False
>>> _is_nested("a.a", "path/a/a", "a", "path/a")
True
>>> _is_nested("b.a", "path/b/a", "a", "path/a")
False
References setuptools.command.editable_wheel._normalize_path().
Referenced by setuptools.command.editable_wheel._remove_nested().
_make_identifier()
str setuptools.command.editable_wheel._make_identifier (str name) protected
Make a string safe to be used as Python identifier.
>>> _make_identifier("12abc")
'_12abc'
>>> _make_identifier("__editable__.myns.pkg-78.9.3_local")
'__editable___myns_pkg_78_9_3_local'
Referenced by setuptools.command.editable_wheel._TopLevelFinder.__call__().
_normalize_path()
str setuptools.command.editable_wheel._normalize_path (_Path filename) protected
Normalize a file/dir name for comparison purposes
Referenced by setuptools.command.editable_wheel._is_nested(), and setuptools.command.editable_wheel._simple_layout().
_parent_path()
setuptools.command.editable_wheel._parent_path (pkg, pkg_path) protected
Infer the parent path containing a package, that if added to ``sys.path`` would
allow importing that package.
When ``pkg`` is directly mapped into a directory with a different name, return its
own path.
>>> _parent_path("a", "src/a")
'src'
>>> _parent_path("b", "src/c")
'src/c'
Referenced by setuptools.command.editable_wheel._simple_layout().
_remove_nested()
Dict[str, str] setuptools.command.editable_wheel._remove_nested (Dict[str, str] pkg_roots) protected
References setuptools.command.editable_wheel._is_nested().
Referenced by setuptools.command.editable_wheel._find_package_roots().
_simple_layout()
bool setuptools.command.editable_wheel._simple_layout (Iterable[str] packages, Dict[str, str] package_dir, Path project_dir) protected
Return ``True`` if:
- all packages are contained by the same parent directory, **and**
- all packages become importable if the parent directory is added to ``sys.path``.
>>> _simple_layout(['a'], {"": "src"}, "/tmp/myproj")
True
>>> _simple_layout(['a', 'a.b'], {"": "src"}, "/tmp/myproj")
True
>>> _simple_layout(['a', 'a.b'], {}, "/tmp/myproj")
True
>>> _simple_layout(['a', 'a.a1', 'a.a1.a2', 'b'], {"": "src"}, "/tmp/myproj")
True
>>> _simple_layout(['a', 'a.a1', 'a.a1.a2', 'b'], {"a": "a", "b": "b"}, ".")
True
>>> _simple_layout(['a', 'a.a1', 'a.a1.a2', 'b'], {"a": "_a", "b": "_b"}, ".")
False
>>> _simple_layout(['a', 'a.a1', 'a.a1.a2', 'b'], {"a": "_a"}, "/tmp/myproj")
False
>>> _simple_layout(['a', 'a.a1', 'a.a1.a2', 'b'], {"a.a1.a2": "_a2"}, ".")
False
>>> _simple_layout(['a', 'a.b'], {"": "src", "a.b": "_ab"}, "/tmp/myproj")
False
>>> # Special cases, no packages yet:
>>> _simple_layout([], {"": "src"}, "/tmp/myproj")
True
>>> _simple_layout([], {"a": "_a", "": "src"}, "/tmp/myproj")
False
References setuptools.command.editable_wheel._normalize_path(), and setuptools.command.editable_wheel._parent_path().
Variable Documentation
_FINDER_TEMPLATE
str setuptools.command.editable_wheel._FINDER_TEMPLATE protected
_LENIENT_WARNING
str setuptools.command.editable_wheel._LENIENT_WARNING protected
Initial value:
=  """
Options like `package-data`, `include/exclude-package-data` or
`packages.find.exclude/include` may have no effect.
"""
_logger
setuptools.command.editable_wheel._logger = logging.getLogger(__name__) protected
_P
setuptools.command.editable_wheel._P = TypeVar("_P", bound=_Path) protected
_Path
setuptools.command.editable_wheel._Path = Union[str, Path] protected
_STRICT_WARNING
str setuptools.command.editable_wheel._STRICT_WARNING protected
Initial value:
=  """
New or renamed files may not be automatically picked up without a new installation.
"""