Django Project: cryptography.hazmat.backends.openssl.aead Namespace Reference
cryptography.hazmat.backends.openssl.aead Namespace Reference
Functions
bool _aead_cipher_supported (Backend backend, _AEADTypes cipher)
bytes _encrypt (Backend backend, _AEADTypes cipher, bytes nonce, bytes data, list[bytes] associated_data, int tag_length)
bytes _decrypt (Backend backend, _AEADTypes cipher, bytes nonce, bytes data, list[bytes] associated_data, int tag_length)
bytes _evp_cipher_cipher_name (_AEADTypes cipher)
_evp_cipher (bytes cipher_name, Backend backend)
_evp_cipher_aead_setup (Backend backend, bytes cipher_name, bytes key, bytes nonce, bytes|None tag, int tag_len, int operation)
None _evp_cipher_set_tag (backend, ctx, bytes tag)
None _evp_cipher_set_length (Backend backend, ctx, int data_len)
None _evp_cipher_process_aad (Backend backend, ctx, bytes associated_data)
bytes _evp_cipher_process_data (Backend backend, ctx, bytes data)
bytes _evp_cipher_encrypt (Backend backend, _AEADTypes cipher, bytes nonce, bytes data, list[bytes] associated_data, int tag_length)
bytes _evp_cipher_decrypt (Backend backend, _AEADTypes cipher, bytes nonce, bytes data, list[bytes] associated_data, int tag_length)
Variables
_AEADTypes = typing.Union[AESCCM, AESGCM]
int _ENCRYPT = 1
int _DECRYPT = 0
Function Documentation
_aead_cipher_supported()
bool cryptography.hazmat.backends.openssl.aead._aead_cipher_supported (Backend backend, _AEADTypes cipher) protected
References cryptography.hazmat.backends.openssl.aead._evp_cipher_cipher_name().
_decrypt()
bytes cryptography.hazmat.backends.openssl.aead._decrypt (Backend backend, _AEADTypes cipher, bytes nonce, bytes data, list[bytes] associated_data, int tag_length) protected
References cryptography.hazmat.backends.openssl.aead._evp_cipher_decrypt().
_encrypt()
bytes cryptography.hazmat.backends.openssl.aead._encrypt (Backend backend, _AEADTypes cipher, bytes nonce, bytes data, list[bytes] associated_data, int tag_length) protected
References cryptography.hazmat.backends.openssl.aead._evp_cipher_encrypt().
_evp_cipher()
cryptography.hazmat.backends.openssl.aead._evp_cipher (bytes cipher_name, Backend backend) protected
Referenced by cryptography.hazmat.backends.openssl.aead._evp_cipher_aead_setup().
_evp_cipher_aead_setup()
cryptography.hazmat.backends.openssl.aead._evp_cipher_aead_setup (Backend backend, bytes cipher_name, bytes key, bytes nonce, bytes | None tag, int tag_len, int operation) protected
References cryptography.hazmat.backends.openssl.aead._evp_cipher(), and cryptography.hazmat.backends.openssl.aead._evp_cipher_set_tag().
Referenced by cryptography.hazmat.backends.openssl.aead._evp_cipher_decrypt(), and cryptography.hazmat.backends.openssl.aead._evp_cipher_encrypt().
_evp_cipher_cipher_name()
bytes cryptography.hazmat.backends.openssl.aead._evp_cipher_cipher_name (_AEADTypes cipher) protected
Referenced by cryptography.hazmat.backends.openssl.aead._aead_cipher_supported(), cryptography.hazmat.backends.openssl.aead._evp_cipher_decrypt(), and cryptography.hazmat.backends.openssl.aead._evp_cipher_encrypt().
_evp_cipher_decrypt()
bytes cryptography.hazmat.backends.openssl.aead._evp_cipher_decrypt (Backend backend, _AEADTypes cipher, bytes nonce, bytes data, list[bytes] associated_data, int tag_length) protected
References cryptography.hazmat.backends.openssl.aead._evp_cipher_aead_setup(), cryptography.hazmat.backends.openssl.aead._evp_cipher_cipher_name(), cryptography.hazmat.backends.openssl.aead._evp_cipher_process_aad(), cryptography.hazmat.backends.openssl.aead._evp_cipher_process_data(), and cryptography.hazmat.backends.openssl.aead._evp_cipher_set_length().
Referenced by cryptography.hazmat.backends.openssl.aead._decrypt().
_evp_cipher_encrypt()
bytes cryptography.hazmat.backends.openssl.aead._evp_cipher_encrypt (Backend backend, _AEADTypes cipher, bytes nonce, bytes data, list[bytes] associated_data, int tag_length) protected
References cryptography.hazmat.backends.openssl.aead._evp_cipher_aead_setup(), cryptography.hazmat.backends.openssl.aead._evp_cipher_cipher_name(), cryptography.hazmat.backends.openssl.aead._evp_cipher_process_aad(), cryptography.hazmat.backends.openssl.aead._evp_cipher_process_data(), and cryptography.hazmat.backends.openssl.aead._evp_cipher_set_length().
Referenced by cryptography.hazmat.backends.openssl.aead._encrypt().
_evp_cipher_process_aad()
None cryptography.hazmat.backends.openssl.aead._evp_cipher_process_aad (Backend backend, ctx, bytes associated_data) protected
Referenced by cryptography.hazmat.backends.openssl.aead._evp_cipher_decrypt(), and cryptography.hazmat.backends.openssl.aead._evp_cipher_encrypt().
_evp_cipher_process_data()
bytes cryptography.hazmat.backends.openssl.aead._evp_cipher_process_data (Backend backend, ctx, bytes data) protected
Referenced by cryptography.hazmat.backends.openssl.aead._evp_cipher_decrypt(), and cryptography.hazmat.backends.openssl.aead._evp_cipher_encrypt().
_evp_cipher_set_length()
None cryptography.hazmat.backends.openssl.aead._evp_cipher_set_length (Backend backend, ctx, int data_len) protected
Referenced by cryptography.hazmat.backends.openssl.aead._evp_cipher_decrypt(), and cryptography.hazmat.backends.openssl.aead._evp_cipher_encrypt().
_evp_cipher_set_tag()
None cryptography.hazmat.backends.openssl.aead._evp_cipher_set_tag (backend, ctx, bytes tag) protected
Referenced by cryptography.hazmat.backends.openssl.aead._evp_cipher_aead_setup().
Variable Documentation
_AEADTypes
cryptography.hazmat.backends.openssl.aead._AEADTypes = typing.Union[AESCCM, AESGCM] protected
_DECRYPT
int cryptography.hazmat.backends.openssl.aead._DECRYPT = 0 protected
_ENCRYPT
int cryptography.hazmat.backends.openssl.aead._ENCRYPT = 1 protected