Django Project: _pytest.assertion.truncate Namespace Reference
_pytest.assertion.truncate Namespace Reference
Functions
list[str] truncate_if_required (list[str] explanation, Item item, int|None max_length=None)
bool _should_truncate_item (Item item)
list[str] _truncate_explanation (list[str] input_lines, int|None max_lines=None, int|None max_chars=None)
list[str] _truncate_by_char_count (list[str] input_lines, int max_chars)
Variables
int DEFAULT_MAX_LINES = 8
int DEFAULT_MAX_CHARS = 8 * 80
str USAGE_MSG = "use '-vv' to show"
Detailed Description
Utilities for truncating assertion output.
Current default behaviour is to truncate assertion explanations at
terminal lines, unless running with an assertions verbosity level of at least 2 or running on CI.
Function Documentation
_should_truncate_item()
bool _pytest.assertion.truncate._should_truncate_item (Item item) protected
Whether or not this test item is eligible for truncation.
Referenced by _pytest.assertion.truncate.truncate_if_required().
_truncate_by_char_count()
list[str] _pytest.assertion.truncate._truncate_by_char_count (list[str] input_lines, int max_chars) protected
Referenced by _pytest.assertion.truncate._truncate_explanation().
_truncate_explanation()
list[str] _pytest.assertion.truncate._truncate_explanation (list[str] input_lines, int | None max_lines = None, int | None max_chars = None) protected
Truncate given list of strings that makes up the assertion explanation.
Truncates to either 8 lines, or 640 characters - whichever the input reaches
first, taking the truncation explanation into account. The remaining lines
will be replaced by a usage message.
References _pytest.assertion.truncate._truncate_by_char_count().
Referenced by _pytest.assertion.truncate.truncate_if_required().
truncate_if_required()
list[str] _pytest.assertion.truncate.truncate_if_required (list[str] explanation, Item item, int | None max_length = None)
Truncate this assertion explanation if the given test item is eligible.
References _pytest.assertion.truncate._should_truncate_item(), and _pytest.assertion.truncate._truncate_explanation().
Variable Documentation
DEFAULT_MAX_CHARS
int _pytest.assertion.truncate.DEFAULT_MAX_CHARS = 8 * 80
DEFAULT_MAX_LINES
int _pytest.assertion.truncate.DEFAULT_MAX_LINES = 8
USAGE_MSG
str _pytest.assertion.truncate.USAGE_MSG = "use '-vv' to show"