Django Project: graphviz.backend.execute Namespace Reference
graphviz.backend.execute Namespace Reference
Classes
class CalledProcessError
class ExecutableNotFound
Functions
subprocess.CompletedProcess run_check (typing.Sequence[typing.Union[os.PathLike, str]] cmd, *, typing.Optional[typing.Iterator[bytes]] input_lines=..., None encoding=..., bool quiet=..., **kwargs)
subprocess.CompletedProcess run_check (typing.Sequence[typing.Union[os.PathLike, str]] cmd, *, typing.Optional[typing.Iterator[str]] input_lines=..., str encoding, bool quiet=..., **kwargs)
subprocess.CompletedProcess run_check (typing.Sequence[typing.Union[os.PathLike, str]] cmd, *, typing.Optional[BytesOrStrIterator] input_lines=..., typing.Optional[str] encoding=..., bool capture_output=..., bool quiet=..., **kwargs)
subprocess.CompletedProcess run_check (typing.Sequence[typing.Union[os.PathLike, str]] cmd, *, typing.Optional[BytesOrStrIterator] input_lines=None, typing.Optional[str] encoding=None, bool quiet=False, **kwargs)
_run_input_lines (cmd, input_lines, *, kwargs)
None _write_stderr (stderr)
Variables
log = logging.getLogger(__name__)
BytesOrStrIterator
Detailed Description
Run subprocesses with ``subprocess.run()`` and ``subprocess.Popen()``.
Function Documentation
_run_input_lines()
graphviz.backend.execute._run_input_lines (cmd, input_lines, * , kwargs) protected
Referenced by graphviz.backend.execute.run_check().
_write_stderr()
None graphviz.backend.execute._write_stderr (stderr) protected
Referenced by graphviz.backend.execute.run_check().
run_check() [1/4]
subprocess.CompletedProcess graphviz.backend.execute.run_check (typing.Sequence[typing.Union[os.PathLike, str]] cmd, * , typing.Optional[BytesOrStrIterator] input_lines = ..., typing.Optional[str] encoding = ..., bool capture_output = ..., bool quiet = ..., ** kwargs)
Accept bytes or string input_lines depending on ``encoding``.
run_check() [2/4]
subprocess.CompletedProcess graphviz.backend.execute.run_check (typing.Sequence[typing.Union[os.PathLike, str]] cmd, * , typing.Optional[BytesOrStrIterator] input_lines = None, typing.Optional[str] encoding = None, bool quiet = False, ** kwargs)
Run the command described by ``cmd``
    with ``check=True`` and return its completed process.
Raises:
    CalledProcessError: if the returncode of the subprocess is non-zero.
References graphviz.backend.execute._run_input_lines(), and graphviz.backend.execute._write_stderr().
run_check() [3/4]
subprocess.CompletedProcess graphviz.backend.execute.run_check (typing.Sequence[typing.Union[os.PathLike, str]] cmd, * , typing.Optional[typing.Iterator[bytes]] input_lines = ..., None encoding = ..., bool quiet = ..., ** kwargs)
Accept bytes input_lines with default ``encoding=None```.
run_check() [4/4]
subprocess.CompletedProcess graphviz.backend.execute.run_check (typing.Sequence[typing.Union[os.PathLike, str]] cmd, * , typing.Optional[typing.Iterator[str]] input_lines = ..., str encoding, bool quiet = ..., ** kwargs)
Accept string input_lines when given ``encoding``.
Variable Documentation
BytesOrStrIterator
graphviz.backend.execute.BytesOrStrIterator
Initial value:
=  typing.Union[typing.Iterator[bytes],
                                  typing.Iterator[str]]
log
graphviz.backend.execute.log = logging.getLogger(__name__)