Django Project: setuptools.dist Namespace Reference
setuptools.dist Namespace Reference
Classes
class DistDeprecationWarning
class Distribution
Functions
_get_unpatched (cls)
get_metadata_version (self)
str rfc822_unescape (str content)
Optional[str] _read_field_from_msg ("Message" msg, str field)
Optional[str] _read_field_unescaped_from_msg ("Message" msg, str field)
Optional[List[str]] _read_list_from_msg ("Message" msg, str field)
Optional[str] _read_payload_from_msg ("Message" msg)
read_pkg_file (self, file)
single_line (val)
write_pkg_file (self, file)
check_importable (dist, attr, value)
assert_string_list (dist, attr, value)
check_nsp (dist, attr, value)
check_extras (dist, attr, value)
_check_extra (extra, reqs)
assert_bool (dist, attr, value)
invalid_unless_false (dist, attr, value)
check_requirements (dist, attr, value)
check_specifier (dist, attr, value)
check_entry_points (dist, attr, value)
check_test_suite (dist, attr, value)
check_package_data (dist, attr, value)
check_packages (dist, attr, value)
Variables
sequence = tuple, list
_Distribution = get_unpatched(distutils.core.Distribution)
metadata_version
name
version
description
author
maintainer
author_email
maintainer_email
url
download_url
license
long_description
keywords
platforms
classifiers
requires
provides
obsoletes
license_files
python_requires
long_description_content_type
provides_extras
Function Documentation
_check_extra()
setuptools.dist._check_extra (extra, reqs) protected
References pkg_resources.invalid_marker().
_get_unpatched()
setuptools.dist._get_unpatched (cls) protected
_read_field_from_msg()
Optional[str] setuptools.dist._read_field_from_msg ("Message" msg, str field) protected
Read Message header field.
Referenced by setuptools.dist._read_field_unescaped_from_msg().
_read_field_unescaped_from_msg()
Optional[str] setuptools.dist._read_field_unescaped_from_msg ("Message" msg, str field) protected
Read Message header field and apply rfc822_unescape.
References setuptools.dist._read_field_from_msg(), and setuptools.dist.rfc822_unescape().
_read_list_from_msg()
Optional[List[str]] setuptools.dist._read_list_from_msg ("Message" msg, str field) protected
Read Message header field and return all results as list.
_read_payload_from_msg()
Optional[str] setuptools.dist._read_payload_from_msg ("Message" msg) protected
assert_bool()
setuptools.dist.assert_bool (dist, attr, value)
Verify that value is True, False, 0, or 1
assert_string_list()
setuptools.dist.assert_string_list (dist, attr, value)
Verify that value is a string list
Referenced by setuptools.dist.check_nsp().
check_entry_points()
setuptools.dist.check_entry_points (dist, attr, value)
Verify that entry_points map is parseable
check_extras()
setuptools.dist.check_extras (dist, attr, value)
Verify that extras_require mapping is valid
check_importable()
setuptools.dist.check_importable (dist, attr, value)
check_nsp()
setuptools.dist.check_nsp (dist, attr, value)
Verify that namespace packages are valid
References setuptools.dist.assert_string_list().
check_package_data()
setuptools.dist.check_package_data (dist, attr, value)
Verify that value is a dictionary of package names to glob lists
check_packages()
setuptools.dist.check_packages (dist, attr, value)
check_requirements()
setuptools.dist.check_requirements (dist, attr, value)
Verify that install_requires is a valid requirements list
check_specifier()
setuptools.dist.check_specifier (dist, attr, value)
Verify that value is a valid version specifier
check_test_suite()
setuptools.dist.check_test_suite (dist, attr, value)
get_metadata_version()
setuptools.dist.get_metadata_version (self)
invalid_unless_false()
setuptools.dist.invalid_unless_false (dist, attr, value)
read_pkg_file()
setuptools.dist.read_pkg_file (self, file)
Reads the metadata values from a file object.
rfc822_unescape()
str setuptools.dist.rfc822_unescape (str content)
Reverse RFC-822 escaping by removing leading whitespaces from content.
Referenced by setuptools.dist._read_field_unescaped_from_msg().
single_line()
setuptools.dist.single_line (val)
Quick and dirty validation for Summary pypa/setuptools#1390.
Referenced by setuptools.dist.write_pkg_file().
write_pkg_file()
setuptools.dist.write_pkg_file (self, file)
Write the PKG-INFO format data to a file object.
References setuptools.dist.single_line().
Variable Documentation
_Distribution
setuptools.dist._Distribution = get_unpatched(distutils.core.Distribution) protected
author
setuptools.dist.author
author_email
setuptools.dist.author_email
classifiers
setuptools.dist.classifiers
description
setuptools.dist.description
download_url
setuptools.dist.download_url
keywords
setuptools.dist.keywords
license
setuptools.dist.license
license_files
setuptools.dist.license_files
long_description
setuptools.dist.long_description
long_description_content_type
setuptools.dist.long_description_content_type
maintainer
setuptools.dist.maintainer
maintainer_email
setuptools.dist.maintainer_email
metadata_version
setuptools.dist.metadata_version
name
setuptools.dist.name
obsoletes
setuptools.dist.obsoletes
platforms
setuptools.dist.platforms
provides
setuptools.dist.provides
provides_extras
setuptools.dist.provides_extras
python_requires
setuptools.dist.python_requires
requires
setuptools.dist.requires
sequence
setuptools.dist.sequence = tuple, list
url
setuptools.dist.url
version
setuptools.dist.version