Django Project: pip._vendor.msgpack.fallback Namespace Reference
pip._vendor.msgpack.fallback Namespace Reference
Classes
class Packer
class StringIO
class Unpacker
Functions
dict_iteritems (d)
_is_recursionerror (e)
_check_type_strict (obj, t, type=type, tuple=tuple)
_get_data_from_buffer (obj)
unpackb (packed, **kwargs)
_unpack_from (f, b, o=0)
Variables
int PY2 = 2
tuple int_types = (int, long)
unicode = str
xrange = range
RecursionError = RuntimeError
bool USING_STRINGBUILDER = True
newlist_hint = lambda size: []
int EX_SKIP = 0
int EX_CONSTRUCT = 1
int EX_READ_ARRAY_HEADER = 2
int EX_READ_MAP_HEADER = 3
int TYPE_IMMEDIATE = 0
int TYPE_ARRAY = 1
int TYPE_MAP = 2
int TYPE_RAW = 3
int TYPE_BIN = 4
int TYPE_EXT = 5
int DEFAULT_RECURSE_LIMIT = 511
_unpack_from = struct.unpack_from
str _NO_FORMAT_USED = ""
dict _MSGPACK_HEADERS
Detailed Description
Fallback pure Python implementation of msgpack
Function Documentation
_check_type_strict()
pip._vendor.msgpack.fallback._check_type_strict (obj, t, type = type, tuple = tuple) protected
_get_data_from_buffer()
pip._vendor.msgpack.fallback._get_data_from_buffer (obj) protected
Referenced by pip._vendor.msgpack.fallback.Unpacker.feed().
_is_recursionerror()
pip._vendor.msgpack.fallback._is_recursionerror (e) protected
Referenced by pip._vendor.msgpack.fallback.unpackb().
_unpack_from()
pip._vendor.msgpack.fallback._unpack_from (f, b, o = 0) protected
Explicit type cast for legacy struct.unpack_from
dict_iteritems()
pip._vendor.msgpack.fallback.dict_iteritems (d)
Referenced by pip._vendor.msgpack.fallback.Packer._pack().
unpackb()
pip._vendor.msgpack.fallback.unpackb (packed, ** kwargs)
Unpack an object from `packed`.
Raises ``ExtraData`` when *packed* contains extra bytes.
Raises ``ValueError`` when *packed* is incomplete.
Raises ``FormatError`` when *packed* is not valid msgpack.
Raises ``StackError`` when *packed* contains too nested.
Other exceptions can be raised during unpacking.
See :class:`Unpacker` for options.
References pip._vendor.msgpack.fallback._is_recursionerror().
Variable Documentation
_MSGPACK_HEADERS
dict pip._vendor.msgpack.fallback._MSGPACK_HEADERS protected
Initial value:
=  {
    0xC4: (1, _NO_FORMAT_USED, TYPE_BIN),
    0xC5: (2, ">H", TYPE_BIN),
    0xC6: (4, ">I", TYPE_BIN),
    0xC7: (2, "Bb", TYPE_EXT),
    0xC8: (3, ">Hb", TYPE_EXT),
    0xC9: (5, ">Ib", TYPE_EXT),
    0xCA: (4, ">f"),
    0xCB: (8, ">d"),
    0xCC: (1, _NO_FORMAT_USED),
    0xCD: (2, ">H"),
    0xCE: (4, ">I"),
    0xCF: (8, ">Q"),
    0xD0: (1, "b"),
    0xD1: (2, ">h"),
    0xD2: (4, ">i"),
    0xD3: (8, ">q"),
    0xD4: (1, "b1s", TYPE_EXT),
    0xD5: (2, "b2s", TYPE_EXT),
    0xD6: (4, "b4s", TYPE_EXT),
    0xD7: (8, "b8s", TYPE_EXT),
    0xD8: (16, "b16s", TYPE_EXT),
    0xD9: (1, _NO_FORMAT_USED, TYPE_RAW),
    0xDA: (2, ">H", TYPE_RAW),
    0xDB: (4, ">I", TYPE_RAW),
    0xDC: (2, ">H", TYPE_ARRAY),
    0xDD: (4, ">I", TYPE_ARRAY),
    0xDE: (2, ">H", TYPE_MAP),
    0xDF: (4, ">I", TYPE_MAP),
}
_NO_FORMAT_USED
str pip._vendor.msgpack.fallback._NO_FORMAT_USED = "" protected
_unpack_from
pip._vendor.msgpack.fallback._unpack_from = struct.unpack_from protected
Referenced by pip._vendor.msgpack.fallback.Unpacker._read_header().
DEFAULT_RECURSE_LIMIT
int pip._vendor.msgpack.fallback.DEFAULT_RECURSE_LIMIT = 511
EX_CONSTRUCT
int pip._vendor.msgpack.fallback.EX_CONSTRUCT = 1
EX_READ_ARRAY_HEADER
int pip._vendor.msgpack.fallback.EX_READ_ARRAY_HEADER = 2
EX_READ_MAP_HEADER
int pip._vendor.msgpack.fallback.EX_READ_MAP_HEADER = 3
EX_SKIP
int pip._vendor.msgpack.fallback.EX_SKIP = 0
int_types
pip._vendor.msgpack.fallback.int_types = (int, long)
newlist_hint
pip._vendor.msgpack.fallback.newlist_hint = lambda size: []
PY2
int pip._vendor.msgpack.fallback.PY2 = 2
RecursionError
pip._vendor.msgpack.fallback.RecursionError = RuntimeError
TYPE_ARRAY
int pip._vendor.msgpack.fallback.TYPE_ARRAY = 1
TYPE_BIN
int pip._vendor.msgpack.fallback.TYPE_BIN = 4
TYPE_EXT
int pip._vendor.msgpack.fallback.TYPE_EXT = 5
TYPE_IMMEDIATE
int pip._vendor.msgpack.fallback.TYPE_IMMEDIATE = 0
TYPE_MAP
int pip._vendor.msgpack.fallback.TYPE_MAP = 2
TYPE_RAW
int pip._vendor.msgpack.fallback.TYPE_RAW = 3
unicode
pip._vendor.msgpack.fallback.unicode = str
USING_STRINGBUILDER
pip._vendor.msgpack.fallback.USING_STRINGBUILDER = True
xrange
pip._vendor.msgpack.fallback.xrange = range
Referenced by pip._vendor.msgpack.fallback.Packer._pack(), and pip._vendor.msgpack.fallback.Unpacker._unpack().