Django Project: pip._vendor.webencodings.mklabels Namespace Reference
pip._vendor.webencodings.mklabels Namespace Reference
Functions
assert_lower (string)
generate (url)
Detailed Description
    webencodings.mklabels
    ~~~~~~~~~~~~~~~~~~~~~
    Regenarate the webencodings.labels module.
    :copyright: Copyright 2012 by Simon Sapin
    :license: BSD, see LICENSE for details.
Function Documentation
assert_lower()
pip._vendor.webencodings.mklabels.assert_lower (string)
Referenced by pip._vendor.webencodings.mklabels.generate().
generate()
pip._vendor.webencodings.mklabels.generate (url)
References pip._vendor.webencodings.mklabels.assert_lower(), and pip._vendor.webencodings.mklabels.generate().
Referenced by pip._vendor.webencodings.mklabels.generate().