Django Project: setuptools._vendor.importlib_metadata Namespace Reference
setuptools._vendor.importlib_metadata Namespace Reference
Namespaces
namespace _adapters
namespace _collections
namespace _compat
namespace _functools
namespace _itertools
namespace _meta
namespace _text
Classes
class Deprecated
class DeprecatedList
class DeprecatedTuple
class Distribution
class DistributionFinder
class EntryPoint
class EntryPoints
class FastPath
class FileHash
class Lookup
class MetadataPathFinder
class PackageNotFoundError
class PackagePath
class PathDistribution
class Prepared
class Sectioned
class SelectableGroups
Functions
distribution (distribution_name)
distributions (**kwargs)
_meta.PackageMetadata metadata (distribution_name)
version (distribution_name)
Union[EntryPoints, SelectableGroups] entry_points (**params)
files (distribution_name)
requires (distribution_name)
Mapping[str, List[str]] packages_distributions ()
_top_level_declared (dist)
_top_level_inferred (dist)
Function Documentation
_top_level_declared()
setuptools._vendor.importlib_metadata._top_level_declared (dist) protected
Referenced by setuptools._vendor.importlib_metadata.packages_distributions().
_top_level_inferred()
setuptools._vendor.importlib_metadata._top_level_inferred (dist) protected
Referenced by setuptools._vendor.importlib_metadata.packages_distributions().
distribution()
setuptools._vendor.importlib_metadata.distribution (distribution_name)
Get the ``Distribution`` instance for the named package.
:param distribution_name: The name of the distribution package as a string.
:return: A ``Distribution`` instance (or subclass thereof).
Referenced by setuptools._vendor.importlib_metadata.files(), setuptools._vendor.importlib_metadata.requires(), and setuptools._vendor.importlib_metadata.version().
distributions()
setuptools._vendor.importlib_metadata.distributions (** kwargs)
Get all ``Distribution`` instances in the current environment.
:return: An iterable of ``Distribution`` instances.
Referenced by setuptools._vendor.importlib_metadata.entry_points(), and setuptools._vendor.importlib_metadata.packages_distributions().
entry_points()
Union[EntryPoints, SelectableGroups] setuptools._vendor.importlib_metadata.entry_points (** params)
Return EntryPoint objects for all installed packages.
Pass selection parameters (group or name) to filter the
result to entry points matching those properties (see
EntryPoints.select()).
For compatibility, returns ``SelectableGroups`` object unless
selection parameters are supplied. In the future, this function
will return ``EntryPoints`` instead of ``SelectableGroups``
even when no selection parameters are supplied.
For maximum future compatibility, pass selection parameters
or invoke ``.select`` with parameters on the result.
:return: EntryPoints or SelectableGroups for all installed packages.
References setuptools._vendor.importlib_metadata.distributions().
files()
setuptools._vendor.importlib_metadata.files (distribution_name)
Return a list of files for the named package.
:param distribution_name: The name of the distribution package to query.
:return: List of files composing the distribution.
References setuptools._vendor.importlib_metadata.distribution().
metadata()
_meta.PackageMetadata setuptools._vendor.importlib_metadata.metadata (distribution_name)
Get the metadata for the named package.
:param distribution_name: The name of the distribution package to query.
:return: A PackageMetadata containing the parsed metadata.
packages_distributions()
Mapping[str, List[str]] setuptools._vendor.importlib_metadata.packages_distributions ()
Return a mapping of top-level packages to their
distributions.
>>> import collections.abc
>>> pkgs = packages_distributions()
>>> all(isinstance(dist, collections.abc.Sequence) for dist in pkgs.values())
True
References setuptools._vendor.importlib_metadata._top_level_declared(), setuptools._vendor.importlib_metadata._top_level_inferred(), and setuptools._vendor.importlib_metadata.distributions().
requires()
setuptools._vendor.importlib_metadata.requires (distribution_name)
Return a list of requirements for the named package.
:return: An iterator of requirements, suitable for
    packaging.requirement.Requirement.
References setuptools._vendor.importlib_metadata.distribution().
version()
setuptools._vendor.importlib_metadata.version (distribution_name)
Get the version string for the named package.
:param distribution_name: The name of the distribution package to query.
:return: The version string for the package as defined in the package's
    "Version" metadata key.
References setuptools._vendor.importlib_metadata.distribution().