Django Project: bootstrap_modal_forms.mixins Namespace Reference
bootstrap_modal_forms.mixins Namespace Reference
Classes
class CreateUpdateAjaxMixin
class DeleteMessageMixin
class FormValidationMixin
class LoginAjaxMixin
class PassRequestMixin
class PopRequestMixin
Functions
is_ajax (meta)
Function Documentation
is_ajax()
bootstrap_modal_forms.mixins.is_ajax (meta)
Referenced by bootstrap_modal_forms.mixins.FormValidationMixin.form_valid(), bootstrap_modal_forms.mixins.LoginAjaxMixin.form_valid(), bootstrap_modal_forms.mixins.DeleteMessageMixin.post(), and bootstrap_modal_forms.mixins.CreateUpdateAjaxMixin.save().