Django Project: setuptools.command.egg_info Namespace Reference
setuptools.command.egg_info Namespace Reference
Classes
class egg_info
class EggInfoDeprecationWarning
class FileList
class InfoCommon
class manifest_maker
Functions
translate_pattern (glob)
write_file (filename, contents)
write_pkg_info (cmd, basename, filename)
warn_depends_obsolete (cmd, basename, filename)
_write_requirements (stream, reqs)
write_requirements (cmd, basename, filename)
write_setup_requirements (cmd, basename, filename)
write_toplevel_names (cmd, basename, filename)
overwrite_arg (cmd, basename, filename)
write_arg (cmd, basename, filename, force=False)
write_entries (cmd, basename, filename)
get_pkg_info_revision ()
Detailed Description
setuptools.command.egg_info
Create a distribution's .egg-info directory and contents
Function Documentation
_write_requirements()
setuptools.command.egg_info._write_requirements (stream, reqs) protected
Referenced by setuptools.command.egg_info.write_requirements(), and setuptools.command.egg_info.write_setup_requirements().
get_pkg_info_revision()
setuptools.command.egg_info.get_pkg_info_revision ()
Get a -r### off of PKG-INFO Version in case this is an sdist of
a subversion revision.
overwrite_arg()
setuptools.command.egg_info.overwrite_arg (cmd, basename, filename)
References setuptools.command.egg_info.write_arg().
translate_pattern()
setuptools.command.egg_info.translate_pattern (glob)
Translate a file path glob like '*.txt' in to a regular expression.
This differs from fnmatch.translate which allows wildcards to match
directory separators. It also knows about '**/' which matches any number of
directories.
Referenced by setuptools.command.egg_info.FileList.exclude(), setuptools.command.egg_info.FileList.global_exclude(), setuptools.command.egg_info.FileList.global_include(), setuptools.command.egg_info.FileList.prune(), and setuptools.command.egg_info.FileList.recursive_exclude().
warn_depends_obsolete()
setuptools.command.egg_info.warn_depends_obsolete (cmd, basename, filename)
write_arg()
setuptools.command.egg_info.write_arg (cmd, basename, filename, force = False)
Referenced by setuptools.command.egg_info.overwrite_arg().
write_entries()
setuptools.command.egg_info.write_entries (cmd, basename, filename)
write_file()
setuptools.command.egg_info.write_file (filename, contents)
Create a file with the specified name and write 'contents' (a
sequence of strings without line terminators) to it.
write_pkg_info()
setuptools.command.egg_info.write_pkg_info (cmd, basename, filename)
write_requirements()
setuptools.command.egg_info.write_requirements (cmd, basename, filename)
References setuptools.command.egg_info._write_requirements().
write_setup_requirements()
setuptools.command.egg_info.write_setup_requirements (cmd, basename, filename)
References setuptools.command.egg_info._write_requirements().
write_toplevel_names()
setuptools.command.egg_info.write_toplevel_names (cmd, basename, filename)