Django Project: _pytest.mark Namespace Reference
_pytest.mark Namespace Reference
Namespaces
namespace expression
namespace structures
Classes
class KeywordMatcher
class MarkMatcher
Functions
ParameterSet param (*object values, MarkDecorator|Collection[MarkDecorator|Mark] marks=(), str|None id=None)
None pytest_addoption (Parser parser)
int|ExitCode|None pytest_cmdline_main (Config config)
None deselect_by_keyword (list[Item] items, Config config)
None deselect_by_mark (list[Item] items, Config config)
Expression _parse_expression (str expr, str exc_message)
None pytest_collection_modifyitems (list[Item] items, Config config)
None pytest_configure (Config config)
None pytest_unconfigure (Config config)
Variables
old_mark_config_key = StashKey[Optional[Config]]()
Detailed Description
Generic mechanism for marking and selecting python functions.
Function Documentation
_parse_expression()
Expression _pytest.mark._parse_expression (str expr, str exc_message) protected
Referenced by _pytest.mark.deselect_by_keyword(), and _pytest.mark.deselect_by_mark().
deselect_by_keyword()
None _pytest.mark.deselect_by_keyword (list[Item] items, Config config)
References _pytest.mark._parse_expression().
Referenced by _pytest.mark.pytest_collection_modifyitems().
deselect_by_mark()
None _pytest.mark.deselect_by_mark (list[Item] items, Config config)
References _pytest.mark._parse_expression().
Referenced by _pytest.mark.pytest_collection_modifyitems().
param()
ParameterSet _pytest.mark.param (*object values, MarkDecorator | Collection[MarkDecorator | Mark] marks = (), str | None id = None)
Specify a parameter in `pytest.mark.parametrize`_ calls or
:ref:`parametrized fixtures <fixture-parametrize-marks>`.
.. code-block:: python
    @pytest.mark.parametrize(
        "test_input,expected",
        [
            ("3+5", 8),
            pytest.param("6*9", 42, marks=pytest.mark.xfail),
        ],
    )
    def test_eval(test_input, expected):
        assert eval(test_input) == expected
:param values: Variable args of the values of the parameter set, in order.
:param marks: A single mark or a list of marks to be applied to this parameter set.
:param id: The id to attribute to this parameter set.
pytest_addoption()
None _pytest.mark.pytest_addoption (Parser parser)
pytest_cmdline_main()
int | ExitCode | None _pytest.mark.pytest_cmdline_main (Config config)
References _pytest.config.create_terminal_writer().
pytest_collection_modifyitems()
None _pytest.mark.pytest_collection_modifyitems (list[Item] items, Config config)
References _pytest.mark.deselect_by_keyword(), and _pytest.mark.deselect_by_mark().
pytest_configure()
None _pytest.mark.pytest_configure (Config config)
pytest_unconfigure()
None _pytest.mark.pytest_unconfigure (Config config)
Variable Documentation
old_mark_config_key
_pytest.mark.old_mark_config_key = StashKey[Optional[Config]]()