Django Project: pycparser.ply.yacc Namespace Reference
pycparser.ply.yacc Namespace Reference
Classes
class Grammar
class GrammarError
class LALRError
class LRGeneratedTable
class LRItem
class LRParser
class LRTable
class MiniProduction
class NullLogger
class ParserReflect
class PlyLogger
class Production
class VersionError
class YaccError
class YaccProduction
class YaccSymbol
Functions
format_result (r)
format_stack_entry (r)
errok ()
restart ()
token ()
call_errorfunc (errorfunc, token, parser)
rightmost_terminal (symbols, terminals)
digraph (X, R, FP)
traverse (x, N, stack, F, X, R, FP)
get_caller_module_dict (levels)
parse_grammar (doc, file, line)
yacc (method='LALR', debug=yaccdebug, module=None, tabmodule=tab_module, start=None, check_recursion=True, optimize=False, write_tables=True, debugfile=debug_file, outputdir=None, debuglog=None, errorlog=None, picklefile=None)
Variables
bool yaccdebug = True
str debug_file = 'parser.out'
str tab_module = 'parsetab'
str default_lr = 'LALR'
int error_count = 3
bool yaccdevel = False
int resultlimit = 40
int pickle_protocol = 0
string_types = basestring
MAXINT = sys.maxsize
_errok = None
_token = None
_restart = None
str _warnmsg
_is_identifier = re.compile(r'^[a-zA-Z0-9_-]+$')
Function Documentation
call_errorfunc()
pycparser.ply.yacc.call_errorfunc (errorfunc, token, parser)
Referenced by pycparser.ply.yacc.LRParser.parseopt(), and pycparser.ply.yacc.LRParser.parseopt_notrack().
digraph()
pycparser.ply.yacc.digraph (X, R, FP)
References pycparser.ply.yacc.traverse().
Referenced by pycparser.ply.yacc.LRGeneratedTable.compute_follow_sets(), and pycparser.ply.yacc.LRGeneratedTable.compute_read_sets().
errok()
pycparser.ply.yacc.errok ()
References pycparser.ply.yacc._errok.
format_result()
pycparser.ply.yacc.format_result (r)
format_stack_entry()
pycparser.ply.yacc.format_stack_entry (r)
get_caller_module_dict()
pycparser.ply.yacc.get_caller_module_dict (levels)
Referenced by pycparser.ply.yacc.yacc().
parse_grammar()
pycparser.ply.yacc.parse_grammar (doc, file, line)
Referenced by pycparser.ply.yacc.ParserReflect.validate_pfunctions().
restart()
pycparser.ply.yacc.restart ()
References pycparser.ply.yacc._restart.
rightmost_terminal()
pycparser.ply.yacc.rightmost_terminal (symbols, terminals)
Referenced by pycparser.ply.yacc.Grammar.add_production().
token()
pycparser.ply.yacc.token ()
References pycparser.ply.yacc._token.
traverse()
pycparser.ply.yacc.traverse (x, N, stack, F, X, R, FP)
References pycparser.ply.yacc.traverse().
Referenced by pycparser.ply.yacc.digraph(), and pycparser.ply.yacc.traverse().
yacc()
pycparser.ply.yacc.yacc (method = 'LALR', debug = yaccdebug, module = None, tabmodule = tab_module, start = None, check_recursion = True, optimize = False, write_tables = True, debugfile = debug_file, outputdir = None, debuglog = None, errorlog = None, picklefile = None)
References pycparser.ply.yacc.get_caller_module_dict().
Variable Documentation
_errok
pycparser.ply.yacc._errok = None protected
Referenced by pycparser.ply.yacc.errok().
_is_identifier
pycparser.ply.yacc._is_identifier = re.compile(r'^[a-zA-Z0-9_-]+$') protected
_restart
pycparser.ply.yacc._restart = None protected
Referenced by pycparser.ply.yacc.restart().
_token
pycparser.ply.yacc._token = None protected
Referenced by pycparser.ply.yacc.token().
_warnmsg
str pycparser.ply.yacc._warnmsg protected
Initial value:
=  '''PLY: Don't use global functions errok(), token(), and restart() in p_error().
Instead, invoke the methods on the associated parser instance:
    def p_error(p):
        ...
        # Use parser.errok(), parser.token(), parser.restart()
        ...
    parser = yacc.yacc()
'''
debug_file
str pycparser.ply.yacc.debug_file = 'parser.out'
default_lr
str pycparser.ply.yacc.default_lr = 'LALR'
error_count
int pycparser.ply.yacc.error_count = 3
MAXINT
pycparser.ply.yacc.MAXINT = sys.maxsize
pickle_protocol
int pycparser.ply.yacc.pickle_protocol = 0
resultlimit
int pycparser.ply.yacc.resultlimit = 40
string_types
pycparser.ply.yacc.string_types = basestring
tab_module
str pycparser.ply.yacc.tab_module = 'parsetab'
yaccdebug
bool pycparser.ply.yacc.yaccdebug = True
yaccdevel
bool pycparser.ply.yacc.yaccdevel = False