Django Project: setuptools._distutils.unixccompiler Namespace Reference
setuptools._distutils.unixccompiler Namespace Reference
Classes
class UnixCCompiler
Functions
_split_env (cmd)
_split_aix (cmd)
_linker_params (linker_cmd, compiler_cmd)
Detailed Description
distutils.unixccompiler
Contains the UnixCCompiler class, a subclass of CCompiler that handles
the "typical" Unix-style command-line C compiler:
  * macros defined with -Dname[=value]
  * macros undefined with -Uname
  * include search directories specified with -Idir
  * libraries specified with -lllib
  * library search directories specified with -Ldir
  * compile handled by 'cc' (or similar) executable with -c option:
    compiles .c to .o
  * link static library handled by 'ar' command (possibly with 'ranlib')
  * link shared library handled by 'cc -shared'
Function Documentation
_linker_params()
setuptools._distutils.unixccompiler._linker_params (linker_cmd, compiler_cmd) protected
The linker command usually begins with the compiler
command (possibly multiple elements), followed by zero or more
params for shared library building.
If the LDSHARED env variable overrides the linker command,
however, the commands may not match.
Return the best guess of the linker parameters by stripping
the linker command. If the compiler command does not
match the linker command, assume the linker command is
just the first element.
>>> _linker_params('gcc foo bar'.split(), ['gcc'])
['foo', 'bar']
>>> _linker_params('gcc foo bar'.split(), ['other'])
['foo', 'bar']
>>> _linker_params('ccache gcc foo bar'.split(), 'ccache gcc'.split())
['foo', 'bar']
>>> _linker_params(['gcc'], ['gcc'])
[]
Referenced by setuptools._distutils.unixccompiler.UnixCCompiler.link().
_split_aix()
setuptools._distutils.unixccompiler._split_aix (cmd) protected
AIX platforms prefix the compiler with the ld_so_aix
script, so split that from the linker command.
>>> _split_aix(['a', 'b', 'c'])
([], ['a', 'b', 'c'])
>>> _split_aix(['/bin/foo/ld_so_aix', 'gcc'])
(['/bin/foo/ld_so_aix'], ['gcc'])
Referenced by setuptools._distutils.unixccompiler.UnixCCompiler.link().
_split_env()
setuptools._distutils.unixccompiler._split_env (cmd) protected
For macOS, split command into 'env' portion (if any)
and the rest of the linker command.
>>> _split_env(['a', 'b', 'c'])
([], ['a', 'b', 'c'])
>>> _split_env(['/usr/bin/env', 'A=3', 'gcc'])
(['/usr/bin/env', 'A=3'], ['gcc'])
Referenced by setuptools._distutils.unixccompiler.UnixCCompiler.link().