Django Project: django.test.testcases Namespace Reference
django.test.testcases Namespace Reference
Classes
class _AssertNumQueriesContext
class _AssertTemplateNotUsedContext
class _AssertTemplateUsedContext
class _DatabaseFailure
class _MediaFilesHandler
class _StaticFilesHandler
class CheckCondition
class DatabaseOperationForbidden
class FSFilesHandler
class LiveServerTestCase
class LiveServerThread
class QuietWSGIRequestHandler
class SerializeMixin
class SimpleTestCase
class TestCase
class TestData
class TransactionTestCase
Functions
to_list (value)
assert_and_parse_html (self, html, user_msg, msg)
connections_support_transactions (aliases=None)
_deferredSkip (condition, reason, name)
skipIfDBFeature (*features)
skipUnlessDBFeature (*features)
skipUnlessAnyDBFeature (*features)
Variables
logger = logging.getLogger("django.test")
Function Documentation
_deferredSkip()
django.test.testcases._deferredSkip (condition, reason, name) protected
Referenced by django.test.testcases.skipIfDBFeature(), django.test.testcases.skipUnlessAnyDBFeature(), and django.test.testcases.skipUnlessDBFeature().
assert_and_parse_html()
django.test.testcases.assert_and_parse_html (self, html, user_msg, msg)
Referenced by django.test.testcases.SimpleTestCase._assert_contains(), django.test.testcases.SimpleTestCase.assertHTMLEqual(), django.test.testcases.SimpleTestCase.assertHTMLNotEqual(), and django.test.testcases.SimpleTestCase.assertInHTML().
connections_support_transactions()
django.test.testcases.connections_support_transactions (aliases = None)
Return whether or not all (or specified) connections support
transactions.
skipIfDBFeature()
django.test.testcases.skipIfDBFeature (* features)
Skip a test if a database has at least one of the named features.
References django.test.testcases._deferredSkip().
skipUnlessAnyDBFeature()
django.test.testcases.skipUnlessAnyDBFeature (* features)
Skip a test unless a database has any of the named features.
References django.test.testcases._deferredSkip().
skipUnlessDBFeature()
django.test.testcases.skipUnlessDBFeature (* features)
Skip a test unless a database has all the named features.
References django.test.testcases._deferredSkip().
to_list()
django.test.testcases.to_list (value)
Put value into a list if it's not already one.
Referenced by django.test.testcases.SimpleTestCase.assertFormError(), and django.test.testcases.SimpleTestCase.assertFormSetError().
Variable Documentation
logger
django.test.testcases.logger = logging.getLogger("django.test")