Django Project: setuptools.package_index Namespace Reference
setuptools.package_index Namespace Reference
Classes
class ContentChecker
class Credential
class HashChecker
class PackageIndex
class PyPIConfig
Functions
parse_requirement_arg (spec)
parse_bdist_wininst (name)
egg_info_for_url (url)
distros_for_url (url, metadata=None)
distros_for_location (location, basename, metadata=None)
distros_for_filename (filename, metadata=None)
interpret_distro_name (location, basename, metadata, py_version=None, precedence=SOURCE_DIST, platform=None)
unique_values (func)
find_external_links (url, page)
decode_entity (match)
htmldecode (text)
socket_timeout (timeout=15)
_encode_auth (auth)
open_with_auth (url, opener=urllib.request.urlopen)
_splituser (host)
fix_sf_url (url)
local_open (url)
Variables
EGG_FRAGMENT = re.compile(r'^egg=([-A-Za-z0-9_.+!]+)$')
HREF = re.compile(, re.I)
PYPI_MD5
URL_SCHEME = re.compile('([-+.a-z0-9]{2,}):', re.I).match
str EXTENSIONS = ".tar.gz .tar.bz2 .tar .zip .tgz".split()
int _SOCKET_TIMEOUT = 15
str _tmpl = "setuptools/{setuptools.__version__} Python-urllib/{py_major}"
str user_agent
REL = re.compile(, re.I)
entity_sub = re.compile(r'&(#(\d+|x[\da-fA-F]+)|[\w.:-]+);?').sub
open_with_auth = socket_timeout(_SOCKET_TIMEOUT)(open_with_auth)
Detailed Description
PyPI and direct package downloading
Function Documentation
_encode_auth()
setuptools.package_index._encode_auth (auth) protected
Encode auth from a URL suitable for an HTTP header.
>>> str(_encode_auth('username%3Apassword'))
'dXNlcm5hbWU6cGFzc3dvcmQ='
Long auth strings should not cause a newline to be inserted.
>>> long_auth = 'username:' + 'password'*10
>>> chr(10) in str(_encode_auth(long_auth))
False
Referenced by setuptools.package_index.open_with_auth().
_splituser()
setuptools.package_index._splituser (host) protected
splituser('user[:passwd]@host[:port]')
--> 'user[:passwd]', 'host[:port]'.
Referenced by setuptools.package_index.PackageIndex._download_svn(), and setuptools.package_index.open_with_auth().
decode_entity()
setuptools.package_index.decode_entity (match)
distros_for_filename()
setuptools.package_index.distros_for_filename (filename, metadata = None)
Yield possible egg or source distribution objects based on a filename
References setuptools.package_index.distros_for_location().
Referenced by setuptools.package_index.PackageIndex.process_filename().
distros_for_location()
setuptools.package_index.distros_for_location (location, basename, metadata = None)
Yield egg or source distribution objects based on basename
References setuptools.package_index.interpret_distro_name(), and setuptools.package_index.parse_bdist_wininst().
Referenced by setuptools.package_index.distros_for_filename(), and setuptools.package_index.distros_for_url().
distros_for_url()
setuptools.package_index.distros_for_url (url, metadata = None)
Yield egg or source distribution objects that might be found at a URL
References setuptools.package_index.distros_for_location(), setuptools.package_index.egg_info_for_url(), and setuptools.package_index.interpret_distro_name().
Referenced by setuptools.package_index.PackageIndex.add_find_links(), and setuptools.package_index.PackageIndex.process_url().
egg_info_for_url()
setuptools.package_index.egg_info_for_url (url)
Referenced by setuptools.package_index.PackageIndex._download_url(), setuptools.package_index.distros_for_url(), setuptools.package_index.PackageIndex.download(), and setuptools.package_index.PackageIndex.process_index().
find_external_links()
setuptools.package_index.find_external_links (url, page)
Find rel="homepage" and rel="download" links in `page`, yielding URLs
References setuptools.package_index.htmldecode().
Referenced by setuptools.package_index.PackageIndex.process_index().
fix_sf_url()
setuptools.package_index.fix_sf_url (url)
htmldecode()
setuptools.package_index.htmldecode (text)
Decode HTML entities in the given text.
>>> htmldecode(
...     'https://../package_name-0.1.2.tar.gz'
...     '?tokena=A&amp;tokenb=B">package_name-0.1.2.tar.gz')
'https://../package_name-0.1.2.tar.gz?tokena=A&tokenb=B">package_name-0.1.2.tar.gz'
References setuptools.package_index.entity_sub.
Referenced by setuptools.package_index.find_external_links(), and setuptools.package_index.PackageIndex.process_index().
interpret_distro_name()
setuptools.package_index.interpret_distro_name (location, basename, metadata, py_version = None, precedence = SOURCE_DIST, platform = None)
Generate alternative interpretations of a source distro name
Note: if `location` is a filesystem filename, you should call
``pkg_resources.normalize_path()`` on it before passing it to this
routine!
Referenced by setuptools.package_index.distros_for_location(), setuptools.package_index.distros_for_url(), and setuptools.package_index.PackageIndex.gen_setup().
local_open()
setuptools.package_index.local_open (url)
Read a local path, with special support for directories
Referenced by setuptools.package_index.PackageIndex.open_url().
open_with_auth()
setuptools.package_index.open_with_auth (url, opener = urllib.request.urlopen)
Open a urllib2 request, handling HTTP authentication
References setuptools.package_index._encode_auth(), and setuptools.package_index._splituser().
parse_bdist_wininst()
setuptools.package_index.parse_bdist_wininst (name)
Return (base,pyversion) or (None,None) for possible .exe name
Referenced by setuptools.package_index.distros_for_location().
parse_requirement_arg()
setuptools.package_index.parse_requirement_arg (spec)
socket_timeout()
setuptools.package_index.socket_timeout (timeout = 15)
unique_values()
setuptools.package_index.unique_values (func)
Wrap a function returning an iterable such that the resulting iterable
only ever yields unique items.
Variable Documentation
_SOCKET_TIMEOUT
int setuptools.package_index._SOCKET_TIMEOUT = 15 protected
_tmpl
str setuptools.package_index._tmpl = "setuptools/{setuptools.__version__} Python-urllib/{py_major}" protected
EGG_FRAGMENT
setuptools.package_index.EGG_FRAGMENT = re.compile(r'^egg=([-A-Za-z0-9_.+!]+)$')
entity_sub
setuptools.package_index.entity_sub = re.compile(r'&(#(\d+|x[\da-fA-F]+)|[\w.:-]+);?').sub
Referenced by setuptools.package_index.htmldecode().
EXTENSIONS
str setuptools.package_index.EXTENSIONS = ".tar.gz .tar.bz2 .tar .zip .tgz".split()
HREF
setuptools.package_index.HREF = re.compile(, re.I)
open_with_auth
setuptools.package_index.open_with_auth = socket_timeout(_SOCKET_TIMEOUT)(open_with_auth)
Referenced by setuptools.package_index.PackageIndex.open_url().
PYPI_MD5
setuptools.package_index.PYPI_MD5
Initial value:
=  re.compile(
    r'<a href="([^"#]+)">([^<]+)</a>\n\s+\‍(<a (?:title="MD5 hash"\n\s+)'
    r'href="[^?]+\?:action=show_md5&amp;digest=([0-9a-f]{32})">md5</a>\‍)'
)
REL
setuptools.package_index.REL = re.compile(, re.I)
URL_SCHEME
setuptools.package_index.URL_SCHEME = re.compile('([-+.a-z0-9]{2,}):', re.I).match
user_agent
str setuptools.package_index.user_agent
Initial value:
=  _tmpl.format(
    py_major='{}.{}'.format(*sys.version_info), setuptools=setuptools)