Django Project: gunicorn.util Namespace Reference
gunicorn.util Namespace Reference
Functions
_setproctitle (title)
load_entry_point (distribution, group, name)
load_class (uri, default="gunicorn.workers.sync.SyncWorker", section="gunicorn.workers")
get_arity (f)
get_username (uid)
set_owner_process (uid, gid, initgroups=False)
chown (path, uid, gid)
_waitfor (func, pathname, waitall=False)
_unlink (filename)
unlink (filename)
is_ipv6 (addr)
parse_address (netloc, default_port='8000')
close_on_exec (fd)
set_non_blocking (fd)
close (sock)
closerange (fd_low, fd_high)
write_chunk (sock, data)
write (sock, data, chunked=False)
write_nonblock (sock, data, chunked=False)
write_error (sock, status_int, reason, mesg)
_called_with_wrong_args (f)
import_app (module)
getcwd ()
http_date (timestamp=None)
is_hoppish (header)
daemonize (enable_stdio_inheritance=False)
seed ()
check_is_writable (path)
to_bytestring (value, encoding="utf8")
has_fileno (obj)
warn (msg)
make_fail_app (msg)
split_request_uri (uri)
reraise (tp, value, tb=None)
bytes_to_str (b)
unquote_to_wsgi_str (string)
Variables
REDIRECT_TO = getattr(os, 'devnull', '/dev/null')
hop_headers = set(.split())
tuple positionals
_unlink = os.unlink
Function Documentation
_called_with_wrong_args()
gunicorn.util._called_with_wrong_args (f) protected
Check whether calling a function raised a ``TypeError`` because
the call failed or because something in the function raised the
error.
:param f: The function that was called.
:return: ``True`` if the call failed.
Referenced by gunicorn.util.import_app().
_setproctitle()
gunicorn.util._setproctitle (title) protected
_unlink()
gunicorn.util._unlink (filename) protected
References gunicorn.util._waitfor().
_waitfor()
gunicorn.util._waitfor (func, pathname, waitall = False) protected
Referenced by gunicorn.util._unlink().
bytes_to_str()
gunicorn.util.bytes_to_str (b)
check_is_writable()
gunicorn.util.check_is_writable (path)
chown()
gunicorn.util.chown (path, uid, gid)
close()
gunicorn.util.close (sock)
close_on_exec()
gunicorn.util.close_on_exec (fd)
closerange()
gunicorn.util.closerange (fd_low, fd_high)
daemonize()
gunicorn.util.daemonize (enable_stdio_inheritance = False)
\
Standard daemonization of a process.
http://www.faqs.org/faqs/unix-faq/programmer/faq/ section 1.7
get_arity()
gunicorn.util.get_arity (f)
get_username()
gunicorn.util.get_username (uid)
 get the username for a user id
Referenced by gunicorn.util.set_owner_process().
getcwd()
gunicorn.util.getcwd ()
has_fileno()
gunicorn.util.has_fileno (obj)
http_date()
gunicorn.util.http_date (timestamp = None)
Return the current date and time formatted for a message header.
import_app()
gunicorn.util.import_app (module)
References gunicorn.util._called_with_wrong_args().
is_hoppish()
gunicorn.util.is_hoppish (header)
is_ipv6()
gunicorn.util.is_ipv6 (addr)
load_class()
gunicorn.util.load_class (uri, default = "gunicorn.workers.sync.SyncWorker", section = "gunicorn.workers")
References gunicorn.util.load_entry_point().
load_entry_point()
gunicorn.util.load_entry_point (distribution, group, name)
Referenced by gunicorn.util.load_class().
make_fail_app()
gunicorn.util.make_fail_app (msg)
References gunicorn.util.to_bytestring().
parse_address()
gunicorn.util.parse_address (netloc, default_port = '8000')
reraise()
gunicorn.util.reraise (tp, value, tb = None)
seed()
gunicorn.util.seed ()
set_non_blocking()
gunicorn.util.set_non_blocking (fd)
set_owner_process()
gunicorn.util.set_owner_process (uid, gid, initgroups = False)
 set user and group of workers processes
References gunicorn.util.get_username().
split_request_uri()
gunicorn.util.split_request_uri (uri)
to_bytestring()
gunicorn.util.to_bytestring (value, encoding = "utf8")
Converts a string argument to a byte string
Referenced by gunicorn.util.make_fail_app().
unlink()
gunicorn.util.unlink (filename)
References gunicorn.util._unlink.
unquote_to_wsgi_str()
gunicorn.util.unquote_to_wsgi_str (string)
warn()
gunicorn.util.warn (msg)
write()
gunicorn.util.write (sock, data, chunked = False)
References gunicorn.util.write_chunk().
Referenced by gunicorn.util.write_nonblock().
write_chunk()
gunicorn.util.write_chunk (sock, data)
Referenced by gunicorn.util.write().
write_error()
gunicorn.util.write_error (sock, status_int, reason, mesg)
References gunicorn.util.write_nonblock().
write_nonblock()
gunicorn.util.write_nonblock (sock, data, chunked = False)
References gunicorn.util.write().
Referenced by gunicorn.util.write_error().
Variable Documentation
_unlink
gunicorn.util._unlink = os.unlink protected
Referenced by gunicorn.util.unlink().
hop_headers
gunicorn.util.hop_headers = set(.split())
positionals
tuple gunicorn.util.positionals
Initial value:
=  (
    inspect.Parameter.POSITIONAL_ONLY,
    inspect.Parameter.POSITIONAL_OR_KEYWORD,
)
REDIRECT_TO
gunicorn.util.REDIRECT_TO = getattr(os, 'devnull', '/dev/null')