Django Project: pip._vendor.pyparsing.core Namespace Reference
pip._vendor.pyparsing.core Namespace Reference
Classes
class _MultipleMatch
class _NullToken
class _PendingSkip
class _SingleCharLiteral
class And
class AtLineStart
class AtStringStart
class cached_property
class CaselessKeyword
class CaselessLiteral
class Char
class CharsNotIn
class CloseMatch
class Combine
class DelimitedList
class Diagnostics
class Dict
class Each
class Empty
class FollowedBy
class Forward
class GoToColumn
class Group
class IndentedBlock
class Keyword
class LineEnd
class LineStart
class Literal
class Located
class MatchFirst
class NoMatch
class NotAny
class OneOrMore
class Opt
class Or
class ParseElementEnhance
class ParseExpression
class ParserElement
class PositionToken
class PrecededBy
class QuotedString
class Regex
class SkipTo
class StringEnd
class StringStart
class Suppress
class Token
class TokenConverter
class White
class Word
class WordEnd
class WordStart
class ZeroOrMore
Functions
None enable_diag (Diagnostics diag_enum)
None disable_diag (Diagnostics diag_enum)
None enable_all_warnings ()
bool _should_enable_warnings (typing.Iterable[str] cmd_line_warn_options, typing.Optional[str] warn_env_var)
_trim_arity (func, max_limit=3)
ParseAction condition_as_parse_action (ParseCondition fn, typing.Optional[str] message=None, bool fatal=False)
_default_start_debug_action (str instring, int loc, "ParserElement" expr, bool cache_hit=False)
_default_success_debug_action (str instring, int startloc, int endloc, "ParserElement" expr, ParseResults toks, bool cache_hit=False)
_default_exception_debug_action (str instring, int loc, "ParserElement" expr, Exception exc, bool cache_hit=False)
null_debug_action (*args)
ParseAction trace_parse_action (ParseAction f)
str srange (str s)
ParseAction token_map (func, *args)
None autoname_elements ()
nullDebugAction ()
traceParseAction ()
conditionAsParseAction ()
tokenMap ()
Variables
_MAX_INT = sys.maxsize
tuple str_type = (str, bytes)
dict _single_arg_builtins
_generatorType = types.GeneratorType
ParseImplReturnType = Tuple[int, Any]
PostParseReturnType = Union[ParseResults, Sequence[ParseResults]]
ParseAction
ParseCondition
ParseFailAction = Callable[[str, int, "ParserElement", Exception], None]
DebugStartAction = Callable[[str, int, "ParserElement", bool], None]
DebugSuccessAction
DebugExceptionAction = Callable[[str, int, "ParserElement", Exception, bool], None]
alphas = string.ascii_uppercase + string.ascii_lowercase
identchars = pyparsing_unicode.Latin1.identchars
identbodychars = pyparsing_unicode.Latin1.identbodychars
str nums = "0123456789"
str hexnums = nums + "ABCDEFabcdef"
str alphanums = alphas + nums
str printables = "".join([c for c in string.printable if c not in string.whitespace])
traceback _trim_arity_call_line = None
Optional = Opt
empty = Empty().set_name("empty")
line_start = LineStart().set_name("line_start")
line_end = LineEnd().set_name("line_end")
string_start = StringStart().set_name("string_start")
string_end = StringEnd().set_name("string_end")
_escapedPunc
_escapedHexChar
_escapedOctChar
tuple _singleChar
_charRange = Group(_singleChar + Suppress("-") + _singleChar)
tuple _reBracketExpr
dbl_quoted_string
sgl_quoted_string
quoted_string
python_quoted_string
unicode_string = Combine("u" + quoted_string.copy()).set_name("unicode string literal")
str alphas8bit = srange(r"[\0xc0-\0xd6\0xd8-\0xf6\0xf8-\0xff]")
str punc8bit = srange(r"[\0xa1-\0xbf\0xd7\0xf7]")
list _builtin_exprs
sglQuotedString = sgl_quoted_string
dblQuotedString = dbl_quoted_string
quotedString = quoted_string
unicodeString = unicode_string
lineStart = line_start
lineEnd = line_end
stringStart = string_start
stringEnd = string_end
Function Documentation
_default_exception_debug_action()
pip._vendor.pyparsing.core._default_exception_debug_action (str instring, int loc, "ParserElement" expr, Exception exc, bool cache_hit = False) protected
_default_start_debug_action()
pip._vendor.pyparsing.core._default_start_debug_action (str instring, int loc, "ParserElement" expr, bool cache_hit = False) protected
_default_success_debug_action()
pip._vendor.pyparsing.core._default_success_debug_action (str instring, int startloc, int endloc, "ParserElement" expr, ParseResults toks, bool cache_hit = False) protected
_should_enable_warnings()
bool pip._vendor.pyparsing.core._should_enable_warnings (typing.Iterable[str] cmd_line_warn_options, typing.Optional[str] warn_env_var) protected
References pip._vendor.pyparsing.core._should_enable_warnings(), and pip._vendor.pyparsing.core.enable_all_warnings().
Referenced by pip._vendor.pyparsing.core._should_enable_warnings().
_trim_arity()
pip._vendor.pyparsing.core._trim_arity (func, max_limit = 3) protected
decorator to trim function calls to match the arity of the target
Referenced by pip._vendor.pyparsing.core.ParserElement.add_parse_action(), pip._vendor.pyparsing.core.condition_as_parse_action(), pip._vendor.pyparsing.core.ParserElement.set_parse_action(), and pip._vendor.pyparsing.core.trace_parse_action().
autoname_elements()
None pip._vendor.pyparsing.core.autoname_elements ()
Utility to simplify mass-naming of parser elements, for
generating railroad diagram with named subdiagrams.
condition_as_parse_action()
ParseAction pip._vendor.pyparsing.core.condition_as_parse_action (ParseCondition fn, typing.Optional[str] message = None, bool fatal = False)
Function to convert a simple predicate function that returns ``True`` or ``False``
into a parse action. Can be used in places when a parse action is required
and :class:`ParserElement.add_condition` cannot be used (such as when adding a condition
to an operator level in :class:`infix_notation`).
Optional keyword arguments:
- ``message`` - define a custom message to be used in the raised exception
- ``fatal`` - if True, will raise :class:`ParseFatalException` to stop parsing immediately;
  otherwise will raise :class:`ParseException`
References pip._vendor.pyparsing.core._trim_arity().
Referenced by pip._vendor.pyparsing.core.ParserElement.add_condition().
conditionAsParseAction()
pip._vendor.pyparsing.core.conditionAsParseAction ()
disable_diag()
None pip._vendor.pyparsing.core.disable_diag (Diagnostics diag_enum)
Disable a global pyparsing diagnostic flag (see :class:`Diagnostics`).
enable_all_warnings()
None pip._vendor.pyparsing.core.enable_all_warnings ()
Enable all global pyparsing diagnostic warnings (see :class:`Diagnostics`).
Referenced by pip._vendor.pyparsing.core._should_enable_warnings().
enable_diag()
None pip._vendor.pyparsing.core.enable_diag (Diagnostics diag_enum)
Enable a global pyparsing diagnostic flag (see :class:`Diagnostics`).
null_debug_action()
pip._vendor.pyparsing.core.null_debug_action (* args)
'Do-nothing' debug action, to suppress debugging output during parsing.
nullDebugAction()
pip._vendor.pyparsing.core.nullDebugAction ()
srange()
str pip._vendor.pyparsing.core.srange (str s)
Helper to easily define string ranges for use in :class:`Word`
construction. Borrows syntax from regexp ``'[]'`` string range
definitions::
    srange("[0-9]")   -> "0123456789"
    srange("[a-z]")   -> "abcdefghijklmnopqrstuvwxyz"
    srange("[a-z$_]") -> "abcdefghijklmnopqrstuvwxyz$_"
The input string must be enclosed in []'s, and the returned string
is the expanded character set joined into a single string. The
values enclosed in the []'s may be:
- a single character
- an escaped character with a leading backslash (such as ``\-``
  or ``\]``)
- an escaped hex character with a leading ``'\x'``
  (``\x21``, which is a ``'!'`` character) (``\0x##``
  is also supported for backwards compatibility)
- an escaped octal character with a leading ``'\0'``
  (``\041``, which is a ``'!'`` character)
- a range of any of the above, separated by a dash (``'a-z'``,
  etc.)
- any combination of the above (``'aeiouy'``,
  ``'a-zA-Z0-9_$'``, etc.)
token_map()
ParseAction pip._vendor.pyparsing.core.token_map (func, * args)
Helper to define a parse action by mapping a function to all
elements of a :class:`ParseResults` list. If any additional args are passed,
they are forwarded to the given function as additional arguments
after the token, as in
``hex_integer = Word(hexnums).set_parse_action(token_map(int, 16))``,
which will convert the parsed data to an integer using base 16.
Example (compare the last to example in :class:`ParserElement.transform_string`::
    hex_ints = Word(hexnums)[1, ...].set_parse_action(token_map(int, 16))
    hex_ints.run_tests('''
        00 11 22 aa FF 0a 0d 1a
        ''')
    upperword = Word(alphas).set_parse_action(token_map(str.upper))
    upperword[1, ...].run_tests('''
        my kingdom for a horse
        ''')
    wd = Word(alphas).set_parse_action(token_map(str.title))
    wd[1, ...].set_parse_action(' '.join).run_tests('''
        now is the winter of our discontent made glorious summer by this sun of york
        ''')
prints::
    00 11 22 aa FF 0a 0d 1a
    [0, 17, 34, 170, 255, 10, 13, 26]
    my kingdom for a horse
    ['MY', 'KINGDOM', 'FOR', 'A', 'HORSE']
    now is the winter of our discontent made glorious summer by this sun of york
    ['Now Is The Winter Of Our Discontent Made Glorious Summer By This Sun Of York']
tokenMap()
pip._vendor.pyparsing.core.tokenMap ()
trace_parse_action()
ParseAction pip._vendor.pyparsing.core.trace_parse_action (ParseAction f)
Decorator for debugging parse actions.
When the parse action is called, this decorator will print
``">> entering method-name(line:<current_source_line>, <parse_location>, <matched_tokens>)"``.
When the parse action completes, the decorator will print
``"<<"`` followed by the returned value, or any exception that the parse action raised.
Example::
    wd = Word(alphas)
    @trace_parse_action
    def remove_duplicate_chars(tokens):
        return ''.join(sorted(set(''.join(tokens))))
    wds = wd[1, ...].set_parse_action(remove_duplicate_chars)
    print(wds.parse_string("slkdjs sld sldd sdlf sdljf"))
prints::
    >>entering remove_duplicate_chars(line: 'slkdjs sld sldd sdlf sdljf', 0, (['slkdjs', 'sld', 'sldd', 'sdlf', 'sdljf'], {}))
    <<leaving remove_duplicate_chars (ret: 'dfjkls')
    ['dfjkls']
References pip._vendor.pyparsing.core._trim_arity().
traceParseAction()
pip._vendor.pyparsing.core.traceParseAction ()
Variable Documentation
_builtin_exprs
list pip._vendor.pyparsing.core._builtin_exprs protected
Initial value:
=  [
    v for v in vars().values() if isinstance(v, ParserElement)
]
_charRange
pip._vendor.pyparsing.core._charRange = Group(_singleChar + Suppress("-") + _singleChar) protected
_escapedHexChar
pip._vendor.pyparsing.core._escapedHexChar protected
Initial value:
=  Regex(r"\\0?[xX][0-9a-fA-F]+").set_parse_action(
    lambda s, l, t: chr(int(t[0].lstrip(r"\0x"), 16))
)
_escapedOctChar
pip._vendor.pyparsing.core._escapedOctChar protected
Initial value:
=  Regex(r"\\0[0-7]+").set_parse_action(
    lambda s, l, t: chr(int(t[0][1:], 8))
)
_escapedPunc
pip._vendor.pyparsing.core._escapedPunc protected
Initial value:
=  Regex(r"\\[\\[\]\/\-\*\.\$\+\^\?()~ ]").set_parse_action(
    lambda s, l, t: t[0][1]
)
_generatorType
pip._vendor.pyparsing.core._generatorType = types.GeneratorType protected
_MAX_INT
pip._vendor.pyparsing.core._MAX_INT = sys.maxsize protected
_reBracketExpr
tuple pip._vendor.pyparsing.core._reBracketExpr protected
Initial value:
=  (
    Literal("[")
    + Opt("^").set_results_name("negate")
    + Group(OneOrMore(_charRange | _singleChar)).set_results_name("body")
    + Literal("]")
)
_single_arg_builtins
dict pip._vendor.pyparsing.core._single_arg_builtins protected
Initial value:
=  {
    sum,
    len,
    sorted,
    reversed,
    list,
    tuple,
    set,
    any,
    all,
    min,
    max,
}
_singleChar
tuple pip._vendor.pyparsing.core._singleChar protected
Initial value:
=  (
    _escapedPunc | _escapedHexChar | _escapedOctChar | CharsNotIn(r"\]", exact=1)
)
_trim_arity_call_line
traceback pip._vendor.pyparsing.core._trim_arity_call_line = None protected
alphanums
str pip._vendor.pyparsing.core.alphanums = alphas + nums
alphas
pip._vendor.pyparsing.core.alphas = string.ascii_uppercase + string.ascii_lowercase
alphas8bit
str pip._vendor.pyparsing.core.alphas8bit = srange(r"[\0xc0-\0xd6\0xd8-\0xf6\0xf8-\0xff]")
dbl_quoted_string
pip._vendor.pyparsing.core.dbl_quoted_string
Initial value:
=  Combine(
    Regex(r'"(?:[^"\n\r\\]|(?:"")|(?:\\(?:[^x]|x[0-9a-fA-F]+)))*') + '"'
).set_name("string enclosed in double quotes")
dblQuotedString
pip._vendor.pyparsing.core.dblQuotedString = dbl_quoted_string
DebugExceptionAction
pip._vendor.pyparsing.core.DebugExceptionAction = Callable[[str, int, "ParserElement", Exception, bool], None]
DebugStartAction
pip._vendor.pyparsing.core.DebugStartAction = Callable[[str, int, "ParserElement", bool], None]
DebugSuccessAction
pip._vendor.pyparsing.core.DebugSuccessAction
Initial value:
=  Callable[
    [str, int, int, "ParserElement", ParseResults, bool], None
]
empty
pip._vendor.pyparsing.core.empty = Empty().set_name("empty")
hexnums
str pip._vendor.pyparsing.core.hexnums = nums + "ABCDEFabcdef"
identbodychars
pip._vendor.pyparsing.core.identbodychars = pyparsing_unicode.Latin1.identbodychars
identchars
pip._vendor.pyparsing.core.identchars = pyparsing_unicode.Latin1.identchars
line_end
pip._vendor.pyparsing.core.line_end = LineEnd().set_name("line_end")
line_start
pip._vendor.pyparsing.core.line_start = LineStart().set_name("line_start")
lineEnd
pip._vendor.pyparsing.core.lineEnd = line_end
lineStart
pip._vendor.pyparsing.core.lineStart = line_start
nums
str pip._vendor.pyparsing.core.nums = "0123456789"
Optional
pip._vendor.pyparsing.core.Optional = Opt
ParseAction
pip._vendor.pyparsing.core.ParseAction
Initial value:
=  Union[
    Callable[[], Any],
    Callable[[ParseResults], Any],
    Callable[[int, ParseResults], Any],
    Callable[[str, int, ParseResults], Any],
]
ParseCondition
pip._vendor.pyparsing.core.ParseCondition
Initial value:
=  Union[
    Callable[[], bool],
    Callable[[ParseResults], bool],
    Callable[[int, ParseResults], bool],
    Callable[[str, int, ParseResults], bool],
]
ParseFailAction
pip._vendor.pyparsing.core.ParseFailAction = Callable[[str, int, "ParserElement", Exception], None]
ParseImplReturnType
pip._vendor.pyparsing.core.ParseImplReturnType = Tuple[int, Any]
PostParseReturnType
pip._vendor.pyparsing.core.PostParseReturnType = Union[ParseResults, Sequence[ParseResults]]
printables
str pip._vendor.pyparsing.core.printables = "".join([c for c in string.printable if c not in string.whitespace])
punc8bit
str pip._vendor.pyparsing.core.punc8bit = srange(r"[\0xa1-\0xbf\0xd7\0xf7]")
python_quoted_string
pip._vendor.pyparsing.core.python_quoted_string
Initial value:
=  Combine(
    (Regex(r'"""(?:[^"\\]|""(?!")|"(?!"")|\\.)*', flags=re.MULTILINE) + '"""').set_name(
        "multiline double quoted string"
    )
    ^ (
        Regex(r"'''(?:[^'\\]|''(?!')|'(?!'')|\\.)*", flags=re.MULTILINE) + "'''"
    ).set_name("multiline single quoted string")
    ^ (Regex(r'"(?:[^"\n\r\\]|(?:\\")|(?:\\(?:[^x]|x[0-9a-fA-F]+)))*') + '"').set_name(
        "double quoted string"
    )
    ^ (Regex(r"'(?:[^'\n\r\\]|(?:\\')|(?:\\(?:[^x]|x[0-9a-fA-F]+)))*") + "'").set_name(
        "single quoted string"
    )
).set_name("Python quoted string")
quoted_string
pip._vendor.pyparsing.core.quoted_string
Initial value:
=  Combine(
    (Regex(r'"(?:[^"\n\r\\]|(?:"")|(?:\\(?:[^x]|x[0-9a-fA-F]+)))*') + '"').set_name(
        "double quoted string"
    )
    | (Regex(r"'(?:[^'\n\r\\]|(?:'')|(?:\\(?:[^x]|x[0-9a-fA-F]+)))*") + "'").set_name(
        "single quoted string"
    )
).set_name("quoted string using single or double quotes")
Referenced by pip._vendor.pyparsing.helpers.nested_expr().
quotedString
pip._vendor.pyparsing.core.quotedString = quoted_string
sgl_quoted_string
pip._vendor.pyparsing.core.sgl_quoted_string
Initial value:
=  Combine(
    Regex(r"'(?:[^'\n\r\\]|(?:'')|(?:\\(?:[^x]|x[0-9a-fA-F]+)))*") + "'"
).set_name("string enclosed in single quotes")
sglQuotedString
pip._vendor.pyparsing.core.sglQuotedString = sgl_quoted_string
str_type
tuple pip._vendor.pyparsing.core.str_type = (str, bytes)
string_end
pip._vendor.pyparsing.core.string_end = StringEnd().set_name("string_end")
string_start
pip._vendor.pyparsing.core.string_start = StringStart().set_name("string_start")
stringEnd
pip._vendor.pyparsing.core.stringEnd = string_end
stringStart
pip._vendor.pyparsing.core.stringStart = string_start
unicode_string
pip._vendor.pyparsing.core.unicode_string = Combine("u" + quoted_string.copy()).set_name("unicode string literal")
unicodeString
pip._vendor.pyparsing.core.unicodeString = unicode_string