Django Project: pytest_django.plugin Namespace Reference
pytest_django.plugin Namespace Reference
Classes
class _DatabaseBlockerContextManager
class DjangoDbBlocker
Functions
None pytest_addoption (pytest.Parser parser)
Generator[None, None, None] _handle_import_error (str extra_message)
str _add_django_project_to_path (args)
None _setup_django (pytest.Config config)
bool _get_boolean_value (None|(bool|str) x, str name, bool|None default=None)
None pytest_load_initial_conftests (pytest.Config early_config, pytest.Parser parser, list[str] args)
None pytest_configure (pytest.Config config)
list[str]|None pytest_report_header (pytest.Config config)
None pytest_collectstart (pytest.Collector collector)
None pytest_itemcollected (pytest.Item item)
None pytest_collection_modifyitems (list[pytest.Item] items)
Generator[None, None, None] django_test_environment (pytest.FixtureRequest request)
DjangoDbBlocker|None django_db_blocker (pytest.FixtureRequest request)
None _django_db_marker (pytest.FixtureRequest request)
Generator[None, None, None] _django_setup_unittest (pytest.FixtureRequest request, DjangoDbBlocker django_db_blocker)
None _dj_autoclear_mailbox ()
list[django.core.mail.EmailMessage]|None mailoutbox (None django_mail_patch_dns, None _dj_autoclear_mailbox)
None django_mail_patch_dns (pytest.MonkeyPatch monkeypatch, str django_mail_dnsname)
str django_mail_dnsname ()
Generator[None, None, None] _django_set_urlconf (pytest.FixtureRequest request)
_fail_for_invalid_template_variable ()
None _template_string_if_invalid_marker (pytest.MonkeyPatch monkeypatch, pytest.FixtureRequest request)
None _django_clear_site_cache ()
list[str] validate_urls (marker)
Variables
str SETTINGS_MODULE_ENV = "DJANGO_SETTINGS_MODULE"
str CONFIGURATION_ENV = "DJANGO_CONFIGURATION"
str INVALID_TEMPLATE_VARS_ENV = "FAIL_INVALID_TEMPLATE_VARS"
tuple PROJECT_FOUND
tuple PROJECT_NOT_FOUND
tuple PROJECT_SCAN_DISABLED
report_header_key = pytest.StashKey[List[str]]()
blocking_manager_key = pytest.StashKey[DjangoDbBlocker]()
fail
Detailed Description
A pytest plugin which helps testing Django applications
This plugin handles creating and destroying the test environment and
test database and provides some useful text fixtures.
Function Documentation
_add_django_project_to_path()
str pytest_django.plugin._add_django_project_to_path (args) protected
Referenced by pytest_django.plugin.pytest_load_initial_conftests().
_dj_autoclear_mailbox()
None pytest_django.plugin._dj_autoclear_mailbox () protected
_django_clear_site_cache()
None pytest_django.plugin._django_clear_site_cache () protected
Clears ``django.contrib.sites.models.SITE_CACHE`` to avoid
unexpected behavior with cached site objects.
_django_db_marker()
None pytest_django.plugin._django_db_marker (pytest.FixtureRequest request) protected
Implement the django_db marker, internal to pytest-django.
_django_set_urlconf()
Generator[None, None, None] pytest_django.plugin._django_set_urlconf (pytest.FixtureRequest request) protected
Apply the @pytest.mark.urls marker, internal to pytest-django.
References pytest_django.plugin.validate_urls().
_django_setup_unittest()
Generator[None, None, None] pytest_django.plugin._django_setup_unittest (pytest.FixtureRequest request, DjangoDbBlocker django_db_blocker) protected
Setup a django unittest, internal to pytest-django.
_fail_for_invalid_template_variable()
pytest_django.plugin._fail_for_invalid_template_variable () protected
Fixture that fails for invalid variables in templates.
This fixture will fail each test that uses django template rendering
should a template contain an invalid template variable.
The fail message will include the name of the invalid variable and
in most cases the template name.
It does not raise an exception, but fails, as the stack trace doesn't
offer any helpful information to debug.
This behavior can be switched off using the marker:
``pytest.mark.ignore_template_errors``
_get_boolean_value()
bool pytest_django.plugin._get_boolean_value (None | (bool | str) x, str name, bool | None default = None) protected
Referenced by pytest_django.plugin.django_test_environment(), and pytest_django.plugin.pytest_load_initial_conftests().
_handle_import_error()
Generator[None, None, None] pytest_django.plugin._handle_import_error (str extra_message) protected
Referenced by pytest_django.plugin.pytest_load_initial_conftests().
_setup_django()
None pytest_django.plugin._setup_django (pytest.Config config) protected
References django.setup().
Referenced by pytest_django.plugin.pytest_configure(), and pytest_django.plugin.pytest_load_initial_conftests().
_template_string_if_invalid_marker()
None pytest_django.plugin._template_string_if_invalid_marker (pytest.MonkeyPatch monkeypatch, pytest.FixtureRequest request) protected
Apply the @pytest.mark.ignore_template_errors marker,
internal to pytest-django.
django_db_blocker()
DjangoDbBlocker | None pytest_django.plugin.django_db_blocker (pytest.FixtureRequest request)
Wrapper around Django's database access.
This object can be used to re-enable database access.  This fixture is used
internally in pytest-django to build the other fixtures and can be used for
special database handling.
The object is a context manager and provides the methods
.unblock()/.block() and .restore() to temporarily enable database access.
This is an advanced feature that is meant to be used to implement database
fixtures.
django_mail_dnsname()
str pytest_django.plugin.django_mail_dnsname ()
django_mail_patch_dns()
None pytest_django.plugin.django_mail_patch_dns (pytest.MonkeyPatch monkeypatch, str django_mail_dnsname)
django_test_environment()
Generator[None, None, None] pytest_django.plugin.django_test_environment (pytest.FixtureRequest request)
Setup Django's test environment for the testing session.
XXX It is a little dodgy that this is an autouse fixture.  Perhaps
    an email fixture should be requested in order to be able to
    use the Django email machinery just like you need to request a
    db fixture for access to the Django database, etc.  But
    without duplicating a lot more of Django's test support code
    we need to follow this model.
References pytest_django.plugin._get_boolean_value().
mailoutbox()
list[django.core.mail.EmailMessage] | None pytest_django.plugin.mailoutbox (None django_mail_patch_dns, None _dj_autoclear_mailbox)
pytest_addoption()
None pytest_django.plugin.pytest_addoption (pytest.Parser parser)
pytest_collection_modifyitems()
None pytest_django.plugin.pytest_collection_modifyitems (list[pytest.Item] items)
pytest_collectstart()
None pytest_django.plugin.pytest_collectstart (pytest.Collector collector)
pytest_configure()
None pytest_django.plugin.pytest_configure (pytest.Config config)
References pytest_django.plugin._setup_django().
pytest_itemcollected()
None pytest_django.plugin.pytest_itemcollected (pytest.Item item)
pytest_load_initial_conftests()
None pytest_django.plugin.pytest_load_initial_conftests (pytest.Config early_config, pytest.Parser parser, list[str] args)
References pytest_django.plugin._add_django_project_to_path(), pytest_django.plugin._get_boolean_value(), pytest_django.plugin._handle_import_error(), and pytest_django.plugin._setup_django().
pytest_report_header()
list[str] | None pytest_django.plugin.pytest_report_header (pytest.Config config)
validate_urls()
list[str] pytest_django.plugin.validate_urls (marker)
Validate the urls marker.
It checks the signature and creates the `urls` attribute on the
marker which will have the correct value.
Referenced by pytest_django.plugin._django_set_urlconf().
Variable Documentation
blocking_manager_key
pytest_django.plugin.blocking_manager_key = pytest.StashKey[DjangoDbBlocker]()
CONFIGURATION_ENV
str pytest_django.plugin.CONFIGURATION_ENV = "DJANGO_CONFIGURATION"
fail
pytest_django.plugin.fail
INVALID_TEMPLATE_VARS_ENV
str pytest_django.plugin.INVALID_TEMPLATE_VARS_ENV = "FAIL_INVALID_TEMPLATE_VARS"
PROJECT_FOUND
tuple pytest_django.plugin.PROJECT_FOUND
Initial value:
=  (
    "pytest-django found a Django project in %s "
    "(it contains manage.py) and added it to the Python path.\n"
    'If this is wrong, add "django_find_project = false" to '
    "pytest.ini and explicitly manage your Python path."
)
PROJECT_NOT_FOUND
tuple pytest_django.plugin.PROJECT_NOT_FOUND
Initial value:
=  (
    "pytest-django could not find a Django project "
    "(no manage.py file could be found). You must "
    "explicitly add your Django project to the Python path "
    "to have it picked up."
)
PROJECT_SCAN_DISABLED
tuple pytest_django.plugin.PROJECT_SCAN_DISABLED
Initial value:
=  (
    "pytest-django did not search for Django "
    "projects since it is disabled in the configuration "
    '("django_find_project = false")'
)
report_header_key
pytest_django.plugin.report_header_key = pytest.StashKey[List[str]]()
SETTINGS_MODULE_ENV
str pytest_django.plugin.SETTINGS_MODULE_ENV = "DJANGO_SETTINGS_MODULE"