Django Project: _pytest.debugging Namespace Reference
_pytest.debugging Namespace Reference
Classes
class PdbInvoke
class PdbTrace
class pytestPDB
Functions
tuple[str, str] _validate_usepdb_cls (str value)
None pytest_addoption (Parser parser)
None pytest_configure (Config config)
None wrap_pytest_function_for_tracing (pyfuncitem)
None maybe_wrap_pytest_function_for_tracing (pyfuncitem)
BaseReport _enter_pdb (Node node, ExceptionInfo[BaseException] excinfo, BaseReport rep)
types.TracebackType _postmortem_traceback (ExceptionInfo[BaseException] excinfo)
None post_mortem (types.TracebackType t)
Detailed Description
Interactive debugging with PDB, the Python Debugger.
Function Documentation
_enter_pdb()
BaseReport _pytest.debugging._enter_pdb (Node node, ExceptionInfo[BaseException] excinfo, BaseReport rep) protected
References _pytest.debugging._postmortem_traceback(), and _pytest.debugging.post_mortem().
Referenced by _pytest.debugging.PdbInvoke.pytest_exception_interact().
_postmortem_traceback()
types.TracebackType _pytest.debugging._postmortem_traceback (ExceptionInfo[BaseException] excinfo) protected
Referenced by _pytest.debugging._enter_pdb(), and _pytest.debugging.PdbInvoke.pytest_internalerror().
_validate_usepdb_cls()
tuple[str, str] _pytest.debugging._validate_usepdb_cls (str value) protected
Validate syntax of --pdbcls option.
maybe_wrap_pytest_function_for_tracing()
None _pytest.debugging.maybe_wrap_pytest_function_for_tracing (pyfuncitem)
Wrap the given pytestfunct item for tracing support if --trace was given in
the command line.
References _pytest.debugging.wrap_pytest_function_for_tracing().
post_mortem()
None _pytest.debugging.post_mortem (types.TracebackType t)
Referenced by _pytest.debugging._enter_pdb(), and _pytest.debugging.PdbInvoke.pytest_internalerror().
pytest_addoption()
None _pytest.debugging.pytest_addoption (Parser parser)
pytest_configure()
None _pytest.debugging.pytest_configure (Config config)
wrap_pytest_function_for_tracing()
None _pytest.debugging.wrap_pytest_function_for_tracing (pyfuncitem)
Change the Python function object of the given Function item by a
wrapper which actually enters pdb before calling the python function
itself, effectively leaving the user in the pdb prompt in the first
statement of the function.
Referenced by _pytest.debugging.maybe_wrap_pytest_function_for_tracing(), and _pytest.debugging.PdbTrace.pytest_pyfunc_call().