Django Project: setuptools.sandbox Namespace Reference
setuptools.sandbox Namespace Reference
Classes
class AbstractSandbox
class DirectorySandbox
class ExceptionSaver
class SandboxViolation
class UnpickleableException
Functions
_execfile (filename, globals, locals=None)
save_argv (repl=None)
save_path ()
override_temp (replacement)
pushd (target)
save_modules ()
_clear_modules (module_names)
save_pkg_resources_state ()
setup_context (setup_dir)
_needs_hiding (mod_name)
hide_setuptools ()
run_setup (setup_script, args)
Variables
_os = sys.modules[os.name]
_file = file
_open = open
dict _MODULES_TO_HIDE
list _EXCEPTIONS = [os.devnull]
WRITE_FLAGS
Function Documentation
_clear_modules()
setuptools.sandbox._clear_modules (module_names) protected
Referenced by setuptools.sandbox.hide_setuptools(), and setuptools.sandbox.save_modules().
_execfile()
setuptools.sandbox._execfile (filename, globals, locals = None) protected
Python 3 implementation of execfile.
Referenced by setuptools.sandbox.run_setup().
_needs_hiding()
setuptools.sandbox._needs_hiding (mod_name) protected
>>> _needs_hiding('setuptools')
True
>>> _needs_hiding('pkg_resources')
True
>>> _needs_hiding('setuptools_plugin')
False
>>> _needs_hiding('setuptools.__init__')
True
>>> _needs_hiding('distutils')
True
>>> _needs_hiding('os')
False
>>> _needs_hiding('Cython')
True
hide_setuptools()
setuptools.sandbox.hide_setuptools ()
Remove references to setuptools' modules from sys.modules to allow the
invocation to import the most appropriate setuptools. This technique is
necessary to avoid issues such as #315 where setuptools upgrading itself
would fail to find a function declared in the metadata.
References setuptools.sandbox._clear_modules(), and _distutils_hack.remove_shim().
Referenced by setuptools.sandbox.setup_context().
override_temp()
setuptools.sandbox.override_temp (replacement)
Monkey-patch tempfile.tempdir with replacement, ensuring it exists
Referenced by setuptools.sandbox.setup_context().
pushd()
setuptools.sandbox.pushd (target)
Referenced by setuptools.sandbox.setup_context().
run_setup()
setuptools.sandbox.run_setup (setup_script, args)
Run a distutils setup script, sandboxed in its directory
References setuptools.sandbox._execfile(), and setuptools.sandbox.setup_context().
save_argv()
setuptools.sandbox.save_argv (repl = None)
Referenced by setuptools.sandbox.setup_context().
save_modules()
setuptools.sandbox.save_modules ()
Context in which imported modules are saved.
Translates exceptions internal to the context into the equivalent exception
outside the context.
References setuptools.sandbox._clear_modules().
Referenced by setuptools.sandbox.setup_context().
save_path()
setuptools.sandbox.save_path ()
Referenced by setuptools.sandbox.setup_context().
save_pkg_resources_state()
setuptools.sandbox.save_pkg_resources_state ()
References pkg_resources.__getstate__(), and pkg_resources.__setstate__().
Referenced by setuptools.sandbox.setup_context().
setup_context()
setuptools.sandbox.setup_context (setup_dir)
References setuptools.sandbox.hide_setuptools(), setuptools.sandbox.override_temp(), setuptools.sandbox.pushd(), setuptools.sandbox.save_argv(), setuptools.sandbox.save_modules(), setuptools.sandbox.save_path(), and setuptools.sandbox.save_pkg_resources_state().
Referenced by setuptools.sandbox.run_setup().
Variable Documentation
_EXCEPTIONS
list setuptools.sandbox._EXCEPTIONS = [os.devnull] protected
_file
setuptools.sandbox._file = file protected
_MODULES_TO_HIDE
dict setuptools.sandbox._MODULES_TO_HIDE protected
Initial value:
=  {
    'setuptools',
    'distutils',
    'pkg_resources',
    'Cython',
    '_distutils_hack',
}
_open
setuptools.sandbox._open = open protected
_os
setuptools.sandbox._os = sys.modules[os.name] protected
WRITE_FLAGS
setuptools.sandbox.WRITE_FLAGS
Initial value:
=  functools.reduce(
    operator.or_,
    [
        getattr(_os, a, 0)
        for a in "O_WRONLY O_RDWR O_APPEND O_CREAT O_TRUNC O_TEMPORARY".split()
    ],
)